(function(root){'use strict';const parse=v=>{if(typeof v==='string'){try{return JSON.parse(v);}catch{return v;}}return v;},num=v=>Number.isFinite(Number(v))?Number(v):0,esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),pretty=v=>String(v??'').replaceAll('_',' ').replaceAll('{','').replaceAll('}','').replaceAll('|',' / ').replace(/\s+/g,' ').trim(),fmt=v=>num(v).toLocaleString();let tabs={guilds:'bonuses',tasks:'tasks',events:'cards'},page=0;
// TaskZZ indices are data categories, not world numbers (client save writer).
const knownNumber=value=>value==null||value===''||!Number.isFinite(Number(value))?null:Number(value);
function guild(data,c=root.ACCOUNT_CATALOG){
 const g=parse(data.Guild)||[],levels=parse(g[0])||[];
 const tasks=g.slice(1).map((entry,slot)=>{entry=parse(entry)||[];const id=knownNumber(entry[0]),r=id==null?null:c.GuildGPtasks[id];if(!r)return null;const progress=knownNumber(entry[2]),claimed=num(entry[1])>0;return{id,slot,name:pretty(r[0]),target:num(r[1]),gp:num(r[2]),progress,claimed,completed:claimed||progress!=null&&progress>=num(r[1])};}).filter(Boolean);
 return{available:g.length>0,gp:null,bonuses:c.GuildBonuses.map((r,id)=>{const level=knownNumber(levels[id]),amount=level==null?null:r[6]==='decay'?level*num(r[4])/(level+num(r[5])):r[6]==='add'?level*num(r[4]):null;const bonus=id===9&&amount!=null?100-amount:amount;return{id,name:pretty(r[0]),description:pretty(String(r[3]).replace(/[{}]/g,bonus==null?'—':Number(bonus.toFixed(2)).toLocaleString()).replaceAll(']',level==null?'—':fmt(level+10))),level,max:num(r[7]),base:num(r[4]),cost:num(r[10])};}),tasks};
}
function taskModel(data,c=root.ACCOUNT_CATALOG){
 const achievements=parse(data.AchieveReg)||[],progress=parse(data.TaskZZ0)||[],tiers=parse(data.TaskZZ1)||[],merits=parse(data.TaskZZ2)||[];
 const worlds=Array.from({length:7},(_,id)=>{
  const savedProgress=parse(progress[id])||[],savedTiers=parse(tiers[id])||[],savedMerits=parse(merits[id])||[];
  const defs=c.TaskDescriptions[id]||[],shop=c.TaskShopDesc[id]||[];
  return{id,name:'World '+(id+1),tasks:defs.map((r,i)=>{
   if(/^(Undisclosed_Task|Nope|Nuh_uh)$/.test(r[0])||id===6&&i>=4)return null;
   const daily=i>=8,level=daily?null:knownNumber(savedTiers[i]),current=daily?null:knownNumber(savedProgress[i]),thresholds=r.slice(i===7?4:5).filter(v=>knownNumber(v)!=null),target=daily?knownNumber(thresholds[0]):level==null?null:knownNumber(thresholds[Math.min(level,thresholds.length-1)]);
   const description=String(r[1]).replaceAll('{',target==null?'—':fmt(target)).replaceAll('}',String(r[2]||'').split('|')[Math.min(level??0,String(r[2]||'').split('|').length-1)]||'');
   return{id:i,name:pretty(r[0]),description:pretty(description),level,progress:current,tiers:thresholds,max:daily?null:thresholds.length,daily,complete:!daily&&level!=null&&level>=thresholds.length};
  }).filter(Boolean),shop:shop.map((r,i)=>{if(r[0]==='IDK_YET'||id===6&&i>=5)return null;const level=knownNumber(savedMerits[i]);return{id:i,name:id===6?['Spelunking Power','World 7 Respawn','Spelunking Stamina','Research Points','Minehead Currency'][i]:pretty(r[0]+' '+r[1]),description:pretty(String(r[0]+' '+r[1]).replaceAll('{',level==null?'—':id===6||i===1?fmt(level*num(r[11])):'…').replaceAll('}',String(r[9]||'').split('|')[Math.max(0,(level??0)-1)]||'—')),level,max:num(r[5]),icon:r[10]};}).filter(Boolean)};
 });
 return{worlds,achievements:c.RegAchieves.map((r,id)=>({id,name:pretty(r[0]),description:pretty(r[2]),reward:pretty(r[3]),complete:knownNumber(achievements[id])==null?null:num(achievements[id])!==0}))};
}
function events(data){const cards=(root.CardsPage?.model(data)?.all||[]).filter(card=>card.group===12).map(card=>({...card,effect:card.bonusText}));const seasonal=/event|anniversary|falloween|summer|spring|snow|frost|lovely|chocolate|gingerbread|egg|gold/i,tags=(root.GALLERY_CATALOG?.nametags||[]).filter(x=>seasonal.test(x.name)),trophies=(root.GALLERY_CATALOG?.trophies||[]).filter(x=>seasonal.test(x.name));return{cards,tags,trophies};}
function render(host,kind,data,rawRoot={}){const c=root.ACCOUNT_CATALOG;if(kind==='guilds')renderGuild(host,guild(data,c));else if(kind==='tasks')renderTasks(host,taskModel(data,c));else renderEvents(host,events(data));}
function shell(host,title,copy,summary,nav,body){const current=title==='Guilds'?tabs.guilds:title.startsWith('Tasks')?tabs.tasks:tabs.events;host.innerHTML=`<div class="account-page-hero"><div><p class="eyebrow">Account</p><h2>${esc(title)}</h2><p>${esc(copy)}</p></div><strong>${esc(summary)}</strong></div><nav class="skill-tabs">${nav.map(([id,n])=>`<button class="skill-tab${current===id?' active':''}" data-ap-tab="${id}">${n}</button>`).join('')}</nav>${body}`;}
function renderGuild(host,m){const paint=()=>{const body=tabs.guilds==='bonuses'?`<div class="account-bonus-grid">${m.bonuses.map(x=>`<article><span>${x.level==null?'Saved level unknown':`Lv ${fmt(x.level)}${x.max?' / '+x.max:''}`}</span><h3>${esc(x.name)}</h3><p>${esc(x.description)}</p></article>`).join('')}</div>`:`<div class="account-task-grid">${m.tasks.map(x=>`<article class="${x.completed?'done':''}"><span>${x.claimed?'Claimed':x.completed?'Ready to claim':x.progress==null?'Progress unknown':`${fmt(x.progress)} / ${fmt(x.target)}`}</span><h3>${esc(x.name)}</h3><strong>+${fmt(x.gp)} GP</strong></article>`).join('')}</div>`;shell(host,'Guilds','Guild bonuses and contribution tasks.',m.available?`${m.tasks.filter(x=>x.completed).length}/${m.tasks.length} tasks complete`:'Guild save data unavailable',[['bonuses','Bonuses'],['tasks','Guild Tasks']],body);host.querySelectorAll('[data-ap-tab]').forEach(b=>b.onclick=()=>{tabs.guilds=b.dataset.apTab;paint();});};paint();}
function renderTasks(host,m){let world=0;const paint=()=>{let body;if(tabs.tasks==='achievements'){const size=60,pages=Math.ceil(m.achievements.length/size),shown=m.achievements.slice(page*size,page*size+size);body=`<div class="achievement-grid">${shown.map(x=>`<article class="${x.complete?'done':''}"><span>${x.complete==null?'Unknown':x.complete?'✓ Complete':'Incomplete'}</span><h3>${esc(x.name)}</h3><p>${esc(x.description)}</p><small>${esc(x.reward)}</small></article>`).join('')}</div><div class="collection-pager"><button class="secondary" id="apPrev" ${page===0?'disabled':''}>Previous</button><span>${page+1} / ${pages}</span><button class="secondary" id="apNext" ${page>=pages-1?'disabled':''}>Next</button></div>`;}else{const w=m.worlds[world],list=tabs.tasks==='merits'?w.shop:w.tasks;body=`<label class="account-world-select">World <select id="apWorld">${m.worlds.map(x=>`<option value="${x.id}" ${x.id===world?'selected':''}>${x.id+1}</option>`).join('')}</select></label><div class="account-bonus-grid">${list.map(x=>`<article><span>${x.daily?'Daily task · progress not decoded':x.level==null?'Saved level unknown':`Lv ${fmt(x.level)}${x.max?' / '+x.max:''}`}</span><h3>${esc(x.name)}</h3>${x.progress!=null?`<small>Saved progress: ${fmt(x.progress)}${x.complete?' · All tiers complete':''}</small>`:''}${x.description?`<p>${esc(x.description)}</p>`:''}</article>`).join('')||'<p>No entries in this world.</p>'}</div>`;}shell(host,'Tasks / Achievements / Merit Shop','World task progress, achievements, and merit purchases.',`${m.achievements.filter(x=>x.complete).length}/${m.achievements.length} achievements`,[['tasks','Tasks'],['achievements','Achievements'],['merits','Merit Shop']],body);host.querySelectorAll('[data-ap-tab]').forEach(b=>b.onclick=()=>{tabs.tasks=b.dataset.apTab;paint();});host.querySelector('#apWorld')?.addEventListener('change',e=>{world=num(e.target.value);paint();});host.querySelector('#apPrev')?.addEventListener('click',()=>{page--;paint();});host.querySelector('#apNext')?.addEventListener('click',()=>{page++;paint();});};paint();}
function renderEvents(host,m){const paint=()=>{const list=tabs.events==='cards'?m.cards:tabs.events==='nametags'?m.tags:m.trophies,body=`<div class="event-bonus-grid">${list.map(x=>`<article class="${x.owned===false?'locked':''}">${x.icon?`<img src="${x.icon}" alt="">`:''}<h3>${esc(x.name)}</h3><p>${x.effect?`${esc(x.effect)}`:(x.bonuses||[]).map(b=>`+${fmt(b.value)}% ${esc(pretty(b.name))}`).join(' · ')||'Cosmetic reward'}</p></article>`).join('')||'<p>No matching bonuses found.</p>'}</div>`;shell(host,'Event Bonuses','Permanent bonuses from event cards, nametags, and trophies.',`${m.cards.length+m.tags.length+m.trophies.length} catalog bonuses`,[['cards','Event Cards'],['nametags','Event Nametags'],['trophies','Event Trophies']],body);host.querySelectorAll('[data-ap-tab]').forEach(b=>b.onclick=()=>{tabs.events=b.dataset.apTab;paint();});};paint();}
const api={guild,taskModel,events,render};if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.AccountPages=api;})(typeof window!=='undefined'?window:globalThis);
