(function(root){'use strict';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const foods=[
 ['PeanutG','Golden Peanut','Mining Efficiency',30,'%'],['ButterBar','Butter Bar','Base Accuracy',60,''],['FoodG1','Golden Jam','Maximum Health',30,'%'],['FoodG2','Golden Kebabs','Total Damage',20,'%'],['FoodG3','Golden Meat Pie','Total Defence',30,'%'],['FoodG4','Golden Nomwich','Base Damage',400,''],['FoodG5','Golden Ham','Skill EXP',18,'%'],['FoodG6','Golden Bread','Coins from Monsters',30,'%'],['FoodG7','Golden Ribs','Fishing Efficiency',40,'%'],['FoodG8','Golden Cheese','Shrine AFK Leveling',20,'%'],['FoodG9','Golden Grilled Cheese Nomwich','STR, AGI, WIS and LUK',10,'%'],['FoodG10','Golden Hampter Gummy Candy','Sailing AFK Time',23,'%'],['FoodG11','Golden Nigiri','Class EXP',40,'%'],['FoodG12','Golden Dumpling','AFK Gains Rate',4,'%'],['FoodG13','Golden Cake','Drop Rate',8,'%'],['FoodG14','Golden Saltwater Taffy','Spelunking EXP',1,'%'],['FoodG15','Golden Sugar Cookie','Drop Rate',2,'%']
].map((x,id)=>({id,key:x[0],name:x[1],effect:x[2],amount:x[3],unit:x[4],icon:`assets/${x[0]}.png`}));
const sourceNames=['Secret Class equipment set','Verminous companion (ID 174)','Shaman family bonus','Equipment, Gallery, Hat Rack and obols','Star talent 99','Golden Food stamp bonuses','Achievement 37','Alchemy GFoodz bubbles','Sigil 14','Cooking meal zGoldFood','Star Sign 69','Bribe 36','Pristine Charm 14','Beanstacker Trainee achievement','Beanstacker Prodigy achievement','Summoning ballot bonus 26','Talent 209 bonus','Companion 48','Legend talent bonus 25','Cropfall event card','5th Anniversary event card','Companion 155','Vault upgrade 86','Jelly Operator obstruction rewards 10 and 51'];
function parse(v){if(typeof v!=='string')return v;try{return JSON.parse(v)}catch{return v}}
function get(data,raw,key){for(const src of [data,raw,raw?.data])if(src&&src[key]!==undefined)return parse(src[key]);return null}
function containers(data,raw){const out=[];function walk(v,depth){v=parse(v);if(!v||typeof v!=='object'||depth>4)return;for(const [k,x] of Object.entries(v)){if(/bean.?stalk|bean.?stack/i.test(k))out.push(parse(x));else if(depth<2&&/^(data|account|options|world6)$/i.test(k))walk(x,depth+1)}}walk(data,0);walk(raw,0);return out}
function savedValue(food,index,sources){for(const src of sources){if(Array.isArray(src)){const v=src[index];if(Number.isFinite(Number(v)))return Number(v)}if(src&&typeof src==='object'){for(const key of [food.key,food.name,food.name.replaceAll(' ','_'),String(index)]){const v=parse(src[key]);if(Number.isFinite(Number(v)))return Number(v);if(v&&Number.isFinite(Number(v.amount??v.value??v.level)))return Number(v.amount??v.value??v.level)}}}return null}
function tier(value){if(value==null)return 0;if(value>=10000)return value>=1000000?3:value>=100000?2:1;return Math.max(0,Math.min(3,Math.floor(Number(value))))}
function runtimeMultiplier(data,raw){for(const src of [data,raw,raw?.data]){const dns=parse(src?.DNSM);for(const v of [src?.GfoodBonusMULTI,src?.GoldFoodBonusMulti,dns?.GfoodBonusMULTI,dns?.h?.GfoodBonusMULTI])if(Number.isFinite(Number(v))&&Number(v)>0)return Number(v)}return null}
function foodBonus(amount,level,multi=1){if(level<=0)return 0;const log=Math.log10(1+1000*Math.pow(10,level));return amount*multi*.05*log*(1+log/2.14)}
function calculatedMultiplier(data,raw){const runtime=runtimeMultiplier(data,raw);if(runtime!=null)return {multiplier:runtime,characters:[],source:'exported runtime value'};try{const characters=root.BeanValueEngine?.calculate?.(raw&&Object.keys(raw).length?raw:{data});if(characters?.length){const best=characters.reduce((a,b)=>b.multiplier>a.multiplier?b:a);return {multiplier:best.multiplier,characters,source:characters.length>1?`${best.name} (highest character value)`:'loaded save'}}}catch(e){console.warn('Beanstalk total calculation failed',e)}return {multiplier:null,characters:[],source:null}}
function model(data,raw){const ninja=get(data,raw,'Ninja'),saved=Array.isArray(ninja?.[104])?ninja[104]:null,sources=saved?[saved]:containers(data,raw),calc=calculatedMultiplier(data,raw),multi=calc.multiplier;return {available:!!saved||sources.length>0,multiplier:multi,multiplierSource:calc.source,characters:calc.characters,totalBonus:multi==null?null:(multi-1)*100,foods:foods.map((x,i)=>{const value=savedValue(x,i,sources),level=tier(value);return {...x,value,level,baseBonus:foodBonus(x.amount,level,1),bonus:foodBonus(x.amount,level,multi??1),nextBonus:level<3?foodBonus(x.amount,level+1,multi??1):null}})}}
const fmt=v=>Number(v).toLocaleString(undefined,{maximumFractionDigits:2});
function gameTotal(v){if(v>=100000&&v<1000000)return Math.ceil(v/1000)+'K';if(v>=10000&&v<100000)return Math.ceil(v/100)/10+'K';if(v>=1000&&v<10000)return Math.ceil(v/10)/100+'K';return short(v);}
function short(v){return root.ProgressionModels?root.ProgressionModels.fmt(v):fmt(v)}
function sourceGuide(source,b){
 const value=source.value,name=source.name;
 const capped=(cap,action)=>({kind:value>=cap?'Capped':'Hard cap',cap,action});
 if(name==='Card')return capped(100,'Each event card is capped at +50%. Collect and upgrade Cropfall and 5th Anniversary cards.');
 if(name==='Jelly Operator')return capped(300,'Defeat obstruction 11 for +100%, then obstruction 52 for another +200%.');
 if(name==='Achievement')return capped(5,'Complete the Golden Food achievement. This is a fixed unlock.');
 if(name==='Achievements')return capped(5,'Complete Beanstacker Trainee (+2%) and Prodigy (+3%).');
 const guidance={
 'Meal':['Multiple multipliers','Raise Yumi Peachring, its mastery and ribbon; improve Summoning meal rewards, Lab and shiny-pet bonuses.'],
 'Bubble':['Diminishing returns','Level SHIMMERON; improve its alchemy multipliers. The effective ceiling depends on your account bonuses.'],
 'Stamp':['Level scaling','Upgrade Golden Apple Stamp and stamp bonus multipliers. No fixed practical cap is assumed.'],
 'Talent':['Diminishing returns','Raise Haungry for Gold and your available talent-level cap.'],
 'Sigil':['Tier upgrades','Charge Emoji Veggie to the next sigil tier; improve sigil bonus multipliers.'],
 'Apocalypse Wow':['Milestone scaling','Reach 1 billion kills on more monsters with Death Bringer and level Apocalypse Wow.'],
 'Star Sign':['Conditional bonus','Activate Beanbie Major; check infinite star signs and star-sign bonus multipliers.'],
 'Bribe':['Fixed unlock','Buy Gold from Lead in the bribe shop.'],
 'Charm':['Fixed unlock','Collect the Gumm Stick pristine charm in Sneaking.'],
 'Vote':['Temporary bonus','This depends on the active Summoning ballot bonus; it is not a permanent upgrade.'],
 'Legend Talent':['Talent levels','Invest in the Golden Food legend talent; available points and level caps depend on progression.'],
 'Vault Upgrade':['Upgrade levels','Level the Golden Food upgrade in the Upgrade Vault.'],
 'Purp Mushroom Companion':['Companion tiers','Obtain or upgrade Purp Mushroom; borrowed companions use base strength.'],
 'Vanillie Companion':['Companion tiers','Obtain or upgrade Vanillie; borrowed companions use base strength.'],
 'Verminous Companion':['Companion tiers','Verminous boosts both the additive bonus and the outer multiplier.'],
 'Equipment':['Equipment-dependent','Check equipped items for Golden Food effect; compare the same character in-game.'],
 'Obols':['Equipment-dependent','Equip available Golden Food effect obols and compare their trade-offs.'],
 'Gallery':['Collection scaling','Review Gallery bonuses for Golden Food effect.'],
 'Hat Rack':['Collection scaling','Review collected hats for Golden Food effect.']};
 const g=guidance[name]||['Account-dependent','Check this source’s upgrade page. No verified fixed cap is shown.'];return {kind:g[0],action:g[1]};
}
function improvementHtml(b){
 const meal=b.sources.find(x=>x.name==='Meal');
 return '<section class="bean-improvement"><h4>Practical targets</h4><p>Milestones below are planning targets, not a universal soft cap. Costs and other benefits still matter.</p>'+b.meals.map(x=>{const target=[5,15,45,95].find(n=>n>x.mastery),fraction=x.mastery/(x.mastery+5);return '<article><strong>'+esc(x.name)+' mastery · Diminishing returns</strong><p>'+fmt(fraction*100)+'% of the extra mastery bonus reached. The multiplier approaches 2×; there is no finite hard cap.</p><progress max="100" value="'+fraction*100+'" aria-label="Cooking mastery scaling progress"></progress><p>'+(target?'Next reference target: mastery '+target+' ('+fmt((1+target/(target+5)))+'×). Estimated total gain: +'+fmt((meal?.contribution||0)*((1+target/(target+5))/x.masteryMulti-1))+' percentage points, with all other bonuses held fixed.':'Past mastery 95 (95% of the extra bonus). Compare further mastery costs with meal levels, ribbons and other sources.')+'</p><small>50% at mastery 5 · 75% at 15 · 90% at 45 · 95% at 95</small></article>';}).join('')+'<p>For comparison: adding +100% to any additive source currently adds <b>+'+fmt(100*b.outer)+' percentage points</b> to your final total.</p></section>';
}
function breakdownHtml(m,id){
 const character=m.characters.find(x=>x.id===id)||m.characters.reduce((a,b)=>b.multiplier>a.multiplier?b:a,m.characters[0]);
 if(!character?.breakdown)return '<p class="collection-note">Source breakdown is unavailable for this export. Reload the save to recalculate.</p>';
 const b=character.breakdown;
 const names={'Talent':'Haungry for Gold talent','Stamp':'Golden Apple Stamp','Achievement':'Golden-food achievement','Bubble':'SHIMMERON bubble','Sigil':'Emoji Veggie sigil','Meal':'Cooking meals','Star Sign':'Beanbie Major star sign','Bribe':'Gold from Lead bribe','Charm':'Gumm Stick pristine charm','Achievements':'Beanstacker achievements','Vote':'Summoning ballot','Card':'Cropfall + Anniversary cards','Legend Talent':'Legend talent: Golden Food','Vault Upgrade':'Upgrade Vault 86','Armor Set':'Secret Class equipment set'};
 return '<div class="bean-breakdown-heading"><h3>Golden Food bonus breakdown</h3><label>Character <select id="beanBreakdownCharacter">'+m.characters.map(x=>'<option value="'+x.id+'" '+(x.id===character.id?'selected':'')+'>'+esc(x.name)+'</option>').join('')+'</select></label></div><p>Calculated total for '+esc(character.name)+': <strong>+'+fmt(character.percent)+'%</strong></p><p class="muted">Source percentages add together before the outer multiplier. The last column shows their contribution to the final total in percentage points.</p><div class="bean-breakdown-factors"><p>Family baseline: <b>'+fmt(b.family)+'×</b></p>'+b.multipliers.map(x=>'<p>'+esc(names[x.name]||x.name)+': <b>+'+fmt(x.value)+'%</b></p>').join('')+'<p>Combined outer multiplier: <b>'+fmt(b.outer)+'×</b></p></div><div class="bean-breakdown-scroll"><table><thead><tr><th>Source</th><th>Source bonus</th><th>Final contribution</th><th>Scaling & next step</th></tr></thead><tbody>'+[...b.sources].sort((a,b)=>b.value-a.value).map(x=>'<tr><th>'+esc(names[x.name]||x.name)+'</th><td>+'+fmt(x.value)+'%</td><td>+'+fmt(x.contribution)+' pp</td><td class="bean-source-guide">'+(()=>{const g=sourceGuide(x,b);return '<b>'+g.kind+'</b>'+(g.cap?'<progress max="'+g.cap+'" value="'+Math.min(g.cap,x.value)+'" aria-label="'+esc(x.name)+' cap progress"></progress><small>'+fmt(x.value)+' / '+g.cap+'%</small>':'')+'<span>'+esc(g.action)+'</span>';})()+'</td></tr>').join('')+'<tr><th>Family baseline + outer multiplier</th><td>Base contribution</td><td>+'+fmt(b.baselineContribution)+' pp</td><td>Baseline contribution; already includes the combined outer multiplier.</td></tr></tbody><tfoot><tr><th>Total</th><td></td><td>+'+fmt(character.percent)+'%</td><td></td></tr></tfoot></table></div>'+improvementHtml(b)+'<details><summary>Cooking contribution details</summary>'+b.meals.map(x=>'<p>'+esc(x.name)+' · Meal Lv '+x.level+' · Mastery Lv '+x.mastery+' ('+fmt(x.masteryMulti)+'×) · Ribbon Lv '+x.ribbon+'</p>').join('')+'<p>Cooking’s contribution above already includes mastery, ribbons, Lab, shiny pets, Summoning winner bonuses, and the meal companion.</p></details><p class="muted">Check against the same character in-game. The main Beanstalk total uses the highest calculated character. Values reflect this saved export.</p>';
}
function render(host,data,raw){const m=model(data,raw),done=m.foods.filter(x=>x.level>0).length,tiers=[1,2,3].map(n=>m.foods.filter(x=>x.level>=n).length),calculated=m.multiplier!=null;host.innerHTML=`<div class="bean-hero"><div><p class="eyebrow">World 6 · Ninja Castle</p><h2>Beanstalk</h2><p>Permanent, account-wide Golden Food bonuses from deposited stacks.</p></div><strong>${done} / ${m.foods.length} added</strong></div><div class="bean-summary"><article><span>Total Golden Food Bonus</span><strong>${m.totalBonus==null?'Unavailable':`+${gameTotal(m.totalBonus)}%`}</strong><small>${m.multiplierSource||'Could not calculate from this export'}</small>${m.totalBonus==null?'':`<small>Exact: +${fmt(m.totalBonus)}% · rounded up as in-game</small>`}</article><article><span>10K completed</span><strong>${tiers[0]} / ${m.foods.length}</strong></article><article><span>100K completed</span><strong>${tiers[1]} / ${m.foods.length}</strong></article><article><span>1M completed</span><strong>${tiers[2]} / ${m.foods.length}</strong></article></div><p class="collection-note">Each food has three permanent deposit milestones: 10K, 100K, then 1M. Tiles compare your current bonus with the next tier, using the highest calculated character multiplier. Other characters may receive different final values.</p><details class="bean-breakdown"><summary>Golden Food breakdown & improvement guide</summary><div id="beanBreakdown">${breakdownHtml(m)}</div></details><div class="bean-key"><span><b>10K</b> Base</span><span><b>100K</b> Supersized</span><span><b>1M</b> Millionmega</span></div>${!m.available?'<p class="collection-note">Beanstalk deposit data was not found in this export. The full food checklist is shown below.</p>':''}<div class="bean-grid">${m.foods.map(x=>`<article class="bean-card tier-${x.level} ${x.level===0?'arcade-zero':''}"><img src="${x.icon}" alt=""><div><strong>${esc(x.name)}</strong><span>${esc(x.effect)}</span><b>+${short(x.bonus)}${x.unit}${calculated?'':' base'}</b>${x.nextBonus==null?'<small>Maximum tier</small>':`<small>Next: +${short(x.nextBonus)}${x.unit} (${short(x.nextBonus-x.bonus)} gain)</small>`}</div><progress max="3" value="${x.level}" aria-label="${esc(x.name)} deposit tiers"></progress><div class="bean-milestones"><i class="${x.level>=1?'done':''}">10K</i><i class="${x.level>=2?'done':''}">100K</i><i class="${x.level>=3?'done':''}">1M</i></div></article>`).join('')}</div>`;const panel=host.querySelector('#beanBreakdown');const bind=()=>{const select=panel.querySelector('select');if(select)select.onchange=()=>{panel.innerHTML=breakdownHtml(m,Number(select.value));bind();};};bind();}
const api={foods,sourceNames,tier,foodBonus,model,render,gameTotal,sourceGuide};if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.Beanstalk=api;
})(typeof window!=='undefined'?window:globalThis);
