(function(root){'use strict';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const foods=[
 ['PeanutG','Golden Peanut','Mining Efficiency',30,'%'],['ButterBar','Butter Bar','Base Accuracy',60,''],['FoodG1','Golden Jam','Maximum Health',30,'%'],['FoodG2','Golden Kebabs','Total Damage',20,'%'],['FoodG3','Golden Meat Pie','Total Defence',30,'%'],['FoodG4','Golden Nomwich','Base Damage',400,''],['FoodG5','Golden Ham','Skill EXP',18,'%'],['FoodG6','Golden Bread','Coins from Monsters',30,'%'],['FoodG7','Golden Ribs','Fishing Efficiency',40,'%'],['FoodG8','Golden Cheese','Shrine AFK Leveling',20,'%'],['FoodG9','Golden Grilled Cheese Nomwich','STR, AGI, WIS and LUK',10,'%'],['FoodG10','Golden Hampter Gummy Candy','Sailing AFK Time',23,'%'],['FoodG11','Golden Nigiri','Class EXP',40,'%'],['FoodG12','Golden Dumpling','AFK Gains Rate',4,'%'],['FoodG13','Golden Cake','Drop Rate',8,'%'],['FoodG14','Golden Saltwater Taffy','Spelunking EXP',1,'%'],['FoodG15','Golden Sugar Cookie','Golden Food Effect',2,'%']
].map((x,id)=>({id,key:x[0],name:x[1],effect:x[2],amount:x[3],unit:x[4],icon:`assets/${x[0]}.png`}));
const sourceNames=['Secret Class equipment set','King Doot companion (ID 174)','Pet arena familiar bonus 66','Miscellaneous account bonus 8','Star talent 99','Golden Food stamp bonuses','Achievement 37','Alchemy GFoodz bubbles','Sigil 14','Cooking meal zGoldFood','Star Sign 69','Bribe 36','Pristine Charm 14','Beanstacker Trainee achievement','Beanstacker Prodigy achievement','Summoning ballot bonus 26','Talent 209 bonus','Companion 48','Legend talent bonus 25','Cropfall event card','5th Anniversary event card','Companion 155','Vault upgrade 86','Jelly Research bonuses 10 and 51'];
function parse(v){if(typeof v!=='string')return v;try{return JSON.parse(v)}catch{return v}}
function get(data,raw,key){for(const src of [data,raw,raw?.data])if(src&&src[key]!==undefined)return parse(src[key]);return null}
function containers(data,raw){const out=[];function walk(v,depth){v=parse(v);if(!v||typeof v!=='object'||depth>4)return;for(const [k,x] of Object.entries(v)){if(/bean.?stalk|bean.?stack/i.test(k))out.push(parse(x));else if(depth<2&&/^(data|account|options|world6)$/i.test(k))walk(x,depth+1)}}walk(data,0);walk(raw,0);return out}
function savedValue(food,index,sources){for(const src of sources){if(Array.isArray(src)){const v=src[index];if(Number.isFinite(Number(v)))return Number(v)}if(src&&typeof src==='object'){for(const key of [food.key,food.name,food.name.replaceAll(' ','_'),String(index)]){const v=parse(src[key]);if(Number.isFinite(Number(v)))return Number(v);if(v&&Number.isFinite(Number(v.amount??v.value??v.level)))return Number(v.amount??v.value??v.level)}}}return null}
function tier(value){if(value==null)return 0;if(value>=10000)return value>=1000000?3:value>=100000?2:1;return Math.max(0,Math.min(3,Math.floor(Number(value))))}
function runtimeMultiplier(data,raw){for(const src of [data,raw,raw?.data]){const dns=parse(src?.DNSM);for(const v of [src?.GfoodBonusMULTI,src?.GoldFoodBonusMulti,dns?.GfoodBonusMULTI,dns?.h?.GfoodBonusMULTI])if(Number.isFinite(Number(v))&&Number(v)>0)return Number(v)}return null}
function foodBonus(amount,level,multi=1){if(level<=0)return 0;const log=Math.log10(1+1000*Math.pow(10,level));return amount*multi*.05*log*(1+log/2.14)}
function calculatedMultiplier(data,raw){const runtime=runtimeMultiplier(data,raw);if(runtime!=null)return {multiplier:runtime,characters:[],source:'exported runtime value'};try{const characters=root.BeanValueEngine?.calculate?.(raw&&Object.keys(raw).length?raw:{data});if(characters?.length){const best=characters.reduce((a,b)=>b.multiplier>a.multiplier?b:a);return {multiplier:best.multiplier,characters,source:characters.length>1?`${best.name} (highest character value)`:'loaded save'}}}catch(e){console.warn('Beanstalk total calculation failed',e)}return {multiplier:null,characters:[],source:null}}
function model(data,raw){const ninja=get(data,raw,'Ninja'),saved=Array.isArray(ninja?.[104])?ninja[104]:null,sources=saved?[saved]:containers(data,raw),calc=calculatedMultiplier(data,raw),multi=calc.multiplier;return {available:!!saved||sources.length>0,multiplier:multi,multiplierSource:calc.source,characters:calc.characters,totalBonus:multi==null?null:(multi-1)*100,foods:foods.map((x,i)=>{const value=savedValue(x,i,sources),level=tier(value);return {...x,value,level,baseBonus:foodBonus(x.amount,level,1),bonus:foodBonus(x.amount,level,multi??1),nextBonus:level<3?foodBonus(x.amount,level+1,multi??1):null}})}}
const fmt=v=>Number(v).toLocaleString(undefined,{maximumFractionDigits:2});
function short(v){return root.ProgressionModels?root.ProgressionModels.fmt(v):fmt(v)}
function render(host,data,raw){const m=model(data,raw),done=m.foods.filter(x=>x.level>0).length,tiers=[1,2,3].map(n=>m.foods.filter(x=>x.level>=n).length),calculated=m.multiplier!=null;host.innerHTML=`<div class="bean-hero"><div><p class="eyebrow">World 6 · Ninja Castle</p><h2>Beanstalk</h2><p>Permanent, account-wide Golden Food bonuses from deposited stacks.</p></div><strong>${done} / ${m.foods.length} added</strong></div><div class="bean-summary"><article><span>Total Golden Food Bonus</span><strong>${m.totalBonus==null?'Unavailable':`+${short(m.totalBonus)}%`}</strong><small>${m.multiplierSource||'Could not calculate from this export'}</small></article><article><span>10K completed</span><strong>${tiers[0]} / ${m.foods.length}</strong></article><article><span>100K completed</span><strong>${tiers[1]} / ${m.foods.length}</strong></article><article><span>1M completed</span><strong>${tiers[2]} / ${m.foods.length}</strong></article></div>${m.characters.length>1?`<details class="garden-help"><summary>Golden Food bonus by character</summary><div class="bean-character-values">${m.characters.map(x=>`<span>${esc(x.name)} <b>+${short(x.percent)}%</b></span>`).join('')}</div></details>`:''}<p class="collection-note">Each food has three permanent deposit milestones: 10K, 100K, then 1M. Tiles compare your current bonus with the next tier, using the highest calculated character multiplier. Other characters may receive different final values.</p><div class="bean-key"><span><b>10K</b> Base</span><span><b>100K</b> Supersized</span><span><b>1M</b> Millionmega</span></div>${!m.available?'<p class="collection-note">Beanstalk deposit data was not found in this export. The full food checklist is shown below.</p>':''}<div class="bean-grid">${m.foods.map(x=>`<article class="bean-card tier-${x.level} ${x.level===0?'arcade-zero':''}"><img src="${x.icon}" alt=""><div><strong>${esc(x.name)}</strong><span>${esc(x.effect)}</span><b>+${short(x.bonus)}${x.unit}${calculated?'':' base'}</b>${x.nextBonus==null?'<small>Maximum tier</small>':`<small>Next: +${short(x.nextBonus)}${x.unit} (${short(x.nextBonus-x.bonus)} gain)</small>`}</div><progress max="3" value="${x.level}" aria-label="${esc(x.name)} deposit tiers"></progress><div class="bean-milestones"><i class="${x.level>=1?'done':''}">10K</i><i class="${x.level>=2?'done':''}">100K</i><i class="${x.level>=3?'done':''}">1M</i></div></article>`).join('')}</div>`;}
const api={foods,sourceNames,tier,foodBonus,model,render};if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.Beanstalk=api;
})(typeof window!=='undefined'?window:globalThis);
