(function(root){'use strict';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=v=>Number.isFinite(Number(v))?Number(v):0,fmt=v=>num(v).toLocaleString(undefined,{maximumFractionDigits:2});
const words=v=>String(v??'').replace(/([a-z])([A-Z])/g,'$1 $2').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
const fill=(text,value)=>String(text||'Bonus').replace(/[{}]/g,fmt(value)).replaceAll('@',' ').replaceAll('~',' ').replace(/\s+/g,' ').trim();
const effect=(text,value)=>String(text||'Bonus').replace('+{%',`+${fmt(value)}%`).replace('}x',`${fmt(value)}x`).replace('$%',`${fmt(value)}%`).replace('+{',`+${fmt(value)}`).replaceAll('@',' ').replaceAll('~',' ').replace(/\s+/g,' ').trim();
let cachedRoot=null,cached=null;
function systems(rawRoot={}){if(rawRoot===cachedRoot&&cached)return cached;cachedRoot=rawRoot;try{cached=root.BeanValueEngine?.systems?.(rawRoot)||new Map();}catch{cached=new Map();}return cached;}
function row(source,name,effect,level,status='active',icon=null,search=''){return{source,name,effect:String(effect||'Bonus'),level,status,icon,search};}
function getRows(rawRoot={}){const d=systems(rawRoot),groups={};
 const salt=d.get('saltLick');groups.saltLick=(salt?.bonuses||[]).map((x,i)=>row('Salt Lick',`Salt Lick Bonus ${i+1}`,salt.getBonusText?.(i)||fill(x.data?.desc,num(x.level)*num(x.data?.baseBonus)),`Lv ${num(x.level)} / ${num(x.data?.maxLevel)}`,num(x.level)?'active':'missing'));
 const alch=d.get('alchemy');groups.vials=(alch?.vials||[]).map(x=>row('Alchemy Vials',x.name,x.getBonusText?.()||fill(x.description,x.getBonus?.()),`Lv ${num(x.level)}${num(x.level)>=13?' · MAX':''}`,num(x.level)?'active':'missing'));
 const sig=d.get('sigils');groups.sigils=(sig?.sigils||[]).map(x=>row('Alchemy Sigils',x.data?.name,x.getBonusText?.()||fill(x.data?.desc,x.getBonus?.()),num(x.boostLevel)?`Boost ${num(x.boostLevel)}`:num(x.progress)?`${fmt(x.progress)} charge`:'Locked',num(x.boostLevel)||num(x.progress)?'active':'missing'));
 const votes=d.get('votes');groups.votes=(votes?.bonuses||[]).map((x,i)=>{const active=i===num(votes.currentBonusIndex);return row('Weekly Votes',`Vote Bonus ${i+1}`,fill(x.data?.text,x.data?.bonus),active?'Current weekly bonus':'Not active',active?'active':'missing');});
 const kill=d.get('killroy');groups.killroy=kill?Object.entries(kill).filter(([k,v])=>typeof v==='number'||typeof v==='boolean').map(([k,v])=>row('Killroy Prime',words(k),typeof v==='boolean'?(v?'Unlocked':'Locked'):`${fmt(v)}× multiplier`,'Account total',v?'active':'missing')):[];
 const breed=d.get('breeding');groups.shinyPets=(breed?.shinyBonuses||[]).map(x=>row('Shiny Pets',fill(x.data?.text,x.getBonus?.()).replace(/^\+/,''),fill(x.data?.text,x.getBonus?.()),`${num(x.totalLevels)} total shiny levels`,num(x.totalLevels)?'active':'missing'));
 const vault=d.get('upgradeVault');groups.upgradeVault=(vault?.bonuses||[]).map(x=>row('Upgrade Vault',x.data?.name,x.getDescription?.()||fill(x.data?.description_line1,x.getBonus?.()),x.unlocked?`Lv ${num(x.level)} / ${num(x.data?.max_level)}`:'Locked',x.unlocked&&num(x.level)?'active':'missing'));
 const gaming=d.get('gaming');groups.gamingPalette=(gaming?.paletteColors||[]).map((x,i)=>{const bonus=gaming.getPaletteBonus?.(i),effect=fill(x.data?.bonus,bonus);return row('Gaming Palette',x.data?.name,effect,`Lv ${num(x.level)}`,num(x.level)&&!/nothing yet/i.test(effect)?'active':'missing');});
 const legend=d.get('legendTalents');groups.legendTalents=(legend?.talents||[]).map(x=>row('Legend Talents',x.data?.name,x.getDesc?.()||fill(x.data?.description,x.getBonus?.()),`Lv ${num(x.level)} / ${num(x.data?.maxLevel)}`,num(x.level)?'active':'missing'));
 const emperor=d.get('emperor');groups.emperorBonuses=(emperor?.emperorBonuses||[]).map(x=>{const value=typeof x.getBonus==='function'?x.getBonus():num(x.data?.bonusValue)*num(x.level),template=x.data?.bonusName,name=String(template||`Emperor Bonus ${num(x.index)+1}`).replace(/^\+?\{%?\s*|^\}x\s*|^\$%\s*/,'').trim();return row('Emperor Bonuses',name,effect(template,value),`Lv ${num(x.level)} · ${num(emperor.emperorKills)} Emperor kills`,num(x.level)?'active':'missing');});
 for(const [key,source] of [['compass','Compass'],['grimoire','Grimoire'],['tesseract','Tesseract']]){const system=d.get(key),upgrades=system?.upgrades||[];groups[key]=upgrades.map(x=>{let description=x.data?.description||'Upgrade bonus';try{description=x.getDescription?.(upgrades)||description;}catch{}const max=num(x.data?.maxLevel??x.data?.max_level),level=num(x.level),levelText=`Lv ${level}${max&&max<999999?` / ${max}`:''}`;return row(source,x.data?.name||`${source} Upgrade ${num(x.id)+1}`,description,x.unlocked?levelText:`Locked · ${levelText}`,x.unlocked&&level?'active':'missing',null,`${x.data?.upgradeType||''} cost ${fmt(x.cost)}`);});}
 const signs=d.get('starsigns'),infinite=new Set((signs?.infinityStarSigns||[]).map(x=>x.name));groups.starSigns=(signs?.unlockedStarSigns||[]).map(x=>{const multi=num(x.seraphCosmosBonus)||1,merit=1+num(x.meritocratyBonus)/100,chip=x.hasChip?2:1,description=(x.bonuses||[]).map(b=>`${num(b.bonus)*multi*merit*chip<0?'':'+'}${fmt(num(b.bonus)*multi*merit*chip)}${b.percent?'%':''} ${b.text}`).join(' · '),always=infinite.has(x.name);return row('Star Signs',x.name,description,always?'Infinite Star Sign':x.aligned?'Currently aligned':'Unlocked, not aligned',always||x.aligned?'active':'missing');});
 const constellations=Object.values(d.get('constellations')||{});groups.constellations=constellations.map(x=>row('Constellations',x.data?.name||`Constellation ${num(x.index)+1}`,x.data?.requirement||`Awards ${num(x.data?.starChartPoints)} star chart points`,x.isComplete?`Completed · ${num(x.data?.starChartPoints)} points`:'Incomplete',x.isComplete?'active':'missing',null,x.data?.area||''));
 const shrines=Object.values(d.get('shrines')||{});groups.shrines=shrines.map(x=>{let description=x.boost||'Shrine bonus';try{description=x.getBonusText?.()||description;}catch{}return row('Shrines',x.name,description,`Lv ${num(x.level)}${x.worldTour?' · World Tour':''}`,num(x.level)?'active':'missing');});
 const death=d.get('deathnote'),killMap=death?.getKillsMap?.()||new Map();groups.deathNote=[];for(const [world,mobs] of killMap)for(const [name,kills] of mobs){const rank=world==='Minibosses'?death.getDeathnoteMinibossRank(kills):death.getDeathnoteRank(kills),next=world==='Minibosses'?death.getNextMinibossRankReq(rank):death.getNextRankReq(rank);groups.deathNote.push(row('Death Note',name,`Skull rank ${rank} contributing to ${world} multikill`,`${fmt(kills)} kills${next?` · next ${fmt(next)}`:' · MAX'}`,rank?'active':'missing',null,world));}
 const forge=d.get('forge');groups.forgeBonuses=(forge?.upgrades||[]).map(x=>row('Forge Bonuses',x.name,x.getBonusText?.()||fill(x.bonus,x.getBonus?.()),`Lv ${num(x.level)} / ${num(x.maxLevel)}`,num(x.level)?'active':'missing'));
 const shop=d.get('eventShop');groups.eventShop=(shop?.bonuses||[]).map(x=>row('Event Shop',x.data?.name,x.data?.desc,x.owned?'Owned':`Not owned · ${num(x.data?.price)} event points`,x.owned?'active':'missing'));
 const family=d.get('family'),familyValues=family?.classBonus?.values?[...family.classBonus.values()]:[];groups.familyBonuses=familyValues.filter(x=>x.bonus!=='FILLER').map((x,i)=>{let description='';try{description=x.getBonusText?.()||'';}catch{}description=description||effect(String(x.bonus).replaceAll('_',' ').replaceAll('|',' '),x.value);return row('Family Bonuses',`Family Bonus ${i+1}`,description,`Character ${num(x.playerID)+1} · Class ${num(x.classIndex)}`,num(x.value)?'active':'missing');});
 for(const [key,source] of [['orion','Orion'],['poppy','Poppy'],['bubba','Bubba']]){const system=d.get(key);groups[key]=(system?.bonuses||[]).map(x=>{const value=system.getGlobalBonus?.(x.index)??x.value??0,template=x.desc||x.data?.desc;return row(source,`${source} Bonus ${num(x.index)+1}`,effect(template,value),key==='bubba'&&!system.unlocked?'Clicker not unlocked':'Permanent clicker bonus',value&&!(key==='bubba'&&!system.unlocked)?'active':'missing');});}
 const clam=d.get('clamworks');groups.clamworks=[...(clam?.workBonuses||[]).map((x,i)=>row('Clamworks',`Clam Work ${i+1}`,clam.getClamBonusText?.(i)||x.data?.description,`Lv ${num(x.level)}`,num(x.level)?'active':'missing')),...(clam?.promoBonuses||[]).map((x,i)=>row('Clamworks Promotions',`Promotion ${i+1}`,x.bonus,x.active?`Active · Promo ${num(clam.promoLevel)}`:`Locked · Promo ${num(clam.promoLevel)}`,x.active?'active':'missing'))];
 const merit=d.get('meritocraty');groups.meritocracy=(merit?.bonuses||[]).map((x,i)=>{const active=i===num(merit.currentBonusIndex);return row('Meritocracy',`Merit Bonus ${i+1}`,effect(x.data?.text,x.data?.bonus),active?'Current bonus':'Not selected',active?'active':'missing');});
 const fish=d.get('bigFish');groups.bigFish=(fish?.bonuses||[]).map(x=>row('Big Fish',x.data?.name,x.getBonusText?.()||effect(x.data?.desc,x.getBonus?.()),x.unlocked?`Lv ${num(x.level)}`:'Locked',x.unlocked&&num(x.level)?'active':'missing'));
 const kid=d.get('coralKid');groups.coralKid=(kid?.coralKidBonuses||[]).map((x,i)=>row('Coral Kid',`Coral Kid Bonus ${i+1}`,x.getBonusText?.()||effect(x.bonus,x.getBonus?.()),`Lv ${num(x.level)}`,num(x.level)?'active':'missing'));
 const reef=d.get('coralReef');groups.coralReef=(reef?.upgrades||[]).map((x,i)=>row('Coral Reef',`Coral Reef Upgrade ${i+1}`,x.getBonusText?.()||x.data?.desc,x.unlocked?`Lv ${num(x.level)}`:'Locked',x.unlocked&&num(x.level)?'active':'missing'));
 const dance=d.get('dancingCoral');groups.dancingCoral=(dance?.bonuses||[]).map(x=>row('Dancing Coral',x.data?.name,x.getBonusText?.()||effect(x.data?.desc,x.getBonus?.()),x.purchased?'Purchased':'Not purchased',x.purchased?'active':'missing'));
 for(const [key,source] of [['hoops','Hoops'],['darts','Darts']]){const system=d.get(key);groups[key]=(system?.bonuses||[]).map(x=>row(source,`${source} Bonus ${num(x.index)+1}`,x.getBonusText?.()||effect(x.desc,x.getBonus?.()),x.unlocked?`Lv ${num(x.level)} · Best ${num(system.highestScore)}`:`Unlock at score ${num(x.unlockThreshold)}`,x.unlocked&&num(x.level)?'active':'missing'));}
 const zen=d.get('zenithMarket');groups.zenithMarket=(zen?.bonuses||[]).map(x=>row('Zenith Market',x.data?.name,effect(x.data?.description,x.getBonus?.()),`Lv ${num(x.level)} / ${num(x.data?.maxLevel)}`,num(x.level)?'active':'missing'));
 const lab=d.get('lab');groups.labMainframe=(lab?.bonuses||[]).map(x=>row('Lab Mainframe',x.name,x.getBonusText?.()||x.description,x.active?'Active connection':x.unlocked?'Unlocked, disconnected':'Locked',x.active?'active':'missing'));groups.labJewels=(lab?.jewels||[]).map(x=>row('Lab Jewels',x.data?.name,x.getBonusText?.()||effect(x.data?.effect,x.getBonus?.()),x.active?'Active':x.available?'Owned, disconnected':'Not owned',x.active?'active':'missing'));
 const collider=d.get('collider');groups.atomCollider=(collider?.atoms||[]).map(x=>row('Atom Collider',x.data?.name,effect(x.data?.desc,num(x.level)*num(x.data?.bonusPerLv)),`Lv ${num(x.level)}`,num(x.level)?'active':'missing'));
 const islands=d.get('islandExpeditions');groups.islandExpeditions=islands?[row('Island Expeditions','Shovel Speed',`+${fmt(islands.bonusToShovelSpeed)}% Shovel Speed`,'Expedition reward',num(islands.bonusToShovelSpeed)?'active':'missing'),row('Island Expeditions','Kitchen Cost Reduction',`${fmt(islands.reductionToKitchenCosts)}% cheaper Kitchen costs`,'Expedition reward',num(islands.reductionToKitchenCosts)?'active':'missing'),row('Island Expeditions','Star Talent Points',`+${fmt(islands.bonusStarTalentPoints)} Star Talent Points`,'Expedition reward',num(islands.bonusStarTalentPoints)?'active':'missing')]:[];
 const po=d.get('POExtra');groups.poExtras=po?[row('Post Office Extras','Orders Completed',`${fmt(po.complete)} completed Post Office orders`,'Account progress',num(po.complete)?'active':'missing'),row('Post Office Extras','Order Streak',`${fmt(po.streak)} current order streak`,'Account progress',num(po.streak)?'active':'missing'),row('Post Office Extras','Miscellaneous PO Progress',fmt(po.misc),'Saved total',num(po.misc)?'active':'missing')]:[];
 const sushi=d.get('sushi');groups.sushi=(sushi?.sushi||[]).map(x=>row('Sushi',x.data?.name,effect(x.data?.unlockDescription,x.getBonus?.()),x.unlocked?'Unlocked':'Locked',x.unlocked?'active':'missing',null,x.data?.knowledgeBonusCategory||''));
 const button=d.get('button');groups.button=(button?.bonuses||[]).map(x=>row('The Button',x.data?.name,`+${fmt(x.getBonus?.())}% ${x.data?.name}`,`${num(x.categoryPresses)} presses`,num(x.categoryPresses)?'active':'missing'));
 const anvils=d.get('anvil'),playerAnvils=anvils?.playerAnvils?Object.values(anvils.playerAnvils):[];groups.anvilUpgrades=playerAnvils.map(x=>row('Anvil Upgrades',`Character ${num(x.playerID)+1}`,`${fmt(x.anvilSpeed)} production speed · ${fmt(x.anvilXP)}× XP · ${fmt(x.productCapacity)} capacity`,`${num(x.speedPoints)} speed · ${num(x.capPoints)} capacity points`,num(x.speedPoints)||num(x.capPoints)||num(x.xpPoints)?'active':'missing'));
 const gems=d.get('gems');groups.gemShop=(gems?.purchases||[]).filter(x=>/^(?:Gem[QP]\d+|InvBag21|InvStorage31|InvStorage99|Pdaily[01]|ClassSwapC)$/.test(x.name)&&x.maxPurchases<100000).map(x=>{const code=x.name,title=x.itemName&&!/Infinite Forge/i.test(x.itemName)?x.itemName:words(code),owned=num(x.pucrhased),max=num(x.maxPurchases);return Object.assign(row('Gem Shop',title,String(x.desc||'Permanent Gem Shop upgrade').replace(/<br\s*\/?\s*>/gi,' '),`${owned} / ${max} purchased`,owned>=max?'maxed':owned?'active':'missing',`assets/${code}.png`),{code,index:num(x.index),owned,max,cost:num(x.cost),costIncrement:num(x.costIncrement)});});
 const friendRaw=rawRoot?.serverVars?.A_friendBons??rawRoot?.A_friendBons,friendIds=String(friendRaw??'').split(',').map(Number).filter(Number.isFinite);groups.friendBonuses=friendRaw==null?[]:friendIds.map((id,i)=>row('Friend Bonuses',`Active Friend Bonus ${i+1}`,`Saved friend bonus type ${id}; its live strength depends on the sender's account level.`,`Slot ${i+1} · Type ${id}`,'active'));
 const hole=d.get('hole'),majiks=hole?.majiks?Object.values(hole.majiks).flat():[];groups.holeSchematics=(hole?.schematics||[]).map(x=>row('The Hole · Schematics',x.data?.name,x.getDescription?.()||effect(x.data?.desc,x.getBonus?.()),x.unlocked?'Created':`Missing · ${fmt(x.data?.baseCost)} ${x.data?.costType||''}`,x.unlocked?'active':'missing'));
 groups.holeMajik=majiks.map(x=>row('The Hole · Conjuror Majik',x.data?.name,x.getDescription?.()||effect(x.data?.desc,x.getBonus?.()),x.unlocked?`Lv ${num(x.level)}`:'Locked',x.unlocked&&num(x.level)?'active':'missing'));
 groups.holeStudies=(hole?.studies||[]).map(x=>row('The Hole · Studies',x.data?.name,x.getDescription?.()||effect(x.data?.description,x.getBonus?.()),x.unlocked?`Lv ${num(x.level)}`:'Locked',x.unlocked&&num(x.level)?'active':'missing'));
 groups.holeMeasurements=(hole?.measurements||[]).map(x=>row('The Hole · Measurements',x.data?.measurementType?.name||`Measurement ${num(x.index)+1}`,x.getDescription?.()||effect(x.data?.description,x.getBonus?.()),x.unlocked?`Lv ${num(x.level)}`:'Locked',x.unlocked&&num(x.level)?'active':'missing'));
 groups.holeBell=[...(hole?.bell?.improvements||[]).map(x=>row('The Hole · Bell Improvements',`Bell Improvement ${num(x.index)+1}`,effect(x.data?.bonus,num(x.level)*num(x.data?.baseValue)),`Lv ${num(x.level)} · ${x.data?.resource||'resource'}`,num(x.level)?'active':'missing')),...(hole?.bell?.bonuses||[]).map(x=>row('The Hole · Bell Bonuses',`Bell Bonus ${num(x.index)+1}`,x.getDescription?.()||effect(x.data?.description,x.getBonus?.()),`Lv ${num(x.level)}`,num(x.level)?'active':'missing'))];
 groups.holeWell=[...(hole?.well?.sediments||[]).map(x=>row('The Hole · Well',x.data?.name,`${fmt(x.current)} / ${fmt(x.currentMax)} sediment`,`Bar expansions ${num(x.expansions)}`,x.unlocked?'active':'missing')),...(hole?.well?.buckets||[]).map((x,i)=>row('The Hole · Well',`Bucket ${i+1}`,`Collects ${hole?.well?.sediments?.[num(x.sedimentIndex)]?.data?.name||`sediment ${num(x.sedimentIndex)+1}`}`,x.unlocked?'Unlocked':x.unlockMethod||'Locked',x.unlocked?'active':'missing'))];
 groups.holeFountain=(hole?.fountain?.upgrades||[]).map(x=>row('The Hole · Fountain',x.data?.name,effect(x.data?.description,x.getBonus?.()),`Lv ${num(x.level)} · Marble ${num(x.marbleizationLevel)}`,num(x.level)?'active':'missing'));
 groups.holeHarp=[...(hole?.harp?.strings||[]).map(x=>row('The Hole · Harp',`String ${x.data?.stringLetter||num(x.index)+1}`,x.getDescription?.()||effect(x.data?.description,x.getBonus?.()),x.unlocked?`Lv ${num(x.level)}`:'Locked',x.unlocked&&num(x.level)?'active':'missing')),...(hole?.harp?.notes||[]).map(x=>row('The Hole · Harp Notes',x.name,`${fmt(x.current)} notes`,'Current amount',num(x.current)?'active':'missing'))];
 groups.holeLamp=(hole?.lamp?.wishes||[]).map(x=>row('The Hole · Lamp',x.data?.name,String(x.data?.desc||'Lamp wish').replaceAll('@',' '),`${num(x.wishCount)} wishes`,num(x.wishCount)?'active':'missing'));
 groups.holeResources=Object.values(hole?.resourceCavrens?.cavrens||{}).map(x=>row('The Hole · Resource Caverns',x.name,`${x.efficiencyType} cavern extracting ${x.resource}`,`Layer ${num(x.layer)} · ${fmt(x.resourceExtracted)} extracted`,num(x.layer)||num(x.resourceExtracted)?'active':'missing'));
 groups.holeDawgDen=hole?.dawgDen?[row('The Hole · Dawg Den','Best Dawg Den Score',fmt(hole.dawgDen.bestScore),'Personal best',num(hole.dawgDen.bestScore)?'active':'missing')]:[];
 groups.holeJars=[...(hole?.jar?.jarTypes||[]).map((x,i)=>row('The Hole · Jars',x.data?.name||x.name||`Jar ${i+1}`,x.getDescription?.()||x.data?.description||'Jar progression',x.unlocked?'Unlocked':'Locked',x.unlocked?'active':'missing')),...(hole?.jar?.jarBonuses||[]).map((x,i)=>row('The Hole · Jar Bonuses',x.data?.name||`Jar Bonus ${i+1}`,x.getDescription?.()||effect(x.data?.description,x.getBonus?.()),`Lv ${num(x.level)}`,num(x.level)||x.unlocked?'active':'missing'))];
 const monuments=hole?.monuments?.monuments?Object.values(hole.monuments.monuments):[];groups.holeMonuments=monuments.flatMap(m=>(m.bonuses||[]).map(x=>row(`The Hole · ${m.name}`,`${m.name}: ${words(x.data?.description||`Bonus ${num(x.index)+1}`)}`,effect(x.data?.description,x.getBonus?.()),`Lv ${num(x.level)} · Round ${num(m.highestRound)}`,num(x.level)?'active':'missing')));
 groups.holeGambit=[...(hole?.gambit?.bonuses||[]).map(x=>row('The Hole · Gambit',String(x.data?.name||`Gambit Bonus ${num(x.index)+1}`).replace(/[{}]/g,fmt(x.getBonus?.())),effect(x.data?.description,x.getBonus?.()),x.unlocked?'Unlocked':`Requires ${fmt(x.getScoreThreshold?.())} points`,x.unlocked?'active':'missing')),...(hole?.gambit?.challenges||[]).map(x=>row('The Hole · Gambit Challenges',x.name,x.description,`${x.getDisplayTime?.()||fmt(x.maxTime)} · ${fmt(x.getScoreValue?.())} points`,num(x.maxTime)?'active':'missing'))];
 return groups;
}
const META={vials:['World 2 · Alchemy','Vials'],sigils:['World 2 · Alchemy','Sigils'],votes:['World 2','Weekly Votes'],killroy:['World 2','Killroy Prime'],saltLick:['World 3','Salt Lick'],shinyPets:['World 4 · Breeding','Shiny Pets'],upgradeVault:['World 5','Upgrade Vault'],gamingPalette:['World 5 · Gaming','Gaming Palette'],emperorBonuses:['World 6','Emperor Bonuses'],compass:['Masterclasses · Wind Walker','Compass'],grimoire:['Masterclasses · Death Bringer','Grimoire'],tesseract:['Masterclasses · Arcane Cultist','Tesseract'],orion:['Clickers','Orion'],poppy:['Clickers','Poppy'],bubba:['Clickers','Bubba'],starSigns:['World 1','Star Signs'],constellations:['World 1 · Star Signs','Constellations'],forgeBonuses:['World 1','Forge Bonuses'],anvilUpgrades:['World 1 · Smithing','Anvil Upgrades'],islandExpeditions:['World 2','Island Expeditions'],poExtras:['World 2 · Post Office','Post Office Extras'],shrines:['World 3 · Construction','Shrines'],deathNote:['World 3','Death Note'],atomCollider:['World 3','Atom Collider'],eventShop:['Account','Event Shop'],familyBonuses:['Account','Family Bonuses'],gemShop:['Account','Gem Shop Upgrades'],friendBonuses:['Account','Friend Bonuses'],holeSchematics:['World 5 · The Hole','Schematics'],holeMajik:['World 5 · The Hole','Conjuror Majik'],holeStudies:['World 5 · The Hole','Studies'],holeMeasurements:['World 5 · The Hole','Measurements'],holeBell:['World 5 · The Hole','Bell'],holeWell:['World 5 · The Hole','The Well'],holeFountain:['World 5 · The Hole','Fountain'],holeHarp:['World 5 · The Hole','Harp'],holeLamp:['World 5 · The Hole','Lamp'],holeResources:['World 5 · The Hole','Resource Caverns'],holeDawgDen:['World 5 · The Hole','Dawg Den'],holeJars:['World 5 · The Hole','Jars'],holeMonuments:['World 5 · The Hole','Monuments'],holeGambit:['World 5 · The Hole','Gambit'],clamworks:['World 7','Clamworks'],meritocracy:['World 7','Meritocracy'],bigFish:['World 7','Big Fish'],coralKid:['World 7','Coral Kid'],coralReef:['World 7','Coral Reef'],dancingCoral:['World 7','Dancing Coral'],hoops:['World 7','Hoops'],darts:['World 7','Darts'],zenithMarket:['World 7','Zenith Market'],sushi:['World 7','Sushi'],button:['World 7','The Button'],legendTalents:['World 7','Legend Talents']};
function masterSummary(key,rawRoot){const x=systems(rawRoot).get(key),pairs=key==='compass'?[['Total Compass Levels',x?.totalCompassLevel],['Dust Collected',x?.totalDustsCollected],['Medallions',x?.medallionsCollected?.length],['Portals Completed',x?.portalsCompleted?.length],['Tempest Damage',x?.currentTempestDamage],['Dust Multiplier',x?.currentDustMultiplier]]:key==='grimoire'?[['Total Grimoire Levels',x?.totalGrimoireLevel],['Wraith Damage',x?.currentWraithDamage],['Bone Drop Rate',x?.currentBoneDropRate],['Wraith Accuracy',x?.currentWraithAccuracy],['Wraith Defence',x?.currentWraithDefense]]:key==='tesseract'?[['Total Tesseract Levels',x?.totalTesseractLevel],['Arcane Damage',x?.currentArcaneDamage],['Tachyon Drop Rate',x?.currentTachyonDropRate],['Arcane Accuracy',x?.currentArcaneAccuracy],['Arcane Defence',x?.currentArcaneDefense],['Prisma Bubbles Found',x?.prismaBubblesFound]]:key==='orion'?[['Feathers',x?.ownedFeather],['Shiny Feathers',x?.ownedShinyFeather],['Mega Feathers',x?.ownedMegafeathers],['Total Feathers',x?.totalProducedFeather]]:key==='poppy'?[['Bluefin Fish',x?.ownedFishes],['Tartar Fish',x?.ownedTartarFishes],['Mega Fish',x?.ownedMegafishes],['Shiny Fish Types',x?.shinyFishes?.length]]:key==='bubba'?[['Unlocked',x?.unlocked?'Yes':'No'],['Happiness',x?.happiness],['Flesh',x?.ownedFlesh],['Mega Flesh',x?.ownedMegaflesh]]:key==='clamworks'?[['Promotion Level',x?.promoLevel],['Pearls Owned',x?.pearlsOwned]]:key==='coralReef'?[['Daily Coral',x?.dailyCoralGains],['Coral Owned',x?.ownedCoral]]:key==='zenithMarket'?[['Deposited Clusters',x?.depositedClusters]]:[];return pairs.filter(([,v])=>v!=null).map(([label,value])=>`<div><span>${esc(label)}</span><strong>${esc(typeof value==='number'?fmt(value):value)}</strong></div>`).join('');}
function renderGemShop(host,rows){const maxed=rows.filter(x=>x.status==='maxed').length,owned=rows.filter(x=>x.owned>0).length;host.innerHTML=`<div class="bonus-system-hero"><div><p class="eyebrow">Account · permanent upgrades</p><h2>Gem Shop Upgrades</h2><p>Select an upgrade picture to see its effect, level and next purchase cost.</p></div><strong>${maxed} maxed · ${owned} purchased</strong></div><div class="bonus-system-controls"><input type="search" placeholder="Search Gem Shop upgrades…"><span>${rows.length} upgrades</span></div><div class="gem-shop-grid compact-upgrades">${rows.map((x,i)=>`<button type="button" class="arcade-tile gem-shop-tile ${x.status==='missing'?'arcade-zero':''}" data-gem-shop="${i}" data-search="${esc(`${x.name} ${x.code} ${x.effect}`.toLowerCase())}" aria-pressed="false"><img class="arcade-icon" src="${esc(x.icon)}" alt="" loading="lazy" onerror="this.src='assets/PremiumGem.png';this.onerror=null"><span class="arcade-name">${esc(x.name)}</span><strong>${x.status==='maxed'?'MAX':`${x.owned} / ${x.max}`}</strong><span class="gem-shop-state ${x.status}">${x.status==='maxed'?'✓ Maxed':x.owned?'Purchased':'Not purchased'}</span><span class="upgrade-tip"><strong>${esc(x.name)}</strong><span>${esc(x.effect)}</span></span></button>`).join('')||'<p>No permanent Gem Shop upgrades were found in this export.</p>'}</div><section id="gemShopDetail" class="exp-card upgrade-detail detail-dismissed" aria-live="polite"></section>`;
 const detail=host.querySelector('#gemShopDetail'),buttons=[...host.querySelectorAll('[data-gem-shop]')],show=i=>{const x=rows[i];buttons.forEach((b,n)=>{b.classList.toggle('selected',n===i);b.setAttribute('aria-pressed',String(n===i));});const nextCost=x.cost+x.costIncrement*x.owned;detail.innerHTML=`<button class="secondary gem-shop-detail-close" aria-label="Close upgrade details">Close</button><div class="gem-shop-detail-head"><img src="${esc(x.icon)}" alt="" onerror="this.src='assets/PremiumGem.png';this.onerror=null"><div><p class="eyebrow">${esc(x.code)}</p><h3>${esc(x.name)}</h3><strong>${x.status==='maxed'?'✓ Maximum purchases reached':`${x.owned} / ${x.max} purchased`}</strong></div></div><p class="exp-benefit">${esc(x.effect)}</p>${x.status==='maxed'?'<p class="gem-cost">No more purchases needed.</p>':`<p class="gem-cost"><img src="assets/PremiumGem.png" alt="Gems"> <strong>${fmt(nextCost)} gems</strong> for the next purchase</p>`}<p class="muted">Purchase availability and your current gem balance are not checked.</p>`;detail.classList.remove('detail-dismissed');detail.querySelector('.gem-shop-detail-close').onclick=()=>detail.classList.add('detail-dismissed');};buttons.forEach((b,i)=>b.onclick=()=>show(i));const input=host.querySelector('input');input.oninput=()=>{const q=input.value.toLowerCase().trim();buttons.forEach(x=>x.hidden=q&&!x.dataset.search.includes(q));};}
function render(host,key,rawRoot={}){let rows=[];try{rows=getRows(rawRoot)[key]||[];}catch(e){host.innerHTML=`<section class="bonus-system-empty"><h2>Could not decode this save</h2><p>${esc(e.message)}</p></section>`;return;}if(key==='gemShop'){renderGemShop(host,rows);return;}const [world,title]=META[key]||['Account',words(key)],active=rows.filter(x=>x.status==='active').length,summary=masterSummary(key,rawRoot);host.innerHTML=`<div class="bonus-system-hero"><div><p class="eyebrow">${esc(world)}</p><h2>${esc(title)}</h2><p>Decoded directly from the imported IdleOn Toolbox save.</p></div><strong>${active} active · ${rows.length-active} missing</strong></div>${summary?`<section class="master-summary">${summary}</section>`:''}<div class="bonus-system-controls"><input type="search" placeholder="Search ${esc(title)}…"><span>${rows.length} bonuses</span></div><div class="bonus-system-grid">${rows.map(x=>`<article class="${x.status==='missing'?'is-missing':''}" data-search="${esc(`${x.name} ${x.effect}`.toLowerCase())}"><span>${esc(x.level)}</span><h3>${esc(x.name)}</h3><p>${esc(x.effect)}</p></article>`).join('')||'<p>No entries were found in this export.</p>'}</div>`;const input=host.querySelector('input'),cards=[...host.querySelectorAll('[data-search]')];input.oninput=()=>{const q=input.value.toLowerCase().trim();cards.forEach(x=>x.hidden=q&&!x.dataset.search.includes(q));};}
const api={systems,getRows,render};if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.BonusSystems=api;})(typeof window!=='undefined'?window:globalThis);
