(function(root){'use strict';
const topics=[
['push','Double-pat push',`<h3>Use two hourly pat allowances in one short burst</h3>
<p>A double pat means spending the current allowance immediately before the hourly refresh, then using the refreshed allowance. It does not mean double-clicking Bubba or waiting two hours to store twice the ordinary allowance. Check the countdown on Happi Boi; this is the Bubba timer, not necessarily the real-world clock hour.</p>
<ol><li><strong>Prepare first:</strong> check your next Megaflesh cost, selected gifts, dice, smoke, and useful upgrades. Decide whether the estimated gift payout can cover the goal and any permanent purchases you want before resetting.</li><li><strong>Just before refresh:</strong> with Joy emulsified if unlocked, spend the current pats. Allow enough time to finish clicking before the countdown reaches zero.</li><li><strong>After refresh:</strong> use the newly available pats promptly while Joy is still emulsified. Happiness decays quickly, so this is an active sequence.</li><li><strong>Switch to Hustle:</strong> open Beeg Slice gifts while production is high. If you also selected Numbahs, single-click Rizz as the training target while leaving Hustle emulsified; its gift levels can reduce subsequent costs.</li><li><strong>Finish with Rizz:</strong> when checking or buying Megaflesh, emulsify Rizz for the discounted cost. Stop opening gifts once you can afford your planned purchases.</li></ol>
<p>The double-pat technique is also described in <a href="https://gameslikefinder.com/article/idleon-bubba-guide/" target="_blank" rel="noopener noreferrer">Samuel Franklin's Bubba guide</a>. The refresh and training behavior above were checked against the local client.</p>
<h4>Do not double-count starting pats</h4><p>MF8's 50 starting pats are a one-time reserve for that run. The hourly reset restores the ordinary allowance; it does not give another 50. A calculator scenario with two batches must use the actual pre-refresh remainder plus the next regular allowance. Simply doubling a number that includes starting pats can overestimate your push.</p>
<h4>Choose a route before spending your openings</h4><p><strong>Save for a final burst:</strong> build steady production and preserve cheap openings until a short happiness burst can finish the run. <strong>Tango's active route:</strong> spend selected openings earlier to unlock major multipliers, then reinvest. Both depend on improving the payout before consuming too many openings. “Never open early” and “open every hour” are route choices, not universal mechanics.</p>
<h4>Compare the same units and the same state</h4><p>This planner's Main header uses meat per <strong>second</strong>; many community targets and the external optimizer use meat per <strong>minute</strong>. Multiply per-second values by 60 before comparing. Also distinguish a no-happiness baseline from a post-pat burst, and count <strong>Megaflesh already owned</strong> separately from the next one you are buying. Fixed community income targets cannot account for every Vault or cost bonus.</p>`],
['start','Start here',`<h3>Build a run around your next permanent upgrade</h3>
<p>Bubba turns Meat Slices (called Flesh in this planner) into production upgrades. Production unlocks more of the board; purchases improve your engine; Megaflesh resets the run for permanent rewards. Bubba Boon supplies the bonuses that benefit the rest of your account.</p>
<ol><li><strong>Start production:</strong> buy 1st Slice, then unlock Happi Boi and Charisma as the board opens. Choose a training attribute in the Charisma Chart; unlocking the chart alone is not a training plan.</li><li><strong>Build several sources of growth:</strong> combine flat Slice production, percentage Meat upgrades, happiness, and cost reductions. Once available, dice and smoked meat add separate multipliers.</li><li><strong>Prepare a burst:</strong> buy useful production upgrades, use available pats, and check your selected Charisma attribute before opening gifts.</li><li><strong>Reinvest the payout:</strong> spend it on the next meaningful unlock or strong production improvement. Recheck gift cost before opening again.</li><li><strong>Prepare the next run:</strong> inspect affordable Bubba Boon and Fun Gifts levels before buying Megaflesh. Read the new Megaflesh reward and choose gifts for the next run deliberately.</li></ol>
<h4>A short routine each visit</h4><p>Check Charisma training → inspect the Smoker timer and dice → buy useful cheap upgrades → pat Bubba → open a worthwhile gift → reinvest → check your reset target. Only do the steps you have unlocked.</p>
<p class="bubba-guide-note">These are decision rules, not a fixed purchase order. Your gifts, Megaflesh count, outside bonuses, and time between visits change which purchase is best.</p>
<h4>Two different numbers: wallet and production</h4><p>Your wallet pays for upgrades. Total produced unlocks new upgrade types. Spending meat reduces the wallet, but does not undo production progress. A newly visible tile still needs its purchase cost.</p>`],
['engine','Production & buying',`<h3>Why several small improvements can beat one expensive level</h3>
<p>The production engine multiplies separate groups together:</p><p class="bubba-guide-formula">Flat Slices × Meat percentage group × Happiness × Dice × Smoked meat × Hustle × first Megaflesh level bonus × Beeg Slice passive × Coins × outside bonuses</p>
<p><strong>Flat production:</strong> 1st Slice, 2nd Slice, and 3rd Slice add to the same base. <strong>Percentage production:</strong> Good Meat, Great Meat, Best Meat, and Crossover add inside one percentage group. Happiness, dice, smoke, and Hustle then multiply that result.</p>
<p>Example: 100 base slices/second with +200% in the Meat group produces 300 before other multipliers. Adding another +20 percentage points makes 320: a 6.67% gain, not a 20% final gain. A separate multiplier rising from 2× to 2.2× gives a 10% final gain.</p>
<h4>Buy time saved, not just the cheapest tile</h4><p>For an ordinary production purchase, estimate <strong>cost ÷ extra slices per second</strong> to get its simple payback time. This ignores unlocks, happiness decay, and later purchases, but helps compare options. If a 1,000-meat upgrade adds 10/second, its simple payback is 100 seconds. Near a reset, a long-payback purchase can delay the reset.</p>
<h4>Cost reduction is a divisor</h4><p>Bargain, Cost Saver, Perma Sale, and Rizz each divide cost by <strong>1 + their bonus/100</strong>. A raw 100 bonus means half price, not free upgrades. Two separate 100-bonus sources give quarter price. Consider these before a large batch of purchases.</p>
<h4>Paid levels versus free levels</h4><p>Effective level is paid level plus bonus levels. Most upgrade effects use effective level, but prices scale with paid levels. Mindful and Surprise Box can therefore improve eligible upgrades without the usual extra price escalation. Special purchases including Boon, Megaflesh, Fun Gifts, Open Gift, dice count/sides, Dice Roll, and Smoker are excluded from the ordinary double-level proc.</p>
<p>After the first Megaflesh, total upgrade levels also grant a separate multiplier: <strong>1 + total levels/100</strong>. At 300 total levels this is 4×. Cheap levels can remain worthwhile, but their cost still matters.</p>`],
['happy','Happiness & pats',`<h3>Use happiness when it can fund progress</h3>
<p>Happi Boi unlocks happiness, raises happiness per pat, and increases the hourly pat allowance. The allowance grows slowly with level; doubling the upgrade does not simply double your available pats.</p>
<p>Happiness is a separate production multiplier. In the checked client, the loss rule is max(1, happiness/13) per second (the visible screen smooths this across frames). It decays, so a high rate immediately after patting is a burst rate, not a guaranteed rate for the entire time you are away. The happiness icon is a rank display; reaching its highest rank does not mean the numeric production formula stops scaling.</p>
<h4>Three ways to build it</h4><ul><li><strong>Pats:</strong> available in limited hourly quantities. Upgrade Happi Boi and happiness bonuses before spending a useful batch.</li><li><strong>Buyer Grin:</strong> gives happiness when purchasing upgrades. Its base happiness per purchase approaches 3 as its bonus grows, before happiness multipliers; it has diminishing returns.</li><li><strong>Beach Ball:</strong> adds a passive happiness bonus and gives 200 happiness when triggered.</li></ul>
<p>Real Love, Joy, and Beach Ball's passive improve pat and purchase happiness through the same additive bonus group. More happiness helps, but investing everything in Joy neglects the other production multipliers.</p>
<h4>Before a Beeg Slice opening</h4><p>Buy your worthwhile production levels, raise happiness with available pats, then trigger Open Gift while the rate is elevated. The payout uses the rate at that moment. With Beeg Slice and Beach Ball together, the client processes the meat payout before Beach Ball's +200 happiness, so that happiness does not boost the same opening's payout.</p>`],
['charisma','Charisma',`<h3>Train with a purpose</h3>
<p>Charisma trains a selected attribute over time. The Charisma upgrade increases training speed; Numbahs supplies a separate training-speed multiplier. Super Chart strengthens all attribute bonuses. Attributes already trained keep giving their bonuses when you select another one.</p>
<div class="bubba-guide-table"><table><thead><tr><th>Attribute</th><th>What it does</th><th>When it helps</th></tr></thead><tbody>
<tr><td>Hustle</td><td>Meat production; base +10% per level.</td><td>Direct production and Beeg Slice payouts.</td></tr><tr><td>Rizz</td><td>Cost divisor; base +2 per level.</td><td>Expensive milestones and purchase batches.</td></tr><tr><td>Joy</td><td>Happiness gain; base +5% per level.</td><td>Making pats and purchase happiness stronger.</td></tr><tr><td>Courage</td><td>Dice luck; base +1% per level.</td><td>Improving the distribution of future rolls.</td></tr><tr><td>Mindful</td><td>Extra upgrade-level chance; base +0.1 percentage point per level.</td><td>Building free levels across many future purchases.</td></tr><tr><td>Savvy</td><td>Extra coin quantity; base +1 percentage point per level.</td><td>Scaling coin rewards once Spare Coins is active.</td></tr></tbody></table></div>
<h4>The hidden cost of spreading training around</h4><p>The requirement for another trained level depends on <strong>total levels in all six attributes</strong>: <code>20 × (1 + total/20) × 1.03^total</code>, before training-speed bonuses. Switching to a low-level attribute does not restore the cheap early training speed. Unfocused early levels make your later priorities slower.</p>
<p>Use Hustle when production is the immediate obstacle and Rizz when a purchase is the obstacle. Mindful is an investment in a run with many purchases left; its value is much smaller just before resetting. Select the attribute you actually want before triggering Numbahs, which grants one level to that selection. Normal timed training stops at 120 per attribute. Numbahs can exceed 120 because its gift-level award does not use that training-cap check. Switch training away from a capped attribute when you want timed levels elsewhere.</p>
<h4>Mindful 120 is not a 120% proc chance</h4><p>At level 120, Mindful contributes 12 percentage points before Super Chart. Emulsifying makes that 36 points; with a 1.5× Super Chart factor it becomes 54 points. Add Surprise Box’s passive if selected. The ordinary purchase check awards at most one extra level, so a combined chance above 100% does not grant two extra levels. Extra levels improve the upgrade effect; they are not extra purchases that independently roll more coins.</p><h4>Emulsification after Megaflesh 6</h4><p>Grand Salmon unlocks double-tapping an attribute to emulsify it. That attribute's bonus is tripled. This is separate from choosing what to train. Tripling a +100% Hustle bonus changes its multiplier from 2× to 4×, not 6×. Check the emulsified selection as well as the training selection. Tango’s active route switches Joy for pats, Hustle for meat payouts, Rizz for expensive purchases, Mindful for early eligible upgrades, and Savvy for coin-stage batches. Building happiness with Joy before switching to Hustle lets both choices help the same burst. See the Tango Strategy subtab for the full sequence.</p>`],
['gifts','Gifts & bursts',`<h3>Choose passives for the run; time the active effects</h3>
<p>Fun Gifts permanently expands the choices at the start of a run, up to six. Megaflesh 3 permits two gifts. Selected gifts provide passive bonuses throughout the run; buying Open Gift triggers their active effects. Treat selection as a commitment for that run.</p>
<div class="bubba-guide-table"><table><thead><tr><th>Gift</th><th>Base passive</th><th>On opening</th></tr></thead><tbody>
<tr><td>Beeg Slice</td><td>+100% meat (2×).</td><td>20 minutes of meat at the current rate.</td></tr><tr><td>Beach Ball</td><td>+50% happiness gain.</td><td>+200 happiness.</td></tr><tr><td>Numbahs</td><td>+150% training speed (2.5×).</td><td>+1 level to the selected training attribute.</td></tr><tr><td>Red Die</td><td>+50% dice luck.</td><td>Reroll dice.</td></tr><tr><td>Slabcakes</td><td>15% chance for 10× smoked meat.</td><td>Produce smoked meat.</td></tr><tr><td>Surprise Box</td><td>10% chance for an extra eligible upgrade level.</td><td>+2 bonus levels to a random eligible upgrade.</td></tr></tbody></table></div>
<h4>Useful choices by purpose</h4><p><strong>Beeg Slice + Numbahs</strong> is a practical general-purpose pair once both slots and choices are available: production funds upgrades while faster training strengthens the run. <strong>Slabcakes</strong> becomes more attractive when smoked meat drives your progress, especially with Megaflesh 9. <strong>Red Die</strong> supports a dice-focused push. <strong>Surprise Box</strong> needs many eligible purchases to exploit its passive. For an active later-run alternative, Tango’s supplied Discord route specifically uses Beeg Slice + Slabcakes, with early Mindful and repeated Smoker purchases; see Tango Strategy. Choose for the mechanics you can actually use, rather than selecting the newest gift automatically.</p>
<h4>Do not spend all your cheap openings at a weak rate</h4><p>Open Gift's base price scales by 3 per paid level, with an additional small level term and applicable discounts. Beeg Slice gives <strong>1,200 × current slices/second</strong>. At 1,000/second, that is 1.2 million meat. If the opening costs 2 million, the meat payout alone loses 800,000; another selected gift might still justify it, but it is no longer a free meat loop.</p>
<p>Open once, reinvest, and reassess. Raising production first makes later openings more valuable. You can also postpone opening for a better Smoker state or a useful Numbahs training target.</p>
<h4>Uber Gifts boosts passives, not every active effect</h4><p>Its passive scaling factor is capped at 5×. At that cap Beeg Slice's +100% becomes +500%, meaning 6× production. It does not turn the active 20-minute payout into 100 minutes. Numbahs still grants one selected attribute level per activation. With Beeg Slice + Slabcakes, the meat payout happens before the smoke award, so the new smoked meat strengthens subsequent production/openings, not the payout that already happened.</p>`],
['dice','Dice, smoke & coins',`<h3>Dice multiply together</h3>
<p>Dice Roll rerolls your dice and its purchase price resets on the hourly timer. More Dice increases the count, More Sides increases the ceiling, and Loaded Dice/Courage/Red Die improve roll luck. The limits are eight dice and twenty sides.</p>
<p>Despite older tooltip wording about a sum, production uses the <strong>product of effective die values</strong>: a roll up to 6 keeps its value; above 6, each additional pip contributes 0.4. The multiplier is <code>1 + product/100</code>. Two sixes give 1.36×; three sixes give 3.16×. A roll of 11 contributes 8, not 11.</p>
<p>Megaflesh 5 adds one die and five sides, and rejects rolls with a lower rounded multiplier. The local client compares whole-number rounded multipliers, so a small decrease within the same rounded value can still replace your result: 3.4× and 2.6× both round to 3. Before MF5 there is no such protection; rerolling can lose a good result. Luck improves probabilities; it does not guarantee the highest roll. Consider count and side upgrades before spending on more rerolls.</p>
<h4>The Smoker rewards waiting, but quality is random</h4><p>Smoker purchases produce smoked meat. Time spent smoking changes the quality distribution; it is not a guaranteed fixed-quality timer. Longer waits favor higher tiers. The client distribution reaches its best shape at about <strong>16 hours 11 minutes</strong>; waiting beyond that does not further improve that distribution.</p>
<p>The five meat types each contribute <code>1 + quantity × tier bonus/100</code>, and these five factors multiply. Adding a neglected type can be more valuable than adding more to a type you already have in abundance.</p>
<p>Ordinary Smoker purchases reset the smoking timer. With Megaflesh 9, the tooltip advertises a 75% chance for free meat; the checked local client actually uses 70%. A successful proc preserves the timer and converts the purchased Smoker level into a bonus level. Meat currency is still spent, but the paid-level counter is rolled back, so the next base price does not rise from that purchase. This allows repeated attempts at the same paid-level cost; it is not a refund of the meat you spent. Slabcakes gift activations also produce meat without the normal purchase timer reset. Check the timer after purchases instead of assuming every attempt preserved it.</p>
<p>2X Smoke improves quantity; Slabcakes supplies a separate chance for 10× quantity. Both can apply to the same production event. Building quantity bonuses before using a mature Smoker makes that waiting time more valuable. Waiting for mature quality is one approach, not a universal rule: Tango’s active route repeatedly buys affordable Smoker levels and triggers Slabcakes to build the multiplier quickly, using MF9 procs when available.</p>
<h4>Coins are another separate multiplier</h4><p>Spare Coins gives purchases a chance to find a coin. Pennies, nickels, quarters, and dollars contribute 1, 5, 25, and 100 to a pool: <code>multiplier = 1 + pool/100</code>. One dollar adds 1 to the multiplier, not a permanent doubling each time. Savvy and Big Ol Coin improve quantity; Megaflesh 11 improves the chances of finding the rarer denominations. Tango reserves cheap 1st Slice and Good Meat purchases until Spare Coins is active, then buys them with Savvy emulsified in the updated published route. This trades some early production for many later coin opportunities.</p>`],
['reset','Megaflesh & bonuses',`<h3>What survives a reset?</h3>
<p><strong>Kept:</strong> paid Bubba Boon levels, Megaflesh count, and Fun Gifts levels. <strong>Cleared:</strong> other paid upgrade levels, bonus levels, wallet (back to 1), production progress, happiness, gift selections, trained Charisma, emulsification, dice results, coins, and smoked-meat inventory. You rebuild the production engine and select gifts again.</p>
<p>Before resetting, compare an affordable permanent Boon or new gift choice against how long it delays your reset. A new gift option can materially improve the next run. Do not delay indefinitely for an upgrade that is far beyond reach.</p>
<div class="bubba-guide-table"><table><thead><tr><th>Megaflesh owned</th><th>New benefit</th></tr></thead><tbody>
<tr><td>1 · Glazed Ham</td><td>+1% production per total upgrade level, in its own multiplier.</td></tr><tr><td>2 · Mutton Chop</td><td>Account bonuses reach 1.2×.</td></tr><tr><td>3 · Bacon Sizzler</td><td>Select two gifts each run.</td></tr><tr><td>4 · Pork Cube</td><td>Account bonuses reach 1.4×.</td></tr><tr><td>5 · Sooshi</td><td>One more die, five more sides, worse rolls ignored.</td></tr><tr><td>6 · Grand Salmon</td><td>Emulsify one Charisma attribute for triple its bonus.</td></tr><tr><td>7 · Golden Ham</td><td>Account bonuses reach 1.6×.</td></tr><tr><td>8 · Beef Pie</td><td>Start each run with 50 pats.</td></tr><tr><td>9 · Big Tenderloin</td><td>Free-meat Smoker procs preserve the timer (tooltip: 75%; checked client: 70%).</td></tr><tr><td>10 · Sirloin Steak</td><td>Account bonuses reach 1.8×.</td></tr><tr><td>11 · Ambiguous Meat</td><td>Double the chances for rarer coin denominations.</td></tr><tr><td>12+ · Chromatic Meat</td><td>Account bonuses reach 2× at 12, then add 0.2× per additional Megaflesh.</td></tr></tbody></table></div>
<h4>Bubba Boon is the account payoff</h4><p>Boon rotates through seven bonuses: Build Rate, Critter Gain, Soul Gain, Total Damage, All Kills, EXP, and Atom Cost reduction. Each seven-level cycle adds another step to each bonus. The Megaflesh account multipliers above strengthen those steps; they do not multiply successively as 1.2 × 1.4 × 1.6.</p>
<p>Use the Account Bonuses subtab to compare Megaflesh counts against the imported Boon levels. That preview is not a simulation of the next run's production, purchases, gifts, or training.</p>`],
['trouble','When progress stalls',`<h3>Find the limiting mechanic</h3>
<dl><dt>“My rate fell after I left.”</dt><dd>Happiness decays. A post-pat rate and a quiet-run rate are different. Build lasting Slice, Meat, Charisma, dice, and smoke improvements as well as happiness.</dd>
<dt>“Charisma is slow even on a new attribute.”</dt><dd>Its requirement uses total trained levels. Improve Charisma and Numbahs speed where available, and choose future training deliberately. Switching attributes does not undo past training.</dd>
<dt>“Opening gifts barely moves my wallet.”</dt><dd>Compare the opening price with 1,200 times current production if using Beeg Slice. Raise the rate and happiness first, and reinvest between openings. Without Beeg Slice, Open Gift does not produce this direct meat payout.</dd>
<dt>“The Smoker keeps giving low-quality meat.”</dt><dd>Check elapsed smoking time. Repeated ordinary purchases restart it. Mature the timer before a quality push; Megaflesh 9 preserves it only on successful free-meat procs.</dd>
<dt>“A discount says 100 but upgrades still cost meat.”</dt><dd>The raw bonus is a divisor input: 100 means divide by 2. Use the actual displayed purchase price when planning.</dd>
<dt>“I bought more production but the next tile stayed locked.”</dt><dd>New tiles require total meat produced. Buying a level is not itself the unlock condition. Beeg Slice payouts also add to total production.</dd>
<dt>“I chose gifts that do not fit this run.”</dt><dd>Work with their passives and active effects, build your weaker production multipliers, and progress toward the next Megaflesh. Plan the next selection before resetting.</dd></dl>
<h4>Outside Bubba</h4><p>Crossover benefits from Poppy fish at powers-of-ten scale. The local game client also applies Bubba production bonuses from Upgrade Vault, Sushi, Jelly, and the Fountain, plus a Minehead upgrade-cost reduction. Inspect those systems for reachable improvements when Bubba's own next purchase is expensive. Companion effects can strengthen account bonuses separately.</p>
<h4>How this guide was checked</h4><p>Mechanics and reset behavior were checked against the locally extracted IdleOn game client and the bundled data catalogs on 27 September 2026. Strategy paragraphs are practical interpretations of those mechanics, not a claim of an optimal route for every save. Game updates can change values.</p>`]
];
topics.push(['sources','Sources & audit',`<h3>What was checked and corrected</h3><p>Research and local-client audit: <strong>27 September 2026</strong>. Game formulas are based on the installed client snapshot. Community routes describe how players use those mechanics; they are not guaranteed completion times.</p>
<ul><li><strong>Double-pat execution:</strong> added the actual refresh sequence, including Joy/Hustle/Rizz switching and the distinction between ordinary hourly pats and MF8's one-time reserve.</li><li><strong>Charisma:</strong> clarified the normal 120 training cap, Numbahs exceeding it, and how Mindful's level becomes an extra-level probability.</li><li><strong>Dice:</strong> corrected “worse rolls are ignored” to explain rounded-multiplier comparisons and the possibility of small losses even after MF5.</li><li><strong>Smoker:</strong> explained that an MF9 proc still spends currency; it preserves the timer and moves the paid level into the bonus-level counter. The local check is 70%, while the tooltip advertises 75%.</li><li><strong>Gift ordering:</strong> Beeg Slice pays before Beach Ball happiness or Slabcakes smoke. Those active benefits help subsequent production, rather than retroactively increasing that meat payout.</li><li><strong>Main tab rewards:</strong> replaced generic descriptions with the actual named Megaflesh effects. MF8 grants starting pats; it does not unlock the Smoker.</li><li><strong>Guide comparisons:</strong> clarified seconds versus minutes, owned versus target Megaflesh, and why fixed income thresholds or “always save gifts” advice may not fit an active route.</li></ul>
<h4>Reading and tools</h4><ul><li><a href="https://docs.google.com/document/u/0/d/e/2PACX-1vT1AXq0n6Vqt9ww2BLj0L-Lkf7SHMkCXULfzpnrqk4l2yWqBzMSZfkgx91YnvL72XqULJuL5PNw9wcX/pub?pli=1" target="_blank" rel="noopener noreferrer">@Tango44 - published Endgame Bubba Guide</a>, checked 27 September 2026: updated coin emulsification, training targets, Smoker budget and MF18+ pacing.</li><li><a href="https://gameslikefinder.com/article/idleon-bubba-guide/" target="_blank" rel="noopener noreferrer">Samuel Franklin — Bubba guide, Games Finder</a> (updated 27 May 2026): an alternative staged progression guide, including double pats and saving openings for a final burst. Its fixed income targets belong to its stated assumptions; its MF7 gift wording is internally inconsistent, so this planner does not repeat that passage as a rule.</li><li><a href="https://idleon-optimizer.vercel.app/bubba" target="_blank" rel="noopener noreferrer">Idleon Optimizer — Bubba</a>: calculator recommended by Tango; compare your current run rather than treating someone else's baseline as your requirement.</li><li><a href="https://www.youtube.com/watch?v=lYZrYL3VZOY" target="_blank" rel="noopener noreferrer">GriffyBit — How to Get Massive Meat Gains</a>: additional video resource found during research. The video transcript was not available for this audit, so no numerical claims here rely on its contents.</li><li><strong>@Tango, with thanks to @nac:</strong> the user-supplied Discord guide dated 16 April 2026, adapted in Tango Strategy. The original message link and screenshots were not supplied.</li></ul>
<h4>Where the evidence differs</h4><p>Community discussions disagree about training priorities and waiting versus buying Smoker repeatedly. The useful distinction is your route and stage: early Mindful pays off across many future purchases, while raising it very late can delay an imminent reset. The local client supports both timer-based quality and repeated quantity gains; it does not establish one universal optimal strategy.</p><p>The wiki could not be retrieved during this audit. We checked the installed game's production, purchase, reset, gift, timer, and dice handlers directly, alongside the local data catalogs. Future patches may change these details.</p>`]);
topics.unshift(topics.splice(topics.findIndex(x=>x[0]==='start'),1)[0]);
function render(){return `<section class="bubba-guide" aria-label="Bubba how-to guide"><header><img src="assets/BubbaMF0.png" width="44" height="44" alt=""><div><p class="eyebrow">Bubba field guide</p><h2>How to play Bubba</h2><p>Understand the engine, plan your bursts, and make each reset count.</p></div></header><nav class="bubba-guide-topics" aria-label="Guide topics">${topics.map(([id,title],i)=>`<button type="button" class="skill-tab${i?'':' active'}" data-bubba-topic="${id}" aria-pressed="${!i}">${title}</button>`).join('')}</nav>${topics.map(([id,,body],i)=>`<article data-bubba-article="${id}"${i?' hidden':''}>${body}</article>`).join('')}</section>`;}
function bind(host){host.querySelectorAll('[data-bubba-topic]').forEach(button=>button.onclick=()=>{host.querySelectorAll('[data-bubba-topic]').forEach(x=>{x.classList.toggle('active',x===button);x.setAttribute('aria-pressed',String(x===button));});host.querySelectorAll('[data-bubba-article]').forEach(x=>x.hidden=x.dataset.bubbaArticle!==button.dataset.bubbaTopic);});}
function renderTango(){return `<section class="bubba-guide" aria-label="Tango Bubba strategy"><header><img src="assets/BubbaMF8.png" width="44" height="44" alt=""><div><p class="eyebrow">Community strategy · 16 April 2026</p><h2>Tango's Beeg Slice + Slabcakes route</h2><p>Created by <strong>@Tango44</strong>. Thanks to <strong>@nac</strong> for early help and sharing his approach.</p></div></header>
<p>Updated against <a href="https://docs.google.com/document/u/0/d/e/2PACX-1vT1AXq0n6Vqt9ww2BLj0L-Lkf7SHMkCXULfzpnrqk4l2yWqBzMSZfkgx91YnvL72XqULJuL5PNw9wcX/pub?pli=1" target="_blank" rel="noopener noreferrer">@Tango44: Endgame Bubba Guide</a>, checked 27 September 2026. This published version supersedes the earlier Discord excerpt. It changes coin batches to Savvy and adds MF18+ advice, with run examples through MF19.</p>
<p class="bubba-guide-note"><strong>Before starting:</strong> select gift 1, <strong>Beeg Slice</strong>, and gift 5, <strong>Slabcakes</strong>. You need both gift slots and the fifth gift choice. The full switching routine needs MF6 emulsification; the 50 starting pats come from MF8, and MF9 Big Tenderloin strengthens the Smoker loop. Tango suggests roughly <strong>30× Bubba Vault</strong> as a workable starting point, not a hard requirement.</p>
<h3>The switch to remember</h3><div class="bubba-guide-table"><table><thead><tr><th>Action</th><th>Emulsify</th><th>Why</th></tr></thead><tbody><tr><td>Use pats</td><td>Joy</td><td>Get more happiness from your limited pats.</td></tr><tr><td>Open a gift / use production candy</td><td>Hustle</td><td>Raise the rate used for the meat payout.</td></tr><tr><td>Check or buy an expensive milestone</td><td>Rizz</td><td>Reduce the purchase cost, including Megaflesh.</td></tr><tr><td>Early eligible upgrades</td><td>Mindful</td><td>Improve extra-level chances.</td></tr><tr><td>Cheap batches and hourly dice purchases after Spare Coins</td><td>Savvy</td><td>Increase quantity when a coin roll succeeds.</td></tr></tbody></table></div>
<p>Training selection and emulsification are different settings. For example, train Rizz while emulsifying Hustle for a candy payout. For large purchases compare Rizz's savings with Mindful's free-level value; The updated route uses Savvy for coin batches and Rizz for expensive milestones.</p>
<p><strong>Charisma numbers below always mean:</strong> Hustle / Rizz / Joy / Courage / Mindful / Savvy. These are rough targets, not required exact builds.</p>
<details open><summary>1 · Build Mindful first, then the supporting attributes</summary><article><p>Leave <strong>1st Slice and Good Meat near level 50</strong>, reserving their cheap purchases for the coin stage. At MF18+, start with about <strong>10 levels each</strong> instead. Reach Charisma and raise that upgrade to around 100.</p><p><strong>With Bubba candy:</strong> train Mindful toward 120, continuing to upgrade Charisma and spending meat between candies with Mindful emulsified. Tango estimates about three candies for this part, depending on training speed. Then use about one candy training Hustle, one training Rizz, and one training Joy; emulsify Hustle for these candy payouts.</p><p>A typical early spread is <strong>12 / 8 / 7 / 0 / 120 / 0</strong>. Keep buying useful upgrades between candies. On first unlocking dice, roll once. Tango reports usually using fewer than ten candies, reaching around Super Chart in about five minutes; those are his results, not a promised time or candy budget.</p><p><strong>Without Bubba candy:</strong> progress normally until roughly <strong>10 / 5 / 5 / 0 / 120 / 0</strong>, then continue with step 2. The rest of the route still applies, but the setup takes longer.</p></article></details>
<details><summary>2 · Turn starting pats into the first gift burst</summary><article><p>Emulsify <strong>Joy</strong> and use some of the 50 starting pats to reach grey happiness. Switch to <strong>Hustle</strong>, then open one gift. Tango expects this burst to reach More Dice. Preserve some pats for the next bursts.</p><p><strong>Why:</strong> Joy builds happiness efficiently; switching afterward keeps that happiness while Hustle raises the production rate used by Beeg Slice. Slabcakes adds smoked meat through the same opening.</p></article></details>
<details><summary>3 · Improve dice, then push to Smoker</summary><article><p>Buy More Dice, use some rerolls, and aim for about a <strong>3–5× dice multiplier</strong>. Spend the meat on useful upgrades. Use Joy-emulsified pats to return to grey happiness, switch to Hustle, and open another gift.</p><p>If this does not reach Smoker, Tango suggests another candy while training Hustle, if available. Without candy, keep building the engine and wait for the next useful pat/gift cycle. The multiplier and unlock are targets, not guaranteed rolls.</p></article></details>
<details><summary>4 · Add Smoker production before the next opening</summary><article><p>With <strong>Rizz emulsified</strong>, buy Smoker repeatedly until its next cost is around Great Meat's next cost. Spend remaining meat on useful upgrades. Use remaining pats with Joy, switch to Hustle, and open a gift with your new smoke multiplier.</p><p>The target is <strong>More Sides</strong>. The point is to improve multiple production factors before paying for another opening, rather than opening gifts back-to-back without reinvesting.</p></article></details>
<details><summary>5 · Establish the hourly loop</summary><article><ol><li>When pats refresh, reroll dice and buy useful upgrades.</li><li>Buy more Smoker levels within your current upgrade budget; the updated guide compares against Great Meat. Reserve some meat for these purchases so Buyer Grin adds happiness before pats.</li><li>Emulsify Joy and use the refreshed pats.</li><li>Switch to Hustle and open a gift.</li><li>Reinvest the payout. Work toward Hustle 20 promptly.</li></ol><p>Tango often unlocked another upgrade with each opening. If progress stalls, check More Dice, More Sides, the retained dice multiplier, and smoked-meat production. One wasted gift is not the end of the run; the route aims to build enough multipliers to leave many openings for the final push.</p></article></details>
<details><summary>6 · Strengthen Super Chart and prepare for coins</summary><article><p>Repeat the loop and focus on Super Chart and later upgrades. Aim around <strong>30 / 10 / 15 / 0 / 120 / 0</strong>. Buy More Dice and More Sides when affordable with Rizz emulsified; check their prices immediately after a gift payout.</p><p>In this step Tango returns to <strong>Great Meat's cost</strong> as the Smoker comparison. The published version consistently uses Great Meat, superseding the earlier excerpt. This is still a spending heuristic.</p><p>Once Best Meat unlocks, train <strong>Savvy to about 10 before Spare Coins</strong>. This prepares coin quantity for the cheap purchase batch you saved earlier.</p></article></details>
<details><summary>7 · Cash in the reserved cheap levels</summary><article><p>Unlock and upgrade <strong>Spare Coins first</strong>. Emulsify <strong>Savvy</strong>, then buy 1st Slice and Good Meat from the levels you held back toward roughly <strong>1,000 each</strong>, as affordable.</p><p><strong>Why save those levels?</strong> Each purchase is now an opportunity to find coins. Savvy improves coin quantity; coins add another production multiplier. Buying the same cheap levels before unlocking coins would miss those coin opportunities.</p><p>Use Savvy for subsequent cheap batches and hourly dice purchases too. At MF18+, follow the smaller batches below instead of buying all reserved levels immediately.</p></article></details>
<details><summary>8 · Check the final Megaflesh push before each gift</summary><article><p>Continue hourly upgrades, Smoker purchases, dice rolls, Joy pats, and Hustle gift openings. A late-run target is about <strong>35 / 20 / 25 / 0 / 120 / 15</strong>. Tango suggests more Savvy may be useful around MF15 and beyond.</p><p>Before spending the next opening, check whether a <strong>Mega Push</strong> can already reach the next Megaflesh. Some runs can finish before coins; completing every step is not the goal.</p><ol><li>Open <a href="https://idleon-optimizer.vercel.app/bubba" target="_blank" rel="noopener noreferrer">Idleon Optimizer — Bubba</a>, Tango's recommended calculator, and use your current run values.</li><li>Following Tango's workflow, compare a push using one gift with a push using all available gifts.</li><li>For his double-pat scenario, enter twice your available pats in <strong>Total Pats Used</strong>. This models two batches; it does not grant extra pats in game. Audit clarification: if the displayed amount includes unused MF8 starting pats, do not double that reserve. Use the current remaining pats plus the next ordinary hourly allowance. The How to → Double-pat push topic explains the timing.</li><li>Double-click Rizz in the calculator to check the Megaflesh price with Rizz emulsified. Compare against the payout using the appropriate production setup.</li></ol><p>These calculator instructions come from Tango's April post; controls may change. Our Account Bonuses subtab only previews permanent rewards and is not this Mega Push calculator.</p><p>Tango reported an MF13 run finishing in <strong>under 24 hours</strong> with <strong>38 gifts available for the push</strong>. His Vault, candies, and run conditions affect that result; it is an example of the route, not a completion guarantee.</p></article></details>
<details><summary>9 - MF18+ pacing</summary><article><p>Start with about 10 levels each in 1st Slice and Good Meat. After Spare Coins, buy 25-50 levels per opening until Big Ol Coin has some investment. Preserve cheap opportunities for better coin quantity.</p><p>Moderate Smoker spending until 2X Smoke improves its yield, while buying enough to progress. Poor smoke results can justify waiting for 12 hours of smoking. After More Dice or More Sides, consider waiting for a stronger roll before spending another gift. An hourly visit can use Savvy dice purchases and pats without opening a gift. Use double pats when needed.</p><p>These are community heuristics, not guaranteed thresholds. Re-import after random outcomes to refresh the optimizer.</p></article></details><h3>Why this route changes the usual advice</h3><p>This is an active <strong>Beeg Slice + Slabcakes</strong> route: early Mindful improves a large future purchase batch, saved cheap levels become coin opportunities, and repeated Smoker/gift cycles build production. It deliberately buys Smoker frequently instead of always waiting for a mature timer. MF9 helps, but the guide's core idea is to compound several multipliers and finish as soon as the push is affordable.</p><p>Credit: <a href="https://docs.google.com/document/u/0/d/e/2PACX-1vT1AXq0n6Vqt9ww2BLj0L-Lkf7SHMkCXULfzpnrqk4l2yWqBzMSZfkgx91YnvL72XqULJuL5PNw9wcX/pub?pli=1" target="_blank" rel="noopener noreferrer"><strong>@Tango44 - published guide</strong></a>, plus the earlier Discord excerpt dated 16 April 2026, with his shoutout to <strong>@nac</strong>. Wording reorganized for this planner; approximate targets and reported results remain attributed to the author.</p></section>`;}
root.BubbaGuide={render,bind,renderTango};
})(typeof window!=='undefined'?window:globalThis);
