(function(root){
  'use strict';
  const parse=value=>{if(typeof value==='string'){try{return JSON.parse(value);}catch{return null;}}return value;};
  const number=value=>value!=null&&value!==''&&Number.isFinite(Number(value))&&Number(value)>=0?Number(value):null;
  const at=(data,key,group,index)=>number(parse(parse(data?.[key])?.[group])?.[index]);
  const grind=level=>level>0?9.7+.3*level:0;
  const stamp=level=>4*level/(level+200);
  const luck=level=>level<1000?(Math.pow(level+1,.37)-1)/30:(level-1000)/(level+2500)*.8+.3963;
  const gain=(pool,delta)=>100*delta/(100+pool);
  function inspect(state){
    const data=state?.rawData||{},names=state?.rawRoot?.charNames||[];
    const roster=Object.keys(data).filter(k=>/^Lv0_\d+$/.test(k)).map(key=>{
      const id=Number(key.slice(4)),level=number(parse(data[key])?.[0]);
      return {id,name:names[id]||`Character ${id+1}`,level,next:[10,30,50,120].find(n=>level!=null&&level<n)??null};
    }).sort((a,b)=>a.id-b.id);
    const vault=parse(data.UpgVault),vaultLevel=number(vault?.[3]),mastery=number(vault?.[32]);
    const dungeon=at(data,'DungUpg',5,2),spelunk=parse(data.Spelunk),arcade=parse(data.ArcadeUpg),divinity=parse(data.Divinity),coralOwned=number(spelunk?.[12]?.[0]),coralLevel=number(spelunk?.[13]?.[0]);
    return {grind:at(data,'CauldronInfo',3,8),stamp:at(data,'StampLv',0,43),obstruction:at(data,'Research',7,9),roster,vaultLevel,vaultBonus:vaultLevel!=null&&mastery!=null?2*vaultLevel*(1+mastery/100):null,activeLearning:number(vault?.[39]),dungeon,dungeonBonus:dungeon==null?null:45*dungeon/(dungeon+100),arcadeClassMulti:number(arcade?.[60]),krukBubbleBoost:number(arcade?.[61]),coral:{owned:coralOwned,level:coralLevel,dailyLevels:coralOwned>0?coralLevel:0},kruk:{unlocked:number(divinity?.[25])>8,linked:Array.from({length:12},(_,id)=>number(divinity?.[12+id])).includes(8)},hole:{explorer:at(data,'Holes',1,0),engineer:at(data,'Holes',1,1),gloomieBuilt:at(data,'Holes',13,47),sanctumBuilt:at(data,'Holes',13,83),colonies:at(data,'Holes',11,26),sanctums:at(data,'Holes',11,55),justiceExp:at(data,'Holes',15,16),justiceMulti:at(data,'Holes',15,19),cosmo:at(data,'Holes',4,0)}};
  }
  const fmt=n=>Number(n).toLocaleString(undefined,{maximumFractionDigits:2});
  const guides={
    jelly:{location:'Jelly Operator',steps:['Open Jelly Operator and continue from the saved obstruction.','Use the Jelly upgrade optimizer for the next clear.','Re-import your save after reaching the target obstruction.'],verify:'The target obstruction reward appears as active after a fresh save import.'},
    'justice-exp':{location:'The Hole → Justice Monument',steps:['Enter the Justice Monument and start a run.','At round 33 or later, take Class EXP when it is offered.','Repeat normally; the displayed target is a planning batch, not a required single session.'],verify:'Re-import and confirm the Justice Class EXP reward level increased.'},
    gloomie:{location:'The Hole → Gloomie Grotto',steps:['Check the next colony requirement and Monarch fight.','Complete and defeat the next reachable colony.','Return here after importing a fresh save.'],verify:'The Gloomie colony count should be one higher.'},
    sanctum:{location:'The Hole → Temple',steps:['Check the torch cost for the next Centurion summon.','Summon and defeat it only if the cost and fight are comfortable.','Import a fresh save after the clear.'],verify:'The Ancient Golem sanctum count should be one higher.'},
    vault:{location:'Codex → Upgrade Vault → Wicked Smart',steps:['Open Wicked Smart and inspect the next coin price.','Buy up to the suggested batch, stopping if it delays progression gear or food.','Import a fresh save to recalculate the next best move.'],verify:'Wicked Smart’s saved level should match the new level.'},
    active:{location:'Codex → Upgrade Vault → Active Learning',steps:['Only continue if this character will level actively.','Check the coin price and buy a comfortable number of levels.','Compare active EXP/hour on the same map before and after.'],verify:'Active EXP/hour should rise; offline EXP/hour should not be used to judge this upgrade.'},
    grind:{location:'Alchemy → Yellow Cauldron → Grind Time',steps:['Let Coral Reef apply its daily levels if that upgrade is active.','Only spend liquid that would otherwise cap; do not make manual Grind Time clicks the main project.','Re-import after daily reset or a convenient liquid dump.'],verify:'The Grind Time level should rise without displacing a stronger finite unlock.'},
    'coral-grind':{location:'World 7 → Coral Reef → first upgrade',steps:['Unlock the first Coral Reef upgrade if it is still locked.','Spend Daily Coral on it when the next level is practical.','Log in after daily reset and confirm Grind Time gained automatic levels.'],verify:'The first Coral Reef upgrade is active and Grind Time rises at daily reset.'},
    'arcade-multi':{location:'World 2 → Arcade → Gold Ball Shop',steps:['Find the Class EXP multiplier upgrade, not the older additive EXP upgrade.','Spend saved Gold Balls only when this competes well with other permanent Arcade upgrades.','Aim toward level 101 over time for the client’s special doubling step.'],verify:'The Class EXP multiplier shop level increased; level 101 shows the doubled curve.'},
    dungeon:{location:'Dungeons → Flurbo Shop → Class EXP',steps:['Check your current Flurbo balance and the next price.','Buy the suggested levels only with spare Flurbos.','Do not start a dedicated dungeon grind for a small late-curve gain.'],verify:'The non-dungeon Class EXP shop level should increase.'},
    stamp:{location:'Stamps → Combat → Gud EXP Stamp',steps:['If unowned, progress Snootie’s quest chain through its third quest.','If owned, check the next coin and material costs.','Buy only cheap levels, then re-import your save.'],verify:'The Gud EXP Stamp should be owned and/or its level should increase.'}
  };
  function recommend(state){
    const a=inspect(state),h=a.hole,actions=[],covered=[],unknown=[];
    const add=(id,title,current,target,benefit,action,effort,reason,priority)=>actions.push({id,title,current,target,benefit,action,effort,reason,priority});
    if(a.obstruction==null)unknown.push('Jelly rewards');
    else if(a.obstruction<31)add('jelly','Get the first Jelly Class EXP multiplier',`Obstruction ${fmt(a.obstruction)}`,'Reach obstruction 31','×1.20 total Class EXP',`Continue Jelly Operator from obstruction ${fmt(a.obstruction)} to 31. Use its upgrade optimizer for your next clear.`,'Progression project',`${31-a.obstruction} more obstruction advances. This is an independent multiplier, so its 20% gain is not diluted by your existing additive EXP. Clear feasibility is not estimated here.`,10);
    else if(a.obstruction<63)add('jelly','Get the second Jelly Class EXP multiplier',`Obstruction ${fmt(a.obstruction)}`,'Reach obstruction 63','×1.25 on top of current EXP','Continue Jelly Operator to obstruction 63.','Progression project',`${63-a.obstruction} more advances; a separate 25% gain once unlocked.`,12);
    else covered.push('Both Jelly Class EXP multipliers are active.');
    if(h.explorer==null)unknown.push('The Hole');
    else if(h.explorer>=10){
      if(h.justiceMulti==null)unknown.push('Justice multiplier reward');
      if(h.justiceExp!=null){
        const factor=h.cosmo!=null&&h.justiceMulti!=null?Math.max(1,1+Math.ceil(h.justiceMulti/(250+h.justiceMulti)*2500)/1000+h.cosmo*.25):null;
        const chunk=100;
        add('justice-exp',h.justiceMulti===0?'Build Justice EXP and unlock its missing multiplier':'Build your Justice Class EXP reward',`EXP reward Lv ${fmt(h.justiceExp)}${h.justiceMulti===0?' · multiplier reward Lv 0':''}`,`EXP reward Lv ${fmt(h.justiceExp+chunk)}${h.justiceMulti===0?' + first multiplier reward':''}`,factor==null?'+100 base reward levels':`+${fmt(chunk*factor)} additive points before Fountain bonuses`,`The Hole → Justice Monument. Take Class EXP rewards when offered (round 33+). ${h.justiceMulti===0?'Push toward round 77 to add the Justice multiplier reward to the reward pool.':''}`,'Repeated monument runs',`This +100-level target is a planning chunk, not a cap. ${factor!=null?`At your saved monument/Cosmo levels it is worth ${fmt(chunk*factor/.3)} unmodified Grind Time levels before Fountain scaling.`:'Monument amplifiers are missing, so the effective gain is unknown.'} Justice’s multiplier strengthens its rewards, not total account EXP independently. Reward offers are random; run count and cost are not estimated.`,h.justiceMulti===0?20:h.justiceExp===0?18:30);
      }else unknown.push('Justice Class EXP reward');
    }
    for(const [id,built,count,points,title,place] of [['gloomie',h.gloomieBuilt,h.colonies,25,'Gloomie Expie','Gloomie Grotto'],['sanctum',h.sanctumBuilt,h.sanctums,40,'Sanctum of EXP','Temple']]){
      if(built===0&&count>0)add(id,`Build ${title}`,`${fmt(count)} clears; upgrade not built`,'Buy the Engineer schematic',`Activates +${fmt(count*points)} additive EXP points`,`The Hole → Engineer → ${title}. Check its resource cost and unlock requirement.`,'Schematic purchase','You already have clears for this bonus, but its saved activation flag is off. Purchase availability and affordability are not yet checked.',5);
      else if(built>0&&count!=null)add(id,`Push one more ${id==='gloomie'?'Gloomie colony':'Ancient Golem sanctum'}`,`${fmt(count)} cleared`,`${fmt(count+1)} cleared`,`+${points} additive EXP points`,`The Hole → ${place}. ${id==='sanctum'?'Use torch points to summon and defeat the next Centurion.':'Finish the colony requirement and defeat the next Monarch.'} ${title} is already built.`,'One clear · difficulty unknown',`Equivalent to ${fmt(points/.3)} unmodified Grind Time levels. Do this before a liquid grind if the next clear is reachable; the save does not establish combat feasibility.`,id==='sanctum'?40:45);
    }
    if(a.vaultLevel==null)unknown.push('Wicked Smart');
    else if(a.vaultLevel<500){const target=Math.min(500,a.vaultLevel+10);add('vault','Buy the next Wicked Smart levels',`Lv ${fmt(a.vaultLevel)}`,`Lv ${fmt(target)}`,`+${fmt((target-a.vaultLevel)*2)} base additive points`,'Codex → Upgrade Vault → Wicked Smart. Buy this batch if the coin price is comfortable.','Coins · price unchecked','A shared EXP upgrade; Vault Mastery amplifies its base gain. Ten levels is a planning batch, not a breakpoint.',a.vaultLevel===0?15:50);}
    else covered.push(`Wicked Smart is already Lv ${fmt(a.vaultLevel)}; no normal paid levels remain.`);
    if(a.activeLearning>=100)covered.push(`Active Learning is already Lv ${fmt(a.activeLearning)}; no normal paid levels remain.`);
    else if(a.activeLearning!=null)add('active','Upgrade Active Learning for active leveling',`Lv ${fmt(a.activeLearning)}`,`Lv ${fmt(Math.min(100,a.activeLearning+10))}`,'Active kills only','Codex → Upgrade Vault → Active Learning. Skip this if your leveling is offline.','Conditional · coins','This is a mode-specific opportunity, not a shared offline EXP improvement. Unlock and affordability need an in-game check.',65);
    if(a.coral.owned===0)add('coral-grind','Unlock automatic daily Grind Time levels','Coral Reef upgrade locked','Unlock its first upgrade','Permanent daily Grind Time growth','World 7 → Coral Reef. Unlock the first reef bonus, then invest Daily Coral when practical.','Finite unlock · passive payoff','The installed client labels this bonus as daily Grind Time levels. This is the reason manual liquid spending should stop being the optimizer’s default main action once it is active.',14);
    else if(a.coral.owned>0&&a.coral.level<15)add('coral-grind','Increase automatic daily Grind Time growth',`Coral Reef Lv ${fmt(a.coral.level)} · +${fmt(a.coral.dailyLevels)} levels/day`,`Coral Reef Lv ${fmt(a.coral.level+1)}`,`+1 more Grind Time level per day`,'World 7 → Coral Reef → first upgrade. Buy the next level when its Daily Coral cost is reasonable.','Daily Coral · finite upgrade','Unlike manually dumping liquids, this improves permanent automatic growth. The saved level is used as the daily amount; max level is 15.',14);
    else if(a.coral.level>=15)covered.push('Coral Reef automatic Grind Time growth is maxed.');
    if(a.arcadeClassMulti!=null&&a.arcadeClassMulti<101){const target=Math.min(101,a.arcadeClassMulti+10),before=50*a.arcadeClassMulti/(a.arcadeClassMulti+100)*(a.arcadeClassMulti===101?2:1),after=50*target/(target+100)*(target===101?2:1);add('arcade-multi','Raise the independent Arcade Class EXP multiplier',`Lv ${fmt(a.arcadeClassMulti)}`,`Lv ${fmt(target)}`,`+${fmt(after-before)} multiplier-pool points`,'World 2 → Arcade → Gold Ball Shop. Buy the Class EXP multiplier with spare Gold Balls.','Periodic currency · finite milestone','This is the newer multiplier upgrade, not Arcade’s additive Class EXP entry. Level 101 triggers a special doubling in the installed client, making it a meaningful long-term breakpoint.',22);}
    if(a.grind==null)unknown.push('Grind Time');
    else if(a.grind===0)add('grind','Unlock Grind Time','Lv 0','Lv 1','+10 base additive points','Alchemy → Yellow cauldron → Grind Time. Unlock it, then verify activation on leveling characters.','Bubble unlock','Zero saved level means this source has not been leveled. Unlock chance and character activation are not simulated.',25);
    else {add('grind','Use spare liquids for Grind Time',`Lv ${fmt(a.grind)}`,`Lv ${fmt(a.grind+100)}`,'+30 base additive points','Alchemy → Yellow cauldron → Grind Time. Buy another 100 levels only after comparing the Hole opportunities above.','Repeatable · liquids',`You already have +${fmt(grind(a.grind))} base points here. Another 100 levels adds 30 points, not 30% total EXP. There is no hard cap; this target is a batch. Bubble modifiers and activation are not simulated.`,70);}
    if(a.dungeon!=null){const target=a.dungeon+10,delta=45*target/(target+100)-a.dungeonBonus;add('dungeon','Spend spare Flurbos on Class EXP',`Lv ${fmt(a.dungeon)}`,`Lv ${fmt(target)}`,`+${fmt(delta)} additive EXP points`,'Dungeons → Flurbo shop → non-dungeon Class EXP. Use spare currency rather than starting a long dungeon farm.','Spare currency',`The next 10 levels give ${fmt(delta)} points. This curve has diminishing returns; that is only ${fmt(delta/.3)} unmodified Grind Time levels.`,85);}else unknown.push('Dungeon Class EXP');
    if(a.stamp==null)unknown.push('Gud EXP Stamp');
    else if(a.stamp===0)add('stamp','Collect Gud EXP Stamp while progressing W7','Stamp Lv 0','Complete Snootie’s third quest','Unlocks the Class EXP stamp','Follow Snootie’s quest chain to finding Mister Jazzie. Hand in the stamp, then buy affordable levels.','Side objective · W7 quest','This missing stamp is real, but its unamplified curve approaches only +4 additive points. Do not prioritize a long quest grind over a missing independent multiplier. Lab, exaltation and other stamp amplifiers are not modeled.',90);
    else {const target=a.stamp+10;add('stamp','Take cheap Gud EXP Stamp levels',`Lv ${fmt(a.stamp)}`,`Lv ${fmt(target)}`,`+${fmt(stamp(target)-stamp(a.stamp))} base additive points`,'Stamps → Combat → Gud EXP Stamp. Buy this batch only if coins and materials are spare.','Low priority · costs unchecked','Effective gains depend on stamp amplifiers. The base curve approaches +4 points; milestone levels are not hard caps.',90);}
    for(const item of actions){
      item.access='F2P · no purchase required';
      const gates={jelly:['Heavy time gate','Progress this in the background. Do not delay other EXP upgrades while waiting for Jelly progress. No completion-date estimate.'], 'justice-exp':['Repeat runs + random rewards','Take EXP rewards during normal Monument progress. The +100-level batch is not a one-session target; reward offers and round progression limit the pace.'], sanctum:['Torch resources + clear difficulty','Check whether the next summon and clear are reachable with current resources. Otherwise leave this running as a longer goal.'], gloomie:['Colony requirements + clear difficulty','Only push now if the next colony requirement and Monarch are within reach.'], grind:['Automatic growth + liquid supply',a.coral.owned>0?`Coral Reef already supplies about ${fmt(a.coral.dailyLevels)} levels per daily reset. Only dump liquid that would otherwise cap.`:'Use liquids already available; if short, wait for refill instead of making this a spending target.'], 'coral-grind':['World 7 access + Daily Coral','This is finite passive infrastructure. Buy the next level only when unlocked and its Daily Coral cost is comfortable.'], 'arcade-multi':['Gold Balls + shop unlock','Spend existing Gold Balls periodically; do not buy balls or delay a substantially stronger permanent Arcade upgrade.'], vault:['Coin cost + unlock','Buy only if already unlocked and affordable. Saved levels do not prove you can afford the batch.'], dungeon:['Flurbo supply','Spend spare Flurbos; do not start a long currency grind for this small gain.'], stamp:['Quest / material requirements','Collect during normal progression, or use spare coins and materials for levels.'], active:['Active play + coin cost','Only prioritize if actively leveling and the upgrade is affordable.']};
      [item.gate,item.gateAdvice]=gates[item.id]||['Requirements unknown','Check availability in game.'];
      const tier=item.id==='grind'&&a.coral.owned>0?'background':item.id==='jelly'||item.id==='justice-exp'?'long':item.id==='active'?'conditional':item.priority===5?'S':['vault','grind','coral-grind','arcade-multi'].includes(item.id)?'A':item.id==='stamp'||item.id==='dungeon'?'C':'B';
      item.tier=tier;
      if(item.priority===5){item.gate='Schematic cost + unlock';item.gateAdvice='Existing clears are ready to benefit. Check the schematic is unlocked and affordable before buying.';}
      item.tierReason=tier==='S'?'Check this first: activate bonuses from progress you already completed. Purchase availability and cost still need checking.':tier==='A'?'Finite unlock or independent multiplier: check this before pouring time into an additive source that grows automatically.':tier==='B'?'Check the next clear while resources accumulate. Its benefit is useful, but combat feasibility and summon costs are not established.':tier==='C'?'Small base gain or diminishing returns. Use spare resources; avoid a dedicated grind.':tier==='long'?'High-value long-term goal, not your next immediate upgrade. Work on it alongside the tiers above.':tier==='background'?'Automatic or repeatable background growth. Maintain it, but do not let it displace finite unlocks and independent multipliers.':'Only helps active leveling. Skip for offline leveling.';
      Object.assign(item,guides[item.id]||{location:'In game',steps:[item.action],verify:'Import a fresh save and confirm the saved level or reward changed.'});
    }
    const tierOrder={S:0,A:1,B:2,C:3,long:4,background:5,conditional:6};
    actions.sort((x,y)=>tierOrder[x.tier]-tierOrder[y.tier]||x.priority-y.priority);
    return {account:a,actions,covered,unknown};
  }
  function plan(model,options={}){
    const mode=options.mode||'both',session=options.session||'all';
    const allowed=item=>session==='all'||(session==='quick'&&!['long','background'].includes(item.tier))||(session==='project'&&['long','B'].includes(item.tier));
    const actions=(model?.actions||[]).filter(item=>(mode!=='offline'||item.tier!=='conditional')&&allowed(item));
    return {actions,next:actions.find(item=>!['long','background','conditional'].includes(item.tier))||actions[0]||null};
  }
  const api={grind,stamp,luck,gain,inspect,recommend,plan};
  if(typeof module==='object'&&module.exports)module.exports=api;else root.ClassExp=api;
})(typeof window==='object'?window:globalThis);
