(function(root){
  'use strict';
  const metricNames=`Stamp Total LV|Statue Total LV|Cards Total LV|Total Talent Max LV|Unique Quests Completed|Account LV|Total Tasks Completed|Total Achievements Completed|Most Money held in Storage|Most Spore Caps held in Inventory at once|Trophies Found|Account Skills LV|Best Spiketrap Surprise round|Total AFK Hours claimed|DPS Record on Shimmer Island|Star Talent Points Owned|Average kills for a Crystal Spawn|Dungeon Rank|Highest Drop Rarity Multi|Constellations Completed|Most DMG Dealt to Gravestone in a Weekly Battle|Unique Obols Found|Total Bubble LV|Total Vial LV|Total Sigil LV|Jackpots Hit in Arcade|Post Office PO Boxes Earned|Highest Killroy Score on a Warrior|Highest Killroy Score on an Archer|Highest Killroy Score on a Mage|Fastest Time to kill Chaotic Efaunt|Largest Oak Log Printer Sample|Largest Copper Ore Printer Sample|Largest Spore Cap Printer Sample|Largest Goldfish Printer Sample|Largest Fly Printer Sample|Best Non Duplicate Goblin Gorefest Wave|Total Best Wave in Worship|Total Digits of all Deathnote Kills|Equinox Clouds Completed|Total Refinery Rank|Total Atom Upgrade LV|Total Construction Buildings LV|Most Tottoise in Storage|Most Greenstacks in Storage|Rift Levels Completed|Highest Power Pet|Fastest Time reaching Round 100 Arena|Total Kitchen Upgrade LV|Total Shiny Pet LV|Total Cooking Meals LV|Total Pet Breedability LV|Total Lab Chips Owned|Total Colosseum Score|Most Giants Killed in a Single Week|Total Onyx Statues|Fastest Time to Kill 200 Tremor Wurms|Total Boat Upgrade LV|God Rank in Divinity|Total Gaming Plants Evolved|Total Artifacts Found|Gold Bar Sailing Treasure Owned|Highest Captain LV|Highest Immortal Snail LV|Best Gold Nugget|Items Found|Most Gaming Bits Owned|Highest Crop OG|Total Crops Discovered|Total Golden Food Beanstacks|Total Summoning Upgrades LV|Total Career Summoning Wins|Ninja Floors Unlocked|Familiars Owned in Summoning|Jade Emporium Upgrades Purchased|Total Minigame Highscore|Total Prayer Upgrade LV|Total Land Rank|Largest Magic Bean Trade|Most Balls earned from LBoFaF|Total Arcade Gold Ball Shop Upgrade LV|Vault Upgrade bonus LV|Total Gambit Time|Total Digits of all Cavern Resources|Total LV of Cavern Villagers|Megafeathers Earned from Orion|Megafish Earned from Poppy|Best Bravery Monument Round|Best Justice Monument Round|Best Wisdom Monument Round|Best Deathbringer Max Damage in Wraith Mode|Best Dawg Den score|Total Resource Layers Destroyed|Total Opals Found|Best Pure Memory Round Reached|Spirited Valley Emperor Boss Kills|Total Summoning Boss Stone victories`.split('|');
  const levelReq=[390,430,470,510,550,590,630,670,710,750,790,830,870,910,950,990,1030,1070,1110,1150,1190,1230,1270,1310,1350,1390,1430,1470,1510,1550,1590,1630,1670,1710,1750,1795,1840,1885,1930,1975,2020,2065,2110,2155,2200,2245,2290,2335,2380,2425,2470,2515,2560,2605,2650,2695,2740,2785,2830,2875,2930,2985,3040,3095,3150,3205,3260,3315,3370,3425,3480,3535,3590,3645,3700,3755,3810,3865,3920,3975,4030,4085,4140,4195,4250,4305,4360,4415,4470,4525,4580,4635,4690,4745,4800,4855,4910];
  const tomeMetrics=metricNames.map((name,id)=>({id,name,levelReq:levelReq[id]}));
  const tomeBonuses=[
    ['Damage','Scales with Tome score','Default'],['Skill Efficiency','+4% per 100 Completion Points over 4,000','2 Blue Tome Pages'],['Drop Rate','+2% per 100 Completion Points over 8,000','7 Red Tome Pages'],['STR','Stacks every 2,000 Completion Points over 5,000','Alchemy · Tome Strength'],['AGI','Stacks every 2,000 Completion Points over 5,000','Alchemy · Tome Agility'],['WIS','Stacks every 2,000 Completion Points over 5,000','Alchemy · Tome Wisdom'],['Crop Evolution Chance','Stacks every 2,000 Completion Points over 5,000','Alchemy · Crop Chapter'],['Stealth','Stacks every 2,000 Completion Points over 5,000','Alchemy · Stealth Chapter'],['All Essence Gain','Stacks every 2,000 Completion Points over 5,000','Alchemy · Essence Chapter'],['Golden Tome Damage','Adds a Tome damage multiplier','Event Shop · Golden Tome']
  ].map(([name,effect,source],id)=>({id,name,effect,source}));
  const slabBonuses=[
    ['SLABI OREFISH','Mining and Fishing Power per 100 items found','Alchemy'],['SLABI STRENGTH','Base STR per 100 items found','Alchemy'],['SLABO CRITTERBUG','Catching and Trapping Power per 100 items found','Alchemy'],['SLABO AGILITY','Base AGI and LUK per 100 items found','Alchemy'],['SLABE LOGSOUL','Choppin and Worship Power per 100 items found','Alchemy'],['SLABE WISDOM','Base WIS per 100 items found','Alchemy'],['Slab Sovereignty','All Slab bonuses are 1.25× higher','Laboratory'],['Pure Opal Rhinestone','Adds another 20% to Slab Sovereignty','Laboratory Jewel'],['Ruble Cuble','+1% Total Damage per 10 items after 500','Sailing Artifact'],['10 AD Tablet','+4% Sailing Speed per 10 items after 500','Sailing Artifact'],['Jade Rock','+3% Divinity per 10 items after 500','Sailing Artifact'],['Gummy Orb','+15% Bits per 10 items after 500','Sailing Artifact'],['Harp Measure','Harp Note Gain from Slab progress','The Hole'],['Villager Measure','Villager EXP Gain from Slab progress','The Hole'],['Slabby Spelunking','Total Spelunking Power from Slab progress','Gaming · Duperbits'],['Slabby Research','Research EXP gain from Slab progress','Gaming · Duperbits'],['+1 Slab','Slab bonuses become 1.15× larger','World 7 Legend Talent']
  ].map(([name,effect,source],id)=>({id,name,effect,source}));
  root.COLLECTION_CATALOG={tomeMetrics,tomeBonuses,slabBonuses};
})(typeof window!=='undefined'?window:globalThis);
