(function(root){
  'use strict';
  const M=typeof module!=='undefined'&&module.exports?require('./dailies-model'):root.DailiesModel;
  const KEY='idleon-dailies-v1',object=x=>x&&typeof x==='object'&&!Array.isArray(x);
  const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function render(host,raw){
    const rows=M.model(raw),account=M.accountKey(raw);
    let saved={},storageError=false,tab='daily',filter='all',settingsOpen=false;
    try{saved=JSON.parse(root.localStorage.getItem(KEY))||{};}catch{storageError=true;}
    if(!object(saved))saved={};
    let state=Object.hasOwn(saved,account)&&object(saved[account])?saved[account]:{};
    for(const key of ['checks','hidden','cycles'])if(!object(state[key]))state[key]={};
    for(const [key,fallback,max] of [['hour',0,23],['weekday',4,6],['weeklyHour',0,23]])if(!Number.isInteger(state[key])||state[key]<0||state[key]>max)state[key]=fallback;
    const save=()=>{try{root.localStorage.setItem(KEY,JSON.stringify({...saved,[account]:state}));}catch{storageError=true;}};
    const hours=selected=>Array.from({length:24},(_,hour)=>`<option value="${hour}" ${selected===hour?'selected':''}>${String(hour).padStart(2,'0')}:00</option>`).join('');
    const paint=()=>{
      const now=Date.now(),hidden=rows.filter(row=>M.hiddenReason(row,state)),active=rows.filter(row=>!M.hiddenReason(row,state)),scope=tab==='hidden'?hidden:active.filter(row=>tab==='all'||tab==='unknown'&&row.ready==null||row.repeat===tab&&row.ready===true);
      const done=scope.filter(row=>M.done(row,state,now)).length,ready=active.filter(row=>row.ready===true&&!M.done(row,state,now));
      const shown=scope.filter(row=>filter==='all'||filter==='todo'&&!M.done(row,state,now)||filter==='ready'&&row.ready===true&&!M.done(row,state,now));
      const counts=repeat=>active.filter(row=>row.repeat===repeat&&row.ready===true).length;
      host.innerHTML=`<section class="dailies"><header class="section-head"><div><p class="eyebrow">Home · Your routine</p><h2>Dailies & weeklies</h2><p>Only tasks your save confirms are ready.</p></div><div class="daily-progress"><strong>${scope.length}</strong><span>in this view</span></div></header>
      <div class="daily-summary"><button type="button" class="secondary" id="dailyReadySummary">${ready.length} ready in saved data</button><button type="button" class="secondary" id="dailyBossSummary">${ready.filter(row=>row.miniboss).length} minibosses at 2+</button><button type="button" class="secondary" id="dailyHiddenSummary">${hidden.length} filtered out</button></div>
      <p class="daily-note">Based on your imported save. Refresh it after playing. Finished, unavailable, and checked tasks are filtered out.</p>
      <nav class="daily-tabs" aria-label="Routine frequency">${[['daily',`Daily · ${counts('daily')}`],['weekly',`Weekly · ${counts('weekly')}`],['timers',`Timers & minibosses · ${counts('timers')}`],['unknown',`Needs checking · ${active.filter(row=>row.ready==null).length}`],['all','All'],['hidden',`Filtered · ${hidden.length}`]].map(([id,label])=>`<button type="button" class="secondary ${tab===id?'active':''}" data-frequency="${id}" aria-pressed="${tab===id}">${label}</button>`).join('')}</nav>
      <div class="daily-controls"><label>Show <select id="dailyFilter">${[['all','All in this view'],['todo','Unchecked'],['ready','Ready in save']].map(([id,label])=>`<option value="${id}" ${filter===id?'selected':''}>${label}</option>`).join('')}</select></label><button type="button" class="secondary" id="dailySettings" aria-expanded="${settingsOpen}">Routine settings</button><span>Saved ${account==='local'?'on this browser (no account name in export)':`for ${esc(account)}`}.</span></div>
      ${settingsOpen?`<section class="daily-settings"><label class="daily-check"><input type="checkbox" id="dailyAutoHide" ${state.autoHide!==false?'checked':''}> Automatically filter finished and unavailable tasks</label><p class="daily-note">Filters completed unlock goals, exhausted attempts, saved completion flags, locked worlds, minibosses below two, and your checked items. Research returns when a new observation becomes available. Unknown status stays under Needs checking. Inspect every reason in Filtered.</p><div class="daily-controls"><label>Daily checklist reset (local)<select id="dailyHour">${hours(state.hour)}</select></label><label>Weekly checklist reset (UTC)<select id="dailyWeekday">${['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'].map((day,i)=>`<option value="${i}" ${state.weekday===i?'selected':''}>${day}</option>`).join('')}</select></label><label>Weekly hour (UTC)<select id="dailyWeeklyHour">${hours(state.weeklyHour)}</select></label></div><p class="daily-note">Weekly checks default to Thursday 00:00 UTC. Timer reminders reset with your daily checklist; this does not predict their in-game cooldowns. Miniboss checks stay marked for the same saved counter and reopen when that counter changes.</p></section>`:''}
      ${storageError?'<p role="status">Browser storage is unavailable. Changes may not survive leaving this page.</p>':''}
      ${tab==='hidden'?'<p class="daily-note">Reasons are shown below. Save-based filters update on import. Restore personal choices here or turn off automatic filtering in settings.</p>':tab==='unknown'?'<p class="daily-note">These activities still need a verified rule, complete save data, or a personal collection target. Details explain what is missing; they are not counted as ready or completed.</p>':''}
      <div class="daily-grid">${shown.map(row=>{
        const checked=M.done(row,state,now),reason=M.hiddenReason(row,state);
        return `<article class="daily-card ${checked?'is-done':''} ${row.miniboss&&row.ready?'daily-boss-ready':''}" data-routine="${row.id}"><div class="daily-card-main"><label class="daily-check"><input type="checkbox" data-daily="${row.id}" ${checked?'checked':''}><strong>${esc(row.name)}</strong></label><span class="daily-status ${row.ready===true?'available':''}">${esc(row.status||'Not confirmed')}</span></div><div class="daily-card-bottom"><span class="daily-world">W${row.world} · ${row.repeat==='timers'?'Timer':row.repeat==='weekly'?'Weekly':'Daily'}</span><div class="daily-card-actions">${row.page?`<button type="button" class="secondary" data-daily-link="${row.page}" aria-label="Open ${esc(row.name)}">Open →</button>`:row.url?`<a href="${esc(row.url)}" target="_blank" rel="noopener noreferrer">Guide ↗</a>`:''}<button type="button" class="secondary" data-hide-routine="${row.id}" ${reason&&!state.hidden[row.id]?'disabled':''}>${state.hidden[row.id]?'Restore':reason?'Filtered':'Hide'}</button></div></div>${reason?`<small class="daily-hidden-reason">${esc(reason)}</small>`:''}<details class="daily-task-detail"><summary>Details${row.miniboss&&row.count!==null?` · ${row.count>=2?'2+ ready':row.count+' / 2 target'}`:''}</summary><p>${esc(row.hint)}</p>${row.detail?`<small>${esc(row.detail)}</small>`:''}</details></article>`;
      }).join('')||`<p class="daily-empty">${tab==='hidden'?'No filtered activities.':filter==='ready'?'No unchecked activities confirmed ready in this save.':'Nothing confirmed ready in this view. See Needs checking for unverified reminders.'}</p>`}</div>
      <details class="daily-sources"><summary>Research & coverage</summary><p>Includes daily claims, weekly rotations, four stacking minibosses, and optional collection reminders. Only verified save counters show availability. Other activities remain manual and can be hidden per account.</p><p><a href="https://incendar.com/idleon-daily-routines.php" target="_blank" rel="noopener noreferrer">Routine reference</a> · <a href="https://idleon.wiki/wiki/Dilapidated_Slush" target="_blank" rel="noopener noreferrer">Miniboss spawn tables</a>. Counter formulas are checked against the local game client; older guides may still list the free companion as weekly.</p></details></section>`;
      const focus=selector=>host.querySelector(selector)?.focus();
      host.querySelectorAll('[data-frequency]').forEach(button=>button.onclick=()=>{tab=button.dataset.frequency;filter='all';paint();focus(`[data-frequency="${tab}"]`);});
      host.querySelector('#dailyReadySummary').onclick=()=>{tab='all';filter='ready';paint();focus('#dailyFilter');};
      host.querySelector('#dailyBossSummary').onclick=()=>{tab='timers';filter='ready';paint();focus('#dailyFilter');};
      host.querySelector('#dailyHiddenSummary').onclick=()=>{tab='hidden';filter='all';paint();focus('[data-frequency="hidden"]');};
      host.querySelector('#dailyFilter').onchange=e=>{filter=e.target.value;paint();focus('#dailyFilter');};
      host.querySelector('#dailySettings').onclick=()=>{settingsOpen=!settingsOpen;paint();focus('#dailySettings');};
      for(const [id,key] of [['dailyHour','hour'],['dailyWeekday','weekday'],['dailyWeeklyHour','weeklyHour']]){const input=host.querySelector('#'+id);if(input)input.onchange=e=>{state[key]=Number(e.target.value);save();paint();focus('#'+id);};}
      const auto=host.querySelector('#dailyAutoHide');if(auto)auto.onchange=e=>{state.autoHide=e.target.checked;save();paint();focus('#dailyAutoHide');};
      host.querySelectorAll('[data-daily]').forEach(input=>input.onchange=()=>{const id=input.dataset.daily;state.checks[id]=input.checked?Date.now():null;const row=rows.find(row=>row.id===id);if(row.miniboss)state.cycles[id]=row.cycle;save();paint();if(host.querySelector(`[data-daily="${id}"]`))focus(`[data-daily="${id}"]`);else focus('#dailyHiddenSummary');});
      host.querySelectorAll('[data-hide-routine]').forEach(button=>button.onclick=()=>{const id=button.dataset.hideRoutine;state.hidden[id]=!state.hidden[id];save();paint();focus(tab==='hidden'?'[data-frequency="hidden"]':'#dailyHiddenSummary');});
      host.querySelectorAll('[data-daily-link]').forEach(button=>button.onclick=()=>root.dispatchEvent(new CustomEvent('idleon:navigate',{detail:button.dataset.dailyLink})));
    };
    paint();clearInterval(render.timer);
    let dailyStart=M.period(Date.now(),state.hour),weeklyStart=M.period(Date.now(),0,'weekly',state.weekday,state.weeklyHour);
    render.timer=setInterval(()=>{if(host.dataset.page!=='dailies'){clearInterval(render.timer);return;}const daily=M.period(Date.now(),state.hour),weekly=M.period(Date.now(),0,'weekly',state.weekday,state.weeklyHour);if(daily!==dailyStart||weekly!==weeklyStart){dailyStart=daily;weeklyStart=weekly;paint();}},30000);
  }
  const api={...M,render};if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.Dailies=api;
})(typeof window==='undefined'?globalThis:window);
