(function(root){
'use strict';
const parse=v=>{if(typeof v==='string'){try{return JSON.parse(v)}catch{}}return v;},n=v=>Number.isFinite(Number(v))?Number(v):0;
const text=v=>String(v??'').replace(/[_@|]/g,' ').replace(/\s+/g,' ').trim(),fmt=v=>root.ProgressionModels.fmt(v);
const effect=(v,b)=>text(v).replace(/\}x/g,fmt(1+n(b)/100)+'x').replace(/[{$^]/g,fmt(b));
const title=v=>text(v).replace(/^[+{}%$^x ]+/,'');
function build(d,raw){
 const data=parse(raw?.data)||raw||{},s=parse(data.Spelunk)||[],r=parse(data.Research)||[],opt=parse(data.OptionsListAccount??data.OptLacc)||[],c=root.WORLD7_CATALOG,a=root.ENDGAME_ASSETS||{},out={};
 const art=id=>a.images?.includes(id)?`assets/${id}.png`:null;
 const row=(name,bonus,level,icon,extra={})=>({name:text(name),effect:text(bonus),level:typeof level==='number'?`Lv ${fmt(level)}`:level,icon:art(icon),status:typeof level==='number'?(level>0?'active':'missing'):'active',...extra});
 const zen=d.get('zenithMarket');if(zen)out.zenithMarket=zen.bonuses.map(x=>row(x.data.name,effect(x.data.description,x.getBonus()),`Lv ${x.level} / ${x.data.maxLevel}`,'Zenith',{status:x.level>=x.data.maxLevel?'maxed':x.level?'active':'missing',summary:`${fmt(zen.depositedClusters)} deposited clusters · ${fmt(zen.nonDepositedClusters.reduce((v,x)=>v+x.quantity,0))} in inventory/storage`,detail:`${x.level>=x.data.maxLevel?'Maximum level reached.':'Base next-level cost: '+fmt(x.data.unlockCost*Math.pow(x.data.costExponent,x.level))+' clusters.'} Bonus per level: ${x.data.bonusPerLevel}.`}));
 const fish=d.get('bigFish');if(fish)out.bigFish=fish.bonuses.map(x=>row(x.data.name,effect(x.data.desc,x.getBonus()),x.level,`Advice_Fish_${x.index}`,{status:x.unlocked?'active':'missing',cost:x.getUpgradeCost(),detail:`Requires total account Lv ${fmt(x.getUnlockLevelRequired())}. Bonus approaches ${x.data.x0}% with diminishing returns. Next: ${effect(x.data.desc,(x.level+1)/(101+x.level)*x.data.x0)}.`}));
 const reef=d.get('coralReef');if(reef)out.coralReef=reef.upgrades.map(x=>row(`Reef ${x.index+1}`,x.getBonusText(),`Lv ${x.level} / ${x.data.x0}`,`Coral${x.index}`,{status:!x.unlocked?'missing':x.level>=x.data.x0?'maxed':'active',summary:`${fmt(reef.ownedCoral)} coral · ${fmt(reef.dailyCoralGains)} generated daily`,detail:`${x.unlocked?'Unlocked reef.':'Not yet unlocked.'} Base upgrade cost: ${fmt(x.data.x1*Math.pow(x.data.x2,x.level))} coral before discounts.`}));
 const kid=d.get('coralKid');if(kid)out.coralKid=kid.coralKidBonuses.map(x=>row(`Coral Kid ${x.index+1}`,effect(x.bonus.split('Total Bonus:')[0].split('(Your Divinity')[0],x.getBonus()),x.level,`CoralKid${x.index}`,{cost:x.getUpgradeCost(),detail:'Cost is Divinity points. Base benefit shown; character-specific Minor Link scaling and account-dependent totals are not included.'}));
 const dance=d.get('dancingCoral');if(dance)out.dancingCoral=dance.bonuses.map(x=>row(x.data.name,x.getBonusText(),x.purchased?'Purchased':'Not purchased',`Coral${x.index}`,{status:x.purchased?'active':'missing',detail:`Resource: ${x.data.itemSource}. Listed purchase cost: ${fmt(x.data.cost)}. Shrine level: ${fmt(x.shrineLevel)}.`}));
 const clam=d.get('clamworks');if(clam)out.clamworks=[...clam.workBonuses.map(x=>row(`Work ${x.index+1}`,clam.getClamBonusText(x.index),x.level,'Clam',{group:'Work upgrades',summary:`${fmt(clam.pearlsOwned)} pearls · Promotion ${clam.promoLevel} · Next promotion chance ${fmt(clam.getPromoChance()*100)}%`,detail:`Next upgrade: ${fmt(clam.getClamCost(x.index))} pearls. Promotion attempt: ${fmt(clam.getPromoTryCost())} pearls.`})),...clam.promoBonuses.map(x=>row(`Promotion ${x.index+1}`,x.bonus,x.active?'Unlocked':'Locked','ClamW',{group:'Promotions',status:x.active?'maxed':'missing',detail:`Current promotion level: ${clam.promoLevel}.`}))];
 const merit=d.get('meritocraty');if(merit)out.meritocracy=merit.bonuses.filter(x=>x.index>0).map(x=>row(`Merit ${x.index}`,effect(x.data.text,x.data.bonus*merit.getBonusMultiplier()),x.index===merit.currentBonusIndex?'Current bonus':'Not selected',`MeritBon${x.index}`,{status:x.index===merit.currentBonusIndex?'active':'unknown',summary:`Merit multiplier: ${fmt(merit.getBonusMultiplier())}x · ${merit.currentBonusIndex?'Current weekly bonus highlighted':'Current weekly selection absent from export'} · ${merit.canVote?'Vote available':'Vote already used / unavailable'}`,detail:'Only the selected weekly merit is active. Other tiles show their effect if selected, not a missing permanent upgrade.'}));
 const legend=d.get('legendTalents');if(legend)out.legendTalents=legend.talents.filter(x=>x.data.name!=='filler').sort((x,y)=>x.displayOrder-y.displayOrder).map(x=>row(x.data.name,x.getDesc(),`Lv ${x.level} / ${x.data.maxLevel}`,`LegendTalentIcon${x.displayOrder}`,{group:['Gold','Purple','Brown','Green','Super'][Math.floor(x.displayOrder/10)]||'Other',status:x.level>=x.data.maxLevel?'maxed':x.level?'active':'missing',summary:`${legend.pointsAvaible} points available · ${legend.pointsSpent} spent · ${legend.pointsOwned} earned · Super talents +${legend.superTalentBonusLevels} levels`,detail:x.getNextLevelDesc()?`Next level: ${x.getNextLevelDesc()}`:'Maximum level reached.'}));
 const sushi=d.get('sushi');if(sushi)out.sushi=sushi.sushi.map(x=>row(x.data.name,effect(x.data.unlockDescription,x.getBonus()),x.unlocked?'Discovered':'Missing',`Sushi${x.index}`,{group:'Sushi collection',status:x.unlocked?'maxed':'missing',summary:`${sushi.uniqueSushi} unique sushi discovered`,detail:`Permanent first-discovery reward. Knowledge category: ${text(x.data.knowledgeBonusCategory).replace(/[{}^]/g,'[value]')}. Base knowledge bonus: ${x.data.knowledgeBonusBase}.`}));
 const button=d.get('button');if(button){const presses=n(opt[594]),active=Math.floor(presses/5)%9;out.button=button.bonuses.map(x=>row(x.data.name,`${String(a.buttonBonusNames?.[x.index]).startsWith('+')?'+'+fmt(x.getBonus())+'%':fmt(1+x.getBonus()/100)+'x'} ${x.data.name}`,`${x.categoryPresses} presses`,'ResBut0',{group:'Bonuses',next:x.index===active,summary:`${fmt(presses)} total presses · ${n(opt[595])} instant skips left · ${presses%5} / 5 presses in current category`,detail:`Next press ${x.index===active?'adds '+fmt(x.data.bonusPerPress*x.bonusMultiplier)+' percentage points to this bonus.':'advances a different category.'} Every five presses rotates to the next category; nine categories form a 45-press cycle.`}));}
 if(button&&c?.ButtonTasks){const presses=n(opt[594]);for(let offset=0;offset<10;offset++){const count=presses+offset,idx=n(c.Research[39][count%100])%c.ButtonTasks.length,t=c.ButtonTasks[idx],base=n(t[1]),factor=n(t[3])||1,required=t[2]==='exponent'?base*Math.pow(factor,count):t[2]==='linear'?Math.ceil(base+count*factor):t[2]==='step'?Math.ceil(base+count/factor):base;out.button.push(row(offset===0?'Current requirement':`Upcoming press ${count+1}`,text(t[0]).replaceAll('{',fmt(required)),`Press ${count+1}`,'ResBut0',{group:'Tasks & next presses',detail:`Rewards ${button.bonuses[Math.floor(count/5)%9]?.data.name}. Requirement is calculated from the saved press count. Completion is not claimed: live character stats can change after this export.`}));}}
 const sushiRaw=parse(data.Sushi)||[];if(sushi&&c?.SushiUPG){for(const [id,x] of c.SushiUPG.entries()){const level=n(sushiRaw[2]?.[id]);out.sushi.push(row(x[0],effect(x[5],level*n(x[3])),level,`SushiUpg${id}`,{group:'Station upgrades',summary:`${fmt(sushiRaw[4]?.[3])} Bucks · ${fmt(sushiRaw[4]?.[0])} fuel · ${fmt(sushiRaw[4]?.[2])} sparks · Best combo ${fmt(sushiRaw[4]?.[8])}`,detail:`Base next-level cost: ${fmt(n(x[1])*Math.pow(n(x[2]),level))} Bucks before discounts. Saved upgrade level ${level}.`}));}for(const [id,lv] of (sushiRaw[7]||[]).entries()){if(!c.Research[34]?.[id])continue;out.sushi.push(row(title(c.Research[34][id]),effect(c.Research[34][id],n(lv)*n(c.Research[35][id])),n(lv),'SushiInfo',{group:'Knowledge',detail:`Saved knowledge EXP: ${fmt(sushiRaw[6]?.[id])}. Knowledge is separate from first-discovery sushi unlock rewards.`}));}}
 if(c){const found=new Set((s[6]||[]).map(text));const sp=d.get('spelunking')||{tunnels:(c.SpelunkRocks||[]).map((rocks,index)=>({index,name:c.Spelunky[6][index],unlocked:n(s[0]?.[index])>0,bestDepth:n(s[1]?.[index]),biggestHaul:n(s[2]?.[index]),bossDepth:n(c.Spelunky[7][index]),loreBonus:'Defeat the lore boss to unlock its chapter.',discoveries:rocks.slice(0,-1).map((x,i)=>({index:i,name:x[0],unlocked:found.has(text(x[0]))}))})),upgrades:c.SpelunkUpg.map((x,index)=>({index,level:s[5]?.[index]??-1}))};out.spelunking=[];
 for(const t of sp?.tunnels||[]){out.spelunking.push(row(t.name,`Best depth ${fmt(t.bestDepth)} · ${t.discoveries.filter(x=>x.unlocked).length}/${t.discoveries.length} discoveries`,t.unlocked?'Unlocked':'Locked',`CaveDoor${t.index}`,{group:'Tunnels',status:t.unlocked?'active':'missing',summary:`${fmt(s[4]?.[0])} Amber · Stamina is saved per character, not per tunnel`,detail:`Best haul: ${fmt(t.biggestHaul)}. Lore boss at depth ${fmt(t.bossDepth)}. ${text(t.loreBonus)}`}));for(const x of t.discoveries)out.spelunking.push(row(x.name,`Tunnel: ${t.name}`,x.unlocked?'Discovered':'Missing',`CaveRock${String.fromCharCode(97+t.index)}${x.index}`,{group:'Discoveries',status:x.unlocked?'maxed':'missing',detail:`${text(t.name)} · Discovery ${x.index+1}. Finding new discoveries improves your account's Spelunking progress.`}));}
 for(const x of sp?.upgrades||[]){const source=c.SpelunkUpg[x.index];out.spelunking.push(row(source[0],text(source[12]).split('Total Bonus:')[0].replace(/\{/g,fmt(n(source[4])*Math.max(0,x.level))).replace(/[}$^]/g,'[account-scaled]'),`Lv ${Math.max(0,x.level)} / ${source[3]}`,`CaveShopUpg${x.index}`,{group:'Upgrades',status:x.level<0?'missing':x.level>=n(source[3])?'maxed':'active',detail:`Base cost ${fmt(source[1])}; cost growth ${source[2]}x. Base rate shown before account-dependent scaling. Locked upgrades show level 0, not a negative level.`}));}
 const chapterNames=['The Fear Within','Decay Surrounds','This Is Gospel','No Escape','Sunken Plunder','Kelp Primeval'];
 (c.SpelunkChapters||[]).forEach((chapter,i)=>{if(!chapterNames[i])return;chapter.forEach((x,j)=>{const pages=n(s[8]?.[4*i+j]),base=n(x[1]),scale=n(x[2]),threshold=n(x[5]),decay=String(x[3]).startsWith('decay'),value=decay?base*pages/(scale+pages||1):base*pages+scale,multi=n(x[4])===1?1+(d.get('sailing')?.artifacts?.[35]?.getBonus?.()||0)/100:1;const breakpoints=decay?[.5,.75,.9,.95,.99].map(p=>`${p*100}% of scaling component: ${fmt(Math.ceil(scale*p/(1-p)))} reads`).join('\n'):'Linear bonus: every additional read adds '+fmt(base*multi)+'.';out.spelunking.push(row(`${chapterNames[i]} · ${j+1}`,text(x[0]).replace('{',fmt(value*multi)).replace('}',fmt(Math.max(1,(value+(x[3]==='decayMulti'?1:0))*multi))),`${fmt(pages)} reads`,`Spelunking${i}`,{group:'Daily Lore',status:pages?'active':'missing',detail:`${text(x[0]).replace(/[{}]/g,'')}.\nPage requirement: ${fmt(threshold)}.\n${breakpoints}\n${decay?'The ceiling is asymptotic, not a finite max. ':''}Daily reading: 5 base reads, increased to 8 with the Spelunking mastery reward. Check the game for remaining daily reads; no daily-claim state is inferred from lifetime totals.`}));});});
 const research=d.get('research'),researchLevel=Math.max(0,...(d.get('players')||[]).map(p=>n(p.skills?.get?.(20)?.level)));out.research=(research?.bonuses||[]).filter(x=>x.data.name!=='Name').map(x=>row(x.data.name,effect(x.data.description,x.getBonus()),x.level,'ResearchQuick0',{id:x.index,max:x.data.maxLevel,shape:n(r[1]?.[x.index]??-1),status:x.level>=x.data.maxLevel?'maxed':x.level?'active':'missing',detail:`Grid cell ${x.index+1} · Lv ${x.level} / ${x.data.maxLevel}. Shape boost +${fmt(x.shapeBonusPercent)}%. Account grid multiplier ${fmt(x.allBonusMultiplier)}x.`,summary:`${researchLevel?'Research Lv '+fmt(researchLevel)+' · ':''}${(r[0]||[]).reduce((a,b)=>a+n(b),0)} grid points spent · ${n(r[7]?.[2])} daily observation rolls left`}));
 out.researchObservations=(r[4]||[]).slice(0,43).map((lv,id)=>row(a.observations?.[id]?.name||`Observation ${id+1}`,`Insight progress ${fmt(r[3]?.[id])}`,n(lv),`ResObj${id}`,{id,status:n(r[2]?.[id])>=1?'active':'missing',detail:`${text(a.observations?.[id]?.description||'')} Requires Research Lv ${a.observations?.[id]?.researchLvReq||'?'}. Found state: ${n(r[2]?.[id])}. Lens placements linked to this observation: ${(r[5]||[]).filter((v,j)=>j%4===2&&n(v)===id).length}.`}));
 }
 return out;
}
root.EndgameModels={build};
})(typeof window!=='undefined'?window:globalThis);
