(function(root){
  'use strict';
  const parse=v=>{if(typeof v==='string'){try{return JSON.parse(v);}catch{return v;}}return v;};
  const number=v=>v!==null&&v!==undefined&&v!==''&&Number.isFinite(Number(v))?Number(v):0;
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const pretty=v=>String(v??'').replaceAll('_',' ').replaceAll('@',' ').replace(/[{}]/g,'').replace(/\s+/g,' ').trim();
  const fmt=v=>Number(v).toLocaleString(undefined,{maximumFractionDigits:2});
  const UNLOCK_REWARDS=[0,2,5,7,10,13,17,20,23,28,31,36];
  const ADDITIVE={3:10,9:15,14:20,19:25,22:30,24:35,29:40,38:60,40:65,44:75,46:90,48:100,51:120,54:150,56:160,57:170,60:185,62:190,63:195,65:200,68:220,74:250};
  const MULTI={45:1.03,49:1.05,52:1.06,59:1.07,67:1.07};
  const CAP_BONUSES={3:{6:3,15:4},4:{12:5,18:10,34:10,39:10},5:{32:6},8:{21:5,26:10},9:{25:4},10:{30:4},11:{35:15},12:{37:5,42:5,43:5,47:5,50:5,55:5,58:6,61:6,64:7,75:8}};
  function decode(data,catalog=root.EQUINOX_CATALOG){
    const dream=parse(data?.Dream)||[],weekly=parse(data?.WeeklyBoss)||{};
    const complete=id=>number(weekly?.['d_'+id])===-1;
    const challenges=catalog.DreamChallenge.map((row,id)=>({id,description:pretty(row[0]),target:number(row[1]),reward:pretty(row[2]),completed:complete(id),progress:complete(id)?number(row[1]):Math.max(0,number(weekly?.['d_'+id]))}));
    const levels=catalog.DreamUpg.map((_,id)=>Math.max(0,number(dream[id+2])));
    const completed=challenges.filter(x=>x.completed).length,totalLevels=levels.reduce((a,b)=>a+b,0);
    const unlockedUpgrades=Math.min(catalog.DreamUpg.length,1+UNLOCK_REWARDS.filter(complete).length);
    const upgrades=catalog.DreamUpg.map((row,id)=>{const extra=Object.entries(CAP_BONUSES[id]||{}).reduce((sum,[challenge,amount])=>sum+(complete(Number(challenge))?amount:0),0);return{id,name:pretty(row[0]),description:pretty(row[1]),level:levels[id],baseMax:number(row[2]),knownMax:number(row[2])+extra,perLevel:row[3],unlocked:id<unlockedUpgrades};});
    const requirement=(120+40*totalLevels)*Math.pow(1.02,totalLevels),bar=Math.max(0,number(dream[0]));
    const additive=Object.entries(ADDITIVE).reduce((sum,[id,value])=>sum+(complete(Number(id))?value:0),0);
    const multiplier=Object.entries(MULTI).reduce((product,[id,value])=>product*(complete(Number(id))?value:1),1);
    return{available:Array.isArray(dream)&&dream.length>0||Object.keys(weekly).some(k=>k.startsWith('d_')),bar,requirement,barPercent:requirement?Math.min(100,bar/requirement*100):0,totalLevels,completed,cloudsOwned:Math.min(5,levels[0]||0),unlockedUpgrades,challenges,upgrades,additive,multiplier};
  }
  let currentTab='dreams',page=0,filter='all';
  function render(host,data){const model=decode(data);function paint(){
    const tabs=[['dreams','Dream Clouds'],['upgrades','Upgrades'],['overview','Equinox Bar']];let body='';
    if(currentTab==='dreams'){
      const filtered=model.challenges.filter(x=>filter==='all'||filter==='complete'&&x.completed||filter==='incomplete'&&!x.completed),size=15,pages=Math.max(1,Math.ceil(filtered.length/size));page=Math.min(page,pages-1);const shown=filtered.slice(page*size,page*size+size);
      body=`<div class="equinox-toolbar"><div>${[['all','All'],['incomplete','Incomplete'],['complete','Completed']].map(([id,label])=>`<button class="secondary ${filter===id?'selected':''}" data-eq-filter="${id}">${label}</button>`).join('')}</div><span>${filtered.length} dreams</span></div><div class="dream-grid">${shown.map(x=>`<button class="dream-card ${x.completed?'complete':''}" data-eq-dream="${x.id}"><img src="assets/${x.completed?'Dream_Cloud2':'Dream_Cloud'}.png" alt=""><span class="dream-number">Dream ${x.id+1}</span><strong>${esc(x.description)}</strong><small>${x.completed?'Completed':`${fmt(x.progress)} / ${fmt(x.target)}`}</small><em>${esc(x.reward)}</em></button>`).join('')}</div><div class="collection-pager"><button class="secondary" data-eq-page="prev" ${page===0?'disabled':''}>Previous</button><span>${page+1} / ${pages}</span><button class="secondary" data-eq-page="next" ${page>=pages-1?'disabled':''}>Next</button></div>`;
    }else if(currentTab==='upgrades')body=`<div class="upgrade-grid">${model.upgrades.map(x=>`<button class="equinox-upgrade ${x.unlocked?'':'locked'}" data-eq-upgrade="${x.id}"><img src="assets/Dream_Upg${x.id%2}.png" alt=""><span>Upgrade ${x.id+1}</span><strong>${esc(x.name)}</strong><small>Lv ${fmt(x.level)} / ${fmt(x.knownMax)} known</small><em>${x.unlocked?esc(x.description):'Complete more Dream Clouds to unlock'}</em></button>`).join('')}</div><p class="equinox-note">“Known max” includes the base cap and completed Dream Cloud cap rewards. Other systems can add more levels to some upgrades.</p>`;
    else body=`<div class="equinox-overview"><section class="equinox-bar-card"><h3>Equinox Bar</h3><div class="equinox-progress"><i style="width:${model.barPercent}%"></i></div><strong>${fmt(model.bar)} / ${fmt(model.requirement)} (${model.barPercent.toFixed(1)}%)</strong><p>Requirement for the next upgrade level, based on ${fmt(model.totalLevels)} total upgrade levels.</p></section><section class="equinox-stats"><article><span>Dream Clouds</span><strong>${model.completed} / ${model.challenges.length}</strong></article><article><span>Visible clouds</span><strong>${model.cloudsOwned} / 5</strong></article><article><span>Upgrades unlocked</span><strong>${model.unlockedUpgrades} / ${model.upgrades.length}</strong></article><article><span>Total upgrade levels</span><strong>${fmt(model.totalLevels)}</strong></article></section><section class="equinox-bonuses"><h3>Earned Dream rewards affecting the bar</h3><p><strong>+${fmt(model.additive)}%</strong> additive fill rate from completed Dream Clouds.</p><p><strong>${model.multiplier.toFixed(3)}×</strong> multiplicative fill rate from completed Dream Clouds.</p><p class="muted">Base production is 60 bar per hour. The final in-game rate also uses bonuses from other systems, so this page does not pretend the Dream-only total is your complete rate.</p></section></div>`;
    host.innerHTML=`<div class="equinox-hero"><img src="assets/FishEquinox.png" alt=""><div><p class="eyebrow">World 3 · Equinox Valley</p><h2>Equinox</h2><p>Every Dream Cloud, permanent reward, upgrade, and saved Equinox Bar value.</p></div><strong>${model.completed} / ${model.challenges.length} dreams</strong></div>${!model.available?'<p class="collection-note">Equinox save fields were not found. The complete in-game catalogs are still available below.</p>':''}<nav class="skill-tabs" role="tablist">${tabs.map(([id,label])=>`<button class="skill-tab${currentTab===id?' active':''}" data-eq-tab="${id}">${label}</button>`).join('')}</nav>${body}<section id="equinoxDetail" class="exp-card w5-detail detail-dismissed"></section>`;
    host.querySelectorAll('[data-eq-tab]').forEach(b=>b.onclick=()=>{currentTab=b.dataset.eqTab;page=0;paint();});host.querySelectorAll('[data-eq-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.eqFilter;page=0;paint();});host.querySelectorAll('[data-eq-page]').forEach(b=>b.onclick=()=>{page+=b.dataset.eqPage==='next'?1:-1;paint();});host.querySelectorAll('[data-eq-dream]').forEach(b=>b.onclick=()=>details('dream',Number(b.dataset.eqDream)));host.querySelectorAll('[data-eq-upgrade]').forEach(b=>b.onclick=()=>details('upgrade',Number(b.dataset.eqUpgrade)));
  }function details(type,id){const panel=host.querySelector('#equinoxDetail'),x=type==='dream'?model.challenges[id]:model.upgrades[id];panel.innerHTML=type==='dream'?`<button class="secondary eq-close">Close</button><p class="eyebrow">Dream ${id+1}</p><h3>${esc(x.description)}</h3><p><strong>Status:</strong> ${x.completed?'Completed':`${fmt(x.progress)} / ${fmt(x.target)}`}</p><p><strong>Permanent reward:</strong> ${esc(x.reward)}</p>`:`<button class="secondary eq-close">Close</button><p class="eyebrow">Upgrade ${id+1}</p><h3>${esc(x.name)}</h3><p>${esc(x.description)}</p><p><strong>Saved level:</strong> ${fmt(x.level)} · <strong>Known max:</strong> ${fmt(x.knownMax)}</p><p class="muted">Base max ${fmt(x.baseMax)}${x.perLevel!=='Filler'?` · catalog value per level ${esc(x.perLevel)}`:''}.</p>`;panel.classList.remove('detail-dismissed');panel.querySelector('.eq-close').onclick=()=>panel.classList.add('detail-dismissed');}paint();}
  const api={decode,render,UNLOCK_REWARDS,ADDITIVE,MULTI};if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.Equinox=api;
})(typeof window!=='undefined'?window:globalThis);
