(function(root){'use strict';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),pretty=v=>String(v??'').replaceAll('_',' '),n=v=>Number.isFinite(Number(v))?Number(v):0,fmt=v=>v==null||!Number.isFinite(Number(v))?'Unavailable':Intl.NumberFormat('en',{notation:Math.abs(Number(v))>=1e15?'scientific':'compact',maximumFractionDigits:2}).format(Number(v));
const titles={ranks:'Land Rank & Database',thresholds:'Crop Thresholds',weekly:'Weekly Exotic',plots:'Plot Overview',scientist:'Crop Scientist',beans:'Bean Trade'};
const cache=new WeakMap();
function load(raw){if(cache.has(raw))return cache.get(raw);const promise=new Promise((resolve,reject)=>{const worker=new Worker('farming-extras-worker.js');const timer=setTimeout(()=>{worker.terminate();reject(Error('Farming calculation timed out.'));},90000);worker.onmessage=e=>{clearTimeout(timer);worker.terminate();e.data.error?reject(Error(e.data.error)):resolve(e.data.result);};worker.onerror=()=>{clearTimeout(timer);worker.terminate();reject(Error('Farming calculator could not load.'));};worker.postMessage(raw);});cache.set(raw,promise);promise.catch(()=>cache.delete(raw));return promise;}
const img=id=>`<img src="assets/FarmCrop${id}.png" alt="Crop ${Number(id)+1}" loading="lazy">`;
const card=(name,value,detail='')=>`<article class="farm-extra-card"><h4>${esc(name)}</h4><strong>${esc(value)}</strong>${detail?`<p>${esc(detail)}</p>`:''}</article>`;
const stats=entries=>`<div class="farm-extra-stats">${entries.map(([a,b])=>card(a,b)).join('')}</div>`;
function renderView(key,result,model,threshold=200,reserve=0,query=''){
 const f=result.farming,crops=model.crops.filter(x=>x.found),formatBonus=(s,v)=>pretty(s).replaceAll('{',fmt(v)).replaceAll('}',fmt(1+n(v)/100));
 if(key==='ranks')return stats([['Total ranks',fmt(f.totalRanks)],['Available points',fmt(f.availablePoints)],['Spent points',fmt(f.usedPoints)],['5th-column cap',fmt(f.fifthColumnMaxLevel)]])+`<h4>Plot ranks</h4><div class="farm-extra-grid">${f.plot.map(p=>card('Plot '+(p.index+1),p.isLocked?'Locked':'Rank '+fmt(p.rank),p.isLocked?'':`${fmt(p.rankProgress)} / ${fmt(p.rankRequirement)} rank EXP`)).join('')}</div><h4>Land Rank Database</h4><div class="farm-extra-grid">${f.ranks.map(r=>card(pretty(r.name),'Lv '+fmt(r.upgradeLevel??0)+(r.maxLevel!=null?' / '+fmt(r.maxLevel):''),`${formatBonus(r.description,r.bonus)} · Unlock: ${fmt(r.unlockAt)} total ranks${n(f.totalRanks)<n(r.unlockAt)?' (locked)':''}`)).join('')}</div><p class="farm-extra-note">Bonuses include decoded account multipliers. Only fifth-column upgrades have a finite level cap.</p>`;
 if(key==='thresholds'){const missing=crops.filter(c=>c.quantity<threshold&&(!query||String(c.id+1).includes(query))).sort((a,b)=>(threshold-a.quantity)-(threshold-b.quantity));return `<div class="exotic-controls"><label>GMO stock target <select data-farm-threshold>${[200,1000,2500,10000,100000].map(v=>`<option value="${v}" ${v===threshold?'selected':''}>${v.toLocaleString('en')}</option>`).join('')}</select></label><input data-farm-query type="search" placeholder="Find crop number…" aria-label="Find crop number" value="${esc(query)}"></div>`+stats([['Qualifying discovered crops',crops.filter(c=>c.quantity>=threshold).length+' / '+crops.length],['Below target',crops.filter(c=>c.quantity<threshold).length],['Target per crop',fmt(threshold)]])+`<p class="farm-extra-note">Discovered crops only, sorted by the smallest stock deficit. Zero-stock discoveries are retained.</p><div class="farm-extra-grid">${missing.map(c=>`<article class="farm-extra-card farm-crop-card">${img(c.id)}<div><h4>Crop #${c.id+1}</h4><strong>${fmt(threshold-c.quantity)} needed</strong><p>${fmt(c.quantity)} / ${fmt(threshold)} in stock</p></div></article>`).join('')||'<p>All matching discovered crops meet this target.</p>'}</div>`;}
 if(key==='plots')return stats([['Plots',f.plot.length],['Unlocked',f.plot.filter(p=>!p.isLocked).length],['Instagrows',fmt(f.instaGrow)]])+`<p class="farm-extra-note">Snapshot from the loaded save. Growth times are estimates from saved conditions, not live timers.</p><div class="farm-extra-grid">${f.plot.map(p=>`<article class="farm-extra-card"><h4>Plot ${p.index+1} · ${p.isLocked?'Locked':p.seedType<0?'Empty':pretty(p.seed?.name)+' seed'}</h4>${!p.isLocked&&p.seedType>=0?`${img(p.cropType)}<strong>Crop #${p.cropType+1}</strong><p>On vine: ${fmt(p.cropQuantity)} · Overgrowth: ${fmt(p.currentOG)}<br>Rank ${fmt(p.rank)} · Growth ${fmt(p.progress)} / ${fmt(p.growthReq)}<br>Estimated growth remaining: ${p.timeLeft==null?'Unavailable':fmt(Math.max(0,p.timeLeft)/3600)+' hours'}</p>`:''}</article>`).join('')}</div>`;
 if(key==='weekly'){if(!result.rotations?.length)return '<p>The save has no usable global timestamp. Weekly offers cannot be determined.</p>';return stats([['Weekly purchase allowance',fmt(f.exoticMarkeMaxPurchases)],['Purchases used',fmt(f.exoticMarketUpgradesPurchased)],['Purchases left',f.exoticMarketUpgradesPurchased==null?'Unavailable':fmt(Math.max(0,f.exoticMarkeMaxPurchases-f.exoticMarketUpgradesPurchased))]])+`<p class="farm-extra-note">Rotation at the save timestamp (${result.savedTime?esc(new Date(result.savedTime*1000).toISOString().slice(0,10)):'unknown'}), not necessarily today. Import a fresh save before spending.</p>`+result.rotations.map(rotation=>`<h4>${rotation.weekOffset?'Following week':'Saved week'} · ${esc(new Date(rotation.date).toISOString().slice(0,10))} UTC</h4><div class="farm-extra-grid">${rotation.upgradeIndices.map(id=>{const x=model.exotic.find(x=>x.id===id);if(!x)return '';return `<article class="farm-extra-card farm-crop-card">${img(x.cropId)}<div><h4>${esc(x.name)}</h4><strong>Lv ${fmt(x.level)}</strong><p>${esc(x.description)}</p><p>Crop #${x.cropId+1}: ${fmt(x.cropQuantity)} saved<br>${x.capped?fmt(100*x.level/(1000+x.level))+'% of ceiling · '+fmt(Math.max(0,9000-x.level))+' levels to 90%':'Linear bonus — no soft cap'}</p></div></article>`;}).join('')}</div>`).join('');}
 if(key==='scientist')return stats([['Discovered crops',fmt(f.cropsFound)],['Scientist Exotic bonus',fmt(model.exotic.find(x=>x.id===40)?.value)+'%']])+`<p class="farm-extra-note">Current account bonuses from the decoded Crop Scientist calculation. Zero means the bonus is inactive or its requirement is unmet. Multipliers include Lab, its jewel, Grimoire, Exotic Market and Upgrade Vault; Jade Emporium unlocks determine which bonuses apply.</p><div class="farm-extra-grid">${Object.entries(f.cropDepot||{}).map(([key,v])=>card(pretty(v.name),['gamingEvo','cookingSpeed'].includes(key)?fmt(v.value)+'×':'+'+fmt(v.value)+'%')).join('')}</div>`;
 if(key==='beans'){const weight=c=>{const seed=model.seeds.find(s=>c.id>=s.start&&c.id<=s.end);return Math.pow(2.5,seed?.id||0)*Math.pow(1.08,c.id-(seed?.start||0));},all=crops.reduce((s,c)=>s+c.quantity*weight(c),0),trade=crops.reduce((s,c)=>s+Math.max(0,c.quantity-reserve)*weight(c),0),estimate=all>0?n(f.stats?.magicBean?.totalValue)*Math.sqrt(trade/all):0;return `<div class="exotic-controls"><label>Keep this stock of each crop <select data-farm-reserve>${[0,200,1000,2500,10000,100000].map(v=>`<option value="${v}" ${v===reserve?'selected':''}>${v===0?'Trade all':v.toLocaleString('en')}</option>`).join('')}</select></label></div>`+stats([['Estimated beans',fmt(estimate)],['Current Magic Beans',fmt(f.crop.beans)],['Crop units traded',fmt(crops.reduce((s,c)=>s+Math.max(0,c.quantity-reserve),0))]])+`<p class="farm-extra-note">Planning estimate using the loaded account multipliers. Keeping stock is a hypothetical selective-trade scenario; check the in-game trade controls before acting. This preview does not spend crops.</p><h4>GMO thresholds lost after this trade</h4><div class="farm-extra-grid">${[200,1000,2500,10000,100000].map(t=>card(fmt(t)+' stock threshold',crops.filter(c=>c.quantity>=t&&Math.min(c.quantity,reserve)<t).length+' crops lose eligibility')).join('')}</div><h4>Bean calculation sources</h4><div class="farm-extra-grid">${(f.stats?.magicBean?.categories||[]).flatMap(g=>g.sources||[]).map(s=>card(s.name,fmt(s.value)+(s.name==='Crop Value'?'':'×'))).join('')}</div><p class="farm-extra-note">Some sources share additive pools; the displayed source factors should not be multiplied together independently.</p>`;}
 return '';
}
async function render(host,key,raw,model){host.innerHTML='<p class="collection-note">Calculating Farming account bonuses…</p>';try{const result=await load(raw);if(!host.isConnected)return;let threshold=200,reserve=0,query='';const paint=()=>{host.innerHTML=`<section class="farm-extra-board"><header><p class="eyebrow">FARMING</p><h3>${esc(titles[key])}</h3></header>${renderView(key,result,model,threshold,reserve,query)}</section>`;host.querySelector('[data-farm-threshold]')?.addEventListener('change',e=>{threshold=Number(e.target.value);paint();});host.querySelector('[data-farm-reserve]')?.addEventListener('change',e=>{reserve=Number(e.target.value);paint();});host.querySelector('[data-farm-query]')?.addEventListener('input',e=>{query=e.target.value;paint();const input=host.querySelector('[data-farm-query]');input.focus();});};paint();}catch(error){if(host.isConnected)host.innerHTML=`<p class="collection-note">${esc(error.message)}</p>`;}}
root.FarmingExtras={render,renderView};
})(window);
