// Extracted from the local game client HoleFountUPG and HolesInfo[76], 2026-09-24.
(function(root){'use strict';const data=[
  {
    "water": 0,
    "index": 0,
    "name": "Yellow Water",
    "prerequisite": 6,
    "currency": 2,
    "baseCost": 100000,
    "costMultiplier": 1.1,
    "bonusPerLevel": 1,
    "description": "Unlock Yellow Water. Tap the Change Water button to toggle which water the Fountain is using. Also, }x Currency Value",
    "marbleEligible": true
  },
  {
    "water": 0,
    "index": 1,
    "name": "Currency Booster I",
    "prerequisite": 4,
    "currency": 2,
    "baseCost": 1500,
    "costMultiplier": 1.2,
    "bonusPerLevel": 10,
    "description": "All currencies are worth +{% more. @ Currencies are ALL money types here at the Fountain, from coins to dollars and more!",
    "marbleEligible": true
  },
  {
    "water": 0,
    "index": 2,
    "name": "Penny Lane",
    "prerequisite": 9,
    "currency": 0,
    "baseCost": 1,
    "costMultiplier": 1.06,
    "bonusPerLevel": 1,
    "description": "Increases the value of Bronze Coins. @ All bronze coins you find have a base value of $ @   @ Your total Currency multi: @ ^ @ (Affects value of all Fountain money)",
    "marbleEligible": true
  },
  {
    "water": 0,
    "index": 3,
    "name": "Nickel and Diming",
    "prerequisite": 12,
    "currency": 1,
    "baseCost": 1,
    "costMultiplier": 1.12,
    "bonusPerLevel": 1,
    "description": "You can now find Silver Coins. @ All silver coins you find have a base value of $",
    "marbleEligible": true
  },
  {
    "water": 0,
    "index": 4,
    "name": "Dubloon Desires",
    "prerequisite": 8,
    "currency": 2,
    "baseCost": 1,
    "costMultiplier": 1.13,
    "bonusPerLevel": 1,
    "description": "You can now find Golden Coins. @ All golden coins you find have a base value of $",
    "marbleEligible": true
  },
  {
    "water": 0,
    "index": 5,
    "name": "Stackin' Silver",
    "prerequisite": 3,
    "currency": 0,
    "baseCost": 10,
    "costMultiplier": 1.1,
    "bonusPerLevel": 5,
    "description": "Silver coins are worth }x more.",
    "marbleEligible": true
  },
  {
    "water": 0,
    "index": 6,
    "name": "Stackin' Gold",
    "prerequisite": 19,
    "currency": 1,
    "baseCost": 15,
    "costMultiplier": 1.1,
    "bonusPerLevel": 5,
    "description": "Golden coins are worth }x more.",
    "marbleEligible": true
  },
  {
    "water": 0,
    "index": 7,
    "name": "Stackin' Dollars",
    "prerequisite": 6,
    "currency": 2,
    "baseCost": 25,
    "costMultiplier": 1.1,
    "bonusPerLevel": 5,
    "description": "Dollar Bills are worth }x more.",
    "marbleEligible": true
  },
  {
    "water": 0,
    "index": 8,
    "name": "Money Back Guarantee",
    "prerequisite": 5,
    "currency": 1,
    "baseCost": 25,
    "costMultiplier": 1.15,
    "bonusPerLevel": 1,
    "description": "Currency generated while at maximum capacity aren't wasted, and instead auto collected at $% of their value.",
    "marbleEligible": false
  },
  {
    "water": 0,
    "index": 9,
    "name": "Fountain Filling",
    "prerequisite": -1,
    "currency": 0,
    "baseCost": 1,
    "costMultiplier": 1.1,
    "bonusPerLevel": 2,
    "description": "Every time the fountain fills up, it creates a new coin. @ This will happen in $ @   @ From empty, it takes: @ # to fill",
    "marbleEligible": true
  },
  {
    "water": 0,
    "index": 10,
    "name": "Extra Space",
    "prerequisite": 2,
    "currency": 0,
    "baseCost": 5,
    "costMultiplier": 20,
    "bonusPerLevel": 1,
    "description": "Coins can appear in $ different areas on the ground. @ This means your current max coin capacity is # coins",
    "marbleEligible": false
  },
  {
    "water": 0,
    "index": 11,
    "name": "Taller Stacks",
    "prerequisite": 3,
    "currency": 1,
    "baseCost": 25,
    "costMultiplier": 4,
    "bonusPerLevel": 1,
    "description": "Each area can stack up to $ coins, this upgrade increases it by +{. @ This means your current max coin capacity is # coins",
    "marbleEligible": false
  },
  {
    "water": 0,
    "index": 12,
    "name": "Water Bender",
    "prerequisite": 2,
    "currency": 0,
    "baseCost": 10,
    "costMultiplier": 1.3,
    "bonusPerLevel": 10,
    "description": "The fountain fills up $x faster while you are actively standing in this cavern specifically. @ ",
    "marbleEligible": true
  },
  {
    "water": 0,
    "index": 13,
    "name": "Monumental Boost",
    "prerequisite": 18,
    "currency": 2,
    "baseCost": 250,
    "costMultiplier": 2.5,
    "bonusPerLevel": 1,
    "description": "All Bravery Monument bonuses are }x larger.",
    "marbleEligible": true
  },
  {
    "water": 0,
    "index": 14,
    "name": "Cosmological Boost",
    "prerequisite": 9,
    "currency": 0,
    "baseCost": 5,
    "costMultiplier": 1.15,
    "bonusPerLevel": 1,
    "description": "Cosmo the Villager gains }x more EXP than normal.",
    "marbleEligible": true
  },
  {
    "water": 0,
    "index": 15,
    "name": "Golden Bucket Boost",
    "prerequisite": 16,
    "currency": 1,
    "baseCost": 25,
    "costMultiplier": 1.1,
    "bonusPerLevel": 5,
    "description": "Your 1st bucket at The Well cavern is golden. Golden buckets have }x fill rate.",
    "marbleEligible": true
  },
  {
    "water": 0,
    "index": 16,
    "name": "Class EXP Boost",
    "prerequisite": 14,
    "currency": 0,
    "baseCost": 50,
    "costMultiplier": 1.12,
    "bonusPerLevel": 1,
    "description": "Boosts Class EXP gain by }x",
    "marbleEligible": true
  },
  {
    "water": 0,
    "index": 17,
    "name": "Treasure Boost",
    "prerequisite": 15,
    "currency": 1,
    "baseCost": 100,
    "costMultiplier": 1.2,
    "bonusPerLevel": 3,
    "description": "All Sailing Chests you open contain }x more Treasure to upgrade your Boats with!",
    "marbleEligible": true
  },
  {
    "water": 0,
    "index": 18,
    "name": "Orion Boost",
    "prerequisite": 17,
    "currency": 2,
    "baseCost": 150,
    "costMultiplier": 1.12,
    "bonusPerLevel": 5,
    "description": "Permanently boost Feather Generation rate at Orion the Horned Owl by }x",
    "marbleEligible": true
  },
  {
    "water": 0,
    "index": 19,
    "name": "Mythril Transience",
    "prerequisite": 4,
    "currency": 2,
    "baseCost": 800,
    "costMultiplier": 1.2,
    "bonusPerLevel": 1,
    "description": "Bronze, silver, and gold coins are worth +{% more per POW 10 Mythril you have, over at The Well cavern. @ Total Bonus:$x",
    "marbleEligible": true
  },
  {
    "water": 1,
    "index": 0,
    "name": "Green Water",
    "prerequisite": 1,
    "currency": 5,
    "baseCost": 1000000,
    "costMultiplier": 1.1,
    "bonusPerLevel": 2,
    "description": "Unlock Green Water. Also, }x Currency Value.",
    "marbleEligible": true
  },
  {
    "water": 1,
    "index": 1,
    "name": "Currency Booster II",
    "prerequisite": 4,
    "currency": 5,
    "baseCost": 10000,
    "costMultiplier": 1.2,
    "bonusPerLevel": 20,
    "description": "All currencies are worth +{% more.",
    "marbleEligible": true
  },
  {
    "water": 1,
    "index": 2,
    "name": "Dolla Dolla Bills",
    "prerequisite": 10,
    "currency": 3,
    "baseCost": 1,
    "costMultiplier": 1.13,
    "bonusPerLevel": 1,
    "description": "You can now find Dollar Bills. @ All dollar bills you find have a base value of $",
    "marbleEligible": true
  },
  {
    "water": 1,
    "index": 3,
    "name": "Credit Swisse",
    "prerequisite": 12,
    "currency": 4,
    "baseCost": 1,
    "costMultiplier": 1.14,
    "bonusPerLevel": 1,
    "description": "You can now find Credit Bills. @ All credit bills you find have a base value of $",
    "marbleEligible": true
  },
  {
    "water": 1,
    "index": 4,
    "name": "In Gov We Trust",
    "prerequisite": 9,
    "currency": 5,
    "baseCost": 1,
    "costMultiplier": 1.15,
    "bonusPerLevel": 1,
    "description": "You can now find Treasury Bills. @ All treasury bills you find have a base value of $",
    "marbleEligible": true
  },
  {
    "water": 1,
    "index": 5,
    "name": "Stackin' Creds",
    "prerequisite": 3,
    "currency": 3,
    "baseCost": 50,
    "costMultiplier": 1.1,
    "bonusPerLevel": 5,
    "description": "Credit bills are worth }x more.",
    "marbleEligible": true
  },
  {
    "water": 1,
    "index": 6,
    "name": "Stackin' T-Bills",
    "prerequisite": 4,
    "currency": 4,
    "baseCost": 100,
    "costMultiplier": 1.1,
    "bonusPerLevel": 5,
    "description": "Treasury bills are worth }x more.",
    "marbleEligible": true
  },
  {
    "water": 1,
    "index": 7,
    "name": "Stackin' Monayy",
    "prerequisite": 0,
    "currency": 5,
    "baseCost": 250,
    "costMultiplier": 1.1,
    "bonusPerLevel": 1,
    "description": "Moolah Stacks are worth }x more.",
    "marbleEligible": true
  },
  {
    "water": 1,
    "index": 8,
    "name": "Royal Stacks",
    "prerequisite": 5,
    "currency": 3,
    "baseCost": 100,
    "costMultiplier": 1.15,
    "bonusPerLevel": 1,
    "description": "There's a 1 in $ chance for a currency stack to become 'royal' when the fountain fills. @ All coins in a royal stack are worth more.",
    "marbleEligible": false
  },
  {
    "water": 1,
    "index": 9,
    "name": "Regal Riches",
    "prerequisite": 8,
    "currency": 4,
    "baseCost": 250,
    "costMultiplier": 1.25,
    "bonusPerLevel": 10,
    "description": "Royal stacks are worth $x more, to be specific.",
    "marbleEligible": true
  },
  {
    "water": 1,
    "index": 10,
    "name": "Marble Filling",
    "prerequisite": -1,
    "currency": 2,
    "baseCost": 50000,
    "costMultiplier": 1.1,
    "bonusPerLevel": 5,
    "description": "Adds a new fountain bar, which when filled creates $ marble. @ Spend these on upgrades to multiply their bonuses via Marbleization.",
    "marbleEligible": false
  },
  {
    "water": 1,
    "index": 11,
    "name": "Greatest Desire",
    "prerequisite": 9,
    "currency": 4,
    "baseCost": 500,
    "costMultiplier": 1.15,
    "bonusPerLevel": 5,
    "description": "You can now click and HOLD on a currency at the top of the screen to DESIRE it, making them worth }x more when collected.",
    "marbleEligible": true
  },
  {
    "water": 1,
    "index": 12,
    "name": "Turn and Push",
    "prerequisite": 2,
    "currency": 3,
    "baseCost": 250,
    "costMultiplier": 1.15,
    "bonusPerLevel": 10,
    "description": "You can now click a currency at the top to IGNORE it, so it's never created. Click again to undo this at any time. @ Also, +{% all currency",
    "marbleEligible": true
  },
  {
    "water": 1,
    "index": 13,
    "name": "Judicial Boost",
    "prerequisite": 18,
    "currency": 5,
    "baseCost": 5000,
    "costMultiplier": 2.5,
    "bonusPerLevel": 1,
    "description": "All Justice Monument bonuses are }x larger.",
    "marbleEligible": true
  },
  {
    "water": 1,
    "index": 14,
    "name": "Skim Reading",
    "prerequisite": 10,
    "currency": 3,
    "baseCost": 25,
    "costMultiplier": 1.2,
    "bonusPerLevel": 3,
    "description": "Boost the Study Rate for Bolaia the Villager by }x",
    "marbleEligible": true
  },
  {
    "water": 1,
    "index": 15,
    "name": "Fine Tuning",
    "prerequisite": 16,
    "currency": 4,
    "baseCost": 250,
    "costMultiplier": 1.15,
    "bonusPerLevel": 2,
    "description": "All your Harp Strings gain }x more exp than normal",
    "marbleEligible": true
  },
  {
    "water": 1,
    "index": 16,
    "name": "Swingy O' Sword",
    "prerequisite": 14,
    "currency": 3,
    "baseCost": 100,
    "costMultiplier": 1.13,
    "bonusPerLevel": 1,
    "description": "Boosts Damage for all characters by }x",
    "marbleEligible": true
  },
  {
    "water": 1,
    "index": 17,
    "name": "Summoneer",
    "prerequisite": 15,
    "currency": 4,
    "baseCost": 500,
    "costMultiplier": 1.15,
    "bonusPerLevel": 3,
    "description": "All Summoning Essence generation is }x greater than before",
    "marbleEligible": true
  },
  {
    "water": 1,
    "index": 18,
    "name": "Better Poppy",
    "prerequisite": 17,
    "currency": 5,
    "baseCost": 1500,
    "costMultiplier": 1.1,
    "bonusPerLevel": 5,
    "description": "Permanently boost Fish Generation rate at Poppy the Kangaroo Mouse by }x",
    "marbleEligible": true
  },
  {
    "water": 1,
    "index": 19,
    "name": "Sharp Surrogate",
    "prerequisite": 6,
    "currency": 5,
    "baseCost": 10000,
    "costMultiplier": 1.2,
    "bonusPerLevel": 1,
    "description": "Dollar, Credit, and Treasury bills are worth +{% more per POW 10 Sharp Notes you have, over at The Harp cavern. @ Total Bonus:$x",
    "marbleEligible": true
  },
  {
    "water": 2,
    "index": 0,
    "name": "Red Water",
    "prerequisite": 6,
    "currency": 8,
    "baseCost": 1000000000,
    "costMultiplier": 1.5,
    "bonusPerLevel": 3,
    "description": "Unlock Red Water... well, it will in the future. Also, }x Currency Value, at least THAT'S here in the present!",
    "marbleEligible": true
  },
  {
    "water": 2,
    "index": 1,
    "name": "Currency Booster III",
    "prerequisite": 5,
    "currency": 6,
    "baseCost": 10000000,
    "costMultiplier": 1.7,
    "bonusPerLevel": 30,
    "description": "All currencies are worth +{% more.",
    "marbleEligible": true
  },
  {
    "water": 2,
    "index": 2,
    "name": "Moolahleluja",
    "prerequisite": 12,
    "currency": 6,
    "baseCost": 5000,
    "costMultiplier": 1.4,
    "bonusPerLevel": 1,
    "description": "You can now find Moolah Stacks. @ All moolah stacks you find have a base value of $, but only get 鉢(Total Currency Multi) which is: @ ^",
    "marbleEligible": true
  },
  {
    "water": 2,
    "index": 3,
    "name": "Shillin Grillin",
    "prerequisite": 8,
    "currency": 7,
    "baseCost": 20000,
    "costMultiplier": 1.6,
    "bonusPerLevel": 1,
    "description": "You can now find Shilling Stacks. @ All shilling stacks you find have a base value of $, but only get 鉢(Total Currency Multi) which is: @ ^",
    "marbleEligible": true
  },
  {
    "water": 2,
    "index": 4,
    "name": "Rob Greane",
    "prerequisite": 1,
    "currency": 8,
    "baseCost": 100000,
    "costMultiplier": 1.8,
    "bonusPerLevel": 1,
    "description": "You can now find Greane Stacks. @ All greane stacks you find have a base value of $, but only get 鉢(Total Currency Multi) which is: @ ^",
    "marbleEligible": true
  },
  {
    "water": 2,
    "index": 5,
    "name": "Stackin' Shillin",
    "prerequisite": 3,
    "currency": 6,
    "baseCost": 50000,
    "costMultiplier": 1.3,
    "bonusPerLevel": 1,
    "description": "Shilling Stacks are worth }x more.",
    "marbleEligible": true
  },
  {
    "water": 2,
    "index": 6,
    "name": "Stackin' Gbacks",
    "prerequisite": 4,
    "currency": 7,
    "baseCost": 200000,
    "costMultiplier": 1.5,
    "bonusPerLevel": 1,
    "description": "Greane Stacks are worth }x more.",
    "marbleEligible": true
  },
  {
    "water": 2,
    "index": 7,
    "name": "Stackin' Funds",
    "prerequisite": 19,
    "currency": 8,
    "baseCost": 1000000,
    "costMultiplier": 1.7,
    "bonusPerLevel": 1,
    "description": "Oldmoney Stacks are worth }x more.",
    "marbleEligible": true
  },
  {
    "water": 2,
    "index": 8,
    "name": "Luck fo' REAL",
    "prerequisite": 2,
    "currency": 6,
    "baseCost": 10000,
    "costMultiplier": 1.5,
    "bonusPerLevel": 1,
    "description": "All currencies collected have a 1 in $ of being LUCKY, multiplying the value of that currency type forever! @ Each additional one is 4x rarer",
    "marbleEligible": true
  },
  {
    "water": 2,
    "index": 9,
    "name": "Skilluck",
    "prerequisite": 11,
    "currency": 8,
    "baseCost": 350000,
    "costMultiplier": 1.9,
    "bonusPerLevel": 1,
    "description": "Boosts bonus of each LUCKY coin to +$%. @ Also, you can see how many LUCKY coins of each type you have from the number of dots above them.",
    "marbleEligible": true
  },
  {
    "water": 2,
    "index": 10,
    "name": "Lucky Ducky",
    "prerequisite": 11,
    "currency": 8,
    "baseCost": 100000,
    "costMultiplier": 1.7,
    "bonusPerLevel": 1,
    "description": "Boost Rubber Ducky chance and LUCKY coin chance by +{%",
    "marbleEligible": true
  },
  {
    "water": 2,
    "index": 11,
    "name": "Ducktactular",
    "prerequisite": 8,
    "currency": 7,
    "baseCost": 10000,
    "costMultiplier": 1.5,
    "bonusPerLevel": 1,
    "description": "Your Rubber Duckies each boost the value of all coins you find by }x. @ Total Ducky Bonus: $x",
    "marbleEligible": true
  },
  {
    "water": 2,
    "index": 12,
    "name": "Rubber Ducky",
    "prerequisite": -1,
    "currency": 5,
    "baseCost": 10000000,
    "costMultiplier": 10,
    "bonusPerLevel": 5,
    "description": "Adds a new fountain bar, which when filled has a 1 in $ chance of giving +1 Rubber Ducky stack.",
    "marbleEligible": true
  },
  {
    "water": 2,
    "index": 13,
    "name": "Wisdom Boost",
    "prerequisite": 18,
    "currency": 7,
    "baseCost": 10000,
    "costMultiplier": 50,
    "bonusPerLevel": 1,
    "description": "All Wisdom Monument bonuses are }x larger.",
    "marbleEligible": true
  },
  {
    "water": 2,
    "index": 14,
    "name": "Minaus Costs",
    "prerequisite": 12,
    "currency": 6,
    "baseCost": 15000,
    "costMultiplier": 8.5,
    "bonusPerLevel": 1,
    "description": "Minau the Villager's upgrades all are }x cheaper than before",
    "marbleEligible": true
  },
  {
    "water": 2,
    "index": 15,
    "name": "Enchanterest",
    "prerequisite": 17,
    "currency": 7,
    "baseCost": 25000,
    "costMultiplier": 4,
    "bonusPerLevel": 1,
    "description": "Your Enchant chance over at The Jar cavern is }x larger than before",
    "marbleEligible": true
  },
  {
    "water": 2,
    "index": 16,
    "name": "Pen N Paper",
    "prerequisite": 14,
    "currency": 6,
    "baseCost": 50000,
    "costMultiplier": 20,
    "bonusPerLevel": 1,
    "description": "Boosts Research EXP gain by }x",
    "marbleEligible": true
  },
  {
    "water": 2,
    "index": 17,
    "name": "Cook Maxxing",
    "prerequisite": 16,
    "currency": 8,
    "baseCost": 100000,
    "costMultiplier": 6.2,
    "bonusPerLevel": 1,
    "description": "Boosts Cooking Mastery EXP gain by }x. Note that Cooking Mastery is unlocked at Rift 61.",
    "marbleEligible": true
  },
  {
    "water": 2,
    "index": 18,
    "name": "Bubba Forever",
    "prerequisite": 15,
    "currency": 7,
    "baseCost": 250000,
    "costMultiplier": 5.4,
    "bonusPerLevel": 2,
    "description": "Permanently boost Meat Slice Production rate at Bubba the Seal by }x",
    "marbleEligible": true
  },
  {
    "water": 2,
    "index": 19,
    "name": "Rupie Monie",
    "prerequisite": 1,
    "currency": 7,
    "baseCost": 1000000,
    "costMultiplier": 2.5,
    "bonusPerLevel": 1,
    "description": "Moolah, Shilling, and Greane stacks are worth +{% more per POW 10 basic Red Rupie you have, over at The Jar cavern.",
    "marbleEligible": true
  }
];if(typeof module!=='undefined'&&module.exports)module.exports=data;else root.FountainData=data;})(typeof window!=='undefined'?window:globalThis);
