(function(root){'use strict';
const parse=v=>{if(typeof v==='string'){try{return JSON.parse(v);}catch{return v;}}return v;},num=v=>Number.isFinite(Number(v))?Number(v):0,esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),label=v=>String(v||'').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase()),fmt=v=>num(v).toLocaleString(undefined,{maximumFractionDigits:2});
function model(data,c=root.GALLERY_CATALOG){const s=parse(data.Spelunk)||[],slots=Array.isArray(s[16])?s[16]:[],grades=Array.isArray(s[17])?s[17]:[];const trophies=c.trophies.map(x=>({...x,count:slots.filter(v=>num(v)===x.id).length,owned:slots.some(v=>num(v)===x.id)}));const nametags=c.nametags.map(x=>({...x,grade:num(grades[x.id]),owned:num(grades[x.id])>0}));return{available:Array.isArray(s)&&s.length>17,slots,trophies,nametags,equipped:slots.filter(v=>num(v)>0).length,ownedTrophies:trophies.filter(x=>x.owned).length,ownedNametags:nametags.filter(x=>x.owned).length};}
const bonusHtml=x=>x.bonuses.length?x.bonuses.map(b=>`<span>+${fmt(b.value)}% ${esc(label(b.name))}</span>`).join(''):'<span>Cosmetic reward</span>';
const tagArt=id=>`<div class="nametag-art"><img src="assets/NametagLeft_${id}.png" alt=""><img src="assets/NametagMiddle_${id}.png" alt=""><img src="assets/NametagRight_${id}.png" alt=""></div>`;
let active='gallery';
function render(host,data,c=root.GALLERY_CATALOG){const m=model(data,c);function paint(){let body='';if(active==='gallery'){body=`<section class="gallery-room"><header><span>TROPHY GALLERY</span><strong>${m.equipped} displayed</strong></header><div class="pedestal-grid">${m.slots.map((id,i)=>{const x=m.trophies.find(t=>t.id===num(id));return`<article class="pedestal ${x?'filled':'locked'}">${x?`<img src="assets/Trophy${x.id}disp.png" onerror="this.src='assets/Trophy${x.id}.png'" alt=""><b>${esc(x.name)}</b>`:`<i>${i+1}</i><b>Empty display</b>`}<small>Gallery slot ${i+1}</small></article>`;}).join('')||'<p class="gallery-empty">No trophy slots were found.</p>'}</div></section><h3 class="gallery-heading">Owned Nametags</h3><div class="nametag-list">${m.nametags.filter(x=>x.owned).map(tagCard).join('')||'<p class="gallery-empty">No nametag grades were found.</p>'}</div>`;}else if(active==='trophies'){body=`<div class="trophy-catalog">${m.trophies.map(x=>`<button class="trophy-card ${x.owned?'owned':'locked'}" data-gallery-kind="trophy" data-id="${x.id}"><img src="assets/Trophy${x.id}.png" alt=""><span>${x.owned?`${x.count} displayed`:'Not displayed'}</span><strong>${esc(x.name)}</strong><div>${bonusHtml(x)}</div></button>`).join('')}</div>`;}else if(active==='nametags'){body=`<div class="nametag-list">${m.nametags.map(tagCard).join('')}</div>`;}else{const rows=new Map();m.trophies.filter(x=>x.count).forEach(x=>x.bonuses.forEach(b=>rows.set(b.name,(rows.get(b.name)||0)+b.value*x.count)));m.nametags.filter(x=>x.owned).forEach(x=>x.bonuses.forEach(b=>rows.set(b.name,(rows.get(b.name)||0)+b.value)));body=`<section class="gallery-totals"><h3>Saved Gallery Bonuses</h3><p>Trophies are counted once per displayed copy. Nametags are counted once; final in-game scaling may include Gallery multipliers.</p><div>${[...rows].sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<article><span>${esc(label(k))}</span><strong>+${fmt(v)}%</strong></article>`).join('')||'<p>No active bonuses found.</p>'}</div></section>`;}
host.innerHTML=`<div class="gallery-hero"><img src="assets/Trophy25.png" alt=""><div><p class="eyebrow">World 7 · Gallery</p><h2>Nametags &amp; Trophies</h2><p>Your displayed trophies, nametag grades, collection progress, and every Gallery bonus.</p></div><strong>${m.ownedTrophies}/${m.trophies.length} trophies · ${m.ownedNametags}/${m.nametags.length} nametags</strong></div>${!m.available?'<p class="collection-note">Gallery save data was not found. The complete in-game catalog is still shown.</p>':''}<nav class="skill-tabs">${[['gallery','Gallery'],['trophies','Trophies'],['nametags','Nametags'],['bonuses','Bonuses']].map(([id,n])=>`<button class="skill-tab${active===id?' active':''}" data-gallery-tab="${id}">${n}</button>`).join('')}</nav>${body}<section id="galleryDetail" class="exp-card w5-detail detail-dismissed"></section>`;
host.querySelectorAll('[data-gallery-tab]').forEach(b=>b.onclick=()=>{active=b.dataset.galleryTab;paint();});host.querySelectorAll('[data-gallery-kind]').forEach(b=>b.onclick=()=>detail(b.dataset.galleryKind,b.dataset.id));function detail(kind,id){const x=(kind==='trophy'?m.trophies:m.nametags).find(v=>v.id===num(id));if(!x)return;const p=host.querySelector('#galleryDetail');p.innerHTML=`<button class="secondary gallery-close">Close</button><h3>${esc(x.name)}</h3><p>${kind==='trophy'?(x.owned?`${x.count} copy/copies displayed.`:'Not displayed.'):(x.owned?`Owned · Grade ${x.grade}`:'Not owned.')}</p><div class="gallery-detail-bonuses">${bonusHtml(x)}</div>`;p.classList.remove('detail-dismissed');p.querySelector('.gallery-close').onclick=()=>p.classList.add('detail-dismissed');}}
function tagCard(x){return`<button class="nametag-card ${x.owned?'owned':'locked'}" data-gallery-kind="nametag" data-id="${x.id}">${tagArt(x.id)}<div><span>${x.owned?`Grade ${x.grade}`:'Not owned'}</span><strong>${esc(x.name)}</strong><small>${bonusHtml(x)}</small></div></button>`;}paint();}
const api={model,render};if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.Gallery=api;})(typeof window!=='undefined'?window:globalThis);
