(function(root){'use strict';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const rows=[
 ['Golden Nomwich','Increase base damage dealt','W1','Crystal farming at Bored Beans','','17.21%','25.02%','34.22%','Food effects use the base food percentage.'],
 ['Golden Jam','Increase maximum health','W1 / W6','W6 Gold Chest','W1 Gold Chest','17.21%','25.02%','34.22%',''],
 ['Butter Bar','Increase base accuracy','W2','AFK or candy at Butterflies','','34.42','50.03','68.45','Base accuracy, not a percentage.'],
 ['Golden Meat Pie','Increase total defence','W2','Crystal farming at Sandy Pots','Crystal farming at Snelbies','17.21%','25.02%','34.22%',''],
 ['Golden Kebabs','Increase total damage to all monsters','W2 / W6','W6 Silver Chest','W2 Silver Chest','11.47%','16.68%','22.82%',''],
 ['Golden Ham','Increase Skill EXP from all skills','W3','Crystal farming at Dedotated Rams','Crystal farming at Neptuneyes','10.33%','15.01%','20.53%',''],
 ['Golden Cheese','AFK claims level shrines faster','W3','Crystal farming at Dedotated Rams','Crystal farming at Neptuneyes','11.47%','16.68%','26.9%',''],
 ['Golden Bread','Increase coins dropped by mobs','W3 / W5','Gold Chest in W5','Gold Chest in W3','17.21%','25.02%','34.22%',''],
 ['Golden Ribs','Increase Fishing Efficiency','W4','Crystal farming at Clammies','','22.95%','33.35%','45.63%',''],
 ['Golden Grilled Cheese Nomwich','Increase STR, AGI, WIS and LUK','W5','Crystal farming at Tremor Wurms','Normal Kattlekruk boss','5.74%','8.34%','11.41%','Kattlekruk is a slower alternative.'],
 ['Golden Hampter Gummy Candy','AFK claims give Sailing AFK time','W5','Crystal farming at Tremor Wurms','','13.15%','19.18%','26.24%','Boss drops are extremely limited.'],
 ['Golden Nigiri','Increase Class EXP gain','W6','Crystal farming at Minichief Spirits','Crystal farming at Lantern Spirits','22.95%','33.35%','45.63%','Lanterns only when Dark Lanterns are needed.'],
 ['Golden Dumpling','Increase all AFK Gains rate','W6','Crystal farming at Minichief Spirits','Crystal farming at Lantern Spirits','2.29%','3.34%','4.56%','Lanterns only when Dark Lanterns are needed.'],
 ['Golden Saltwater Taffy','Increase Spelunking EXP gain','W7','AFK at Coral Cave Guardian','Crystal farming at Coral Cave Guardian','0.57%','0.83%','1.14%',''],
 ['Golden Sugar Cookie','Not obtainable yet','—','Not obtainable','','—','—','—','']
].map((x,id)=>({id,name:x[0],effect:x[1],world:x[2],best:x[3],second:x[4],k10:x[5],k100:x[6],m1:x[7],notes:x[8],icon:`assets/FoodG${id+1}.png`}));
const crafted={cakes:[['Pearler Shells','W4','Arcane Cultist','Full drop-rate setup at Clammies','Clammies with candies','Use drop-rate gear instead of efficiency gear when using candies.'],['Ghosts','W2','Arcane Cultist','Full drop-rate setup at Moonmoons','Moonmoons with candies','Use drop-rate gear instead of efficiency gear when using candies.'],['Golden Hampters','W5','Royal Guardian','Crystal farming at Tremor Wurms','Tremor Wurms',''],['Golden Nomwiches','W1','Royal Guardian','Crystal farming at Bored Beans','Godshard crafting route','']],peanuts:[['Hot Dogs','W1','Beginner','Candy at Gigafrogs','Always use candies','Requires very high AFK gain rate and drop rate.'],['Copper Ore','W1','Royal Guardian','Mining sample gear at the Copper Vein','Always use candies','Use a dedicated mining sampling setup.'],['Birch Logs','W1','Voidwalker','Chopping sample gear at the Birch Tree','Always use candies','Use a dedicated chopping sampling setup.']]};
const source='<footer class="gf-source">Farming and crafting reference: <a href="https://docs.google.com/spreadsheets/d/1IcxwlHKPcw57PJxOWmtCJTP2Iv6ubdRSEwzMjbH476U/edit?gid=510141304#gid=510141304" target="_blank" rel="noopener noreferrer">Antho &amp; Arkh’s IdleOn spreadsheet</a></footer>';
function bonusTable(){return `<div class="gold-food-table"><div class="gf-head"><span>Food</span><span>Effect</span><span>World</span><span>Best farm</span><span>Second choice</span><span>10K</span><span>100K</span><span>1M</span></div>${rows.map(x=>`<article><div class="gf-food"><img src="${x.icon}" onerror="this.hidden=true" alt=""><strong>${esc(x.name)}</strong></div><span>${esc(x.effect)}</span><b>${esc(x.world)}</b><span>${esc(x.best)}</span><span>${esc(x.second||'—')}</span><em>${x.k10}</em><em>${x.k100}</em><em>${x.m1}</em>${x.notes?`<small>${esc(x.notes)}</small>`:''}</article>`).join('')}</div>`;}
function craftGroup(title,kind,data){const icon=kind==='cake'?'assets/FoodG13.png':'assets/PeanutG.png';return `<section class="gf-crafted-group"><h3><img src="${icon}" alt="">${title}</h3><div class="gf-crafted-head"><span>What to farm</span><span>World</span><span>Class</span><span>Best farming method</span><span>Second choice</span><span>Notes</span></div>${data.map(x=>`<article><div class="gf-crafted-item"><img class="gf-crafted-icon" src="${icon}" alt=""><strong>${esc(x[0])}</strong></div><b>${esc(x[1])}</b><span>${esc(x[2])}</span><span>${esc(x[3])}</span><span>${esc(x[4])}</span><small>${esc(x[5]||'—')}</small></article>`).join('')}</section>`;}
function craftedTable(){return `<div class="gf-crafted">${craftGroup('Golden Cakes','cake',crafted.cakes)}${craftGroup('Golden Peanuts','peanut',crafted.peanuts)}</div>`;}
function render(host){host.innerHTML=`<div class="section-head compact"><div><p class="eyebrow">Account · Golden Food</p><h2>Gold Food Bonuses</h2><p>Bonuses, farming routes, and the materials used to craft Golden Cakes and Golden Peanuts.</p></div></div><div class="gf-tabs"><button class="active" data-gf-tab="bonuses">Gold Food Bonuses</button><button data-gf-tab="crafted">Crafted Gold Foods</button></div><div id="gfTabBody">${bonusTable()}</div>${source}`;const body=host.querySelector('#gfTabBody');host.querySelectorAll('[data-gf-tab]').forEach(btn=>btn.addEventListener('click',()=>{host.querySelectorAll('[data-gf-tab]').forEach(x=>x.classList.toggle('active',x===btn));body.innerHTML=btn.dataset.gfTab==='crafted'?craftedTable():bonusTable();}));}
const api={rows,render};if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.GoldFood=api;
})(typeof window!=='undefined'?window:globalThis);
