(function(root){'use strict';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),pretty=v=>String(v??'').replaceAll('_',' '),fmt=v=>Number(v||0).toLocaleString('en',{maximumFractionDigits:2}),cache=new WeakMap();
function load(raw){if(cache.has(raw))return cache.get(raw);const promise=new Promise((resolve,reject)=>{const w=new Worker('killroy-worker.js'),timer=setTimeout(()=>{w.terminate();reject(Error('Killroy calculation timed out.'));},90000);w.onmessage=({data})=>{clearTimeout(timer);w.terminate();data.error?reject(Error(data.error)):resolve(data.result);};w.onerror=()=>{clearTimeout(timer);w.terminate();reject(Error('Could not load Killroy calculations.'));};w.postMessage(raw);});cache.set(raw,promise);promise.catch(()=>cache.delete(raw));return promise;}
async function render(host,raw,afterRender){const token={};host.killroyRequest=token;host.innerHTML='<p>Loading Killroy…</p>';afterRender?.();try{const d=await load(raw);if(host.killroyRequest!==token||host.dataset.page!=='killroy')return;const m=root.KillroyModel,k=d.killroy,completed=({1:1,21:2,321:3})[d.options[113]]||0,remaining=Math.max(0,k.rooms-completed);let tab='week',weeks=6;
 const settings={budget:remaining,goal:'balanced',spawn:true},shop={budget:k.skulls,target:-1,quantity:1,remainder:true,weights:{}};
 function fights(week,index){return `<article class="kr-week"><header><strong>${index===0?'Saved week':`+${index} week${index===1?'':'s'}`}</strong>${index===0?'<span>Account snapshot</span>':''}</header><div class="kr-fights">${week.classes.map((c,i)=>{const monster=week.monsters[i],best=k.list.find(x=>x.name===monster?.Name)?.killRoyKills||0;return `<div class="kr-fight ${best<100?'kr-target':''}"><img src="assets/ClassIcons${c.classIndex}.png" alt=""><div><strong>${esc(c.className)}</strong><span>${esc(pretty(monster?.Name||'Unknown monster'))}</span><small>${index===0&&i<completed?'Completed · ':''}Best ${fmt(best)} kills${best<100?' · Aim for 100':''}</small></div>${monster?`<img src="assets/Mface${monster.MonsterFace}.png" alt="">`:''}</div>`;}).join('')}</div></article>`;}
 function paint(){host.innerHTML=`<section class="kr-page"><header class="kr-hero"><img src="assets/KillsSkull.png" alt=""><div><span class="kr-kicker">WORLD 2 · WEEKLY PLANNER</span><h2>Killroy’s Slaughterhouse</h2><p>Plan your runs, spend your skulls, and see what comes next.</p></div></header><div class="kr-stats">${[['Skulls saved',k.skulls],['Runs remaining',remaining+' / '+k.rooms],['Total best kills',fmt(k.totalKills)],['Prime damage',d.prime?fmt(Math.min(3,k.totalDamageMulti))+'×':'Locked']].map(([a,b])=>`<div><span>${a}</span><strong>${b}</strong></div>`).join('')}</div><nav class="kr-tabs">${[['week','This week & upcoming'],['points','Upgrade points'],['shop','Skull shop'],['bonuses','Prime bonuses']].map(([key,label])=>`<button data-kr-tab="${key}" class="${tab===key?'active':''}">${label}</button>`).join('')}</nav><div data-kr-body></div></section>`;
 const body=host.querySelector('[data-kr-body]');
 if(tab==='week')body.innerHTML=`<div class="kr-section-head"><h3>Upcoming fights</h3><label>Show <select data-kr-weeks>${[3,6,12,20].map(n=>`<option ${n===weeks?'selected':''}>${n}</option>`).join('')}</select> weeks</label></div><p class="kr-note">Starts at your save${d.savedTime?' ('+new Date(d.savedTime*1000).toISOString().slice(0,10)+')':''}; import a fresh save for this week. Green marks monsters below 100 best kills. Future rotations assume unchanged unlocks${d.swapKnown?'':' and KillroySwap = 0 (server value missing)'}.</p><div class="kr-schedule">${d.schedule.slice(0,weeks).map(fights).join('')||'<p>Rotation unavailable: the export is missing reset timing.</p>'}</div>`;
 if(tab==='points'){body.innerHTML=`<div class="kr-split"><section class="kr-panel"><h3>Weekly upgrade points</h3><p class="kr-note">One point after each run. Default budget uses unfinished runs in your save.</p><label>Points to plan <input data-kr-points type="number" min="0" max="100" value="${settings.budget}"></label><label>Priority <select data-kr-goal>${[['balanced','Balanced · timer + skulls'],['kills','More kills / Prime'],['skulls','Skull drops'],['talents','Talent drops'],['dungeon','Dungeon drops'],['pearls','Pearl drops']].map(([key,name])=>`<option value="${key}" ${settings.goal===key?'selected':''}>${name}</option>`).join('')}</select></label><label class="kr-check"><input data-kr-spawn type="checkbox" ${settings.goal==='balanced'?'disabled':''} ${settings.spawn?'checked':''}> I clear mobs and wait for respawns</label><p class="kr-note">Balanced spends only on timer and bonus skulls, favoring the larger relative gain; it is not a fixed 50/50 split. A marginal-gain estimate, not a guaranteed score. Timer assumes a steady kill rate; respawn gains apply only when enabled. Skull estimates omit the per-run diminishing drop chance. Actual gains depend on your class and map.</p></section><section class="kr-panel" data-kr-point-plan></section></div>`;pointResult();}
 if(tab==='shop'){body.innerHTML=`<div class="kr-split"><section class="kr-panel"><h3>Weekly skull budget</h3><label>Skulls to spend <input data-kr-skulls type="number" min="0" max="100000" value="${shop.budget}"></label><p class="kr-note">Saved: ${fmt(k.skulls)} skulls. Raise the budget to include planned runs.</p><label>Buy first <select data-kr-target><option value="-1">No priority purchase</option>${m.shopNames.slice(0,19).map((n,i)=>`<option value="${i}" ${shop.target===i?'selected':''} ${!m.shopUnlocked(d,i)||i===10&&d.options[227]?'disabled':''}>${n} · ${m.costs[i]} skulls</option>`).join('')}</select></label><label>Purchases / attempts <input data-kr-quantity type="number" min="0" max="10000" value="${shop.quantity}"></label><label class="kr-check"><input data-kr-remainder type="checkbox" ${shop.remainder?'checked':''}> Optimize remaining skulls for permanent bonuses</label><details><summary>Permanent bonus priorities</summary>${Object.keys(m.curves).map(id=>`<label>${m.shopNames[id]}<input data-kr-weight="${id}" type="number" min="0" max="100" value="${shop.weights[id]??1}"></label>`).join('')}</details><p class="kr-note">Higher weight favors a bonus; 0 excludes it. Remaining spending uses applied bonus gain per skull, including your Gallery and coral additive pools. Gallery podium-grade jumps are not valued automatically; use Buy first to target them. Consumables use your buy-first target. Arcade: ${Math.max(0,50-(d.options[417]||0))} purchases left. ${d.prime?(d.options[466]>=3?'':'Final shop row needs the Billroy dialogue unlock.'):'Prime shop is locked in this save.'}</p></section><section class="kr-panel" data-kr-shop-plan></section></div>`;shopResult();}
 if(tab==='bonuses')body.innerHTML=`<h3>Permanent account bonuses</h3><div class="kr-bonuses">${k.permanentUpgrades.filter((x,i)=>i!==2&&i!==9).map((x,i)=>`<article class="kr-panel"><span class="kr-kicker">${d.prime?'SAVED BONUS':'PRIME LOCKED'}</span><h3>${esc(m.shopNames[[10,11,13,14,15,16,17,18][i]])}</h3><strong>${[16,17].includes([10,11,13,14,15,16,17,18][i])?(m.value([10,11,13,14,15,16,17,18][i],x.level)).toFixed(5)+'× applied factor':esc(x.bonusDisplay||((d.options[227]||0)?'Unlocked':'Not unlocked'))}</strong><p class="kr-note">${esc(m.limits[[10,11,13,14,15,16,17,18][i]]||pretty(x.description))}</p><small>Saved level ${fmt(x.level)}</small></article>`).join('')}</div>`;
 host.querySelectorAll('[data-kr-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.krTab;paint();});host.querySelector('[data-kr-weeks]')?.addEventListener('change',e=>{weeks=Number(e.target.value);paint();});
 const bind=(selector,fn)=>host.querySelector(selector)?.addEventListener('change',e=>fn(e.target));
 bind('[data-kr-points]',e=>{settings.budget=Math.max(0,Math.min(100,Math.floor(Number(e.value)||0)));e.value=settings.budget;pointResult();});bind('[data-kr-goal]',e=>{settings.goal=e.value;host.querySelector('[data-kr-spawn]').disabled=settings.goal==='balanced';pointResult();});bind('[data-kr-spawn]',e=>{settings.spawn=e.checked;pointResult();});
 bind('[data-kr-skulls]',e=>{shop.budget=Math.max(0,Math.min(100000,Math.floor(Number(e.value)||0)));e.value=shop.budget;shopResult();});bind('[data-kr-target]',e=>{shop.target=Number(e.value);shopResult();});bind('[data-kr-quantity]',e=>{shop.quantity=Math.max(0,Math.min(10000,Math.floor(Number(e.value)||0)));e.value=shop.quantity;shopResult();});bind('[data-kr-remainder]',e=>{shop.remainder=e.checked;shopResult();});host.querySelectorAll('[data-kr-weight]').forEach(e=>e.onchange=()=>{shop.weights[e.dataset.krWeight]=Math.max(0,Math.min(100,Number(e.value)||0));e.value=shop.weights[e.dataset.krWeight];shopResult();});afterRender?.();
 }
 function pointResult(){const result=m.points(d,settings);host.querySelector('[data-kr-point-plan]').innerHTML=`<h3>Your upgrade plan</h3><div class="kr-levels">${m.names.map((n,i)=>`<div><span>${n}</span><strong>${result.before[i]} → ${result.levels[i]}</strong><b>${result.levels[i]>result.before[i]?'+'+(result.levels[i]-result.before[i]):'—'}</b></div>`).join('')}</div><details><summary>Spending order · ${result.steps.length} points</summary><ol>${result.steps.map(x=>`<li>${x.name} → Lv ${x.level}</li>`).join('')}</ol></details>${!result.steps.length?'<p class="kr-note">No points selected or no eligible upgrade improves this goal.</p>':''}<p class="kr-note">Respects completed-run requirements and Equinox upgrade unlocks. Budgets above ${remaining} are future-run scenarios.</p>`;}
 function shopResult(){const result=m.skulls(d,shop);host.querySelector('[data-kr-shop-plan]').innerHTML=`<h3>Recommended purchases</h3><div class="kr-stats"><div><span>Spend</span><strong>${fmt(result.spent)}</strong></div><div><span>Skulls left</span><strong>${fmt(result.left)}</strong></div></div>${result.rows.map(r=>`<div class="kr-purchase"><div><strong>${r.name}</strong><small>${r.chance!=null?`${fmt(r.chance*100)}% chance of at least one success · stop and recalculate after success`:r.after!=null?`Lv ${r.before} → ${r.after}`:'Priority purchase'}</small></div><span>${r.count} × <b>${m.costs[r.id]}</b><small>${r.cost} skulls</small></span></div>`).join('')||'<p class="kr-note">Select a priority purchase or enable an affordable permanent bonus.</p>'}<p class="kr-note">Third-fight attempts are 1% each. Gallery is 5% per attempt until level 2, then guaranteed upgrades. The reserved future bonus is excluded. No purchases are made in game.</p><details class="kr-audit"><summary>Verified caps & hidden effects</summary><ul><li>Arcade: 50 purchases per week, 10 balls each. Skulls reset weekly.</li><li>No finite level cap found for permanent shop upgrades; their curves have diminishing returns.</li>${Object.values(m.limits).map(t=>`<li>${esc(t)}</li>`).join('')}<li>Gallery’s hidden podium contribution uses rounding and a cap of 2. With integer contributions from other sources, extra podium steps occur at Lv 11 and 36; the raw contribution reaches 2 at Lv 50. This does not cap the Gallery multiplier.</li><li>Masterclass Drops and World 7 EXP are percentage inputs in the actual formulas despite the shop’s × labels. EXP shares an additive pool for Spelunking; its research factor is separate.</li><li>Final shop row requires Prime plus Billroy dialogue state ≥3. The future bonus has a formula but no gameplay consumer found.</li><li>Meritocracy affects skull drops during runs, not the audited purchase prices, level gains, or success chances.</li></ul></details>`;}
 paint();
}catch(e){if(host.killroyRequest===token&&host.dataset.page==='killroy')host.innerHTML=`<p>${esc(e.message)}</p>`;}}
root.KillroyPage={render};
})(window);
