(function(root){
'use strict';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>Number.isFinite(n)?n.toLocaleString(undefined,{maximumFractionDigits:2}):'—';
const duration=s=>{s=Math.max(0,Math.ceil(s));return `${Math.floor(s/86400)?Math.floor(s/86400)+'d ':''}${Math.floor(s%86400/3600)}h ${Math.floor(s%3600/60)}m ${s%60}s`;};
let worker=null,ticker=null,pendingTimeout=null;
function dispose(){worker?.terminate();worker=null;clearInterval(ticker);ticker=null;clearTimeout(pendingTimeout);pendingTimeout=null;}
const sourceCard=(s,value)=>`<article><div>${s.page?`<button class="secondary" data-library-open="${s.page}">${esc(s.name)}</button>`:`<span>${esc(s.name)}</span>`}<strong>${esc(value)}</strong></div><p>${esc(s.where)}</p></article>`;
const speedSources={
 'Meal Bonus':['Fortune Cookie','cooking','W4 Cooking: level Fortune Cookie. Its meal-effect multipliers are broken down below.'],
 'Atom Bonus':['Oxygen — Library Booker','atomCollider','Atom Collider: Oxygen levels multiply checkout speed.'],
 'Tower Bonus':['Talent Book Library building','construction','W3 Construction: +5% checkout speed per Library building level. Construction mastery raises the building cap, allowing more speed upgrades.'],
 'Bubble Bonus':['Ignore Overdues','alchemy','W2 Alchemy: level the Ignore Overdues bubble.'],
 'Vial Bonus':['Chonker Chug','vials','W2 Alchemy: unlock and level the Chonker Chug vial.'],
 'Stamp Bonus':['Biblio Stamp','stamps','W1 Stamps: obtain Biblio Stamp from Snouts and level it with Tundra Logs.'],
 'Superbit Bonus':['Library Checkouts superbit','gaming','W5 Gaming: unlock the Library Checkouts superbit; +1% speed per Gaming level.'],
 'Achievement Bonus':['Checkout Takeout','tasks','W3 achievement: 1,000 checkouts unlocks +30% checkout speed.']
};
function breakdownContent(m){
 const b=m.breakdown;if(!b)return '';
 const total=m.sources.find(s=>s.name==='Summoning victories').value;
 return `<section class="exp-card library-summoning"><h3>Summoning relics, upgrades & paid bonuses</h3><p>These sources produce the <strong>+${fmt(total)}</strong> Summoning total above. They are already included in your maximum book level.</p><div class="library-formula">${fmt(b.base)} base levels × ${b.multipliers.map(s=>`${fmt(s.value)} ${esc(s.name)}`).join(' × ')} × ${fmt(b.poolMultiplier)} reward pool = <strong>+${fmt(total)} levels</strong></div><h4>Library reward battles</h4><div class="library-sources">${b.battles.map(s=>sourceCard({name:s.name,page:'summoning',where:`${s.won?'Won':'Not yet won'} · +${fmt(s.base)} base Library levels before the multipliers below.`},s.won?'Unlocked':'Missing')).join('')}</div><h4>Separate multipliers</h4><div class="library-sources">${b.multipliers.map(s=>sourceCard(s,`${fmt(s.value)}×`)).join('')}</div><h4>Reward pool · +${fmt((b.poolMultiplier-1)*100)}%</h4><p class="muted">These percentages add together before multiplying the base reward.</p><div class="library-sources">${b.pool.map(s=>sourceCard(s,`+${fmt(s.value)}%`)).join('')}</div><p class="library-paid"><strong>Daydreamer Pack: ${m.paid.owned?'owned':'not owned'}.</strong> At your current progress, the book cap is <strong>${fmt(m.paid.withoutPack)} without</strong> and <strong>${fmt(m.paid.withPack)} with</strong> this pack. Its unrounded contribution is +${fmt(m.paid.packPotential)} book levels.</p><p class="muted">The Library Max reward has its own formula. Emperor and Endless winner-bonus multipliers do not increase this cap; they can still affect other Summoning rewards.</p></section>
 <details class="exp-card"><summary>Minimum book level · ${fmt(m.minBookLv)}</summary><div class="library-sources">${b.minimum.map(s=>sourceCard(s,`+${fmt(s.value)}`)).join('')}</div><p class="muted">Minimum-roll upgrades improve ordinary random books. They do not increase a guaranteed maximum-level book.</p></details>`;
}
function mealContent(m){
 const b=m.breakdown;if(!b)return '';
 return `<h4>Inside the Fortune Cookie bonus</h4><div class="library-sources">${b.meals.map(s=>sourceCard({name:s.name,where:`Level ${fmt(s.level)} gives +${fmt(s.base)}% before meal multipliers. Death Bringer ribbon: ${fmt(s.ribbon)}×. Cooking mastery node: ${fmt(s.mastery)}×.`,page:'cooking'},`Lv ${fmt(s.level)}`)).join('')}${b.mealBonuses.map(s=>sourceCard(s,s.pool==='add'?`+${fmt(s.value)}%`:`${fmt(s.value)}×`)).join('')}</div><p class="muted">Lab and shiny percentages share one pool. Summoning, Wickerlight Spirit, the meal ribbon, and the mastery node multiply it. These effects are already included in the Fortune Cookie speed value above.</p>`;
}
function characterContent(m){
 const chars=m.characters||[];
 return `<section class="exp-card library-characters"><h3>Character books &amp; talent levels</h3><p>Book target: <strong>${fmt(m.maxBookLv)}</strong>. Book caps are shared. Preset levels show invested points, before bonuses.</p><label class="library-filter"><input type="checkbox" data-library-needs> Only show talents needing a book or points</label>${chars.length?chars.map(ch=>{
 const books=ch.talents.filter(t=>t.needsBook).length,maxed=ch.talents.filter(t=>t.cap!==null&&t.cap>=m.maxBookLv).length;
 return `<details class="library-character"><summary>${esc(ch.name)} <span>${esc(ch.className)} · ${maxed}/${ch.talents.length} books at max · ${books} need books</span></summary><p class="muted">Active preset: ${ch.active+1}. Only Library-eligible class talents are listed.</p><div class="library-talent-list">${ch.talents.map(t=>{
 const points=t.levels.some(l=>l!==null&&t.cap!==null&&l<t.cap),needs=t.needsBook||points||t.cap===null||t.levels.includes(null);
 return `<article class="library-talent" data-library-needed="${needs}"><div class="library-talent-name"><img src="assets/UISkillIcon${t.id}.png" alt="" loading="lazy"><strong>${esc(t.name)}</strong></div><div class="library-book-cap"><small>Book cap / target</small><strong>${fmt(t.cap)} / ${fmt(m.maxBookLv)}</strong><span class="${t.needsBook?'library-pending':'library-complete'}">${t.cap===null?'Cap unavailable':t.needsBook?`Book needed +${fmt(m.maxBookLv-t.cap)}`:'Book at max'}</span></div>${t.levels.map((level,i)=>`<div class="library-preset"><small>Preset ${i+1}${ch.active===i?' · active':''}</small><strong>${fmt(level)} / ${fmt(t.cap)}</strong><span>${level===null||t.cap===null?'Unavailable':level<t.cap?`+${fmt(t.cap-level)} points`:'At cap'}</span></div>`).join('')}</article>`;
 }).join('')}</div><p class="library-filter-empty" hidden>All known books and both presets are at their caps.</p></details>`;
 }).join(''):'<p>No character talent records were found in this save.</p>'}</section>`;
}
function content(m){
 if(m.missing)return '<section class="exp-card"><h3>Load your save to view the Library</h3><p>Import your account on Home to see your maximum book level, upgrade sources, and checkout times.</p></section>';
 return `<div class="library-tabs" role="tablist" aria-label="Library sections"><button role="tab" id="library-overview-tab" aria-controls="library-overview" aria-selected="true" data-library-tab="overview">Overview</button><button role="tab" id="library-characters-tab" aria-controls="library-characters" aria-selected="false" tabindex="-1" data-library-tab="characters">Characters &amp; Talents</button></div><div id="library-overview" class="library-tab-panel" role="tabpanel" aria-labelledby="library-overview-tab"><div class="library-summary"><article><span>Your maximum book level</span><strong>${fmt(m.maxBookLv)}</strong><small>Ordinary roll: ${fmt(m.minBookLv)}–${fmt(m.maxBookLv)}</small></article><article><span>Saved checkouts</span><strong>${fmt(m.count)}</strong><small>${m.unlocked?'Library unlocked':'Build the Library in Construction'}</small></article><article><span>Guaranteed max-level books</span><strong>${m.automation&&m.count!==null?Math.floor(m.count/20):'—'}</strong><small>${m.automation?'20 checkouts each · enable Max Book in game':'Requires Automation Arm level 5'}</small></article></div>
 <div class="library-columns"><section class="exp-card"><h3>Next books</h3><p class="muted">Checkouts accumulate more slowly as you stockpile them.</p>${!m.unlocked?'<p>Build the Library to start accumulating checkouts.</p>':!m.timers.length?'<p>Timer unavailable: import a full save with its Library timestamp.</p>':`<div class="library-timers">${m.timers.map(t=>`<div><span>${esc(t.label)}${t.target===20?' · one max-level book':''}</span><strong ${t.ready?'':`data-library-time="${t.at}"`}>${t.ready?'Ready in save':duration((t.at-Date.now())/1000)}</strong><small>${t.ready?'Available at the saved snapshot':esc(new Date(t.at).toLocaleString())}</small></div>`).join('')}</div>`}<p class="muted library-note">${m.at?`Save: ${esc(new Date(m.at).toLocaleString())}. `:''}Times are estimates at saved bonuses with no checkouts spent. “Due” means the estimate has passed; refresh your save to confirm.</p></section>
 <section class="exp-card"><h3>Where to get books</h3><p><strong>Class talent books:</strong> visit the Library in W3 town, choose a class and talent, then spend a checkout. Consume the book from your inventory to raise that talent’s cap.</p><p><strong>Guaranteed maximum:</strong> build Automation Arm level 5 and enable the Library’s Max Book option. It spends 20 checkouts for a book at your maximum level.</p><p><strong>VIP star talent books:</strong> use the VIP Bookshelf inside the Library. These cost 5 checkouts; more choices unlock as your VIP membership rises through Cooking, the Pet Arena, and the VIP Parchment sigil.</p><p class="muted">The book cap is separate from extra talent levels granted by equipment, pets, and other bonuses.</p></section></div>
 <section class="exp-card"><h3>Maximum book level — sources</h3><p class="muted">Each source shows current / maximum book-level bonus. Summoning’s maximum includes the Daydreamer Pack. Open a source to work on its upgrade.</p><div class="library-sources">${m.sources.map(s=>`<article><div><button class="secondary" data-library-open="${s.page}">${esc(s.name)}</button><strong aria-label="${esc(s.name)}: ${fmt(s.value)} of ${fmt(s.max)} maximum book levels">${fmt(s.value)}/${fmt(s.max)}</strong></div><p>${esc(s.where)}</p></article>`).join('')}</div></section>
 ${breakdownContent(m)}
 <details class="exp-card"><summary>Checkout speed bonuses & meal multipliers</summary><div class="library-sources">${m.speed.map(s=>{const info=speedSources[s.name]||[s.name,null,''];return sourceCard({name:info[0],page:info[1],where:info[2]},`+${fmt(s.value)}%`);}).join('')}</div><p class="muted">Fortune Cookie and Oxygen each multiply the combined speed pool from the other six sources.</p>${mealContent(m)}</details>
 <details class="exp-card"><summary>Other ways to get checkouts & audit notes</summary><p><button class="secondary" data-library-open="killroy">Killroy’s Skull Shop</button> offers 2 Library checkouts per purchase. These add to your balance without changing your book cap or passive speed.</p><p>Book cap, minimum roll, Summoning multipliers, and checkout speed were traced through the saved game client and account formulas. General bonus descriptions can include effects that the Library-specific formula excludes.</p><p><a href="https://idleon.wiki/wiki/Summoning" target="_blank" rel="noopener noreferrer">Summoning reference</a> · <a href="https://gameslikefinder.com/article/idleon-max-talent-guide/" target="_blank" rel="noopener noreferrer">Book-level source reference</a></p></details></div><div id="library-characters" class="library-tab-panel" role="tabpanel" aria-labelledby="library-characters-tab" hidden>${characterContent(m)}</div>`;
}
function render(host,raw){
 dispose();host.innerHTML='<div class="section-head compact"><div><p class="eyebrow">World 3</p><h2>Library</h2><p>Talent book levels, upgrade sources, and upcoming checkouts.</p></div></div><div class="library-page" data-library-body role="status">Reading your Library…</div>';
 const panel=host.querySelector('[data-library-body]');worker=new Worker('library-worker.js');
 const fail=()=>{dispose();if(host.contains(panel))panel.innerHTML='<section class="exp-card"><h3>Library unavailable</h3><p>Import a complete save and try again.</p><button data-library-retry>Retry</button></section>';panel.querySelector('[data-library-retry]')?.addEventListener('click',()=>render(host,raw));};
 const timeout=pendingTimeout=setTimeout(fail,60000),active=worker;
 worker.onerror=()=>{clearTimeout(timeout);fail();};
 worker.onmessage=e=>{clearTimeout(timeout);active.terminate();if(worker===active)worker=null;if(!host.contains(panel))return;if(e.data.error){fail();return;}panel.removeAttribute('role');panel.innerHTML=content(e.data.result);const tabs=[...panel.querySelectorAll('[data-library-tab]')];const selectTab=tab=>{tabs.forEach(b=>{const selected=b===tab;b.setAttribute('aria-selected',String(selected));b.tabIndex=selected?0:-1;panel.querySelector('#'+b.getAttribute('aria-controls')).hidden=!selected;});};tabs.forEach((b,i)=>{b.onclick=()=>selectTab(b);b.onkeydown=event=>{let next;if(event.key==='ArrowRight')next=(i+1)%tabs.length;else if(event.key==='ArrowLeft')next=(i+tabs.length-1)%tabs.length;else if(event.key==='Home')next=0;else if(event.key==='End')next=tabs.length-1;else return;event.preventDefault();selectTab(tabs[next]);tabs[next].focus();};});panel.querySelector('[data-library-needs]')?.addEventListener('change',event=>{panel.querySelectorAll('.library-character').forEach(ch=>{ch.querySelectorAll('[data-library-needed]').forEach(row=>row.hidden=event.target.checked&&row.dataset.libraryNeeded==='false');ch.querySelector('.library-filter-empty').hidden=!!ch.querySelector('[data-library-needed]:not([hidden])');});});panel.querySelectorAll('[data-library-open]').forEach(b=>b.onclick=()=>window.dispatchEvent(new CustomEvent('idleon:navigate',{detail:b.dataset.libraryOpen})));const tick=()=>{if(!host.contains(panel)){clearInterval(ticker);return;}panel.querySelectorAll('[data-library-time]').forEach(n=>{const seconds=(Number(n.dataset.libraryTime)-Date.now())/1000;n.textContent=seconds<=0?'Due · refresh save':duration(seconds);});};tick();ticker=setInterval(tick,1000);};
 worker.postMessage(raw||{});
}
root.LibraryPage={render,dispose,content};
})(window);
