(function(root){
'use strict';
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clean=value=>String(value??'').replace(/[{}]/g,'').replace(/_/g,' ').replace(/\|/g,' ').replace(/\s+/g,' ').trim();
const PET_NAMES={
 babaMummy:'King Doot',rift2:'Rift Slug',ram:'Dedotated Ram',Crystal3:'Crystal Custard',sheep:'Sheepie',w5b1:'Molti',beanG:'Bored Bean',slimeG:'Slime',jarSand:'Sandy Pot',bloque:'Bloque',frogG:'Frog',slimeBz:'Glunko Supreme',caveC:'Ancient Golem',w6d3:'Samurai Guardian',rift3:'Rift Jocund',w6b4:'Leek Spirit',Crystal4:'Crystal Capybara',w5b6:'Biggole Mole',frogBIG:'Gigafrog',potato:'Mashed Potato',w4b1:'Flying Worm',frogP:'Poisonic Frog',glass:'Quenchie',mushG:'Green Mushroom',Pet10:'Cool Bird',Pet12:'Axolotl',Pet3:'Mallay',reindeer:'Spirit Reindeer',w7d1:'RIP Tide',Pet0:'Squirrel',Pet1:'Mr Pig',Pet2:'Wild Boar',Pet4:'Whale',Pet5:'Chippy',Pet6:'Bunny',Pet8:'Panda',Pet11:'Hedgehog',w7e1:'Whallamus',w7a5:'Balloonfish',w7a8:'Pufferblob',w7a4:'Shellslug',Crystal6:'Crystal Cuttlefish',w7a3:'Eamsy Earl',w7a7:'Litterfish',w7a10:'Spearfish',w7a1:'Equinox Broadbass',coconut:'Mafioso',snakeG:'Baby Boa',mushP:'Purp Mushroom',bubba:'Bubba the Seal',snakeR:'Santa Snake',w6c2b:'Santas Little Helper',w7b5:'Jellofish',w7b1b:'Koi Fish',w7b6b:'Neonscale',w7b11:'Pirate Deckhand',w7b12:'Dreadnaught Captain',rift1:'Rift Spooker',rift4:'Rift Hivemind',snakeB:'Cryosnake',w4c1:'Clammie',w6a2:'Ricecake',w6a4:'Baby Troll',w6b3:'Mama Troll',w6d1:'Royal Egg',w7a12:'Coralcave Guardian',w7b2:'Boomy Mine',w7b4:'Eggroll',w7b7:'Mantaray',w7b8:'Glowfish',T1a:'Bronze Champion Ram',T1b:'Silver Champion Ram',T1c:'Gold Champion Ram',rift5:'Rift Stalker',w7b3b:'Glimbo',w4b4b:'Vanillie',slimeR:'Valenslime',Pet7:'Mechanical Mouse',slugG:'Lucky Slug',PotG:'Potluck',slimeB:'Glunko The Massive',poppy:'Poppy',w6b2b:'Wickerlight Spirit',w5b5b:'Smoke Devil',T2a:'Bronze Champion Troll',T2b:'Silver Champion Troll',T2c:'Gold Champion Troll','fm frog':'Abacus Frog',caveD:'Crystal Glunko','fm goose':'Bin Goosey',r0a:'Magician Grub',r0b:'Armadillo',r0c:'Imperial Ogre',r0d:'Pipsqueak','fm rat':'Verminous'
};
const spriteCode=code=>({'fm frog':'fm_frog','fm goose':'fm_goose','fm rat':'fm_rat'}[String(code).toLowerCase()]||String(code));
let filter='owned',query='';
function parse(value){if(typeof value!=='string')return value;try{return JSON.parse(value);}catch{return null;}}
function model(data={},rawRoot={}){
 const sources=[rawRoot,parse(rawRoot.data),data].filter(Boolean);
 let rows=null;
 for(const source of sources){const comp=parse(source.companion??source.Companion),list=parse(comp?.l??(Array.isArray(comp)?comp:null));if(Array.isArray(list)){rows=list;break;}}
 const owned=new Map();
 for(const row of rows||[]){const parts=Array.isArray(row)?row:String(row).split(','),id=Number(parts[0]);if(!String(parts[0]??'').trim()||!Number.isInteger(id)||id<0)continue;const pet=owned.get(id)||{copies:0,level:0};pet.copies++;pet.level=Math.max(pet.level,Number(parts[4])||0);owned.set(id,pet);}
 let options;for(const source of sources){options=parse(source.OptionsListAccount??source.OptLacc);if(options)break;}
 const borrowed=new Set(String(options?.[606]??options?.h?.[606]??'').split(',').filter(x=>x.trim()!=='').map(Number).filter(x=>Number.isInteger(x)&&x>=0));
 if(!Array.isArray(root.PETS_CATALOG))throw new Error('Pets catalog failed to load. Reload the planner.');
 const all=root.PETS_CATALOG.map(entry=>{const found=owned.get(entry.id),isBorrowed=borrowed.has(entry.id),upgraded=found?.level===1;return {...entry,name:PET_NAMES[entry.code]||entry.name,owned:!!found,upgraded,borrowed:isBorrowed,copies:found?.copies||0,effectiveBonus:!found&&!isBorrowed?0:upgraded&&!isBorrowed?entry.upgradedBonus:entry.baseBonus};});
 return{available:rows!==null,all,owned:all.filter(x=>x.owned),upgraded:all.filter(x=>x.upgraded),borrowed:all.filter(x=>x.borrowed)};
}
function render(host,data,rawRoot){
 const m=model(data,rawRoot),paint=()=>{const needle=query.trim().toLowerCase(),shown=m.all.filter(x=>(filter==='all'||filter==='owned'&&x.owned||filter==='upgraded'&&x.upgraded||filter==='borrowed'&&x.borrowed)&&(!needle||`${x.name} ${x.code} ${x.description} ${x.upgradedDescription} ${x.id}`.toLowerCase().includes(needle)));
 host.innerHTML=`<div class="pets-hero"><div><p class="eyebrow">Misc · companions</p><h2>Pets</h2><p>Every companion decoded from the imported save. Upgraded pets use Bonus 2; a borrowed pet uses its base bonus, matching the client.</p></div><div class="pets-summary"><strong>${m.available?m.owned.length:'—'}</strong><span>${m.available?'unique owned':'companion data unavailable'}</span><b>${m.available?`${m.upgraded.length} upgraded · ${m.borrowed.length} borrowed`:'Load a full account export'}</b></div></div>${m.available?'':`<section class="pets-warning"><strong>This export has no companion list.</strong><span>Use the full IdleOn Toolbox export, not the data-only JSON. The app will not claim that you own zero pets when the field is missing.</span></section>`}<div class="pets-tools"><nav class="skill-tabs" aria-label="Pet filters">${[['owned','Owned'],['upgraded','Upgraded'],['borrowed','Borrowed'],['all','All pets']].map(([id,label])=>`<button class="skill-tab${filter===id?' active':''}" data-pet-filter="${id}">${label}</button>`).join('')}</nav><input id="petSearch" type="search" value="${esc(query)}" placeholder="Search pet or bonus…" aria-label="Search pets"></div><p class="pets-count">${m.available?`Showing ${shown.length} of ${m.all.length} companions`:'Catalog shown for reference; ownership unavailable'}</p><div class="pets-grid">${shown.map(x=>{const icon=encodeURIComponent(spriteCode(x.code));return `<article class="pet-card ${x.owned?'owned':'missing'} ${x.upgraded?'upgraded':''} ${x.borrowed?'borrowed':''}"><div class="pet-card-head"><span class="pet-id">#${x.id}</span><div class="pet-state">${x.borrowed?'<b>Borrowed</b>':x.upgraded?'<b>Upgraded</b>':x.owned?'<b>Owned</b>':'<span>Missing</span>'}${x.copies>1?`<small>${x.copies} copies</small>`:''}</div></div><div class="pet-identity"><span class="pet-picture"><img src="assets/pets-static/${icon}.png" alt="${esc(x.name)}" loading="lazy"></span><div><h3>${esc(x.name)}</h3></div></div><p class="pet-active-bonus">${esc(clean(x.upgraded&&!x.borrowed?x.upgradedDescription:x.description))}</p><details><summary>Base vs upgraded</summary><p><strong>Base:</strong> ${esc(clean(x.description))}</p><p><strong>Upgraded:</strong> ${esc(clean(x.upgradedDescription))}</p><small>Raw strength: ${x.baseBonus} → ${x.upgradedBonus}; active ${x.effectiveBonus}</small></details></article>`;}).join('')||`<p class="pets-empty">${m.available?'No pets match this view.':'Ownership cannot be read from this export.'}</p>`}</div>`;
 host.querySelectorAll('.pet-picture img').forEach(image=>image.onerror=()=>image.closest('.pet-picture')?.classList.add('missing-picture'));
 host.querySelectorAll('[data-pet-filter]').forEach(button=>button.onclick=()=>{filter=button.dataset.petFilter;paint();});const search=host.querySelector('#petSearch');search.oninput=()=>{query=search.value;paint();const next=host.querySelector('#petSearch');next.focus();next.setSelectionRange(query.length,query.length);};};paint();
}
root.PetsPage={model,render};
})(typeof window!=='undefined'?window:globalThis);
