(function(root){
  'use strict';
  const fmt=v=>{const n=Number(v);if(!Number.isFinite(n))return 'Unknown';if(Math.abs(n)>=1e18)return n.toExponential(2).replace('e+','e');for(const [d,s] of [[1e15,'Q'],[1e12,'T'],[1e9,'B'],[1e6,'M'],[1e3,'K']])if(Math.abs(n)>=d)return +(n/d).toFixed(2)+s;return n.toLocaleString('en-US',{maximumFractionDigits:2});};
  const clean=v=>String(v??'').replaceAll('_',' ').replaceAll('@',' ').trim();
  const effect=(text,value)=>clean(text).replace(/\}x/g,fmt(1+value/100)+'x').replace('$',fmt(Math.floor((value+4)/(value+100)*1000)/10)).replace(/[{}]/g,fmt(value));
  function build(systems,raw={}){
    const out={},breeding=systems.get('breeding'),vault=systems.get('upgradeVault'),emperor=systems.get('emperor'),tome=systems.get('tome'),slab=systems.get('slab');
    const row=(name,effect,level,icon,extra={})=>({name:clean(name),effect:clean(effect),level,icon:`assets/${/^(MotherlodeTREE|(?:Bone|Dust|Tach|DungRNG)\d+)$/.test(icon)?icon+'_x1':icon}.png`,status:'active',...extra});
    const arena=['Unlocks 3rd mob battle slot','+25% Library VIP membership','1.20x total damage','New Post Office upgrade crate','Unlocks 4th mob battle slot','1.5x monster cash','New Post Office upgrade crate','−50% kitchen upgrade costs','Unlocks 5th mob battle slot','New Post Office upgrade crate','+60% Library VIP membership','Equip a 3rd large bubble','Unlocks 6th mob battle slot','+20% line width for all players','2x monster cash','1.40x total damage'];
    if(breeding){
      const parse=v=>{try{return typeof v==='string'?JSON.parse(v):v;}catch{return null;}},saved=raw?.data||raw||{},b=parse(saved.Breeding),opts=parse(saved.OptionsListAccount??saved.OptLacc),rawPets=parse(saved.Pets),stored=parse(saved.PetsStored),rawTerritory=parse(saved.Territory);
      const species=(breeding.basePets||[]).filter(p=>p.data.world<4&&p.data.petId!=='_').map(p=>({id:p.data.petId,world:p.data.world+1,order:p.indexInWorld,gene:p.gene.data.name,unlocked:b?.[1]?.[p.data.world]==null?null:p.indexInWorld<Number(b[1][p.data.world])}));
      const inventory=[];for(const [zone,values] of [['Assigned',rawPets],['Storage',stored]])for(const [slot,rawPet] of Object.entries(values||{})){const p=parse(rawPet),g=breeding.genes?.[Number(p?.[1])];if(!p||!species.some(s=>s.id===p[0])||!g||!(Number(p[2])>0))continue;inventory.push({key:zone+slot,id:p[0],gene:g.data.name,power:Number(p[2]),location:zone==='Storage'?'Storage #'+(Number(slot)+1):Number(slot)<27?'Fenceyard #'+(Number(slot)+1):'Territory '+(Math.floor((Number(slot)-27)/4)+1)+' · slot '+((Number(slot)-27)%4+1)});}
      out.breedingTeams=[{arenaWave:opts?.[89]==null?null:Number(opts[89]),inventoryKnown:rawPets!=null||stored!=null,species,inventory,genes:(breeding.genes||[]).map(g=>({name:g.data.name,active:clean(g.data.description),passive:clean(g.data.combatDescription)})),territories:(breeding.territory||[]).filter(t=>t.index!==14&&t.data.battleName!=='Filler Filler').map((t,i)=>({index:i,name:clean(t.data.battleName),unlocked:opts?.[85]==null?null:i<Number(opts[85]),requirement:t.data.fightPower,rounds:rawTerritory?.[i]?.[1]??null,pets:inventory.filter(p=>p.location.startsWith('Territory '+(i+1)+' ·'))}))}];
      out.petArena=arena.map((text,i)=>{const wave=[2,5,8,12,15,20,25,35,50,65,80,100,125,150,175,200][i],owned=breeding.arenaWave>=wave;return row(`Wave ${wave}`,text,owned?'Unlocked':'Locked','pets-static/mushG',{status:owned?'maxed':'missing',summary:`Highest arena wave: ${fmt(breeding.arenaWave)} · ${arena.filter((_,j)=>breeding.arenaWave>=[2,5,8,12,15,20,25,35,50,65,80,100,125,150,175,200][j]).length} / 16 rewards`,detail:owned?'Permanent arena reward unlocked.':`${wave-breeding.arenaWave} more waves to this reward.`});});
      out.shinyPets=(breeding.shinyBonuses||[]).map(x=>row(clean(x.data.text).replace(/^[+{}%x ]+/g,''),effect(x.data.text,x.getBonus()),`${fmt(x.totalLevels)} combined levels`,`pets-static/${x.pets?.find(p=>root.ARCADE_PAGE_ASSETS?.petSprites?.includes(p.data.petId))?.data.petId||'mushG'}`,{status:x.totalLevels?'active':'missing',bonusId:x.data.index,pets:(x.pets||[]).filter(p=>p.data.world<4&&p.data.petId!=='_').map(p=>{const saved=raw?.data||raw||{},parse=v=>{try{return typeof v==='string'?JSON.parse(v):v;}catch{return null;}},b=parse(saved.Breeding),progress=b?.[22+p.data.world]?.[p.indexInWorld],known=progress!=null&&Number.isFinite(Number(progress)),unlocks=b?.[1]?.[p.data.world];return {id:p.data.petId,world:p.data.world+1,order:p.indexInWorld,level:known?p.shinyLevel:null,unlocked:unlocks==null?null:p.indexInWorld<Number(unlocks),bonus:known?effect(x.data.text,p.getShinyBonus()):'Saved progress unavailable',perLevel:effect(x.data.text,x.data.bonusPerLevel),icon:'assets/pets-static/'+(root.ARCADE_PAGE_ASSETS?.petSprites?.includes(p.data.petId)?p.data.petId:'mushG')+'.png'};}),detail:(x.pets||[]).map(p=>`${clean(p.data.petId)}: shiny Lv ${p.shinyLevel}`).join(' · ')}));}
    if(vault)out.upgradeVault=vault.bonuses.map(x=>row(x.data.name,x.getDescription(),`Lv ${fmt(x.level)}${x.level<=x.data.max_level?' / '+fmt(x.data.max_level):''}`,`VaultUpg${x.id}`,{status:!x.unlocked?'missing':x.level>=x.data.max_level?'maxed':'active',cost:x.cost,detail:x.level>=x.data.max_level?'Catalog maximum reached (additional granted levels are retained).':`Next upgrade cost shown in coins. ${fmt(x.data.max_level-x.level)} levels to catalog maximum.`}));
    if(emperor)out.emperorBonuses=emperor.emperorBonuses.map(x=>{const next=x.data.levelMappings.includes(emperor.emperorKills%48),bonus=x.getBonus(),projected=Math.floor(x.data.bonusValue*(x.level+(next?1:0))*(1+(x.arcaneBonus48+x.arcadeBonus51)/100));const second=x.data.levelMappings.includes((emperor.emperorKills+1)%48),afterTwo=Math.floor(x.data.bonusValue*(x.level+(next?1:0)+(second?1:0))*(1+(x.arcaneBonus48+x.arcadeBonus51)/100));let futureLevel=x.level;const killProjections=Array.from({length:25},(_,i)=>{const improved=x.data.levelMappings.includes((emperor.emperorKills+i)%48);if(improved)futureLevel++;return{kill:emperor.emperorKills+i+1,level:futureLevel,improved,effect:effect(x.data.bonusName,Math.floor(x.data.bonusValue*futureLevel*(1+(x.arcaneBonus48+x.arcadeBonus51)/100)))};});return row(clean(x.data.bonusName).replace(/^\+?\{%?\s*|^\}x\s*|^\$%\s*/, ''),effect(x.data.bonusName,bonus),`Lv ${x.level}`,['ClassIcons58','Bone0_x1','ClassIcons57','Opal','ClassIcons29','Quest78','Tach0_x1','ClassIcons56','ClassIcons59','ClassIcons60','ClassIcons61','Owlb_5'][x.index],{killProjections,emperorKills:emperor.emperorKills,afterOne:effect(x.data.bonusName,projected),afterTwo:effect(x.data.bonusName,afterTwo),second,levelOne:x.level+(next?1:0),levelTwo:x.level+(next?1:0)+(second?1:0),status:x.level?'active':'missing',next,summary:`${fmt(emperor.emperorKills)} Emperor kills · Next boss HP: ${fmt(emperor.bossHP)}`,projection:next?`Next kill → ${effect(x.data.bonusName,projected)}`:'Unchanged after next kill',detail:`${[9,10].includes(x.index)?'Reserved World 7 bonus in the installed client; no specific active effect is claimed. ':''}Next kill: ${x.level} → ${x.level+(next?1:0)} levels. Projection holds your current Arcade and Arcane multipliers fixed.`});});
    if(tome){const player=Math.max(0,tome.highestScoreIndex||0);out.tome=tome.lines.map(x=>{const bounded=['linearToMax','boundedDecay'].includes(x.data.scalingType),score=x.getPlayerScore(player),target=x.data.totalVal;return row(x.getLineName(),x.getLineDescription(),fmt(score)+' points','TomeClaim',{id:x.index,order:x.getDisplayOrder(),status:!x.unlocked?'missing':bounded&&score>=target?'maxed':'active',score,target,bounded,progress:Math.max(0,Math.min(1,score/target)),value:fmt(x.currentValues?.[player]),unlock:x.getLineUnlockLevel(),summary:`Calculated score: ${tome.getPlayerTotalScore(player).toLocaleString('en-US')} · Best account score: ${tome.highestScore.toLocaleString('en-US')} · ${clean(raw.charNames?.[player]||'Character '+(player+1))} · ${tome.getScoreRankingDisplay()} (saved thresholds)`,detail:bounded?`Maximum: ${fmt(target)} points`:`Benchmark: ${fmt(target)} points. This metric can scale beyond its benchmark; it has no finite reachable cap.`});}).sort((a,b)=>a.order-b.order);
      out.tomeBonuses=(tome.epilogueBonuses||[]).map(x=>row('Epilogue '+(x.index+1),effect(x.data.bonus,x.getBonus(tome.highestScore)),x.unlocked?'Unlocked':'Locked','TomeClaim',{status:x.unlocked?'active':'missing'}));}
    if(slab){out.slab=slab.obtainableItems.map(x=>row(x.displayName,(x.sources?.sources||[]).map(s=>s.txtName).filter(Boolean).join(' · ')||'Source details unavailable',x.obtained?'Found':'Missing',x.internalName,{id:x.internalName,group:clean(x.type||x.typeGen||'Other'),status:x.obtained?'maxed':'missing',summary:`${slab.obtainableItems.filter(x=>x.obtained).length} / ${slab.obtainableItems.length} obtainable items found · Raw saved count: ${fmt(slab.rawObtainedCount)}`}));
      const saved=raw?.data||raw||{},greenStacks=String(saved.GreenStacks??'').split(',').map(x=>x.trim()).filter(Boolean),greenSet=new Set(greenStacks),byId=new Map(slab.obtainableItems.map(x=>[x.internalName,x])),nonStorable=new Set(['CURRENCY','DUNGEON_EVAPORATE','DUNGEON_FOOD','DUNGEON_ITEM','DUNGEON_KEY']),candidates=slab.obtainableItems.filter(x=>typeof x.typeGen==='string'&&!x.typeGen.startsWith('a')&&!nonStorable.has(x.type));
      const stackRow=item=>{const stacked=greenSet.has(item.internalName);return row(item.displayName,(item.sources?.sources||[]).map(s=>s.txtName).filter(Boolean).join(' · ')||'Source details unavailable',stacked?'Greenstacked':'Not greenstacked',item.internalName,{id:item.internalName,group:clean(item.type||item.typeGen||'Other'),status:stacked?'maxed':'missing',summary:`${candidates.filter(x=>greenSet.has(x.internalName)).length} / ${candidates.length} eligible items Greenstacked`});};
      out.slabGreenStacks=[...candidates.map(stackRow),...greenStacks.filter(id=>!byId.has(id)).map(id=>row(id,'Recorded in the save GreenStacks registry.','Greenstacked',id,{id,group:'Other',status:'maxed',summary:`${greenStacks.length} registered Greenstacks`}))];
      out.slabBonuses=(slab.bonuses||[]).map(x=>row(x.type,`+${fmt(x.bonus)}% ${x.type}`,'Active','Slab5'));}
    return out;
  }
  root.ProgressionModels={build,fmt};
})(typeof window!=='undefined'?window:globalThis);
