(function(root){'use strict';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clean=v=>String(v??'').replace(/<br\s*\/?\s*>/gi,' ').replace(/QUEST:/gi,'').replace(/\s+/g,' ').trim();
const worlds=['Blunder Hills','Yum-Yum Desert','Frostbite Tundra','Hyperion Nebula','Smolderin Plateau','Spirited Valley','The Rift'];
const worldId=name=>{const i=worlds.indexOf(name);return i<0?7:i;};
const keyOf=q=>String(q.QuestName||q.Name||'').replaceAll(' ','_');
function model(rawRoot={}){let system;try{system=root.BeanValueEngine?.systems?.(rawRoot)?.get?.('quests');}catch{}if(!system)return[];const out=[];for(const [npc,record] of Object.entries(system.npcData||{})){const wid=worldId(record.data?.head?.world);for(const quest of Object.values(record.data?.quests||{})){const key=keyOf(quest),states=Object.values(system.playerData||{}).map(player=>Number(player?.[key]??-1)),complete=states.some(v=>v===1),started=states.some(v=>v===0);out.push({world:wid,npc,name:quest.Name||quest.QuestName||key,description:clean(quest.DialogueText),requirements:[...(quest.ItemReq||[]).map(x=>`${x.quantity} × ${x.item}`),...(quest.CustomArray||[]).map(x=>`${x.desc} ${x.finalV}`)],rewards:(quest.Rewards||[]).map(x=>`${x.quantity} × ${x.item}`),status:complete?'Complete':started?'In progress':'Not started'});}}
 return out.sort((a,b)=>a.npc.localeCompare(b.npc)||a.name.localeCompare(b.name));}
function render(host,rawRoot={}){const rows=model(rawRoot);let tab=0,filter='all';const paint=()=>{const list=rows.filter(x=>x.world===tab&&(filter==='all'||x.status===filter));const totals=rows.filter(x=>x.world===tab),done=totals.filter(x=>x.status==='Complete').length;host.innerHTML=`<div class="quest-hero"><div><p class="eyebrow">Misc · imported save</p><h2>Quests</h2><p>Quest status is combined across your characters: complete anywhere counts as complete.</p></div><strong>${done} / ${totals.length} complete</strong></div><nav class="skill-tabs quest-world-tabs">${[...worlds,'Other'].map((name,id)=>`<button class="skill-tab ${id===tab?'active':''}" data-quest-world="${id}">${id<7?`W${id+1}`:'Other'} · ${esc(name)}</button>`).join('')}</nav><nav class="skill-tabs quest-state-tabs"><button class="skill-tab ${filter==='all'?'active':''}" data-quest-filter="all">All</button><button class="skill-tab ${filter==='In progress'?'active':''}" data-quest-filter="In progress">In progress</button><button class="skill-tab ${filter==='Not started'?'active':''}" data-quest-filter="Not started">Not started</button><button class="skill-tab ${filter==='Complete'?'active':''}" data-quest-filter="Complete">Complete</button></nav><div class="quest-grid">${list.map(x=>`<article class="quest-${x.status.replaceAll(' ','-').toLowerCase()}"><span>${esc(x.status)} · ${esc(x.npc)}</span><h3>${esc(x.name)}</h3><p>${esc(x.description)}</p>${x.requirements.length?`<small><b>Requirements:</b> ${esc(x.requirements.join(' · '))}</small>`:''}${x.rewards.length?`<small><b>Rewards:</b> ${esc(x.rewards.join(' · '))}</small>`:''}</article>`).join('')||'<p class="collection-note">No quests match this tab or filter in the imported save.</p>'}</div>`;host.querySelectorAll('[data-quest-world]').forEach(b=>b.onclick=()=>{tab=Number(b.dataset.questWorld);paint();});host.querySelectorAll('[data-quest-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.questFilter;paint();});};paint();}
const api={model,render};if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.QuestsPage=api;})(typeof window!=='undefined'?window:globalThis);
