(function(root){'use strict';
const parse=v=>{if(typeof v==='string'){try{return JSON.parse(v);}catch{return v;}}return v;},num=v=>Number.isFinite(Number(v))?Number(v):0,pretty=v=>String(v??'').replaceAll('_',' ').replaceAll('@',' ').replaceAll('{','').replaceAll('}','').replace(/\s+/g,' ').trim(),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),fmt=v=>num(v).toLocaleString(undefined,{maximumFractionDigits:2,notation:Math.abs(num(v))>=1e6?'compact':'standard'});
const statueSources=['Carrotman','Xylobone','Crystal Carrot','Poop','Gigafrog','Monolith quest','Wood Mushroom','Crystal Carrot','Crystal Crabal','Crystal Crabal','Mashed Potato','Crabcake','Snelbie','Wood Mushroom','Wood Mushroom','Penguins','Quenchie','W3 Crystals','Cryosnake','Demon Genie','Choccie','Flombeige','Cheese Nub','Tremor Wurm','Biggole Mole','Woodlin Spirit','Leek Spirit','Skydoggie Spirit','Cavern 9','Cavern 15','Coral Cave Guardian','Coral Cave Guardian'];
const crystalWorlds=new Set([2,7,8,9,10,17]);
const statueGroups=[
 {title:'World 1 Statues',ids:[0,1,2,3,4,14],method:'Crystal farm at Frogs · Royal Guardian'},
 {title:'World 2 Statues',ids:[7,9,10,11,12,13,8],method:'Crystal farm at Sand Castles · Royal Guardian'},
 {title:'World 4 Statues',ids:[19,20,21],method:'Crystal farm at Clammies · Royal Guardian'},
 {title:'World 5 Statues',ids:[22,23,24],method:'Crystal farm at Tremor Wurms · Royal Guardian'},
 {title:'World 6 Statues',ids:[25,26,27],method:'Crystal farm at Minichief Spirits · Royal Guardian'},
 {title:'World 7 Statues',ids:[30,31],method:'AFK at Coral Cave Guardian · Clusters active at Frogs'},
 {title:'Other Statues',ids:[15,16,18,17,5,28,29],method:'Target the listed source'}
];
const statueValueBoosts=[['Voidwalker statue talent','Raises every statue bonus','assets/UISkillIcon112.png'],['Onyx statues','Doubles that statue','assets/EquipmentStatues1.png'],['Hole — Cavern 15','Adds a large statue-value bonus','assets/EquipmentStatues30.png'],['Seasonal event bonus','Multiplies statue value when owned','assets/EquipmentStatues6.png'],['World 5 Sailing','Adds statue-value doubling','assets/SailT31.png'],['World 7 Zenith Market','Raises statue value','assets/EquipmentStatues31.png'],['Zenith statue tier','Adds another tier multiplier','assets/EquipmentStatues32.png']];
const statueDropBoosts=[['Light Cyan palette','Chance for double statues',null],['Parallel Statues','Arcane Cultist upgrade','assets/EquipmentStatues1.png'],['Grey Hardhat','Spelunking upgrade','assets/Spelunking6.png'],['Yellow 6','World 7 Legend bonus','assets/UISkillIcon112.png'],['Statue Metallurgy','Star talent','assets/UISkillIcon647.png'],['Autumn Breeze','Gem-shop account bonus','assets/EquipmentStatues6.png'],['Kruk Minor link','Extra statue drops','assets/ObolKruk.png']];
const otherStatueMeta={15:['W3','Elemental Sorcerer'],16:['W3','Elemental Sorcerer'],18:['W3','Elemental Sorcerer'],17:['W3','Royal Guardian'],5:['W4','No class'],28:['Hole / W5','AFK'],29:['Hole / W5','AFK']};
function statueBoostStatus(data,account={}){const out={},set=(name,state,detail='')=>out[name]={state,detail};const unknown=['Onyx statues','Hole — Cavern 15','Seasonal event bonus','World 7 Zenith Market','Zenith statue tier','Light Cyan palette','Parallel Statues','Yellow 6','Autumn Breeze','Kruk Minor link'];unknown.forEach(x=>set(x,'unknown','Save field not decoded yet'));const chars=root.CharacterTalents?.model?.(data,account,root.TALENT_CATALOG)||[];if(chars.length){const all=chars.flatMap(c=>c.loadouts.flat());const statue=all.filter(x=>/statue/i.test(x.name)&&!/metallurgy/i.test(x.name)),metallurgy=all.filter(x=>/statue metallurgy/i.test(x.name));set('Voidwalker statue talent',statue.length?'owned':'missing',statue.length?`Lv ${Math.max(...statue.map(x=>x.level))}`:'No active level found');set('Statue Metallurgy',metallurgy.length?'owned':'missing',metallurgy.length?`Lv ${Math.max(...metallurgy.map(x=>x.level))}`:'No active level found');}else{set('Voidwalker statue talent','unknown','Talent data unavailable');set('Statue Metallurgy','unknown','Talent data unavailable');}const spelunk=root.World7?.spelunk?.(data,root.WORLD7_CATALOG);if(spelunk?.available){const hardhat=spelunk.upgrades.find(x=>x.name==='Grey Hardhat');set('Grey Hardhat',hardhat?.level>0?'owned':'missing',hardhat?`Lv ${hardhat.level}`:'Upgrade not found');}else set('Grey Hardhat','unknown','Spelunking data unavailable');const sailing=root.World5?.decodeSailing?.(data,root.WORLD5_CATALOG);if(sailing?.available){const lantern=sailing.artifacts.find(x=>/Onyx Lantern/i.test(x.name));set('World 5 Sailing',lantern?.tier>0?'owned':'missing',lantern?.tierName||'Artifact missing');}else set('World 5 Sailing','unknown','Sailing data unavailable');return out;}
function statues(data,account={},c=root.REMAINING_CATALOG){const ids=Object.keys(data).filter(k=>/^StatueLevels_\d+$/.test(k)).map(k=>num(k.split('_')[1])).sort((a,b)=>a-b),levels=parse(data['StatueLevels_'+(ids[0]??0)])||[];const rows=(c.StatueInfo||[]).map((r,i)=>({id:i,name:pretty(r[0]),effect:pretty(r[1]),level:num(levels[i]?.[0]),progress:num(levels[i]?.[1]),rate:num(r[3]),world:num(r[4])+1,bonus:num(levels[i]?.[0])*num(r[3]),icon:`assets/EquipmentStatues${i+1}.png`,source:statueSources[i]||'Special source',method:crystalWorlds.has(i)?'Crystal mob':'Direct drop'}));return{available:ids.length>0,rows,boostStatus:statueBoostStatus(data,account)};}
function statueFarmView(m,mode){const source=`<footer class="rw-source-credit">Reference: <a href="https://docs.google.com/spreadsheets/d/1IcxwlHKPcw57PJxOWmtCJTP2Iv6ubdRSEwzMjbH476U/edit?gid=510141304#gid=510141304" target="_blank" rel="noopener noreferrer">Antho &amp; Arkh’s spreadsheet</a></footer>`;const boost=(title,rows)=>`<section class="rw-boost-card"><h3>${title}</h3>${rows.map(x=>{const s=m.boostStatus[x[0]]||{state:'unknown',detail:''},label=s.state==='owned'?'Owned':s.state==='missing'?'Not owned':'Check in game';return`<div title="${esc(x[1])}">${x[2]?`<img src="${x[2]}" onerror="this.hidden=true" alt="">`:'<i class="rw-palette-swatch"></i>'}<span class="rw-bonus-state ${s.state}">${label}</span><strong>${x[0]}</strong><small>${esc(s.state==='unknown'?x[1]:s.detail||x[1])}</small></div>`;}).join('')}</section>`;const groups=statueGroups.map(g=>{const other=g.title==='Other Statues',rows=g.ids.map(id=>m.rows[id]).filter(Boolean);return`<section class="rw-world-card${other?' rw-world-other':''}"><header><strong>${g.title}</strong><span>${esc(g.method)}</span></header><div class="rw-world-rows">${rows.map(x=>{const meta=other?otherStatueMeta[x.id]:null;return`<div><img src="${x.icon}" onerror="this.hidden=true" alt=""><span><b>${esc(x.name)}</b><small>${esc(x.effect)}</small>${other?`<em>${esc(meta?.[0]||'')} · ${esc(meta?.[1]||'')} · ${esc(x.source)}</em>`:''}</span></div>`;}).join('')}</div></section>`;}).join('');return`<div class="rw-worlds">${groups}</div><div class="rw-boosts">${boost('Increase Statue Value',statueValueBoosts)}${boost('Get More Statue Drops',statueDropBoosts)}</div>${source}`;}
function dungeons(data,c=root.REMAINING_CATALOG){const d=parse(data.DungUpg)||[],levels=d[0]||[],formula=(r,l)=>r[3]==='add'?num(r[1])*l:num(r[1])*l/(l+num(r[2])||1);const passives=[...(c.DungPassiveStats||[]),...(c.DungPassiveStats2||[])].map((r,id)=>({id,name:pretty(r[0]),level:num(levels[id]),bonus:formula(r,num(levels[id])),unit:r[4]==='%'?'%':'',icon:`assets/DungPassive${id}.png`}));const shop=(c.DungFlurboShop||[]).map((r,id)=>({id,name:pretty(r[3]),description:pretty(r[4]),cost:num(r[1]),owned:num(d[2]?.[id])>0,icon:`assets/${r[0]}.png`}));return{available:Array.isArray(d)&&d.length>0,passives,shop,rank:num(d[4]?.[0]),credits:num(d[4]?.[1]),flurbos:num(d[4]?.[2])};}
function obols(data,account={}){const ids=Object.keys(data).filter(k=>/^ObolEqO0_\d+$/.test(k)).map(k=>num(k.split('_')[1])).sort((a,b)=>a-b),boards=[{id:'family',name:'Family',items:parse(data.ObolEqO1)||[],map:parse(data.ObolEqMAPz1)||{}},...ids.map(id=>({id,name:account.charNames?.[id]||`Character ${id+1}`,items:parse(data['ObolEqO0_'+id])||[],map:parse(data['ObolEqMAP_'+id])||{}}))];boards.forEach(b=>{b.slots=b.items.map((name,id)=>({id,name,stats:b.map?.[id]||b.map?.[String(id)]||{},icon:name&&name!=='Blank'?`assets/${name}.png`:null})).filter(x=>x.name&&x.name!=='Blank');b.totals={};b.slots.forEach(x=>Object.entries(x.stats).forEach(([k,v])=>{if(typeof v==='number'&&!/DisplayType/.test(k))b.totals[k]=(b.totals[k]||0)+v;}));});return{available:boards.some(x=>x.slots.length),boards,fragments:num(data.CYObolFragments),inventory:num(parse(data.ObolInvOwn)?.reduce?.((a,b)=>a+num(b),0))};}
function prayers(data,account={},c=root.REMAINING_CATALOG){const ids=Object.keys(data).filter(k=>/^Prayers_\d+$/.test(k)).map(k=>num(k.split('_')[1])).sort((a,b)=>a-b),equipped=new Map;ids.forEach(id=>(parse(data['Prayers_'+id])||[]).filter(x=>num(x)>=0).forEach(x=>{const n=num(x);if(!equipped.has(n))equipped.set(n,[]);equipped.get(n).push(account.charNames?.[id]||`Character ${id+1}`);}));const rows=(c.PrayerInfo||[]).map((r,id)=>({id,name:pretty(r[0]),positive:pretty(r[1]),negative:pretty(r[2]),basePositive:num(r[3]),baseNegative:num(r[4]),soul:r[5],equipped:equipped.get(id)||[],icon:`assets/Prayer${id}.png`}));return{available:ids.length>0,rows};}
function refinery(data,c=root.REMAINING_CATALOG){const r=parse(data.Refinery)||[];return{available:Array.isArray(r)&&r.length>3,slots:(c.RefineryInfo||[]).map((x,id)=>({id,name:`Salt ${id+1}`,rank:num(r[id+3]?.[1]),cycle:num(r[id+3]?.[0]),auto:num(r[id+3]?.[3]),stored:num(r[2]?.[id]),inputs:x.slice(0,6).map((item,i)=>({item,qty:num(x[6+i])})).filter(x=>x.item!=='Blank'&&x.qty>0),output:x[12],icon:`assets/Refinery${id+1}.png`}))};}
function printer(data,account={}){const p=parse(data.Print)||[],extra=parse(data.PrinterXtra)||[],pairs=list=>{const out=[];for(let i=5;i+1<list.length;i+=2)if(list[i]&&list[i]!=='Blank'&&num(list[i+1])>0)out.push({item:list[i],rate:num(list[i+1]),icon:`assets/${list[i]}.png`});return out;};return{available:p.length>0,characters:Object.keys(data).filter(k=>/^Print_\d+$/.test(k)).map(k=>num(k.split('_')[1])).map(id=>({id,name:account.charNames?.[id]||`Character ${id+1}`,slots:pairs(parse(data['Print_'+id])||[])})),main:pairs(p),extra:pairs([0,0,0,0,0,...extra])};}
function hole(data,c=root.REMAINING_CATALOG){const h=parse(data.Holes)||[],levels=h[0]||[],villagerNames=['Explorer','Engineer','Conjuror','Measurer','Librarian','Elder'];const villagers=villagerNames.map((name,id)=>({id,name,level:num(levels[id]),exp:num(h[1]?.[id]),resource:num(h[2]?.[id])}));const buildings=(c.HolesBuildings||[]).map((r,id)=>({id,name:pretty(r[0]),description:pretty(r[5]),owned:num(h[7]?.[id])>0,level:num(h[7]?.[id])}));return{available:Array.isArray(h)&&h.length>0,villagers,buildings};}
let selection={statuesTab:'levels',obols:0};function render(host,kind,data,account={}){const c=root.REMAINING_CATALOG,m=kind==='statues'?statues(data,account,c):kind==='dungeons'?dungeons(data,c):kind==='obols'?obols(data,account):kind==='prayers'?prayers(data,account,c):kind==='refinery'?refinery(data,c):kind==='printer'?printer(data,account):hole(data,c);let body='',summary='';
if(kind==='statues'){summary=`${m.rows.filter(x=>x.level>0).length} / ${m.rows.length} active`;const tabs=`<nav class="skill-tabs"><button class="skill-tab ${selection.statuesTab==='levels'?'active':''}" data-statue-tab="levels">Your Statues</button><button class="skill-tab ${selection.statuesTab==='farm'?'active':''}" data-statue-tab="farm">Where to Farm</button></nav>`;if(selection.statuesTab==='farm'){body=`${tabs}${statueFarmView(m,'active')}`;}else body=`${tabs}${grid(m.rows,x=>`<img src="${x.icon}" onerror="this.hidden=true" alt=""><span>Lv ${fmt(x.level)} · ${fmt(x.progress)} deposited</span><strong>${esc(x.name)}</strong><small>+${fmt(x.bonus)} ${esc(x.effect)}</small>`)}`;}
else if(kind==='dungeons'){summary=`Rank ${fmt(m.rank)} · ${fmt(m.flurbos)} Flurbos`;body=`<nav class="skill-tabs"><button class="skill-tab active">Passive Bonuses</button></nav>${grid(m.passives,x=>`<img src="${x.icon}" onerror="this.hidden=true" alt=""><span>Lv ${fmt(x.level)}</span><strong>${esc(x.name)}</strong><small>+${fmt(x.bonus)}${x.unit}</small>`)}`;}
else if(kind==='obols'){const b=m.boards[selection.obols]||m.boards[0];summary=`${fmt(m.inventory)} inventory · ${fmt(m.fragments)} fragments`;body=`<label class="rw-select">Board <select id="rwSelect">${m.boards.map((x,i)=>`<option value="${i}" ${i===selection.obols?'selected':''}>${esc(x.name)}</option>`).join('')}</select></label><div class="rw-totals">${Object.entries(b?.totals||{}).map(([k,v])=>`<span>${esc(pretty(k))} <b>+${fmt(v)}</b></span>`).join('')}</div>${grid(b?.slots||[],x=>`<img src="${x.icon}" onerror="this.hidden=true" alt=""><strong>${esc(pretty(x.name))}</strong><small>${Object.entries(x.stats).filter(([,v])=>typeof v==='number').map(([k,v])=>`${pretty(k)} +${fmt(v)}`).join(' · ')}</small>`)}`;}
else if(kind==='prayers'){summary=`${m.rows.filter(x=>x.equipped.length).length} equipped account-wide`;body=grid(m.rows,x=>`<img src="${x.icon}" onerror="this.hidden=true" alt=""><span>${x.equipped.length?`Equipped: ${esc(x.equipped.join(', '))}`:'Not equipped'}</span><strong>${esc(x.name)}</strong><small>${esc(x.positive)} · Tradeoff: ${esc(x.negative)}</small>`);}
else if(kind==='refinery'){summary=`${m.slots.filter(x=>x.rank).length} salts active`;body=grid(m.slots,x=>`<img src="${x.icon}" onerror="this.hidden=true" alt=""><span>Rank ${fmt(x.rank)} · ${fmt(x.stored)} stored</span><strong>${esc(pretty(x.output))}</strong><small>${x.inputs.map(i=>`${fmt(i.qty)} ${pretty(i.item)}`).join(' · ')}</small>`);}
else if(kind==='printer'){summary=`${m.main.length+m.extra.length} active samples`;body=`<h3>Account printer slots</h3>${grid([...m.main,...m.extra],x=>`<img src="${x.icon}" onerror="this.hidden=true" alt=""><strong>${esc(pretty(x.item))}</strong><small>${fmt(x.rate)} / hr</small>`)}`;}
else{summary=`${m.villagers.filter(x=>x.level).length} villagers active`;body=`<div class="rw-villagers">${m.villagers.map(x=>`<article><span>Lv ${fmt(x.level)}</span><strong>${x.name}</strong><small>${fmt(x.exp)} EXP · ${fmt(x.resource)} resource</small></article>`).join('')}</div><h3>Schematics & permanent buildings</h3>${grid(m.buildings,x=>`<span>${x.owned?'Built':'Missing'}</span><strong>${esc(x.name)}</strong><small>${esc(x.description)}</small>`)}`;}
host.innerHTML=`<div class="section-head compact"><div><p class="eyebrow">${kind==='hole'?'World 5':kind==='dungeons'||kind==='statues'?'World 1':kind==='obols'?'World 2':'World 3'}</p><h2>${esc({statues:'Statues',dungeons:'Dungeons',obols:'Obols',prayers:'Prayers',refinery:'Refinery',printer:'3D Printer',hole:'The Hole'}[kind])}</h2></div><strong>${esc(summary)}</strong></div>${!m.available?'<p class="collection-note">The required save records were not found.</p>':''}${body}`;host.querySelector('#rwSelect')?.addEventListener('change',e=>{selection[kind]=num(e.target.value);render(host,kind,data,account);});host.querySelectorAll('[data-statue-tab]').forEach(btn=>btn.addEventListener('click',()=>{selection.statuesTab=btn.dataset.statueTab;render(host,kind,data,account);}));}
function grid(items,content){return`<div class="rw-grid">${items.map(x=>`<article>${content(x)}</article>`).join('')||'<p>No saved entries found.</p>'}</div>`;}
const api={statues,dungeons,obols,prayers,refinery,printer,hole,render};if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.RemainingWorlds=api;
})(typeof window!=='undefined'?window:globalThis);
