(function(root){'use strict';
const parse=v=>{if(typeof v==='string'){try{return JSON.parse(v);}catch{return v;}}return v;},num=v=>Number.isFinite(Number(v))?Number(v):0,pretty=v=>String(v??'').replaceAll('_',' ').replaceAll('@',' ').replaceAll('{','').replaceAll('}','').replace(/\s+/g,' ').trim(),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),fmt=v=>num(v).toLocaleString(undefined,{maximumFractionDigits:2,notation:Math.abs(num(v))>=1e6?'compact':'standard'});
const statueSources=['Carrotman','Xylobone','Crystal Carrot','Poop','Gigafrog','Monolith quest','Wood Mushroom','Crystal Carrot','Crystal Crabal','Crystal Crabal','Mashed Potato','Crabcake','Snelbie','Wood Mushroom','Wood Mushroom','Penguins','Quenchie','W3 Crystals','Cryosnake','Demon Genie','Choccie','Flombeige','Cheese Nub','Tremor Wurm','Biggole Mole','Woodlin Spirit','Leek Spirit','Skydoggie Spirit','Cavern 9','Cavern 15','Coral Cave Guardian','Coral Cave Guardian'];
const crystalWorlds=new Set([2,7,8,9,10,17]);
const statueGroups=[
 {title:'World 1 Statues',ids:[0,1,2,3,4,14],method:'Crystal farm at Frogs · Royal Guardian'},
 {title:'World 2 Statues',ids:[7,9,10,11,12,13,8],method:'Crystal farm at Sand Castles · Royal Guardian'},
 {title:'World 4 Statues',ids:[19,20,21],method:'Crystal farm at Clammies · Royal Guardian'},
 {title:'World 5 Statues',ids:[22,23,24],method:'Crystal farm at Tremor Wurms · Royal Guardian'},
 {title:'World 6 Statues',ids:[25,26,27],method:'Crystal farm at Minichief Spirits · Royal Guardian'},
 {title:'World 7 Statues',ids:[30,31],method:'AFK at Coral Cave Guardian · Clusters active at Frogs'},
 {title:'Other Statues',ids:[15,16,18,17,5,28,29],method:'Target the listed source'}
];
const statueValueBoosts=[['Voidwalker statue talent','Raises every statue bonus','assets/UISkillIcon112.png'],['Onyx statues','Doubles that statue','assets/EquipmentStatues1.png'],['Hole — Cavern 15','Adds a large statue-value bonus','assets/EquipmentStatues30.png'],['Seasonal event bonus','Multiplies statue value when owned','assets/EquipmentStatues6.png'],['World 5 Sailing','Adds statue-value doubling','assets/SailT31.png'],['World 7 Zenith Market','Raises statue value','assets/EquipmentStatues31.png'],['Zenith statue tier','Adds another tier multiplier','assets/EquipmentStatues32.png']];
const statueDropBoosts=[['Light Cyan palette','Chance for double statues',null],['Parallel Statues','Arcane Cultist upgrade','assets/EquipmentStatues1.png'],['Grey Hardhat','Spelunking upgrade','assets/Spelunking6.png'],['Yellow 6','World 7 Legend bonus','assets/UISkillIcon112.png'],['Statue Metallurgy','Star talent','assets/UISkillIcon647.png'],['Autumn Breeze','Gem-shop account bonus','assets/EquipmentStatues6.png'],['Kruk Minor link','Extra statue drops','assets/ObolKruk.png']];
const otherStatueMeta={15:['W3','Elemental Sorcerer'],16:['W3','Elemental Sorcerer'],18:['W3','Elemental Sorcerer'],17:['W3','Royal Guardian'],5:['W4','No class'],28:['Hole / W5','AFK'],29:['Hole / W5','AFK']};
const knownStatue=v=>v==null||v===''||typeof v==='boolean'||!Number.isFinite(Number(v))||Number(v)<0?null:Number(v);
const statueNumber=v=>v==null?'Unknown':fmt(v);
function statueBoostStatus(data,account={}){
 const out={},set=(name,state,detail='')=>out[name]={state,detail};
 [...statueValueBoosts,...statueDropBoosts].forEach(x=>set(x[0],'unknown','Effect not calculated from this export'));
 const grades=parse(data.StuG??data.StatueG);
 if(Array.isArray(grades))for(const [name,tier] of [['Onyx statues',2],['Zenith statue tier',3]]){const count=grades.filter(v=>knownStatue(v)!=null&&Number(v)>=tier).length,complete=(root.REMAINING_CATALOG?.StatueInfo||[]).every((_,i)=>knownStatue(grades[i])!=null);set(name,count?'owned':complete?'missing':'unknown',`${count} recorded at this tier or higher; applies per statue`);}
 const chars=root.CharacterTalents?.model?.(data,account,root.TALENT_CATALOG)||[];
 if(chars.length){const active=chars.flatMap(c=>c.loadouts[c.active]||[]),complete=chars.every(c=>parse(data['SL_'+c.id])!=null);for(const [name,re] of [['Voidwalker statue talent',/voodoo statufication/i],['Statue Metallurgy',/statue metallurgy/i]]){const found=active.filter(x=>re.test(x.name));set(name,found.length?'owned':complete?'missing':'unknown',found.length?`Lv ${Math.max(...found.map(x=>x.level))} in a saved active preset; character conditions still apply`:'No level recorded in saved active presets');}}
 const spelunk=parse(data.Spelunk),hardhat=root.WORLD7_CATALOG?.SpelunkUpg?.findIndex(x=>x[0]==='Grey_Hardhat');
 if(hardhat>=0){const level=knownStatue(parse(spelunk?.[5])?.[hardhat]);if(level!=null)set('Grey Hardhat',level>0?'owned':'missing',`Lv ${fmt(level)}`);}
 const artifact=root.WORLD5_CATALOG?.ArtifactInfo?.findIndex(x=>/Onyx_Lantern/i.test(x[0]));
 if(artifact>=0){const level=knownStatue(parse(parse(data.Sailing)?.[3])?.[artifact]);if(level!=null)set('World 5 Sailing',level>0?'owned':'missing',`Artifact tier ${fmt(level)}`);}
 return out;
}
function statues(data,account={},c=root.REMAINING_CATALOG,characterId=null){
 const ids=Object.keys(data).filter(k=>/^StatueLevels_\d+$/.test(k)).map(k=>num(k.split('_')[1])).sort((a,b)=>a-b),id=ids.includes(Number(characterId))&&characterId!=null?Number(characterId):ids[0],levels=parse(data['StatueLevels_'+id]),grades=parse(data.StuG??data.StatueG)||[];
 const rows=(c.StatueInfo||[]).map((r,i)=>{const saved=parse(levels?.[i]),level=knownStatue(saved?.[0]),grade=knownStatue(grades[i]);return{id:i,name:pretty(r[0]),effect:pretty(r[1]),level,progress:knownStatue(saved?.[1]),grade,tier:grade==null?'Tier unknown':['Normal','Gold','Onyx','Zenith'][Math.min(3,grade)]||'Tier unknown',rate:num(r[3]),world:num(r[4])+1,bonus:level==null?null:level*num(r[3]),icon:`assets/EquipmentStatues${i+1}.png`,source:statueSources[i]||'Special source',method:crystalWorlds.has(i)?'Crystal mob':'Direct drop'};});
 return{available:Array.isArray(levels),characterId:id,characterName:account.charNames?.[id]||`Character ${(id??0)+1}`,characters:ids.map(id=>({id,name:account.charNames?.[id]||`Character ${id+1}`})),rows,boostStatus:statueBoostStatus(data,account)};
}
function statueFarmView(m,mode){const source=`<footer class="rw-source-credit">Reference: <a href="https://docs.google.com/spreadsheets/d/1IcxwlHKPcw57PJxOWmtCJTP2Iv6ubdRSEwzMjbH476U/edit?gid=510141304#gid=510141304" target="_blank" rel="noopener noreferrer">Antho &amp; Arkh’s spreadsheet</a></footer>`;const boost=(title,rows)=>`<section class="rw-boost-card"><h3>${title}</h3>${rows.map(x=>{const s=m.boostStatus[x[0]]||{state:'unknown',detail:''},label=s.state==='owned'?'Owned':s.state==='missing'?'Not owned':'Check in game';return`<div title="${esc(x[1])}">${x[2]?`<img src="${x[2]}" onerror="this.hidden=true" alt="">`:'<i class="rw-palette-swatch"></i>'}<span class="rw-bonus-state ${s.state}">${label}</span><strong>${x[0]}</strong><small>${esc(s.detail||x[1])}</small></div>`;}).join('')}</section>`;const groups=statueGroups.map(g=>{const other=g.title==='Other Statues',rows=g.ids.map(id=>m.rows[id]).filter(Boolean);return`<section class="rw-world-card${other?' rw-world-other':''}"><header><strong>${g.title}</strong><span>${esc(g.method)}</span></header><div class="rw-world-rows">${rows.map(x=>{const meta=other?otherStatueMeta[x.id]:null;return`<div><img src="${x.icon}" onerror="this.hidden=true" alt=""><span><b>${esc(x.name)}</b><small>${esc(x.effect)}</small>${other?`<em>${esc(meta?.[0]||'')} · ${esc(meta?.[1]||'')} · ${esc(x.source)}</em>`:''}</span></div>`;}).join('')}</div></section>`;}).join('');return`<div class="rw-worlds">${groups}</div><div class="rw-boosts">${boost('Increase Statue Value',statueValueBoosts)}${boost('Get More Statue Drops',statueDropBoosts)}</div>${source}`;}
function dungeons(data,c=root.REMAINING_CATALOG){const d=parse(data.DungUpg)||[],levels=d[0]||[],formula=(r,l)=>r[3]==='add'?num(r[1])*l:num(r[1])*l/(l+num(r[2])||1);const passives=[...(c.DungPassiveStats||[]),...(c.DungPassiveStats2||[])].map((r,id)=>({id,name:pretty(r[0]),level:num(levels[id]),bonus:formula(r,num(levels[id])),unit:r[4]==='%'?'%':'',icon:`assets/DungPassive${id}.png`}));const shop=(c.DungFlurboShop||[]).map((r,id)=>({id,name:pretty(r[3]),description:pretty(r[4]),cost:num(r[1]),owned:num(d[2]?.[id])>0,icon:`assets/${r[0]}.png`}));return{available:Array.isArray(d)&&d.length>0,passives,shop,rank:num(d[4]?.[0]),credits:num(d[4]?.[1]),flurbos:num(d[4]?.[2])};}
function obols(data,account={}){const ids=Object.keys(data).filter(k=>/^ObolEqO0_\d+$/.test(k)).map(k=>num(k.split('_')[1])).sort((a,b)=>a-b),boards=[{id:'family',name:'Family',items:parse(data.ObolEqO1)||[],map:parse(data.ObolEqMAPz1)||{}},...ids.map(id=>({id,name:account.charNames?.[id]||`Character ${id+1}`,items:parse(data['ObolEqO0_'+id])||[],map:parse(data['ObolEqMAP_'+id])||{}}))];boards.forEach(b=>{b.slots=b.items.map((name,id)=>({id,name,stats:b.map?.[id]||b.map?.[String(id)]||{},icon:name&&name!=='Blank'?`assets/${name}.png`:null})).filter(x=>x.name&&x.name!=='Blank');b.totals={};b.slots.forEach(x=>Object.entries(x.stats).forEach(([k,v])=>{if(typeof v==='number'&&!/DisplayType/.test(k))b.totals[k]=(b.totals[k]||0)+v;}));});return{available:boards.some(x=>x.slots.length),boards,fragments:num(data.CYObolFragments),inventory:num(parse(data.ObolInvOwn)?.reduce?.((a,b)=>a+num(b),0))};}
function prayers(data,account={},c=root.REMAINING_CATALOG){const ids=Object.keys(data).filter(k=>/^Prayers_\d+$/.test(k)).map(k=>num(k.split('_')[1])).sort((a,b)=>a-b),equipped=new Map;ids.forEach(id=>(parse(data['Prayers_'+id])||[]).filter(x=>num(x)>=0).forEach(x=>{const n=num(x);if(!equipped.has(n))equipped.set(n,[]);equipped.get(n).push(account.charNames?.[id]||`Character ${id+1}`);}));const rows=(c.PrayerInfo||[]).map((r,id)=>({id,name:pretty(r[0]),positive:pretty(r[1]),negative:pretty(r[2]),basePositive:num(r[3]),baseNegative:num(r[4]),soul:r[5],equipped:equipped.get(id)||[],icon:`assets/Prayer${id}.png`}));return{available:ids.length>0,rows};}
function refinery(data,c=root.REMAINING_CATALOG){const r=parse(data.Refinery)||[];return{available:Array.isArray(r)&&r.length>3,slots:(c.RefineryInfo||[]).map((x,id)=>({id,name:`Salt ${id+1}`,rank:num(r[id+3]?.[1]),cycle:num(r[id+3]?.[0]),auto:num(r[id+3]?.[3]),stored:num(r[2]?.[id]),inputs:x.slice(0,6).map((item,i)=>({item,qty:num(x[6+i])})).filter(x=>x.item!=='Blank'&&x.qty>0),output:x[12],icon:`assets/Refinery${id+1}.png`}))};}
function printer(data,account={}){
 const p=parse(data.Print??data.Printer)||[],extra=parse(data.PrinterXtra)||[],characters=[];
 const pairs=(list,active=false)=>{const out=[];for(let i=0;i+1<list.length;i+=2)if(typeof list[i]==='string'&&list[i]!=='Blank'&&num(list[i+1])>0)out.push({item:list[i],name:root.ITEM_NAMES?.[list[i]]||'Unknown item',rate:num(list[i+1]),icon:`assets/${list[i]}.png`,active});return out;};
 for(let id=0;id<Math.ceil(Math.max(0,p.length-5)/14);id++){const block=p.slice(5+id*14,5+(id+1)*14);characters.push({id,name:account.charNames?.[id]||`Character ${id+1}`,slots:[...pairs(block.slice(0,10)),...pairs(extra.slice(id*10,(id+1)*10)),...pairs(block.slice(10,14),true)]});}
 return{available:p.length>5,characters,main:characters.flatMap(c=>c.slots.filter(s=>s.active)),extra:[]};
}
function hole(data,c=root.REMAINING_CATALOG){const h=parse(data.Holes)||[],levels=h[0]||[],villagerNames=['Explorer','Engineer','Conjuror','Measurer','Librarian','Elder'];const villagers=villagerNames.map((name,id)=>({id,name,level:num(levels[id]),exp:num(h[1]?.[id]),resource:num(h[2]?.[id])}));const buildings=(c.HolesBuildings||[]).map((r,id)=>({id,name:pretty(r[0]),description:pretty(r[5]),owned:num(h[7]?.[id])>0,level:num(h[7]?.[id])}));return{available:Array.isArray(h)&&h.length>0,villagers,buildings};}
function savedField(data,account,names){for(const source of [data,account,account?.data,account?.rawData,account?.account,account?.account?.data])for(const name of names)if(source?.[name]!=null)return parse(source[name]);return null;}
const coveNames=['Opal Find','Slop Drop','Reslime','Droplier','Killionaire','Insta-Ribbon','Big Hit Multikill','Active Drops','Sleepy Drops','One Big Blue','Blue Collector','Researchy','Droplier+','Sleepy Drops+','Cavernicus','Multikill','One Big Purp','Slop Drop+','Rich Get Rich','DeEmGe','Grandioso','Slop Drop++','Purp Collector','IDK Broh'];
const coveDescriptions=['Get +1 Opal to invest into Villagers.','Boost Drop Rate here in the Cove by {%.','Increase Crystal Glunko respawn rate by +{%.','Multiply Drop Rate here in the Cove by }x.','+{% Drop Rate here per power of 10 Crystal Glunko kills.','Get a Rank 15 Cooking Ribbon instantly.','Boost Multikill per Damage Tier here to {%.','Decrease the cost of all Cove upgrades by $%.','Boost AFK Gains rate here by +{%.','}x Drop Value for your selected blue shape.','+{% Drop Rate here per digit of Blue Shapes owned.','}x Research EXP gain outside this Cove.','Multiply Drop Rate here in the Cove by }x.','Boost AFK Gains rate here by +{%.','Earn }x more resources from all caverns.','Boost base Multikill here by +{%.','}x Drop Value for your selected purple shape.','Boost Drop Rate here by +{%.','Boost Drop Rate here by +{% per power of 10 normal Drop Rate.','Boost Total Damage for all characters by }x.','Boost Grand Discovery Chance in Spelunking by }x.','Boost Drop Rate here in Cavern 18 by {%.','+{% Drop Rate here per digit of Purple Shapes owned.','Future World 7 skill bonus.'];
const coveBase=[1,15,2,8,3,1,1,3,1,10,1,1,25,3,10,100,10,25,2,1,5,150,2,1];
function holeLate(data,kind,account={}){const h=savedField(data,account,['Holes'])||[],options=savedField(data,account,['OptionsListAccount','OptLacc'])||[],hasSave=Array.isArray(h)&&h.length>0,explorerLevel=num(h?.[0]?.[0]),unlocked=explorerLevel>=(kind==='holeCove'?18:17);if(kind==='holeCove'){const shapeNames=['Gooey Triangle','Gooey Square','Gooey Pentagon','Gooey Hexagon','Gooey Heptagon','Gooey Nonagon','Quartz Prismagon','Quartz Cubigon','Quartz Pointagon','Quartz Octagogon','Quartz Noragon','Quartz Brillagon'],shapeRows=shapeNames.map((name,id)=>({id,name,count:num(options[654+id]),icon:`assets/HoleGshape${id}.png`,description:`${name} collected from Crystal Glunko monsters.`})),upgrades=coveNames.map((name,id)=>{const level=num(options[630+id]),value=level*coveBase[id];return{id:12+id,name,level,value,count:level,icon:`assets/HoleGshape${id%12}.png`,description:coveDescriptions[id].replace('{',fmt(value)).replace('}',fmt(1+value/100)).replace('$',fmt(value))};});return{available:hasSave||options.length>0,unlocked,explorerLevel,shapes:[...shapeRows,...upgrades],shapeRows,upgrades,blueSelection:num(options[666]),purpleSelection:num(options[667])};}const depth=Math.max(0,num(options[602])-2);return{available:hasSave||options.length>0,unlocked,explorerLevel,depth,items:[{id:0,name:'Depth Casts',count:depth,icon:null,description:'Each depth cast lowers the resources needed to destroy other skilling caverns.'},{id:1,name:'Coin Synergy',count:depth,icon:null,description:`Fountain coin value: ${fmt(Math.pow(1.1,depth))}x from Trench depth.`},{id:2,name:'Trench Trickledown',count:depth,icon:null,description:`+${fmt(15*depth)}% All Skill Efficiency and +${fmt(10*depth)}% All Skill EXP from Trench depth.`}]};}
const floorInfo=[['The Well','Sediment buckets and permanent upgrades.','HoleCaveBG.png'],['The Motherlode','Mine layers for Opals and account bonuses.','HoleCaveBGb.png'],['The Dawg Den','Fight increasingly difficult monster waves.','HoleFightBarBG.png'],['Bravery Monument','Story combat and stacking rewards.','HoleBraveryBG.png'],['The Bell','Ring for Opals, improvements, and bonuses.','HoleBellBG.png'],['The Harp','Produce notes and unlock strings.','HoleHarpBG.png'],['The Lamp','Spend daily wishes on permanent upgrades.','HoleLampBG.png'],['The Hive','Catch through layers for Opals.','HoleCaveBGc.png'],['Gloomie Grotto','Defeat Gloomies and challenge the Monarch.','HoleShroomBG.png'],['Justice Monument','Judge cases for stacking rewards.','HoleJusticeBG.png'],['The Jars','Collect and enchant cavern collectibles.','HoleJarBG0.png'],['The Evertree','Chop layers for Opals and bonuses.','HoleCaveBGc.png'],['Wisdom Monument','Match cards through Wisdom stories.','HoleWisdomBG.png'],['The Gambit','Complete challenges for Gambit points.','HoleGambitBG.png'],['Sanctum Temple','Collect torches and earn Temple rewards.','HoleTempleBG.png'],['The Fountain','Stack coins, fill bars, and marbleize upgrades.','HoleFountainBG.png'],['Bottomless Trench','Cast down through increasing depths.','HoleCaveBGb.png'],['Crystal Glunko Cove','Farm shapes and improve Cove bonuses.','HoleCoveBG.png']];
function holeFloors(data,account={}){const h=savedField(data,account,['Holes'])||[],explorerLevel=num(h?.[0]?.[0]);return{available:Array.isArray(h)&&h.length>0,explorerLevel,floors:floorInfo.map((x,id)=>({id:id+1,name:x[0],description:x[1],icon:`assets/${x[2]}`,unlocked:explorerLevel>=id+1}))};}
let selection={statuesTab:'levels',obols:0};function render(host,kind,data,account={}){const c=root.REMAINING_CATALOG,m=kind==='statues'?statues(data,account,c,selection.statueCharacter):kind==='dungeons'?dungeons(data,c):kind==='obols'?obols(data,account):kind==='prayers'?prayers(data,account,c):kind==='refinery'?refinery(data,c):kind==='printer'?printer(data,account):kind==='holeFloors'?holeFloors(data,account):kind==='holeTrench'||kind==='holeCove'?holeLate(data,kind,account):hole(data,c);let body='',summary='';
if(kind==='statues'){
 summary=`${m.rows.filter(x=>x.level>0).length} leveled · ${m.rows.filter(x=>x.level==null).length} unknown`;
 const tabs=`<nav class="skill-tabs"><button class="skill-tab ${selection.statuesTab==='levels'?'active':''}" data-statue-tab="levels">Your Statues</button><button class="skill-tab ${selection.statuesTab==='farm'?'active':''}" data-statue-tab="farm">Where to Farm</button></nav>`;
 if(selection.statuesTab==='farm')body=`${tabs}${statueFarmView(m,'active')}`;
 else body=`${tabs}${m.characters.length?`<label>Character <select id="statueCharacter">${m.characters.map(x=>`<option value="${x.id}" ${x.id===m.characterId?'selected':''}>${esc(x.name)}</option>`).join('')}</select></label>`:''}<p class="collection-note">Base contributions for ${esc(m.characterName)}: saved level × base rate. These are not final character bonuses. Tier, talents, Dragon statue and other account multipliers are not included. Unknown means the export lacks that value.</p>${grid(m.rows,x=>`<img src="${x.icon}" onerror="this.hidden=true" alt=""><span>${x.level==null?'Saved level unknown':'Lv '+fmt(x.level)} · ${statueNumber(x.progress)} deposited · ${x.tier}</span><strong>${esc(x.name)}</strong><small>${x.bonus==null?'Base contribution unknown':`Base contribution: +${fmt(x.bonus)} ${esc(x.effect)}`}</small>`)}`;
}
else if(kind==='dungeons'){summary=`Rank ${fmt(m.rank)} · ${fmt(m.flurbos)} Flurbos`;body=`<nav class="skill-tabs"><button class="skill-tab active">Passive Bonuses</button></nav>${grid(m.passives,x=>`<img src="${x.icon}" onerror="this.hidden=true" alt=""><span>Lv ${fmt(x.level)}</span><strong>${esc(x.name)}</strong><small>+${fmt(x.bonus)}${x.unit}</small>`)}`;}
else if(kind==='obols'){const b=m.boards[selection.obols]||m.boards[0];summary=`${fmt(m.inventory)} inventory · ${fmt(m.fragments)} fragments`;body=`<label class="rw-select">Board <select id="rwSelect">${m.boards.map((x,i)=>`<option value="${i}" ${i===selection.obols?'selected':''}>${esc(x.name)}</option>`).join('')}</select></label><div class="rw-totals">${Object.entries(b?.totals||{}).map(([k,v])=>`<span>${esc(pretty(k))} <b>+${fmt(v)}</b></span>`).join('')}</div>${grid(b?.slots||[],x=>`<img src="${x.icon}" onerror="this.hidden=true" alt=""><strong>${esc(pretty(x.name))}</strong><small>${Object.entries(x.stats).filter(([,v])=>typeof v==='number').map(([k,v])=>`${pretty(k)} +${fmt(v)}`).join(' · ')}</small>`)}`;}
else if(kind==='prayers'){summary=`${m.rows.filter(x=>x.equipped.length).length} equipped account-wide`;body=grid(m.rows,x=>`<img src="${x.icon}" onerror="this.hidden=true" alt=""><span>${x.equipped.length?`Equipped: ${esc(x.equipped.join(', '))}`:'Not equipped'}</span><strong>${esc(x.name)}</strong><small>${esc(x.positive)} · Tradeoff: ${esc(x.negative)}</small>`);}
else if(kind==='refinery'){summary=`${m.slots.filter(x=>x.rank).length} salts active`;body=grid(m.slots,x=>`<img src="${x.icon}" onerror="this.hidden=true" alt=""><span>Rank ${fmt(x.rank)} · ${fmt(x.stored)} stored</span><strong>${esc(pretty(x.output))}</strong><small>${x.inputs.map(i=>`${fmt(i.qty)} ${pretty(i.item)}`).join(' · ')}</small>`);}
else if(kind==='printer'){summary=`${m.main.length} active print slots`;body=`<p class="muted">Saved base sample amounts; final output multipliers are not included.</p>${m.characters.map(c=>`<section class="printer-character"><h3>${esc(c.name)}</h3>${grid(c.slots,x=>`<img src="${x.icon}" onerror="this.hidden=true" alt=""><strong>${esc(x.name)}</strong><small>${fmt(x.rate)} base / hr</small><span class="printer-slot-state">${x.active?'Printing':'Stored sample'}</span>`)}</section>`).join('')}`;}
else if(kind==='holeFloors'){summary=`${Math.min(18,m.explorerLevel)} / 18 floors unlocked`;body=`<div class="hole-floor-path">${m.floors.map(x=>`<article class="hole-floor-card${x.unlocked?' unlocked':' locked'}"><div class="hole-floor-image"><img src="${x.icon}" onerror="this.hidden=true" alt=""></div><span>Floor ${String(x.id).padStart(2,'0')}</span><strong>${esc(x.name)}</strong><small>${x.unlocked?'Unlocked':`Requires Explorer Lv ${x.id}`}</small><p>${esc(x.description)}</p></article>`).join('')}</div>`;}
else if(kind==='holeCove'){const order=[0,2,4,6,8,10,1,3,5,7,9,11],panel=(title,offset,tone,shapeOffset)=>`<section class="cove-panel ${tone}"><header><h3>${title}</h3><span>${tone==='gooey'?'Crystal':'Jeweled'} upgrades</span></header><div class="cove-upgrade-grid">${order.map(id=>{const x=m.upgrades[offset+id];return`<button type="button" class="cove-upgrade-card${x.level?'':' is-missing'}" data-hole-late="${x.id}"><span><strong>${esc(x.name)}</strong><small>Lv ${fmt(x.level)}</small></span><em>${esc(x.description)}</em></button>`;}).join('')}</div><div class="cove-shape-strip">${m.shapeRows.slice(shapeOffset,shapeOffset+6).map(x=>`<button type="button" data-hole-late="${x.id}"><img src="${x.icon}" alt=""><span><small>You have</small><strong>${fmt(x.count)}</strong></span></button>`).join('')}</div></section>`;summary=`${m.shapeRows.filter(x=>x.count>0).length} / ${m.shapeRows.length} shapes · ${m.upgrades.reduce((a,x)=>a+x.level,0)} upgrade levels`;body=`${!m.unlocked?`<p class="collection-note">Cavern 18 unlocks at Explorer Lv 18. Current Explorer level: ${fmt(m.explorerLevel)}.</p>`:''}<div class="cove-status"><span>Crystal Glunko Cove</span><strong>${fmt(m.shapeRows.reduce((a,x)=>a+x.count,0))} total shapes</strong></div>${panel('Gooey Upgrades',0,'gooey',0)}${panel('Quartz Upgrades',12,'quartz',6)}<section id="holeBonusDetail" class="exp-card upgrade-detail detail-dismissed" aria-live="polite"></section>`;}
else if(kind==='holeTrench'){summary=`Depth ${fmt(m.depth)}`;body=`${!m.unlocked?`<p class="collection-note">Cavern 17 unlocks at Explorer Lv 17. Current Explorer level: ${fmt(m.explorerLevel)}.</p>`:''}<div class="hole-bonus-grid">${m.items.map(x=>`<button type="button" class="hole-bonus-tile${m.unlocked?'':' is-missing'}" data-hole-late="${x.id}"><span class="hole-bonus-art fallback">↧</span><small>Depth ${fmt(m.depth)}</small><strong>${esc(x.name)}</strong></button>`).join('')}</div><section id="holeBonusDetail" class="exp-card upgrade-detail detail-dismissed" aria-live="polite"></section>`;}
else{const explorer=m.villagers[0];summary=`Explorer Lv ${fmt(explorer?.level)}`;body=`<div class="rw-villagers rw-explorer-card"><button type="button" id="explorerTile"><span class="rw-portrait"><img src="assets/HoleUIvillager0.png" alt=""></span><span>Lv ${fmt(explorer?.level)}</span><strong>Polonai · Explorer</strong><small>${fmt(explorer?.exp)} EXP · ${fmt(explorer?.resource)} resource</small></button></div><section id="explorerDetail" class="exp-card upgrade-detail detail-dismissed" aria-live="polite"></section>`;}
host.innerHTML=`<div class="section-head compact"><div><p class="eyebrow">${kind.startsWith('hole')?'World 5 · The Hole':kind==='dungeons'||kind==='statues'?'World 1':kind==='obols'?'World 2':'World 3'}</p><h2>${esc({statues:'Statues',dungeons:'Dungeons',obols:'Obols',prayers:'Prayers',refinery:'Refinery',printer:'3D Printer',hole:'Explore',holeTrench:'Bottomless Trench',holeCove:'Crystal Glunko Cove'}[kind])}</h2></div><strong>${esc(summary)}</strong></div>${!m.available?'<p class="collection-note">Saved data for this section is unavailable; unlock status cannot be determined.</p>':''}${body}`;host.querySelector('#statueCharacter')?.addEventListener('change',e=>{selection.statueCharacter=Number(e.target.value);render(host,kind,data,account);});host.querySelector('#rwSelect')?.addEventListener('change',e=>{selection[kind]=num(e.target.value);render(host,kind,data,account);});host.querySelectorAll('[data-statue-tab]').forEach(btn=>btn.addEventListener('click',()=>{selection.statuesTab=btn.dataset.statueTab;render(host,kind,data,account);}));if(kind==='hole'){const explorer=m.villagers[0],tile=host.querySelector('#explorerTile'),detail=host.querySelector('#explorerDetail');tile?.addEventListener('click',()=>{tile.classList.add('selected');detail.innerHTML=`<button type="button" class="secondary upgrade-close">Close</button><p class="eyebrow">Villagers · Explore</p><h3>Polonai, Explorer of the Hole</h3><p><strong>Level ${fmt(explorer?.level)}</strong></p><p class="exp-benefit">${fmt(explorer?.exp)} EXP · ${fmt(explorer?.resource)} resource</p><p>Explorer progress reveals new caverns and discoveries throughout The Hole.</p>`;detail.classList.remove('detail-dismissed');detail.querySelector('.upgrade-close').onclick=()=>{detail.classList.add('detail-dismissed');tile.classList.remove('selected');};});}if(kind==='holeTrench'||kind==='holeCove'){const detail=host.querySelector('#holeBonusDetail'),items=kind==='holeCove'?m.shapes:m.items;host.querySelectorAll('[data-hole-late]').forEach(tile=>tile.addEventListener('click',()=>{host.querySelectorAll('[data-hole-late]').forEach(x=>x.classList.remove('selected'));tile.classList.add('selected');const item=items[num(tile.dataset.holeLate)];detail.innerHTML=`<button type="button" class="secondary upgrade-close">Close</button><div class="hole-detail-head"><span class="hole-bonus-art${item.icon?'':' fallback'}">${item.icon?`<img src="${item.icon}" alt="">`:'↧'}</span><div><p class="eyebrow">The Hole · ${kind==='holeCove'?'Crystal Cove':'Trench'}</p><h3>${esc(item.name)}${kind==='holeCove'?' Shape':''}</h3></div></div><p><strong>${kind==='holeCove'?`${fmt(item.count)} owned`:m.available?'Unlocked':'Not reached'}</strong></p><p>${esc(item.description)}</p>`;detail.classList.remove('detail-dismissed');detail.querySelector('.upgrade-close').onclick=()=>{detail.classList.add('detail-dismissed');tile.classList.remove('selected');};}));}}
function grid(items,content){return`<div class="rw-grid">${items.map(x=>`<article>${content(x)}</article>`).join('')||'<p>No saved entries found.</p>'}</div>`;}
const api={statues,dungeons,obols,prayers,refinery,printer,hole,holeFloors,holeLate,render};if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.RemainingWorlds=api;
})(typeof window!=='undefined'?window:globalThis);
