(function(root){'use strict';
const parse=v=>{if(typeof v==='string')try{return JSON.parse(v);}catch{return [];}return v||[];},num=v=>Number.isFinite(Number(v))?Number(v):0,fmt=v=>num(v).toLocaleString(undefined,{maximumFractionDigits:2,notation:Math.abs(num(v))>=1e6?'compact':'standard'}),clean=v=>String(v??'').replaceAll('_',' ').replace(/[{}製千]/g,'').replaceAll('@',' ').replace(/\s+/g,' ').trim(),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const apply=(text,value)=>clean(text).replace(/[{}]/g,fmt(value)).replace('$',fmt(value)).replace('}x',`${fmt(value)}x`);
function model(rawRoot={}){const data=rawRoot?.data||rawRoot||{},catalog=root.ROYAL_ARMORY_CATALOG||{},royal=parse(data.RoyalG),maps=parse(data.RoyalMaps),levels=royal[2]||[],total=(catalog.upgrades||[]).reduce((s,x)=>s+num(levels[x.index]),0),slotMap=(catalog.slotToId||[]).map(num);
 const upgrades=(catalog.upgrades||[]).map(x=>{const level=num(levels[x.index]),bonus=level*num(x.bonusPerLevel),slot=slotMap.indexOf(x.index);return{id:x.index,slot,level,max:num(x.maxLevel),bonus,name:clean(x.name),description:apply(x.description,bonus),unlocked:total>=num(x.unlockTotalLevels)};});
 const outposts=maps.map((x,id)=>({id,data:x})).filter(x=>Array.isArray(x.data)&&x.data.length>=3).map(x=>({id:x.id,barracks:num(x.data[0]),logistics:num(x.data[1]),education:num(x.data[2]),tradeExp:num(x.data[3]),intelExp:num(x.data[4]),commandExp:num(x.data[5]),militaryExp:num(x.data[6]),purityExp:num(x.data[7]),connection1:num(x.data[8]),connection2:num(x.data[9]),mode:num(x.data[10]),units:String(x.data[11]??''),boosted:num(x.data[12])>0}));
 const resourceStorage=royal[1]||[],nodeLevels=royal[5]||[];const resources=(catalog.royalResources||[]).map(x=>({id:x.index,world:Math.floor(x.index/20)+1,grade:num(nodeLevels[x.index]),stored:num(resourceStorage[x.resourceIndex]),resourceIndex:num(x.resourceIndex),baseMax:num(x.baseMaxQuantity)}));
 const statueLevels=royal[0]||[];const statues=(catalog.royalStatueNames||[]).map((name,id)=>{const level=num(statueLevels[id]),base=num(catalog.royalStatueBase?.[id]),per=num(catalog.royalStatuePerLevel?.[id]),label=typeof name==='string'&&name.length>2?clean(name):`Royal Statue ${id+1}`;return{id,name:label,level,bonus:base+level*per};});
 const orbletLevels=royal[23]||[];const orblets=(catalog.orbletMarket||[]).map(x=>{const level=num(orbletLevels[x.index]),bonus=level*num(x.bonusPerLevel);return{id:x.index,name:clean(x.name),level,max:num(x.maxLevel),bonus,description:apply(x.description,bonus)};});
 return{available:royal.length>0,total,upgrades,outposts,resources,statues,orblets};}
function bonusRows(rawRoot={}){const m=model(rawRoot),row=(source,name,effect,level,status)=>({source,name,effect,level,status});return[
 ...m.upgrades.map(x=>row('Royal Armory',x.name,x.description,x.unlocked?`Shelf ${x.slot+1} · Lv ${x.level} / ${x.max}`:`Locked at ${x.level} / ${x.max}`,x.unlocked&&x.level?'active':'missing')),
 ...m.statues.map(x=>row('Royal Statues',x.name,`${fmt(x.bonus)} ${x.name}`,`Lv ${x.level}`,x.level?'active':'missing')),
 ...m.orblets.map(x=>row('Orblet Market',x.name,x.description,`Lv ${x.level} / ${x.max}`,x.level?'active':'missing'))
 ];}
let selected='armory';function render(host,rawRoot={}){const m=model(rawRoot),tabs=[['armory','Armory'],['outposts','Outposts'],['resources','Resources'],['statues','Royal Statues'],['orblets','Orblet Market']],card=(name,effect,level,missing=false)=>`<article class="${missing?'is-missing':''}"><span>${esc(level)}</span><h3>${esc(name)}</h3><p>${esc(effect)}</p></article>`;let body='';
 if(selected==='armory')body=m.upgrades.map(x=>card(x.name,x.description,x.unlocked?`Shelf ${x.slot+1} · Lv ${x.level} / ${x.max}`:`Locked · needs ${x.id}`,!x.unlocked||!x.level)).join('');
 if(selected==='outposts')body=m.outposts.map(x=>card(`Map ${x.id}`,`Barracks ${x.barracks} · Logistics ${x.logistics} · Education ${x.education} · ${['Resource Depot','Support Camp','Savage Stronghold'][x.mode]||`Mode ${x.mode}`}`,`${x.boosted?'Boosted · ':''}Ranks: ${x.tradeExp}/${x.intelExp}/${x.commandExp}/${x.militaryExp}/${x.purityExp}`)).join('');
 if(selected==='resources')body=m.resources.map(x=>card(`World ${x.world} · Node ${x.id%20+1}`,`Grade ${x.grade} · base capacity ${fmt(x.baseMax)}`,`${fmt(x.stored)} stored`,!x.grade)).join('');
 if(selected==='statues')body=m.statues.map(x=>card(x.name,`${fmt(x.bonus)} ${x.name}`,`Lv ${x.level}`,!x.level)).join('');
 if(selected==='orblets')body=m.orblets.map(x=>card(x.name,x.description,`Lv ${x.level} / ${x.max}`,!x.level)).join('');
 host.innerHTML=`<div class="bonus-system-hero"><div><p class="eyebrow">Masterclasses · Royal Guardian</p><h2>Royal Armory</h2><p>Armory, outposts, resources, Royal Statues, and Orblet Market decoded from RoyalG and RoyalMaps.</p></div><strong>${fmt(m.total)} total Armory levels</strong></div><nav class="skill-tabs">${tabs.map(([id,label])=>`<button class="skill-tab${selected===id?' active':''}" data-royal-tab="${id}">${label}</button>`).join('')}</nav>${!m.available?'<p>No Royal Guardian data was found in this export.</p>':`<div class="bonus-system-grid">${body||'<p>No entries were found for this section.</p>'}</div>`}`;host.querySelectorAll('[data-royal-tab]').forEach(b=>b.onclick=()=>{selected=b.dataset.royalTab;render(host,rawRoot);});}
const api={model,bonusRows,render};if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.RoyalArmory=api;})(typeof window!=='undefined'?window:globalThis);
