(function(root){
'use strict';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),fmt=v=>Number.isFinite(v)&&Math.abs(v)>=1e21?v.toExponential(2).replace('e+','E'):Number.isFinite(v)?v.toLocaleString('en-US',{maximumFractionDigits:2,notation:Math.abs(v)>=1e6?'compact':'standard'}):'Unavailable';
function projection(hourly,rate,sample){if(!Number.isFinite(hourly)||hourly<0||!Number.isFinite(rate)||rate<0||rate>90)return null;const value=Math.floor(hourly*rate/100),output=Number.isFinite(sample.freshMultiplier)?value*sample.freshMultiplier:null;return {value,output,oldOutput:sample.output,gain:output===null?null:output-sample.output};}
function render(host,raw){
 host.innerHTML='<section class="review-impact"><h3>Sampling</h3><p role="status">Reading samples and character sample rates…</p></section>';const marker=host.firstElementChild,worker=new Worker('sampling-worker.js');
 const timer=setTimeout(()=>{worker.terminate();if(host.firstElementChild===marker)marker.innerHTML='<p>Sampling calculation timed out.</p>';},60000);
 worker.onerror=()=>{clearTimeout(timer);worker.terminate();if(host.firstElementChild===marker)marker.innerHTML='<p>Sampling calculator could not load.</p>';};
 worker.onmessage=({data})=>{clearTimeout(timer);worker.terminate();if(host.firstElementChild!==marker)return;if(data.error){marker.textContent=data.error;return;}
  let selected=0,slot=0,hourly='';
  function paint(){const c=data.rows[selected],s=c?.samples[slot];
   marker.innerHTML=`<h3>Sampling &amp; resampling</h3><p>Compare a new sample against saved production, including the printer-age bonus lost when resampling.</p><div class="review-impact-controls"><label>Character <select data-sampling-character>${data.rows.map((r,i)=>`<option value="${i}" ${i===selected?'selected':''}>${esc(r.name)} · ${fmt(r.rate)}% sample rate</option>`).join('')}</select></label><label>Saved resource <select data-sampling-resource>${(c?.samples||[]).map((r,i)=>`<option value="${i}" ${i===slot?'selected':''}>${esc(r.name.replaceAll('_',' '))}${r.active?' · printing':''}</option>`).join('')}</select></label></div>${s?`<p>Saved sample: <b>${fmt(s.value)}</b> · Current slot output: <b>${fmt(s.output)}/hr</b></p><label>In-game AFK resource gains per hour, with your sampling loadout <input data-sampling-hourly type="number" min="0" step="any" value="${esc(hourly)}" placeholder="Enter the AFK screen value"></label><div data-sampling-result aria-live="polite"></div><p class="review-note">Uses the selected character's saved sample rate. Enter an AFK resource rate measured with that same setup. Estimates exclude temporary or skill-specific effects missing from the export. New output uses the current printer multipliers with the Legend Talent age bonus reset.</p>`:'<p>No stored samples for this character.</p>'}<details><summary>All saved samples</summary>${data.rows.map(r=>`<h4>${esc(r.name)}</h4>${r.samples.map(x=>`<p>${esc(x.name.replaceAll('_',' '))}: ${fmt(x.value)} → ${fmt(x.output)}/hr ${x.active?'· printing':''}</p>`).join('')}`).join('')}</details>`;
   marker.querySelector('[data-sampling-character]').onchange=e=>{selected=Number(e.target.value);slot=0;hourly='';paint();};marker.querySelector('[data-sampling-resource]').onchange=e=>{slot=Number(e.target.value);hourly='';paint();};
   const input=marker.querySelector('[data-sampling-hourly]');if(input)input.oninput=()=>{hourly=input.value;const p=hourly===''?null:projection(Number(hourly),c.rate,s);marker.querySelector('[data-sampling-result]').innerHTML=p?`<p>Estimated new sample: <b>${fmt(p.value)}</b></p><p>Fresh slot output: <b>${fmt(p.output)}/hr</b> (${p.gain>=0?'+':''}${fmt(p.gain)}/hr)</p><strong>${p.gain>0?'Resampling would increase this slot’s modeled output.':p.gain===null?'Fresh printer output is unavailable.':'Keep this sample for now: the modeled fresh output is no better.'}</strong>`:'';};
  }paint();
 };worker.postMessage(raw);
}
root.Sampling={render,projection};
})(typeof window==='undefined'?globalThis:window);
