(function(root){'use strict';
const M=root.SpelunkingOptimizer,esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),fmt=v=>Number(v).toLocaleString(undefined,{maximumFractionDigits:3,notation:Math.abs(v)>=1e9?'scientific':'standard'}),pct=v=>fmt(v*100)+'%';
let options={goal:'power',mode:'roadmap',steps:100,discount:1},compressed=false,signature='',done=[],undo=[];
const storage='idleon-spelunking-checklist-v1';
function render(host,raw){const saved=M.decode(raw,root.WORLD7_CATALOG.SpelunkUpg);if(!saved){host.innerHTML='<p>Import a save with Spelunking upgrade data to plan purchases.</p>';return;}
const sig=JSON.stringify(saved);if(signature!==sig){signature=sig;done=[];undo=[];options.discount=1;try{const old=JSON.parse(localStorage.getItem(storage));if(old?.signature===sig){done=old.done||[];undo=old.undo||[];}}catch{}}
const persist=()=>{try{localStorage.setItem(storage,JSON.stringify({signature,done,undo}));}catch{}};
const draw=()=>{const result=M.plan(saved,options),remaining=result.steps.filter(a=>!done.includes(a.key)),rows=[];for(const a of remaining){const last=rows.at(-1);if(compressed&&last?.i===a.i&&last.to===a.from&&last.order+last.keys.length===a.order){last.to=a.to;last.cost+=a.cost;last.gain=(1+last.gain)*(1+a.gain)-1;last.shortfall+=a.shortfall;last.future ||= a.future;last.keys.push(a.key);}else rows.push({...a,keys:[a.key]});}
const available=saved.catalog.map((x,i)=>({x,i})).filter(({x,i})=>saved.levels[i]>=0&&saved.levels[i]<Number(x[3]));
host.innerHTML=`<section class="fountain-page"><h3>Spelunking upgrade optimizer</h3><p>${fmt(saved.amber)} Amber saved · ${fmt(saved.skill)} total Spelunking levels</p><form class="fountain-controls"><label>Goal <select name="goal"><option value="power" ${options.goal==='power'?'selected':''}>Spelunking POW</option><option value="amber" ${options.goal==='amber'?'selected':''}>Amber amount per drop</option></select></label><label>Plan <select name="mode"><option value="roadmap" ${options.mode==='roadmap'?'selected':''}>Long-term roadmap</option><option value="now" ${options.mode==='now'?'selected':''}>Buy now</option></select></label><label>Purchases <select name="steps">${[20,50,100,250,500].map(n=>`<option ${n===options.steps?'selected':''}>${n}</option>`).join('')}</select></label><label><input type="checkbox" data-compress ${compressed?'checked':''}> Compress consecutive upgrades</label></form>
<details><summary>Match your in-game upgrade costs</summary><p>Select an available upgrade and enter its exact next-level Amber price. This calibrates the account discount for all purchases. Without calibration, costs use undiscounted base prices.</p><form data-calibrate class="fountain-controls"><label>Upgrade <select name="upgrade">${available.map(({x,i})=>`<option value="${i}">${esc(x[0].replaceAll('_',' '))} · Lv ${saved.levels[i]}</option>`).join('')}</select></label><label>Next price <input name="price" type="number" min="0" step="any" required aria-label="In-game next upgrade price"></label><button ${available.length?'':'disabled'}>Apply price</button><button type="button" data-base>Use base costs</button></form><p data-calibration-error role="status"></p></details>
<p class="fountain-note">${options.discount===1?'Base-cost estimate — calibrate above for your account discounts.':'Calibrated account cost multiplier: '+fmt(options.discount)+'.'} Gains compare shop bonuses with other account factors held fixed.</p>
<div class="fountain-plan-summary"><strong>+${pct(result.gain)} modeled ${options.goal==='amber'?'Amber amount':'POW'}</strong><span>${fmt(result.spent)} Amber total · ${fmt(result.funding)} additional Amber needed</span></div>
<div class="fountain-checklist"><span>${remaining.length} remaining of ${result.steps.length} purchases</span><button type="button" data-undo ${undo.length?'':'disabled'}>Undo last</button><button type="button" data-reset ${done.length?'':'disabled'}>Reset checklist</button></div>
<div class="fountain-plan"><table><thead><tr><th>Done</th><th>#</th><th>Buy in order</th><th>Level</th><th>Amber cost</th><th>Gain</th><th>Funding</th></tr></thead><tbody>${rows.map((a,j)=>`<tr class="${a.future?'fountain-future':''}"><td><button type="button" data-done="${j}" aria-label="Mark ${esc(saved.catalog[a.i][0].replaceAll('_',' '))} through level ${a.to} done">${a.keys.length>1?'Done all':'Done'}</button></td><td>${a.order}</td><td><img src="assets/CaveShopUpg${a.i}.png" alt="" width="36" height="36"> ${esc(saved.catalog[a.i][0].replaceAll('_',' '))}</td><td>${a.from} → ${a.to}</td><td>${fmt(a.cost)}</td><td>+${pct(a.gain)}</td><td>${a.shortfall?'Save '+fmt(a.shortfall)+' more':a.future?'After earlier steps':'Buy now'}</td></tr>`).join('')}</tbody></table>${rows.length?'':'<p>'+(result.steps.length?'All purchases checked off.':'No eligible purchases improve this goal within the selected budget.')+'</p>'}</div>
<details class="fountain-assumptions"><summary>Planning method and limits</summary><p>Each step chooses the largest relative gain per Amber, recalculating levels and costs. Affordable upgrades come first; roadmap steps then record additional funding. This greedy plan is not a globally optimal solution.</p><p>Locked and maxed upgrades are excluded. Discoveries, depths, character levels, grand discoveries, manic depths and Overstim stay at their saved values. POW assumes you have completed the Spelunking tutorial. Amber compares amount per drop, not Amber per hour: drop chance, supply swap, stamina, speed, future Overstim levels and unlock purchases are not optimized.</p><p>Checking Done only hides purchases; totals and funding still cover the entire imported-save plan. Import a fresh save to refresh balances and reset the checklist. Your save is never modified.</p></details></section>`;
host.querySelector('form').onsubmit=e=>e.preventDefault();host.querySelectorAll('form:first-of-type select').forEach(el=>el.onchange=()=>{options[el.name]=el.name==='steps'?Number(el.value):el.value;draw();});host.querySelector('[data-compress]').onchange=e=>{compressed=e.target.checked;draw();};
host.querySelector('[data-calibrate]').onsubmit=e=>{e.preventDefault();const f=e.currentTarget,value=M.calibration(saved,Number(f.elements.upgrade.value),Number(f.elements.price.value));if(!Number.isFinite(value)||value<=0||value>1){host.querySelector('[data-calibration-error]').textContent='Enter an exact price above the fixed level surcharge and no higher than the undiscounted cost.';return;}options.discount=value;draw();};host.querySelector('[data-base]').onclick=()=>{options.discount=1;draw();};
host.querySelectorAll('[data-done]').forEach(el=>el.onclick=()=>{const keys=rows[Number(el.dataset.done)].keys.filter(k=>!done.includes(k));done.push(...keys);undo.push(keys);persist();const scroll=host.querySelector('.fountain-plan').scrollTop;draw();host.querySelector('.fountain-plan').scrollTop=scroll;});host.querySelector('[data-undo]').onclick=()=>{const keys=undo.pop()||[];done=done.filter(k=>!keys.includes(k));persist();draw();};host.querySelector('[data-reset]').onclick=()=>{done=[];undo=[];persist();draw();};};draw();}
root.SpelunkingPage={render};
})(window);
