(function(root){'use strict';
const M=root.SpelunkingOptimizer,esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),fmt=v=>Number(v).toLocaleString(undefined,{maximumFractionDigits:3,notation:Math.abs(v)>=1e9?'scientific':'standard'}),pct=v=>(v>0&&v*100<.001?(v*100).toExponential(2):fmt(v*100))+'%';
let options={goal:'balanced',scope:'all',mode:'roadmap',steps:100,discount:1,amberHoard:true,hoardMode:'calculated',customHoard:0},compressed=false,signature='',done=[],undo=[];
const compact=v=>{if(!Number.isFinite(v))return '—';if(v!==0&&Math.abs(v)<.01)return v.toExponential(2);const units=['','K','M','B','T','Q'];const t=Math.max(0,Math.floor(Math.log10(Math.abs(v)||1)/3));return t>=units.length?v.toExponential(2):Number((v/1000**t).toPrecision(4)).toLocaleString('en-US',{maximumFractionDigits:3})+units[t];};
const effectText=e=>{const unit=['percent','chance','nova','retained'].includes(e.kind)?'%':'';return esc(e.label)+': '+fmt(e.before)+unit+' → '+fmt(e.after)+unit;};
const storage='idleon-spelunking-checklist-v1';
const hoardCache=new WeakMap();
function loadHoard(raw){
 if(hoardCache.has(raw))return hoardCache.get(raw);
 const promise=new Promise(resolve=>{
  if(!root.Worker){resolve({error:'Talent calculation requires browser worker support.'});return;}
  let worker;try{worker=new root.Worker('spelunking-hoard-worker.js');}catch(error){resolve({error:error.message});return;}
  worker.onmessage=e=>{worker.terminate();resolve(e.data);};
  worker.onerror=()=>{worker.terminate();resolve({error:'Could not calculate Amber Hoard from this save.'});};
  try{worker.postMessage(raw);}catch(error){worker.terminate();resolve({error:error.message});}
 });
 hoardCache.set(raw,promise);return promise;
}
async function render(host,raw){const saved=M.decode(raw,root.WORLD7_CATALOG.SpelunkUpg);if(!saved){host.innerHTML='<p>Import a save with Spelunking upgrade data to plan purchases.</p>';return;}
const request={};host.spelunkRequest=request;host.innerHTML='<p role="status">Calculating Royal Guardian Amber Hoard…</p>';
const hoardResult=await loadHoard(raw);if(!host.isConnected||host.spelunkRequest!==request)return;
saved.hoard=hoardResult.hoard||null;
const tier=M.amberTier(saved),money=v=>'<span class="spelunk-amber" style="color:'+tier.color+'" title="'+esc(v)+' Orange Amber">'+compact(v/tier.divisor)+' <small>'+tier.name+'</small></span>';
const sig=JSON.stringify(saved);if(signature!==sig){signature=sig;done=[];undo=[];options.discount=1;options.hoardMode='calculated';options.customHoard=100*(1-(saved.hoard?.multiplier??1));try{const old=JSON.parse(localStorage.getItem(storage));if(old?.signature===sig){done=old.done||[];undo=old.undo||[];}}catch{}}
const persist=()=>{try{localStorage.setItem(storage,JSON.stringify({signature,done,undo}));}catch{}};
const customPercent=()=>options.hoardMode==='custom'?options.customHoard:null;
const draw=()=>{const result=M.plan(saved,{...options,hoardCustomPercent:customPercent()}),remaining=result.steps.filter(a=>!done.includes(a.key)),rows=[],groups=new Map();
for(const a of remaining){
 const group=compressed?groups.get(a.i):null;
 if(group){
  group.to=a.to;group.cost+=a.cost;group.gain=(1+group.gain)*(1+a.gain)-1;
  group.powerGain=(1+group.powerGain)*(1+a.powerGain)-1;group.amberGain=(1+group.amberGain)*(1+a.amberGain)-1;
  for(const effect of a.effects){const existing=group.effects.find(e=>e.i===effect.i);if(existing){existing.after=effect.after;existing.delta+=effect.after-effect.before;}else group.effects.push({...effect,delta:effect.after-effect.before});}
  group.shortfall+=a.shortfall;group.future ||= a.future;group.readyCount+=a.future?0:1;group.futureCount+=a.future?1:0;group.keys.push(a.key);
 }else{
  const row={...a,effects:a.effects.map(e=>({...e,delta:e.after-e.before})),keys:[a.key],readyCount:a.future?0:1,futureCount:a.future?1:0};rows.push(row);groups.set(a.i,row);
 }
}
const available=saved.catalog.map((x,i)=>({x,i})).filter(({x,i})=>saved.levels[i]>=0&&saved.levels[i]<Number(x[3]));
host.innerHTML=`<section class="fountain-page spelunk-page"><h3>Spelunking upgrade optimizer</h3><p>${money(saved.amber)} Amber saved · ${fmt(saved.skill)} total Spelunking levels</p><form class="fountain-controls"><label>Goal <select name="goal"><option value="balanced" ${options.goal==='balanced'?'selected':''}>Amber + POW · balanced</option><option value="power" ${options.goal==='power'?'selected':''}>Spelunking POW</option><option value="amber" ${options.goal==='amber'?'selected':''}>Amber amount per drop</option><option value="outside" ${options.goal==='outside'?'selected':''}>Outside / misc bonuses</option></select></label>${options.goal==='outside'?'<label>Bonuses <select name="scope">'+[['all','All outside / misc'],['account','Account bonuses · hardhats'],['utility','Spelunking utility']].map(([value,label])=>'<option value="'+value+'" '+(options.scope===value?'selected':'')+'>'+label+'</option>').join('')+'</select></label>':''}<label>Plan <select name="mode"><option value="roadmap" ${options.mode==='roadmap'?'selected':''}>Long-term roadmap</option><option value="now" ${options.mode==='now'?'selected':''}>Buy now</option></select></label><label>Purchases <select name="steps">${[20,50,100,250,500,1000,2500,5000].map(n=>`<option ${n===options.steps?'selected':''}>${n}</option>`).join('')}</select></label><label><input type="checkbox" data-hoard ${options.amberHoard?'checked':''} ${saved.hoard||options.hoardMode==='custom'?'':'disabled'}> Amber Hoard discount</label><label>Amber Hoard value <select name="hoardMode"><option value="calculated" ${options.hoardMode==='calculated'?'selected':''}>Calculated from save</option><option value="custom" ${options.hoardMode==='custom'?'selected':''}>Custom reduction %</option></select></label>${options.hoardMode==='custom'?`<label>Cost reduction % <input data-hoard-custom type="number" min="0" max="99.999999999" step="any" value="${options.customHoard}" aria-label="Custom Amber Hoard cost reduction percent" style="width:110px" ${options.amberHoard?'':'disabled'}></label>`:''}<label><input type="checkbox" data-compress ${compressed?'checked':''}> Compress upgrades</label></form>
${options.hoardMode==='custom'?'<p class="fountain-note" data-hoard-custom-status>Custom Amber Hoard: '+fmt(options.customHoard)+'% cost reduction'+(options.amberHoard?' applied.':' saved, currently OFF.')+' Enter the final cost reduction (50 means half price), not a talent level or the per-statue talent bonus. This replaces the calculated Amber Hoard value; the fixed level surcharge is unchanged.</p>':''}
<p class="fountain-note" data-hoard-status>${saved.hoard?`Calculated Amber Hoard ${options.hoardMode==='custom'?'(reference only)':options.amberHoard?'ON':'OFF'} · ${saved.hoard.talent?esc(saved.hoard.talent.character)+' · Talent Lv '+fmt(saved.hoard.talent.level)+' ('+fmt(saved.hoard.talent.baseLevel)+' allocated + '+fmt(saved.hoard.talent.addedLevels)+' bonus)':'No allocated Amber Hoard talent in saved active presets'} · ${fmt(saved.hoard.statueLevels)} Royal Statue levels · ${pct(1-saved.hoard.multiplier)} reduction to the discountable cost when enabled.`:'Amber Hoard unavailable: '+esc(hoardResult.error||'Missing talent data.')}</p>
<details><summary>Match your in-game upgrade costs</summary><p>Select an available upgrade and enter its exact next-level price in ${tier.name} Amber (enter the full number, without K/M suffixes). Set the Amber Hoard checkbox to match the in-game price you enter. Calibration separates that discount from other discounts, so toggling Amber Hoard never counts it twice. Without calibration, only the enabled Amber Hoard discount is applied.</p><form data-calibrate class="fountain-controls"><label>Upgrade <select name="upgrade">${available.map(({x,i})=>`<option value="${i}">${esc(x[0].replaceAll('_',' '))} · Lv ${saved.levels[i]}</option>`).join('')}</select></label><label>Next price (${tier.name}) <input name="price" type="number" min="0" step="any" required aria-label="In-game next upgrade price"></label><button ${available.length?'':'disabled'}>Apply price</button><button type="button" data-base>Reset other discounts</button></form><p data-calibration-error role="status"></p></details>
<p class="fountain-note" data-cost-status>${options.discount===1?'Other account discounts are not calibrated.':'Calibrated other-discount multiplier: '+fmt(options.discount)+'.'} Total applied cost multiplier: ${fmt(options.discount*M.hoardMultiplier(saved,options.amberHoard,customPercent()))}. Gains compare shop bonuses with other account factors held fixed.</p>
<div class="fountain-plan-summary"><strong><span class="spelunk-pow-gain">+${pct(result.powerGain)} POW</span> · <span style="color:${tier.color}">+${pct(result.amberGain)} Amber amount</span></strong><span>${money(result.spent)} Amber total · ${money(result.funding)} additional Amber needed</span></div>
<div class="fountain-checklist"><span>${remaining.length} remaining of ${result.steps.length} purchases${compressed?' · '+rows.length+' upgrade rows':''}</span><button type="button" data-undo ${undo.length?'':'disabled'}>Undo last</button><button type="button" data-reset ${done.length?'':'disabled'}>Reset checklist</button></div>
${compressed?'<p class="fountain-note" data-compression-note>Grouped totals by upgrade, not purchase order. Uncheck Compress upgrades to follow the recommended sequence. Gains are contributions from the original sequence; funded counts also assume that sequence. Done all checks off only the remaining purchases in that row.</p>':''}
<div class="fountain-plan"><table><thead><tr><th>Done</th><th>#</th><th>${compressed?'Upgrade totals':'Buy in order'}</th><th>Level</th><th>Amber cost</th><th>POW gain</th><th>Amber gain</th>${options.goal==='outside'?'<th>Outside / misc effect</th>':''}<th>Funding</th></tr></thead><tbody>${rows.map((a,j)=>`<tr class="${a.future?'fountain-future':''}"><td><button type="button" data-done="${j}" aria-label="Mark ${esc(saved.catalog[a.i][0].replaceAll('_',' '))} through level ${a.to} done">${a.keys.length>1?'Done all':'Done'}</button></td><td>${compressed?j+1:a.order}</td><td><img src="assets/CaveShopUpg${a.i}.png" alt="" width="36" height="36"> ${esc(saved.catalog[a.i][0].replaceAll('_',' '))}</td><td>${a.from} → ${a.to}${compressed?'<small>'+a.keys.length+' purchases'+(a.to-a.from>a.keys.length?' · '+(a.to-a.from-a.keys.length)+' already done in range':'')+'</small>':''}</td><td>${money(a.cost)}</td><td class="spelunk-pow-gain">${a.powerGain?'+ '+pct(a.powerGain):'—'}</td><td style="color:${tier.color}">${a.amberGain?'+ '+pct(a.amberGain):'—'}</td>${options.goal==='outside'?'<td>'+a.effects.map(e=>compressed?esc(e.label)+': +'+fmt(e.delta)+(['percent','chance','nova','retained'].includes(e.kind)?' percentage points':''):effectText(e)).join('<br>')+'</td>':''}<td>${compressed?a.readyCount+' in funded sequence · '+a.futureCount+' after saving'+(a.shortfall?'<small>Save '+money(a.shortfall)+' more</small>':''):a.shortfall?'Save '+money(a.shortfall)+' more':a.future?'After earlier steps':'Buy now'}</td></tr>`).join('')}</tbody></table>${rows.length?'':'<p>'+(result.steps.length?'All purchases checked off.':'No eligible purchases improve this goal within the selected budget.')+'</p>'}</div>
${options.goal==='outside'?'<details class="spelunk-effect-summary" open><summary>Outside / misc bonus changes</summary><div class="fountain-effect-grid">'+result.effects.map(e=>'<p>'+effectText(e)+'</p>').join('')+'</div></details>':''}
<p class="fountain-note">Amber prices use your saved ${tier.name} tier: 1 ${tier.name} = ${compact(tier.divisor)} Orange Amber. Hover a price for its raw Orange amount. The display tier stays fixed across the roadmap.</p>
<details class="fountain-assumptions"><summary>Planning method and limits</summary><p>Each step recalculates levels and costs. Amber + POW balances proportional improvements to both equally (geometric mean), then ranks gain per Amber. Single-goal modes prioritize only that goal; both gains are always shown. Affordable upgrades come first; roadmap steps then record additional funding. This greedy plan is not a globally optimal solution.</p><p>Outside / misc balances direct shop-source improvements per Amber: percentage bonuses use 1 + bonus/100, while counts use 1 + count. This is a utility heuristic, not a combined account gain. The effect column shows the actual source change; additive account bonuses and shared chance caps can reduce the final benefit. Unmodeled unlock-only and fragment-chance upgrades remain in the catalogue below.</p><p>Locked and maxed upgrades are excluded. Discoveries, depths, character levels, grand discoveries, manic depths and Overstim stay at their saved values. POW assumes you have completed the Spelunking tutorial. Amber compares amount per drop, not Amber per hour: drop chance, supply swap, stamina, speed, future Overstim levels and supply-swap purchases are not optimized. Amber assumes the first depth with no cleared-depth stacks.</p><p>Amber Hoard uses the strongest allocated talent across saved active presets, including capped Royal Guardian added levels and owner super talents. Added levels use the character most recently active in the save. Its multiplier is 1 / (1 + talent bonus × first eight Royal Statue levels / 100). The fixed level² + 5 × level surcharge is not discounted. Royal Statue levels and talents stay fixed through the plan.</p><p>Checking Done only hides purchases; totals and funding still cover the entire imported-save plan. Import a fresh save to refresh balances and reset the checklist. Your save is never modified.</p></details></section>`;
host.querySelector('form').onsubmit=e=>e.preventDefault();host.querySelectorAll('form:first-of-type select').forEach(el=>el.onchange=()=>{options[el.name]=el.name==='steps'?Number(el.value):el.value;draw();});const customInput=host.querySelector('[data-hoard-custom]');if(customInput)customInput.onchange=()=>{const value=Number(customInput.value);if(customInput.value===''||!Number.isFinite(value)||value<0||value>=100){customInput.setCustomValidity('Enter a cost reduction from 0% to less than 100%.');customInput.reportValidity();return;}customInput.setCustomValidity('');options.customHoard=value;draw();};if(customInput)customInput.oninput=()=>customInput.setCustomValidity('');host.querySelector('[data-hoard]').onchange=e=>{options.amberHoard=e.target.checked;draw();};host.querySelector('[data-compress]').onchange=e=>{compressed=e.target.checked;draw();};
host.querySelector('[data-calibrate]').onsubmit=e=>{e.preventDefault();const f=e.currentTarget,value=M.calibration(saved,Number(f.elements.upgrade.value),Number(f.elements.price.value)*tier.divisor,options.amberHoard,customPercent());if(!Number.isFinite(value)||value<=0||value>1){host.querySelector('[data-calibration-error]').textContent='Enter an exact price above the fixed level surcharge and no higher than the cost with the selected Amber Hoard setting.';return;}options.discount=value;draw();};host.querySelector('[data-base]').onclick=()=>{options.discount=1;draw();};
host.querySelectorAll('[data-done]').forEach(el=>el.onclick=()=>{const keys=rows[Number(el.dataset.done)].keys.filter(k=>!done.includes(k));done.push(...keys);undo.push(keys);persist();const scroll=host.querySelector('.fountain-plan').scrollTop;draw();host.querySelector('.fountain-plan').scrollTop=scroll;});host.querySelector('[data-undo]').onclick=()=>{const keys=undo.pop()||[];done=done.filter(k=>!keys.includes(k));persist();draw();};host.querySelector('[data-reset]').onclick=()=>{done=[];undo=[];persist();draw();};};draw();}
root.SpelunkingPage={render};
})(window);
