(function(root){'use strict';
const M=root.SummoningOptimizer,fmt=M.format,esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const upgradeIcon=id=>'<img class="sum-upgrade-icon" src="assets/SumUpgIc'+id+'.png" alt="" loading="lazy">',essenceIcon=id=>'<img class="sum-essence-icon" src="assets/SummC'+(id+1)+'.png" alt="" loading="lazy">';
let settings={goal:'all',mode:'now',count:'100',percent:'100',color:'all',multiplier:'1',collapse:false};
function render(host,raw){const model=M.snapshot(raw);host.innerHTML=`<section class="mc-page summoning-planner"><header><p class="eyebrow">Summoning · Purchase planner</p><h3>Next Purchase Optimizer</h3><p>Choose a goal and plan your next essence upgrades.</p></header>${!model.available?'<p class="mc-empty">Import a save containing Summoning levels to build a purchase plan.</p>':`<div class="mc-wallet">${M.colors.map((color,id)=>`<div>${essenceIcon(id)}<span>${color} essence<strong>${fmt(model.balances[id])}</strong></span></div>`).join('')}</div><div class="mc-controls"><label>I want to boost<select name="sum-goal">${M.goals.map(([id,label])=>`<option value="${id}">${label}</option>`).join('')}</select></label><label>Purchases<select name="sum-mode"><option value="now">Affordable now</option><option value="future">Plan future purchases</option></select></label><label>Plan length<select name="sum-count"><option value="0">One level per upgrade</option>${[50,100,500,1000].map(n=>`<option value="${n}">Next ${n.toLocaleString()} purchases</option>`).join('')}</select></label><label>Spend essence<select name="sum-color"><option value="all">All colors</option>${M.colors.map((name,i)=>`<option value="${i}">${name}</option>`).join('')}</select></label><label>Use balance (%)<input name="sum-percent" type="number" min="0" max="100"></label><label class="mc-collapse-control"><input name="sum-collapse" type="checkbox"> Collapse repeat upgrades</label></div><details class="sum-assumptions"><summary>Estimated costs & planning rules</summary><p>Cheapest matching next level within each essence color, rotating between colors. Required unowned prerequisites are included. This is a purchase-order heuristic, not a simulation of battle wins or maximum stat gain.</p><p>Prices update after every purchase, including Cost Crashing, Cost Deflation, Sell Sell Sell, Cost Laundering, saved doublers and stone trials. External talent, Tesseract, Jelly and Sushi discounts and the talent boost to doublers are not decoded. Future plans assume no daily resets or new victories. The first Teal upgrade requires its saved Spelunking lore unlock.</p><label>External cost multiplier<input name="sum-multiplier" type="number" min="0.000000001" step="any"></label><p>Default 1 excludes outside discounts. To calibrate, divide an in-game next price by this planner’s price at multiplier 1. This fixed factor may become approximate if your doubler talent interacts with planned upgrades.</p></details><div class="mc-plan sum-plan" aria-live="polite"></div><details><summary>Upgrade costs & unlocks</summary><div class="mc-controls"><label>Find upgrades<input name="sum-search" type="search" placeholder="Search name or effect…"></label></div><div class="mc-grid sum-catalog"></div></details>`}</section>`;
 if(!model.available)return;
 for(const [key,value] of Object.entries(settings)){const input=host.querySelector(`[name="sum-${key}"]`);if(input){if(key==='collapse')input.checked=value;else input.value=value;input.onchange=update;if(input.type==='number')input.oninput=update;}}
 function update(){for(const key of Object.keys(settings)){const input=host.querySelector(`[name="sum-${key}"]`);settings[key]=key==='collapse'?input.checked:input.value;}const result=M.optimize(model,settings),rows=settings.collapse?M.collapse(result.steps):result.steps,future=settings.mode==='future';host.querySelector('.sum-plan').innerHTML=`<h4>${result.steps.length.toLocaleString()} ${future?'planned purchases':'purchases within estimated budget'}</h4><p class="mc-note">${settings.collapse?'Grouped totals are a summary; turn off collapse to follow purchase order.':'Follow the list in order; later prices include earlier planned discounts.'} Your imported save is unchanged.</p>${rows.length?`<ol>${rows.map(x=>`<li>${upgradeIcon(x.id)}<span class="mc-plan-description"><strong>${esc(x.name)}</strong><small>Lv ${fmt(x.level)} → ${fmt(x.endLevel)}${x.count?' · '+x.count+' purchases':''}${x.prerequisite?' · Required unlock':''}</small><small class="mc-plan-effect">${esc(x.before)} → ${esc(x.after)}</small></span><span class="mc-plan-price"><span class="mc-price-amount">${essenceIcon(x.color)}<strong>${fmt(x.cost)}</strong></span><small>${M.colors[x.color]} essence · estimated</small>${future?`<small class="${x.shortfall>0?'mc-shortfall':'mc-ready'}">${x.shortfall==null?'Saved balance unknown':x.shortfall>0?'Save '+fmt(x.shortfall)+' more for plan':'Within budget'}</small>`:''}</span></li>`).join('')}</ol>`:'<p>No purchases match this budget and goal. Try future purchases, another goal, or another essence color.</p>'}<details><summary>${future?'Total essence needed':'Estimated budget remaining'}</summary><p>${M.colors.map((name,i)=>`<span class="sum-budget-entry">${essenceIcon(i)}${name}: ${fmt((future?result.needed:result.remaining)[i])}</span>`).join(' · ')}</p></details>${result.locked.length?`<details><summary>${result.locked.length} matching upgrades initially locked</summary><p>Required unlocks are added when possible, using the selected essence colors.</p>${result.locked.map(u=>`<p class="sum-locked-entry">${upgradeIcon(u.id)}${esc(u.name)} · ${u.parent===u.id?'Requires Spelunking lore 5':u.parent>=0?'Requires '+esc(model.upgrades[u.parent]?.name||'unknown upgrade'):'Saved level or skill requirement unavailable'}</p>`).join('')}</details>`:''}`;catalogue();}
 function catalogue(){const query=host.querySelector('[name=sum-search]').value.toLowerCase();host.querySelector('.sum-catalog').innerHTML=model.upgrades.filter(u=>(u.name+' '+M.effect(model,u)).toLowerCase().includes(query)).map(u=>`<article class="mc-upgrade mc-upgrade-row"><div class="mc-row-art">${upgradeIcon(u.id)}</div><div class="mc-row-copy"><h3>${esc(u.name)}</h3><p>${esc(M.effect(model,u))}</p></div><div class="mc-row-status"><strong>LV ${fmt(model.levels[u.id])} / ${fmt(u.max)}</strong><small class="sum-catalog-price">${essenceIcon(u.color)}${model.levels[u.id]>=u.max?'MAX LV':!M.unlocked(model,u)?'Locked / unavailable':fmt(M.cost(model,u,Number(settings.multiplier)>0?Number(settings.multiplier):1))+' '+M.colors[u.color]+' essence'}</small></div></article>`).join('');}
 host.querySelector('[name=sum-search]').oninput=catalogue;update();
}
root.SummoningPage={render};
})(window);
