(function(root){
'use strict';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const D=typeof module!=='undefined'&&module.exports?require('./summoning-battle-data'):root.SummoningBattleData;
const colors=['White','Green','Yellow','Blue','Purple','Red','Cyan','Teal'];
const labels=['Total damage','Jade gain','Farming speed','Artifact find chance','Lab connection range','All essence gain','Sneaking EXP','Sigil speed','Farming EXP','Drop rate','Crop evolution chance','AFK gains','Skill EXP','Construction speed','Skill efficiency','Cooking speed','Gaming bits','Shiny EXP','All stats','Library maximum level','Stamp levels per day','Villager EXP','Ballot bonus','Class EXP','Equinox maximum level','Monument AFK progress','Meal bonuses','Spelunking power','Amber gain','World 7 bonus','World 7 bonus','Winner bonuses'];
function reward(x){if(x.rewardId===null)return 'No listed reward';const flat=[4,19,20,24].includes(x.rewardId);return `+${x.rewardValue}${flat?'':'%'} ${labels[x.rewardId]||'reward'}`;}
function battles(model){return model.enemies.filter(x=>x.battleName&&Object.hasOwn(D.normal,x.code)).map(x=>({...x,rewardText:reward(x)}));}
let view='remaining',query='';
function renderNormal(host,model){const rows=battles(model),known=model.available,won=rows.filter(x=>x.won).length;
 host.innerHTML=`<section class="summoning-battles"><div class="exp-card"><h3>Normal Pillars</h3><p>These are the named battles on the in-game Summoning board. Win a battle to earn its permanent bonus.</p><p><strong>${known?`${won} / ${rows.length} battles won`:'Import your save to see which battles you have won.'}</strong></p><small>Rewards below are base contributions, before winner-bonus boosts. They are not predictions of your final account stats. Unwon battles may still need earlier battles or colors unlocked.</small></div><div class="sum-battle-controls"><label>Show<select aria-label="Battle status"><option value="remaining">Not yet won</option><option value="all">All battles</option><option value="won">Already won</option></select></label><label>Find a battle or reward<input type="search" aria-label="Search Summoning battles" placeholder="Battle name, monster, or reward…"></label><span data-battle-count aria-live="polite"></span></div><div class="sum-battle-list"></div><p class="muted">Need stronger summons? Open Upgrades or Next Purchase Optimizer to plan how to spend your essence. Win status updates when you import a new save. Endless battles are not included in this list.</p></section>`;
 const select=host.querySelector('select'),input=host.querySelector('input');select.value=known?view:'all';input.value=query;
 function paint(){const shown=rows.filter(x=>(!known||select.value==='all'||(select.value==='won'?x.won:!x.won))&&`${x.battleName} ${x.name} ${x.rewardText}`.toLowerCase().includes(query));host.querySelector('[data-battle-count]').textContent=shown.length+' battles shown';host.querySelector('.sum-battle-list').innerHTML=shown.map(x=>`<article class="sum-battle-row ${known&&x.won?'is-won':''}"><div><h4>${esc(x.battleName)}</h4><small>${colors[D.normal[x.code]]} pillar · Enemy: ${esc(x.name)}</small></div><div><strong>${esc(x.rewardText)}</strong><small>Base victory reward</small></div><span class="sum-battle-status">${!known?'Save needed':x.won?'✓ Won':'Not yet won'}</span></article>`).join('')||`<p class="exp-card">${select.value==='remaining'&&won===rows.length&&!query?'All listed battles are won. Choose All battles to review their rewards.':'No battles match these filters.'}</p>`;}
 select.onchange=()=>{view=select.value;paint();};input.oninput=()=>{query=input.value.toLowerCase();paint();};paint();
}

// Stone bosses gain 4000x HP per recorded victory. Logs keep large values finite.
function stoneHp(base,kills){if(kills===null)return 'Unknown';const log=Math.log10(base)+kills*Math.log10(4000);if(log<12)return Math.round(10**log).toLocaleString('en-US');const exponent=Math.floor(log);return (10**(log-exponent)).toFixed(2)+'e'+exponent;}
const parse=v=>{try{return typeof v==='string'?JSON.parse(v):v;}catch{return null;}};
function progress(raw,c=root.WORLD6_CATALOG){const data=parse(raw?.data)||raw||{},kills=parse(data.KRbest),options=parse(data.OptionsListAccount??data.OptLacc),endless=options?.[319],count=Number.isFinite(Number(endless))&&endless!=null?Math.max(0,Math.floor(Number(endless))):null;return {stones:D.stones.map((x,i)=>{const value=kills?.['SummzTrz'+i];return {...x,color:colors[i],kills:value!=null&&Number.isFinite(Number(value))?Math.max(0,Math.floor(Number(value))):null,boss:String(c.SummonEnemies[4][106+i]||'').replaceAll('_',' ')};}),endless:count};}
function endlessRows(start,c=root.WORLD6_CATALOG){return Array.from({length:40},(_,i)=>{const index=start+i,slot=index%40,modifier=String(c.SummonEnemies[12][Number(c.SummonEnemies[11][slot])]||'').replaceAll('_',' ').split('|');return {number:index+1,rewardText:reward({rewardId:Number(c.SummonEnemies[9][slot])-1,rewardValue:Number(c.SummonEnemies[10][slot])}),modifier:modifier.shift(),rule:modifier.join(' ')};});}
let active='normal';
function render(host,model,raw){const saved=progress(raw);host.innerHTML='<nav class="skill-tabs" aria-label="Summoning battle types"><button class="skill-tab" data-sum-battle-tab="normal">Normal Pillars</button><button class="skill-tab" data-sum-battle-tab="stones">Summoning Stones</button><button class="skill-tab" data-sum-battle-tab="endless">Endless</button></nav><div data-sum-battle-panel></div>';const panel=host.querySelector('[data-sum-battle-panel]');
 function paint(){host.querySelectorAll('[data-sum-battle-tab]').forEach(b=>{b.classList.toggle('active',b.dataset.sumBattleTab===active);b.setAttribute('aria-pressed',String(b.dataset.sumBattleTab===active));});if(active==='normal'){renderNormal(panel,model);return;}
 if(active==='stones'){panel.innerHTML='<section class="summoning-battles"><div class="exp-card"><h3>Summoning Stones</h3><p>Find each stone at its map and defeat its summoned boss. Repeat victories strengthen the corresponding color’s Summoning upgrade bonuses.</p><small>These boss victories are separate from normal pillar and Endless wins. Missing stone records are shown as unknown.</small></div><div class="sum-battle-list">'+saved.stones.map(x=>'<article class="sum-battle-row"><div class="sum-stone-identity"><img class="sum-stone-icon" src="assets/'+esc(x.icon)+'.png" alt="" loading="lazy"><div><h4>'+esc(x.name)+' Stone</h4><small>Boss: '+esc(x.boss)+'</small><small>World '+x.world+' · '+esc(x.map)+'</small><small>Map mob: '+esc(x.mob)+'</small></div></div><div><strong>'+x.color+' upgrades</strong><small>'+ (x.kills===null?'Bonus unknown':(1+x.kills)+'× from stone victories')+'</small><small class="sum-stone-hp">Next boss HP: '+stoneHp(x.baseHp,x.kills)+'</small></div><span class="sum-battle-status">'+(x.kills===null?'No saved record':x.kills+' victories')+'</span></article>').join('')+'</div></section>';return;}
 let start=saved.endless??0;panel.innerHTML='<section class="summoning-battles"><div class="exp-card"><h3>Endless</h3><p>Repeated Summoning battles with special rules. The reward and rule sequence repeats every 40 battles.</p><strong>'+(saved.endless===null?'Import a save with Endless progress.':saved.endless+' battles won · Next: battle '+(saved.endless+1))+'</strong><small>Rewards shown are base contributions before winner-bonus boosts. A next battle number does not confirm that Endless is unlocked.</small></div><div class="sum-battle-controls"><button data-endless-prev>Previous 40</button><button data-endless-current>Next unbeaten battle</button><button data-endless-next>Next 40</button><span data-endless-range></span></div><div class="sum-battle-list"></div></section>';
 function list(){panel.querySelector('[data-endless-prev]').disabled=start===0;panel.querySelector('[data-endless-range]').textContent='Battles '+(start+1)+'–'+(start+40);panel.querySelector('.sum-battle-list').innerHTML=endlessRows(start).map(x=>'<article class="sum-battle-row"><div><h4>Battle '+x.number+' · '+esc(x.modifier)+'</h4><small>'+esc(x.rule)+'</small></div><div><strong>'+esc(x.rewardText)+'</strong><small>Base victory reward</small></div><span class="sum-battle-status">'+(saved.endless===null?'Progress unknown':x.number<=saved.endless?'✓ Won':x.number===saved.endless+1?'Next battle':'Upcoming')+'</span></article>').join('');}
 panel.querySelector('[data-endless-prev]').onclick=()=>{start=Math.max(0,start-40);list();};panel.querySelector('[data-endless-next]').onclick=()=>{start+=40;list();};panel.querySelector('[data-endless-current]').onclick=()=>{start=saved.endless??0;list();};list();
 }
 host.querySelectorAll('[data-sum-battle-tab]').forEach(b=>b.onclick=()=>{active=b.dataset.sumBattleTab;paint();});paint();
}
const api={stoneHp,battles,reward,progress,endlessRows,render};if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.SummoningBattles=api;
})(typeof window!=='undefined'?window:globalThis);
