(function(root){
'use strict';
const M=root.SushiModel,cache=new WeakMap();
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=v=>v===null||!Number.isFinite(v)?'Unavailable':v!==0&&Math.abs(v)<.001?v.toExponential(2):Intl.NumberFormat('en',{notation:Math.abs(v)>=1e15?'scientific':Math.abs(v)>=1e4?'compact':'standard',maximumFractionDigits:2}).format(v);
const time=h=>h===null||!Number.isFinite(h)?'No passive income':h===0?'Ready now':h<1/60?'<1 min':h<24?fmt(h)+' hr':fmt(h/24)+' days';
const plates=['Normal','Hot','Cold','Milktoast'],fires=['Red · fuel','Green · bucks','Blue · tier-ups','Pink · EXP','Purple · sparks'];
function load(raw){
  if(cache.has(raw))return cache.get(raw);
  const promise=new Promise(resolve=>{
    let worker,timer;const finish=value=>{clearTimeout(timer);worker?.terminate();resolve(value);};
    try{worker=new Worker('sushi-worker.js');worker.onmessage=e=>finish(e.data);worker.onerror=()=>finish({error:'Account bonuses could not be calculated.'});timer=setTimeout(()=>finish({error:'Account bonus calculation timed out.'}),45000);worker.postMessage(raw);}catch(error){finish({error:error.message});}
  });cache.set(raw,promise);promise.then(r=>{if(r.error)cache.delete(raw);});return promise;
}
async function render(host,raw,rows,afterRender){
  const request={};host.sushiRequest=request;host.innerHTML='<p role="status">Calculating your Sushi Station…</p>';
  let saved;try{saved=M.decode(raw,root.WORLD7_CATALOG,null);}catch{}
  if(!saved){host.innerHTML='<h2>Sushi Station</h2><p>Import a save with complete Sushi Station data to see your station and plan upgrades.</p>';afterRender?.();return;}
  const context=await load(raw);if(host.sushiRequest!==request||host.dataset.page!=='sushi')return;
  saved.context=context.context||null;
  const base=M.calculate(saved),absolute=!!saved.context;
  let tab='Overview',goal='bucks',onlyAffordable=false,query='',knowledgeFilter='discovered',board={...saved,tiers:saved.tiers.slice(),plates:saved.plates.slice(),fires:saved.fires.slice()},selected=null,move='sushi',boardNote='',selectedDiscovery=null;
  const amount=v=>absolute?fmt(v):'Unavailable',eta=v=>absolute?time(v):'Account bonuses unavailable';
  const stat=(label,value,detail='')=>`<article class="sushi-stat"><span>${esc(label)}</span><strong>${esc(value)}</strong><small>${esc(detail)}</small></article>`;
  const navigation=['Overview','Upgrade priorities','Board planner','Knowledge','Sushi collection','Bonus breakdowns'];
  const next=base.knowledge.find(k=>!k.discovered),reward=i=>M.formatEffect(saved.catalog.Research[36][i],Number(saved.catalog.Research[37][i])||0);
  const discovery=()=>next?`<section class="sushi-next"><img src="assets/Sushi${next.i}.png" alt=""><div><small>NEXT DISCOVERY · TIER ${next.i+1}</small><h3>${esc(next.name)}</h3><p>${esc(reward(next.i))}</p><small>${saved.levels[44]>0?'Permanent account reward':'Requires Sushi Service Bonuses to activate account rewards'} · Also adds 10% to the discovery bucks multiplier.</small></div></section>`:'<section class="sushi-next"><div><h3>Every catalog sushi discovered</h3><p>Continue improving knowledge and Perfecto bonuses.</p></div></section>';
  function overview(){
    return `<div class="sushi-stats">${stat('Bucks saved',fmt(saved.misc[3]),'At save import')}${stat('Bucks per hour',amount(base.bucksPerHour),'Current station layout')}${stat('Fuel generation',fmt(base.fuel)+'/hr')}${stat('Fuel capacity',fmt(base.cap),fmt(saved.misc[0])+' fuel saved')}${stat('Time until full',time(base.hoursToCap),'Assumes no fuel is spent')}${stat('Best combo',fmt(saved.misc[8]),fmt(base.combo)+'× bucks')}</div>${discovery()}<h3>Shakers available</h3><div class="sushi-stats">${['Salt','Pepper','Saffron'].map((name,i)=>stat(name,saved.levels[17+i]>0?fmt(saved.misc[5+i]||0):'Locked',i===0?'Chance to tier up sushi':i===1?'Chance to Perfecto sushi':(1+Number(saved.levels[22]||0))+' hours of bucks per use')).join('')}</div><div class="sushi-overview-links">${[['Upgrade priorities','Compare your next purchases'],['Board planner','Preview a better arrangement'],['Knowledge','Find your next permanent bonus']].map(([t,copy])=>`<button data-tab="${t}"><strong>${t}</strong><span>${copy} →</span></button>`).join('')}</div><p class="sushi-note">Rates reflect the imported save. Fuel and knowledge forecasts hold bonuses and the board fixed; daily plate EXP arrives at daily resets.</p>`;
  }
  function upgradeView(){
    const ranked=M.upgrades(saved,goal),list=ranked.filter(x=>(!onlyAffordable||(x.affordable&&x.available&&!x.maxed))&&(!query||x.name.toLowerCase().includes(query.toLowerCase())));
    const labels={bucks:'Bucks / hour',fuel:'Fuel / hour',knowledge:'Daily plate EXP',capacity:'Fuel capacity'};
    return `<div class="sushi-controls"><label>Prioritize <select data-goal>${Object.entries(labels).map(([v,l])=>`<option value="${v}" ${goal===v?'selected':''}>${l}</option>`).join('')}</select></label><label><input type="checkbox" data-affordable ${onlyAffordable?'checked':''}> Affordable now</label><label>Search upgrades <input type="search" data-search value="${esc(query)}"></label></div><p class="sushi-note">Ranked by immediate ${labels[goal].toLowerCase()} gained per Buck. Each row compares one purchase with your saved station. Unlocks, discounts, and active-play upgrades remain listed separately from measurable passive gains.</p><div class="sushi-table-wrap"><table><thead><tr><th>Upgrade</th><th>Discounted cost</th><th>Benefit</th><th>Funding / payback</th></tr></thead><tbody>${list.map(x=>`<tr class="${x.maxed||!x.available?'sushi-muted':''}"><td><strong>${esc(x.name)}</strong><small>Lv ${x.level}${x.max>998?'':' / '+x.max} · ${x.maxed?'Maxed':!x.available?'Buy the previous station upgrade to unlock':x.affordable?'Affordable':'Saving up'}</small></td><td>${x.maxed?'—':fmt(x.cost)+' Bucks'}</td><td>${x.maxed?'—':x.deltas[goal]>0?`+${goal==='bucks'?amount(x.deltas[goal]):fmt(x.deltas[goal])} ${esc(labels[goal])}<small>+${fmt(x.gain*100)}%</small>`:x.discountGain>0?`${fmt(x.discountGain*100)}% cheaper upgrades`:'No immediate gain on this board'}${!x.maxed?`<details><summary>Next-level effect</summary><p>${esc(x.effect.replaceAll('$','(see bonus breakdown)'))}</p></details>`:''}</td><td>${x.maxed?'Maxed':!x.available?'Locked':eta(x.wait)}${!x.maxed&&x.payback!==null?`<small>Pays back in ${eta(x.payback)}</small>`:''}</td></tr>`).join('')||'<tr><td colspan="4">No upgrades match these filters.</td></tr>'}</tbody></table></div><p class="sushi-note">Payback = price ÷ added bucks/hour. New slots and unlocks need a board change before they produce income. Other purchases and future discoveries are excluded.</p>`;
  }
  function boardView(){
    const preview=M.calculate(board),changed=board.tiers.some((x,i)=>x!==saved.tiers[i])||board.plates.some((x,i)=>x!==saved.plates[i])||board.fires.some((x,i)=>x!==saved.fires[i]);
    const metric=(label,before,after,isMoney=false)=>stat(label,(isMoney?amount(after):fmt(after)),(isMoney?amount(before):fmt(before))+' saved · '+(before?fmt((after/before-1)*100)+'%':after>0?'New production':'No change'));
    return `<div class="sushi-controls"><label>Optimize for <select data-board-goal>${[['bucks','Bucks'],['knowledge','Daily plate EXP'],['fuel','Fuel']].map(([v,l])=>`<option value="${v}" ${goal===v?'selected':''}>${l}</option>`).join('')}</select></label><button data-optimize>Suggest arrangement</button><button class="secondary" data-board-reset>Reset to saved</button><label>Swap <select data-move><option value="sushi" ${move==='sushi'?'selected':''}>Sushi</option><option value="plates" ${move==='plates'?'selected':''} ${saved.levels[42]>0?'':'disabled'}>Plates</option></select></label></div><p class="sushi-note">Select two available cells to swap ${move==='sushi'?'sushi':'plates'}. Change fireplaces below each column. ${changed?'Preview differs from your save.':'Showing your saved arrangement.'} Purple fires grow sparks over time; blue fires help future tier-ups. These future gains are excluded from the rate comparison.</p><div class="sushi-stats">${metric('Bucks / hour',base.bucksPerHour,preview.bucksPerHour,true)}${metric('Fuel / hour',base.fuel,preview.fuel)}${metric('Knowledge EXP / daily reset',base.totalXpDaily,preview.totalXpDaily)}</div><p role="status">${esc(boardNote||'Suggestions keep your sushi and plate inventories fixed and use unlocked fireplace colors.')}</p><div class="sushi-board-scroll"><div class="sushi-live-board" aria-label="Station board, 15 columns">${board.tiers.map((tier,i)=>`<button class="sushi-cell sushi-plate-${board.plates[i]} ${selected===i?'sushi-cell-selected':''}" data-cell="${i}" ${board.plates[i]<0?'disabled':''} aria-pressed="${selected===i}" aria-label="Row ${Math.floor(i/15)+1}, column ${i%15+1}, ${board.plates[i]<0?'locked':plates[board.plates[i]]+' plate, '+(tier<0?'empty':base.knowledge[tier]?.name+', tier '+(tier+1))}">${tier>=0?`<img src="assets/Sushi${tier}.png" alt=""><strong>T${tier+1}</strong>`:`<span>${board.plates[i]<0?'—':'Empty'}</span>`}<small>${plates[board.plates[i]]||'Locked'}</small></button>`).join('')}${board.fires.map((f,i)=>`<label class="sushi-fire">Column ${i+1}<select data-fire="${i}" aria-label="Column ${i+1} fireplace" ${f<0?'disabled':''}>${f<0?'<option value="-1">Locked</option>':fires.map((name,t)=>`<option value="${t}" ${t===f?'selected':''} ${t===0||t===f||saved.levels[({1:27,2:24,3:26,4:25})[t]]>0?'':'disabled'}>${name}</option>`).join('')}</select></label>`).join('')}</div></div><p class="sushi-note">Hot: extra bucks · Cold: daily EXP to every lower tier · Milktoast: daily EXP to its own tier. Suggestions maximize immediate output through swaps; they are not a merge route or a guarantee of a globally optimal board.</p>`;
  }
  function knowledgeView(){
    const list=base.knowledge.filter(k=>(knowledgeFilter==='all'||knowledgeFilter==='perfecto'&&k.discovered&&!k.perfecto||knowledgeFilter==='discovered'&&k.discovered)&&(!query||(k.name+' '+k.effect).toLowerCase().includes(query.toLowerCase()))).sort((a,b)=>(a.days??Infinity)-(b.days??Infinity)||a.remaining-b.remaining);
    return `<div class="sushi-controls"><label>Show <select data-knowledge-filter>${[['discovered','Discovered sushi'],['perfecto','Missing Perfecto'],['all','All sushi']].map(([v,l])=>`<option value="${v}" ${v===knowledgeFilter?'selected':''}>${l}</option>`).join('')}</select></label><label>Search knowledge <input type="search" data-search value="${esc(query)}"></label></div><p class="sushi-note">Nearest passive level-ups first. Daily resets needed are rounded up; active cooking and merges can bring levels sooner. EXP rates use your saved board.</p>${saved.levels[13]>0?'':'<p>Unlock Seared Knowledge to start earning Knowledge EXP.</p>'}<div class="sushi-knowledge-cards">${list.map(k=>`<article><header><img src="assets/Sushi${k.i}.png" alt=""><div><h3>${esc(k.name)}</h3><small>Tier ${k.i+1} · Lv ${k.level} · ${!k.discovered?'Undiscovered':k.perfecto?'Perfecto':'Missing Perfecto'}</small></div></header><p>${esc(k.effect)}</p><progress aria-label="${esc(k.name)} knowledge progress" max="${k.required}" value="${Math.min(k.required,k.xp)}"></progress><small>${fmt(k.xp)} / ${fmt(k.required)} EXP · ${fmt(k.remaining)} remaining</small><p>Next level: ${esc(k.nextEffect)}</p><small>${fmt(k.daily)} EXP / reset · ${!k.discovered?'Discover this sushi first':k.days===null?'No passive EXP on this board':Math.ceil(k.days)+' daily resets to next level'}</small>${k.discovered&&!k.perfecto?`<p class="sushi-perfecto">With Perfecto: ${esc(k.perfectEffect)}</p>`:''}</article>`).join('')||'<p>No sushi match these filters.</p>'}</div>`;
  }
  function collectionView(){return `${discovery()}<div class="sushi-collection-grid">${base.knowledge.map(k=>`<button class="sushi-collection-item ${k.discovered?'':'sushi-undiscovered'}" data-discovery="${k.i}" aria-pressed="${selectedDiscovery===k.i}" aria-label="${esc(k.name)} discovery reward"><img src="assets/Sushi${k.i}.png" alt=""><strong>${k.discovered?'Lv '+k.level:'Locked'}</strong></button>`).join('')}</div><section class="sushi-next" aria-live="polite">${selectedDiscovery===null?'<p>Select a sushi to see its permanent discovery reward.</p>':`<img src="assets/Sushi${selectedDiscovery}.png" alt=""><div><h3>${esc(base.knowledge[selectedDiscovery].name)}</h3><p>${esc(reward(selectedDiscovery))}</p><small>${base.knowledge[selectedDiscovery].discovered?'Discovered':'Not yet discovered'}</small></div>`}</section>`;}
  function breakdownView(){
    const factors=(title,items,note)=>`<section class="sushi-breakdown"><h3>${title}</h3><p>${note}</p><dl>${items.map(x=>`<div><dt>${x.page?`<button class="sushi-source-link" data-source="${esc(x.page)}">${esc(x.name)} ↗</button>`:esc(x.name)}</dt><dd>${fmt(x.value)}×</dd></div>`).join('')}</dl></section>`;
    return `<div class="sushi-breakdowns">${factors('Bucks multipliers',base.currencyFactors,'Multiply these factors, then apply tier income, Hot plates, and green fireplaces. Total: '+amount(base.currencyMulti)+'×.')}${factors('Fuel generation',base.fuelFactors,'Base generation: 50 fuel/hour. Multiply by every factor below.')}${factors('Knowledge EXP',base.knowledgeFactors,'Base EXP per creation: '+fmt(1+saved.levels[37]/10)+'. Pink fireplace: '+fmt(1+base.fireBase)+'× for that column. Plate strength: '+fmt(base.plateBase)+'×.')}${factors('Upgrade discounts',base.discounts,'All four discounts multiply. Final cost is '+fmt(base.discount*100)+'% of the undiscounted price.')}</div><section class="sushi-breakdown"><h3>Knowledge bonuses by category</h3>${saved.catalog.Research[34].map((description,i)=>`<details><summary>${esc(M.formatEffect(description,base.totals[i]||0))}</summary><ul>${base.knowledge.filter(k=>k.category===i&&k.discovered).map(k=>`<li>${esc(k.name)} · Lv ${k.level}${k.perfecto?' · Perfecto':''}: ${esc(k.effect)}</li>`).join('')||'<li>No discoveries in this category.</li>'}</ul></details>`).join('')}</section>`;
  }
  function draw(focusSearch=false,selection=0){
    if(host.dataset.page!=='sushi')return;
    host.innerHTML=`<section class="sushi-planner"><header class="sushi-hero"><div><p class="eyebrow">WORLD 7 · SUSHI STATION</p><h2>Your station, next steps included.</h2><p>${base.unique} / ${base.knowledge.length} discovered · ${base.knowledge.filter(k=>k.perfecto).length} Perfecto</p></div><img src="assets/Sushi${Math.max(0,base.unique-1)}.png" alt=""></header>${context.error?`<p role="alert">${esc(context.error)} Bucks rates, funding times, and payback are unavailable. <button data-retry>Retry calculation</button></p>`:''}<nav class="skill-tabs" aria-label="Sushi sections">${navigation.map(t=>`<button class="skill-tab ${t===tab?'active':''}" data-tab="${t}" aria-pressed="${t===tab}">${t}</button>`).join('')}</nav><div class="sushi-panel">${tab==='Overview'?overview():tab==='Upgrade priorities'?upgradeView():tab==='Board planner'?boardView():tab==='Knowledge'?knowledgeView():tab==='Sushi collection'?collectionView():breakdownView()}</div></section>`;
    host.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;query='';selected=null;if(tab==='Board planner'&&goal==='capacity')goal='bucks';draw();});
    host.querySelector('[data-retry]')?.addEventListener('click',()=>render(host,raw,rows,afterRender));
    host.querySelectorAll('[data-goal],[data-board-goal]').forEach(el=>el.onchange=()=>{goal=el.value;draw();});
    const affordable=host.querySelector('[data-affordable]');if(affordable)affordable.onchange=()=>{onlyAffordable=affordable.checked;draw();};
    const search=host.querySelector('[data-search]');if(search){search.oninput=()=>{query=search.value;draw(true,search.selectionStart);};if(focusSearch){search.focus();search.setSelectionRange(selection,selection);}}
    const kfilter=host.querySelector('[data-knowledge-filter]');if(kfilter)kfilter.onchange=()=>{knowledgeFilter=kfilter.value;draw();};
    host.querySelectorAll('[data-discovery]').forEach(b=>b.onclick=()=>{selectedDiscovery=Number(b.dataset.discovery);draw();host.querySelector(`[data-discovery="${selectedDiscovery}"]`).focus();});
    host.querySelectorAll('[data-source]').forEach(b=>b.onclick=()=>root.dispatchEvent(new CustomEvent('idleon:navigate',{detail:b.dataset.source})));
    host.querySelector('[data-optimize]')?.addEventListener('click',()=>{board=M.optimize(board,goal);selected=null;boardNote='Suggestion ready. Compare the totals and adjust individual cells below.';draw();});
    host.querySelector('[data-board-reset]')?.addEventListener('click',()=>{board={...saved,tiers:saved.tiers.slice(),plates:saved.plates.slice(),fires:saved.fires.slice()};selected=null;boardNote='Restored the saved layout.';draw();});
    const moveSelect=host.querySelector('[data-move]');if(moveSelect)moveSelect.onchange=()=>{move=moveSelect.value;selected=null;draw();};
    const preserveScroll=action=>{const scroll=host.querySelector('.sushi-board-scroll')?.scrollLeft||0;action();draw();host.querySelector('.sushi-board-scroll').scrollLeft=scroll;};
    host.querySelectorAll('[data-cell]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.cell);preserveScroll(()=>{if(selected===null){selected=i;boardNote='Select a second cell to swap, or select this cell again to cancel.';}else{const key=move==='plates'?'plates':'tiers';[board[key][i],board[key][selected]]=[board[key][selected],board[key][i]];selected=null;boardNote='Preview updated.';}});host.querySelector(`[data-cell="${i}"]`).focus({preventScroll:true});});
    host.querySelectorAll('[data-fire]').forEach(el=>el.onchange=()=>preserveScroll(()=>{board.fires[Number(el.dataset.fire)]=Number(el.value);}));
    afterRender?.();
  }
  draw();
}
root.SushiPage={render};
})(window);
