'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),D=require('./dailies');
const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');
const fixture={charNames:['DailyTester'],data:{CauldronP2W:[[],[],[],[],[],[2]],Research:[[],[],[],[],[],[],[],[0,0,3]],OptLacc:Array(411).fill(null)}};
fixture.data.OptLacc[96]=7;fixture.data.OptLacc[98]=6;fixture.data.OptLacc[225]=7;fixture.data.OptLacc[226]=0;
assert.equal(D.classify({ready:null}),'unknown');assert.equal(D.classify({ready:true}),'ready');assert.equal(D.classify({ready:true,autoHidden:'Locked'}),'settled');
(async()=>{const browser=await chromium.launch({headless:true});try{
 const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('http://localhost:7331/**',async route=>{
  const pathname=decodeURIComponent(new URL(route.request().url()).pathname);
  if(pathname.startsWith('/__'))return route.fulfill({contentType:'application/json',body:'{}'});
  const file=path.resolve(__dirname,'.'+(pathname==='/'?'/index.html':pathname));
  if(!file.startsWith(__dirname+path.sep)||!fs.existsSync(file)||fs.statSync(file).isDirectory())return route.fulfill({status:404,body:''});
  return route.fulfill({contentType:({'.js':'text/javascript','.css':'text/css','.html':'text/html','.png':'image/png','.svg':'image/svg+xml'})[path.extname(file)]||'application/octet-stream',body:fs.readFileSync(file)});
 });
 await page.goto('http://localhost:7331/');await page.locator('#navDailies').click();
 await page.evaluate(()=>{window.Dashboard.dispose();window.Dailies.render(document.getElementById('worldContent'),{});});
 assert.equal(await page.locator('.daily-card').count(),0,'An empty save cannot invent readiness');
 assert.equal(await page.locator('.dailies input[type=checkbox]').count(),0,'Dashboard has no manual completion checkboxes');
 await page.locator('[data-frequency="unknown"]').click();assert(await page.locator('.daily-card').count()>0);
 await page.evaluate(()=>localStorage.setItem('idleon-dailies-v1',JSON.stringify({DailyTester:{checks:{vials:Date.now()},hidden:{},cycles:{}}})));
 const render=raw=>page.evaluate(raw=>{window.Dashboard.dispose();window.Dailies.render(document.getElementById('worldContent'),raw);},raw);
 await render(fixture);assert(await page.locator('[data-routine="vials"]').isVisible(),'Legacy checkmarks must not hide ready activities');
 assert.equal(await page.locator('.daily-boss-ready').count(),2);assert.equal(await page.locator('[data-boss="mush"] meter').getAttribute('value'),'1');
 await page.locator('#dailyWorld').selectOption('2');assert.equal(await page.locator('.daily-world-group').count(),1);assert.equal(await page.locator('.daily-boss').count(),0);
 await page.locator('#dailyWorld').selectOption('all');await page.locator('#dailySearch').fill('vial');assert.equal(await page.locator('.daily-card').count(),1);await page.locator('#dailySearch').fill('');
 await page.locator('[data-routine="vials"] summary').click();await page.locator('[data-hide-routine="vials"]').click();assert.equal(await page.locator('[data-routine="vials"]').count(),0);
 await page.locator('[data-frequency="hidden"]').click();await page.locator('[data-routine="vials"] summary').click();await page.locator('[data-hide-routine="vials"]').click();
 await page.locator('[data-frequency="daily"]').click();assert(await page.locator('[data-routine="vials"]').isVisible());
 const spent=structuredClone(fixture);spent.data.CauldronP2W[5][0]=0;await render(spent);assert.equal(await page.locator('[data-routine="vials"]').count(),0,'New save automatically clears exhausted attempts');
 await page.locator('[data-frequency="settled"]').click();await page.locator('[data-routine="vials"] summary').click();assert.match(await page.locator('[data-routine="vials"]').innerText(),/No attempts/);
 await page.locator('[data-hide-routine="vials"]').click();await render({...fixture,charNames:['Another']});assert(await page.locator('[data-routine="vials"]').isVisible(),'Hidden preferences are per account');
 await render(fixture);await page.locator('[data-frequency="daily"]').click();assert.equal(await page.locator('[data-routine="vials"]').count(),0,'Hidden preference persists');
 const example=JSON.parse(fs.readFileSync('../example json.txt','utf8').replace(/^\uFEFF/,''));await render(example);
 await page.locator('[data-frequency="daily"]').click();assert.equal(await page.locator('.daily-card').count(),10);
 for(const id of ['research','vials','lore','jewelCogs','tournament','petGems','raid'])assert.equal(await page.locator(`[data-routine="${id}"]`).count(),0,id);
 await page.locator('[data-frequency="unknown"]').click();assert.equal(await page.locator('.daily-card').count(),23);
 await page.locator('[data-routine="alchemyShop"] summary').click();assert.match(await page.locator('[data-routine="alchemyShop"]').innerText(),/selected purchase/);
 await page.locator('[data-frequency="weekly"]').click();assert.equal(await page.locator('.daily-card').count(),2);
 await page.locator('[data-frequency="overview"]').click();await page.locator('#quickNotesToggle').click();
 await page.evaluate(raw=>window.PlannerLiveBridge.apply(raw),example);
 await page.waitForFunction(()=>/^(Save age|Imported):/.test(document.getElementById('qolFreshness').textContent),{},{timeout:60000});
 await render(example);
 await page.screenshot({path:'../audit/dailies-dashboard-desktop.png',fullPage:true});
 assert(await page.locator('.dailies').evaluate(el=>el.scrollWidth<=el.clientWidth+1));
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'../audit/dailies-dashboard-mobile.png',fullPage:true});assert(await page.locator('.dailies').evaluate(el=>el.scrollWidth<=el.clientWidth+1),'No mobile overflow');
 await page.locator('[data-frequency="settled"]').click();await page.locator('[data-routine="research"] summary').click();assert.match(await page.locator('[data-routine="research"]').innerText(),/All 38 observations/);
 await page.locator('[data-daily-link="vials"]').click();assert.equal(await page.locator('#worldContent').getAttribute('data-page'),'vials');
 assert.deepEqual(errors,[]);console.log('Dailies dashboard: save-driven readiness, legacy check migration, miniboss watch, search/world filters, account isolation, persistence, navigation and mobile layout passed.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
