const assert=require('assert'),vm=require('vm'),fs=require('fs');const box={window:{}};vm.runInNewContext(fs.readFileSync('world6-data.js','utf8'),box);vm.runInNewContext(fs.readFileSync('world4-data.js','utf8'),box);global.WORLD6_CATALOG=box.window.WORLD6_CATALOG;global.WORLD4_CATALOG=box.window.WORLD4_CATALOG;const W=require('./world6.js');
const f=W.farm({FarmCrop:{0:12,22:7},FarmUpg:[0,55,3],FarmPlot:[[1]]});assert.equal(f.crops.length,332);assert.equal(f.found,2);assert.equal(f.beans,55);assert.equal(f.market[0].level,3);assert.equal(f.seeds.length,7);
const n=Array(108).fill(null).map(()=>[]);n[0]=[2,0,50];n[102]=[1,12345,0,0,0,0,0,0,0,'a'];n[103]=[4];n[104]=[1,0];n[106]=['NjItem0'];const s=W.sneak({Ninja:n});assert.equal(s.jade,12345);assert.equal(s.twins[0].floor,3);assert.equal(s.upgrades[0].level,4);assert.equal(s.discoveredItems,1);
const sum=W.summon({Summon:[[2],['mushG'],[100,20],[3],[2]]});assert.equal(sum.wins,1);assert.equal(sum.upgrades.length,82);assert.equal(sum.upgrades[0].level,2);assert.equal(sum.essences[0].value,100);assert(sum.enemies[0].won);assert.equal(sum.enemies[0].name,'Green Mushroom');assert.equal(sum.enemies[0].reward,'<x Total DMG');assert.equal(sum.enemies[0].rewardValue,15);assert.equal(sum.enemies[6].rewardId,null);assert.equal(sum.victoryBonuses[0].value,15);console.log('world6 tests passed');

const B=require("./summoning-battles.js"),battles=B.battles(sum);assert(battles.length<sum.enemies.length);assert(battles.every(x=>x.battleName));assert(!battles.some(x=>x.code==="Copper"));assert.equal(battles[0].battleName,"Jonesy and his Lil Mushies");assert.equal(B.reward(battles[0]),"+15% Total damage");assert(!("hp" in battles[0]));assert.equal(B.reward({rewardId:19,rewardValue:2}),"+2 Library maximum level");

assert(!battles.some(x=>/^rift/.test(x.code)||x.id>=100&&x.id<=114));
const progress=B.progress({KRbest:JSON.stringify({SummzTrz0:6}),OptionsListAccount:JSON.stringify(Array.from({length:320},(_,i)=>i===319?43:0))},global.WORLD6_CATALOG);assert.equal(progress.stones.length,7);assert.equal(progress.stones[0].kills,6);assert.equal(progress.stones[1].kills,null);assert.equal(progress.endless,43);assert.equal(B.progress({},global.WORLD6_CATALOG).endless,null);
const endless=B.endlessRows(43,global.WORLD6_CATALOG);assert.equal(endless[0].number,44);assert.equal(endless.length,40);assert.equal(endless[0].rewardText,B.endlessRows(83,global.WORLD6_CATALOG)[0].rewardText);assert(endless.every(x=>x.rule&&x.modifier));
