'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const D=require('./dailies');
const empty=D.model({});assert(empty.every(x=>x.ready==null&&!x.autoHidden&&x.detail));
const fixture={charNames:['DailyTester'],data:{CauldronP2W:JSON.stringify([[],[],[],[],[],[0]]),Research:[[],[],[],[],[],[],[],[0,0,3]],OptLacc:Array(411).fill(null)}};
fixture.data.OptLacc[410]=2;fixture.data.OptLacc[96]=7;fixture.data.OptLacc[98]=6;fixture.data.OptLacc[225]=7;fixture.data.OptLacc[226]=0;
assert.equal(D.model(fixture).find(x=>x.id==='vials').count,0);
assert.equal(D.model(fixture).find(x=>x.id==='research').count,3);
assert.equal(D.model(fixture).find(x=>x.id==='lore').status,'2 reads used');
const before=new Date(2026,8,25,3,59).getTime(),after=new Date(2026,8,25,4,0).getTime();
assert(D.isDone(before,before,4));assert(!D.isDone(before,after,4));assert(!D.isDone(null,after,4));
assert.notEqual(D.accountKey(fixture),D.accountKey({charNames:['Another']}));
const {chromium}=require(process.env.PLAYWRIGHT_PATH||'C:/Users/Sofia/AppData/Local/npm-cache/_npx/e41f203b7505f1fb/node_modules/playwright');
(async()=>{const browser=await chromium.launch({headless:true});try{
 const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('http://localhost:7331/**',async route=>{
  const pathname=decodeURIComponent(new URL(route.request().url()).pathname);
  if(pathname.startsWith('/__'))return route.fulfill({contentType:'application/json',body:'{}'});
  const file=path.resolve(__dirname,'.'+(pathname==='/'?'/index.html':pathname));
  if(!file.startsWith(__dirname+path.sep)||!fs.existsSync(file)||fs.statSync(file).isDirectory())return route.fulfill({status:404,body:''});
  const type={'.js':'text/javascript','.css':'text/css','.html':'text/html','.png':'image/png','.json':'application/json','.svg':'image/svg+xml'}[path.extname(file)]||'application/octet-stream';
  return route.fulfill({contentType:type,body:fs.readFileSync(file)});
 });

 await page.goto('http://localhost:7331/');await page.locator('#navDailies').click();
 assert.equal(await page.locator('.daily-card').count(),0,'No save must not invent ready tasks');
 await page.locator('[data-frequency="unknown"]').click();assert((await page.locator('.daily-card').count())>0);
 fixture.data.CauldronP2W=JSON.stringify([[],[],[],[],[],[2]]);
 await page.evaluate(raw=>window.Dailies.render(document.getElementById('worldContent'),raw),fixture);
 await page.locator('[data-daily="vials"]').click();assert.equal(await page.locator('[data-routine="vials"]').count(),0,'Checking removes the task');
 await page.locator('[data-frequency="hidden"]').click();await page.locator('[data-daily="vials"]').click();
 await page.locator('[data-frequency="daily"]').click();await page.locator('[data-hide-routine="vials"]').click();
 await page.locator('[data-frequency="hidden"]').click();await page.locator('[data-hide-routine="vials"]').click();
 await page.locator('[data-frequency="daily"]').click();assert(await page.locator('[data-routine="vials"]').isVisible());
 await page.locator('[data-daily="vials"]').click();await page.reload();await page.locator('#navDailies').click();
 await page.evaluate(raw=>window.Dailies.render(document.getElementById('worldContent'),raw),fixture);
 assert.equal(await page.locator('[data-routine="vials"]').count(),0);
 await page.locator('[data-frequency="hidden"]').click();assert(await page.locator('[data-daily="vials"]').isChecked());
 await page.evaluate(raw=>window.Dailies.render(document.getElementById('worldContent'),{...raw,charNames:['Another']}),fixture);assert(!await page.locator('[data-daily="vials"]').isChecked());
 await page.locator('[data-frequency="timers"]').click();assert.equal(await page.locator('.daily-boss-ready').count(),2);assert.equal(await page.locator('[data-routine="mush"]').count(),0);
 const example=JSON.parse(fs.readFileSync(path.join(__dirname,'../example json.txt'),'utf8').replace(/^\uFEFF/,''));
 await page.evaluate(raw=>window.Dailies.render(document.getElementById('worldContent'),raw),example);
 for(const id of ['research','vials','lore','jewelCogs','tournament','petGems','raid'])assert.equal(await page.locator(`[data-routine="${id}"]`).count(),0,id);
 assert.equal(await page.locator('.daily-card').count(),10);
 await page.locator('[data-frequency="unknown"]').click();assert.equal(await page.locator('.daily-card').count(),23);
 await page.locator('[data-routine="alchemyShop"] summary').click();assert.match(await page.locator('[data-routine="alchemyShop"]').innerText(),/selected purchase/);
 await page.locator('[data-frequency="weekly"]').click();assert.equal(await page.locator('.daily-card').count(),2);
 await page.locator('[data-frequency="daily"]').click();
 await page.locator('#quickNotesToggle').click();await page.evaluate(()=>document.getElementById('inputPanel').classList.add('hidden'));
 await page.screenshot({path:'../audit/dailies-compact-desktop.png',fullPage:true});
 const heights=await page.locator('.daily-card').evaluateAll(nodes=>nodes.map(n=>n.getBoundingClientRect().height));assert(Math.max(...heights)<145,'Routine rows should stay compact');
 await page.setViewportSize({width:390,height:844});assert(await page.locator('.dailies').evaluate(el=>el.scrollWidth<=el.clientWidth+1));
 await page.screenshot({path:'../audit/dailies-compact-mobile.png',fullPage:true});
 await page.locator('[data-frequency="hidden"]').click();assert.match(await page.locator('[data-routine="research"]').innerText(),/All 38 observations/);
 await page.locator('#dailySettings').click();await page.locator('#dailyAutoHide').uncheck();await page.locator('[data-frequency="all"]').click();assert(await page.locator('[data-routine="research"]').isVisible());
 await page.locator('[data-daily-link="vials"]').click();assert.equal(await page.locator('#worldContent').getAttribute('data-page'),'vials');
 assert.deepEqual(errors,[]);console.log('Dailies: counters, unknowns, reset boundary, account isolation, navigation, persistence, filter and mobile layout passed.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
