(function(root){
  'use strict';
  const parse=v=>{if(typeof v==='string'){try{return JSON.parse(v);}catch{return null;}}return v;},num=v=>v!==null&&v!==undefined&&v!==''&&Number.isFinite(Number(v))?Number(v):null;
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),pretty=v=>String(v??'').replaceAll('_',' ').replaceAll('@',' ');
  const fmt=v=>{if(v===null)return'?';const n=Number(v),a=Math.abs(n);if(a>=1e18)return n.toExponential(2).replace('e+','e');for(const [d,s] of [[1e15,'Q'],[1e12,'T'],[1e9,'B'],[1e6,'M']])if(a>=d)return(n/d).toLocaleString(undefined,{maximumFractionDigits:2})+s;return n.toLocaleString(undefined,{maximumFractionDigits:2});};
  const tiers=['Missing','Normal','Ancient','Eldritch','Sovereign','Omnipotent','Transcendent'];
  function decodeSailing(data,c=root.WORLD5_CATALOG){
    const sailing=parse(data.Sailing),boats=parse(data.Boats)||[],captains=parse(data.Captains)||[],chests=parse(data.SailChests)||[],levels=sailing?.[3]||[];
    const artifacts=c.ArtifactInfo.map((row,id)=>({id,name:pretty(row[0]),tier:num(levels[id])??0,tierName:tiers[num(levels[id])??0]||`Tier ${levels[id]}`,effect:pretty(row[4]),icon:id<35?`assets/SailT${id}.png`:null}));
    const boatRows=boats.map((raw,id)=>{const b=parse(raw)||[],captainId=num(b[0]),island=num(b[1]);return{id,captainId,island,returning:num(b[2])===1,lootLevel:num(b[3]),speedLevel:num(b[5]),unlocked:(num(b[3])||0)>0||captainId>=0};}).filter(b=>b.unlocked);
    const captainRows=captains.slice(0,30).map((raw,id)=>{const x=parse(raw)||[];return{id,tier:num(x[0]),bonusA:num(x[1]),bonusB:num(x[2]),level:num(x[3]),exp:num(x[4]),trait:num(x[5]),hired:num(x[0])>=0};}).filter(x=>x.hired);
    return{available:Array.isArray(sailing),goldBars:num(sailing?.[1]?.[0]),captainSlots:num(sailing?.[2]?.[0])===null?null:1+Number(sailing[2][0]),boatSlots:num(sailing?.[2]?.[1])===null?null:1+Number(sailing[2][1]),artifacts,boats:boatRows,captains:captainRows,chests:chests.length,islands:c.IslandInfo};
  }
  function plantIcon(type,evo){if(type===1)return`assets/GamingPlant${Math.min(4,Math.max(0,evo||0))}.png`;if(type>=2&&type<=10)return`assets/GamingPlant${String.fromCharCode(95+type)}0.png`;return null;}
  function decodeGaming(data,c=root.WORLD5_CATALOG){
    const gaming=parse(data.Gaming),sprouts=parse(data.GamingSprout)||[];
    const plants=sprouts.slice(0,25).map((raw,id)=>{const p=parse(raw)||[],type=num(p[1])||0,evo=num(p[3])||0;return{id,type,evo,progress:num(p[0]),x:num(p[4]),y:num(p[5]),occupied:type>0,icon:plantIcon(type,evo)};});
    const l1=num(gaming?.[1]),l2=num(gaming?.[2]),l3=num(gaming?.[3]),l7=num(gaming?.[7]);
    const upgrades=[{name:'Sprout Value',level:l1,effect:l1===null?'Unknown':`${fmt((1+4*l1)*Math.pow(1.065,l1))} base value`},{name:'Sprout Speed',level:l2,effect:l2===null?'Unknown':`+${fmt(2*l2)}% core growth speed`},{name:'Sprout Capacity',level:l3,effect:l3===null?'Unknown':`${Math.min(24,3+l3)} base slots`},{name:'Mutation',level:l7,effect:l7===null?'Unknown':`${fmt(100*(.13+.11*l7/(150+l7)))}% base growth chance`}];
    const superString=String(gaming?.[12]??''),letters='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-_';
    const superbits=c.GamingUpg.map((row,id)=>({id,name:pretty(row[3]).replace('|',' '),description:pretty(row[0]),owned:id<letters.length?superString.includes(letters[id]):null,cost:row[1],requiredLevel:Number(row[2])}));
    return{available:Array.isArray(gaming),bits:num(gaming?.[0]),bestNugget:num(gaming?.[8]),mutationLevel:num(gaming?.[4]),plants,upgrades,superbits,snailLevel:num(sprouts?.[32]?.[1]),imports:String(gaming?.[6]??'')};
  }
  const tabs={sailing:'artifacts',gaming:'garden'};let selected=null,superPage=0;
  function render(host,kind,data){const c=root.WORLD5_CATALOG,model=kind==='sailing'?decodeSailing(data,c):decodeGaming(data,c);function paint(){const tab=tabs[kind],tabList=kind==='sailing'?[['artifacts','Artifacts'],['boats','Boats'],['captains','Captains']]:[['garden','Garden'],['upgrades','Upgrades'],['superbits','Superbits']];
    let body='';if(!model.available)body='<section class="exp-card"><h3>Save data unavailable</h3><p>Load a complete account export to decode this page.</p></section>';
    else if(kind==='sailing'&&tab==='artifacts')body=`<div class="w5-grid artifacts">${model.artifacts.map(a=>`<button class="w5-tile ${a.tier?'':'locked'}" data-w5="artifact" data-id="${a.id}">${a.icon?`<img src="${a.icon}" alt="">`:'<span class="w5-fallback">'+(a.id+1)+'</span>'}<strong>${esc(a.name)}</strong><small>${esc(a.tierName)}</small><div class="w5-tip"><b>${esc(a.name)}</b><span>${esc(a.effect)}</span></div></button>`).join('')}</div>`;
    else if(kind==='sailing'&&tab==='boats')body=`<div class="w5-list">${model.boats.map(b=>`<button class="w5-row" data-w5="boat" data-id="${b.id}"><b>Boat ${b.id+1}</b><span>Loot Lv ${fmt(b.lootLevel)}</span><span>Speed Lv ${fmt(b.speedLevel)}</span><span>${b.island>=0?`Island ${b.island+1}`:'Harbor'}</span><small>${b.returning?'Returning':'Sailing / docked'}</small></button>`).join('')||'<p>No unlocked boats found.</p>'}</div>`;
    else if(kind==='sailing')body=`<div class="w5-list">${model.captains.map(x=>`<button class="w5-row" data-w5="captain" data-id="${x.id}"><b>Captain ${x.id+1}</b><span>Lv ${fmt(x.level)}</span><span>Tier ${fmt(x.tier)}</span><span>Bonuses ${fmt(x.bonusA)} / ${fmt(x.bonusB)}</span></button>`).join('')||'<p>No hired captains found.</p>'}</div>`;
    else if(tab==='garden')body=`<div class="gaming-garden">${model.plants.map(p=>`<button class="gaming-plant ${p.occupied?'':'empty'}" data-w5="plant" data-id="${p.id}">${p.icon?`<img src="${p.icon}" alt="">`:'<span>+</span>'}<b>${p.occupied?`Evo ${p.evo}`:'Empty'}</b><small>Slot ${p.id+1}${p.occupied?` · Type ${p.type}`:''}</small></button>`).join('')}</div>`;
    else if(tab==='upgrades')body=`<div class="gaming-upgrades">${model.upgrades.map((u,id)=>`<button class="w5-row" data-w5="upgrade" data-id="${id}"><b>${esc(u.name)}</b><span>Lv ${fmt(u.level)}</span><strong>${esc(u.effect)}</strong></button>`).join('')}</div>`;
    else {const pages=[['super','Super'],['duper','Duper'],['zuper','Zuper']],page=pages[superPage],shown=model.superbits.slice(superPage*24,superPage*24+24);body=`<div class="superbit-heading"><b>${page[1]}bits</b><span>Select an available bonus to see what it does.</span></div><div class="w5-grid superbits ${page[0]}">${shown.map(s=>`<button class="w5-tile superbit-card ${s.owned===false?'locked':''}" data-w5="superbit" data-id="${s.id}"><strong>${esc(s.name)}</strong><small>${s.owned===null?'UNKNOWN':s.owned?'UNLOCKED':`LOCKED · LV ${s.requiredLevel}`}</small><div class="w5-tip"><b>${esc(s.name)}</b><span>${esc(s.description)}</span></div></button>`).join('')}</div><nav class="superbit-pages" aria-label="Superbit tier">${pages.map(([id,label],i)=>`<button class="${id}${i===superPage?' active':''}" data-super-page="${i}">${label}</button>`).join('')}</nav>`;}
    const summary=kind==='sailing'?`${model.artifacts.filter(a=>a.tier>0).length}/${model.artifacts.length} artifacts · ${model.boats.length} boats · ${model.chests} chests`:`${fmt(model.bits)} bits · ${model.plants.filter(p=>p.occupied).length}/25 plants · Snail Lv ${fmt(model.snailLevel)}`;
    host.innerHTML=`<div class="section-head compact"><div><p class="eyebrow">World 5 · account-wide</p><h2>${kind==='sailing'?'Sailing':'Gaming'}</h2><p>${kind==='sailing'?'Artifacts, boats, captains, routes, and saved progression.':'Garden contents, core upgrades, and Superbit ownership.'}</p></div><strong class="w5-summary">${esc(summary)}</strong></div><nav class="skill-tabs" role="tablist">${tabList.map(([id,label])=>`<button class="skill-tab${tab===id?' active':''}" data-w5-tab="${id}">${label}</button>`).join('')}</nav>${body}<section id="w5Detail" class="exp-card w5-detail detail-dismissed"></section>`;
    host.querySelectorAll('[data-w5-tab]').forEach(b=>b.onclick=()=>{tabs[kind]=b.dataset.w5Tab;selected=null;paint();});host.querySelectorAll('[data-w5]').forEach(b=>b.onclick=()=>show(b.dataset.w5,Number(b.dataset.id)));host.querySelectorAll('[data-super-page]').forEach(b=>b.onclick=()=>{superPage=Number(b.dataset.superPage);selected=null;paint();});
  }
  function show(type,id){const panel=host.querySelector('#w5Detail');let title='',html='';if(type==='artifact'){const a=model.artifacts[id];title=a.name;html=`<p><strong>${esc(a.tierName)}</strong></p><p>${esc(a.effect)}</p><p class="muted">Saved tier only. The displayed catalog effect may depend on other account values.</p>`;}else if(type==='boat'){const b=model.boats.find(x=>x.id===id);title=`Boat ${id+1}`;html=`<p>Loot Lv ${fmt(b.lootLevel)} · Speed Lv ${fmt(b.speedLevel)}</p><p>Captain slot: ${b.captainId>=0?b.captainId+1:'None'} · ${b.island>=0?`Island ${b.island+1}`:'Harbor'}</p><p class="muted">Final speed, loot value, and travel time include account-wide bonuses not reconstructed here.</p>`;}else if(type==='captain'){const x=model.captains.find(v=>v.id===id);title=`Captain ${id+1}`;html=`<p>Level ${fmt(x.level)} · EXP ${fmt(x.exp)} · Tier ${fmt(x.tier)}</p><p>Saved bonus rolls: ${fmt(x.bonusA)} and ${fmt(x.bonusB)} · Trait ${fmt(x.trait)}</p>`;}else if(type==='plant'){const p=model.plants[id];title=`Garden slot ${id+1}`;html=p.occupied?`<p>Plant type ${p.type} · Evolution ${p.evo}</p><p class="muted">Current harvest value is not estimated because it depends on account multipliers and special plant behavior.</p>`:'<p>This garden slot is empty.</p>';}else if(type==='upgrade'){const u=model.upgrades[id];title=u.name;html=`<p>Level ${fmt(u.level)}</p><p>${esc(u.effect)}</p><p class="muted">Core effect only; external account bonuses are excluded.</p>`;}else{const s=model.superbits[id];title=s.name;html=`<p>${s.owned===null?'Ownership unavailable':s.owned?'Owned':'Not owned'} · requires Gaming Lv ${s.requiredLevel}</p><p>${esc(s.description)}</p>`;}panel.innerHTML=`<button class="secondary w5-close">Close</button><h3>${esc(title)}</h3>${html}`;panel.classList.remove('detail-dismissed');panel.querySelector('.w5-close').onclick=()=>panel.classList.add('detail-dismissed');}
  paint();}
  const api={decodeSailing,decodeGaming,render};if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.World5=api;
})(typeof window!=='undefined'?window:globalThis);
