(function(root){
  'use strict';
  const parse=v=>{if(typeof v==='string'){try{return JSON.parse(v);}catch{return v;}}return v;};
  const letters='_abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';
  // GamingStatType MSA_Bonus in the installed client. The final Skill3 slot
  // currently returns zero even when its Superbit is owned.
  const bonuses=[['Damage',7,1],['Cooking speed',13,13],['Sailing speed',3,1],['Gaming bits',20,50],['Class EXP',11,1.12],['Skill EXP',16,1],['Farming EXP',12,1.75,'jade'],['Jade coins',13,2,'jade'],['Essence',14,1.5,'jade'],['Spelunking POW',27,2.5,'over300'],['Research EXP',44,.3,'over300'],['Skill3',46,0]];
  function evaluate(data={},targetWave=null){
    const totems=parse(data.TotemInfo),gaming=parse(data.Gaming),ninja=parse(data.Ninja),saved=parse(totems?.[0]);
    if(targetWave!==null&&(Array.isArray(targetWave)?targetWave.length!==8||targetWave.some(n=>!Number.isSafeInteger(n)||n<0):!Number.isSafeInteger(targetWave)||targetWave<0))throw new RangeError('Enter a whole wave number of zero or more.');
    const waves=Array.from({length:8},(_,i)=>targetWave!==null?(Array.isArray(targetWave)?targetWave[i]:targetWave):saved?.[i]!=null&&Number.isFinite(Number(saved[i]))?Number(saved[i]):null);
    const total=waves.every(v=>v!==null)?waves.reduce((a,b)=>a+b,0):null;
    const owned=(value,id)=>value==null?null:String(value).includes(letters[id]);
    return {waves,total,bonuses:bonuses.map(([name,id,rate,type])=>{const active=owned(type==='jade'?ninja?.[102]?.[9]:gaming?.[12],id);return {name,active,source:type==='jade'?`Jade Emporium · MSA Expander ${['I','II','III'][id-12]}`:`Gaming Superbit #${id+1}`,value:active===false?0:active===null||total===null?null:rate*Math.max(0,Math.floor((total-(type==='over300'?300:0))/10))};})};
  }
  function render(host,data){
    const m=evaluate(data),fmt=n=>Math.round(n).toLocaleString();
    const art=model=>`<div class="worship-art" aria-hidden="true"></div><div class="worship-waves">${model.waves.map((n,i)=>`<div title="Totem ${i+1}"><small>Wave</small><strong>${n??'?'}</strong></div>`).join('')}</div>`;
    const grid=(model,compare=false)=>`<div class="worship-bonuses">${model.bonuses.map((b,i)=>{const current=m.bonuses[i].value,delta=b.value===null||current===null?null:Math.round(b.value)-Math.round(current);return `<div class="${b.active===false?'is-locked':''}" title="${b.source}"><span>${b.name}</span><strong>${b.value===null?'?':'+'+fmt(b.value)+'%'}</strong><small>${b.active===false?'Locked':b.active===null?'Unlock unknown':compare&&delta!==null?(delta===0?'No change':(delta>0?'+':'')+fmt(delta)+' percentage points'):''}</small></div>`;}).join('')}</div>`;
    host.innerHTML=`<div class="section-head compact"><div><p class="eyebrow">World 3</p><h2>Worship</h2></div></div><div class="worship-comparison"><section class="worship-totalizer"><h3>Your saved waves <small>${m.total===null?'Wave data unavailable':fmt(m.total)+' total waves'}</small></h3>${art(m)}${grid(m)}</section><section class="worship-totalizer worship-calculator"><h3>Wave calculator <small>Uses your current bonus unlocks</small></h3><div class="worship-art" aria-hidden="true"></div><div class="worship-waves worship-wave-inputs">${m.waves.map((n,i)=>`<label><small>Wave</small><input data-worship-wave="${i}" aria-label="Totem ${i+1} target wave" type="number" min="0" max="1000000" step="1" value="${n??0}" inputmode="numeric"></label>`).join('')}</div><p id="worshipInputError" class="worship-input-error" role="status"></p><div id="worshipProjection"></div></section></div><details class="worship-unlocks"><summary>Bonus unlocks & calculation notes</summary>${m.bonuses.map(b=>`<p><strong>${b.name}:</strong> ${b.source} · ${b.active===true?'Unlocked':b.active===false?'Not unlocked':'Save data missing'}</p>`).join('')}<p>Each input sets the wave for the totem directly above it, even if it is lower than your saved record. Differences compare the rounded bonuses shown in game; they are percentage points, not a final stat multiplier. Your saved layout is unchanged.</p><p>Skill3 currently gives 0% in the audited game client.</p></details>`;
    const inputs=Array.from(host.querySelectorAll('[data-worship-wave]'));
    const update=()=>{const waves=inputs.map(input=>Number(input.value)),error=host.querySelector('#worshipInputError'),output=host.querySelector('#worshipProjection');if(inputs.some((input,i)=>input.value.trim()===''||!Number.isSafeInteger(waves[i])||waves[i]<0||waves[i]>1000000)){error.textContent='Enter a whole wave number from 0 to 1,000,000 for each totem.';output.innerHTML='';return;}error.textContent='';const projected=evaluate(data,waves);output.innerHTML=`<p class="worship-projected-total">${fmt(projected.total)} total waves</p>${grid(projected,true)}`;};
    inputs.forEach(input=>input.addEventListener('input',update));update();
  }
  // TotemInfo order, shared with the totalizer's eight wave slots.
  const tdMaps=['Goblin Gorefest','Wakawaka War','Acorn Assault','Frosty Firefight','Clash of Cans','Citric Conflict','Breezy Battle','Pufferblob Brawl'];
  function goblinGuide(){
    const upgrades=[['Pulse','AAAAA'],['Fireball Lobber','AAABB'],['Boulder Roller','ABBBB'],['Frozone Malone','AAAAAA<em>A</em>'],['Stormcaller','BBBBBA'],['Party Caller','AAAAAA<em>A</em>'],['Kraken Cosplayer','BAAAAA'],['Poisonic Elder','ABABBB'],['Voidinator','BBBB<em>B</em>']];
    return `<article class="worship-td-guide"><h4>TOME TD [180–200]</h4><p class="worship-td-credit">Guide by Pancakex</p><div class="worship-td-guide-layout"><figure><a href="assets/td-goblin-gorefest-tome-180-200.png" target="_blank" rel="noopener"><img src="assets/td-goblin-gorefest-tome-180-200.png" alt="Goblin Gorefest tower placements: initial setup on top and the wave 170 setup below" width="552" height="507"></a><figcaption>Top: initial setup. Bottom: wave 170 setup. Click to open the full image.</figcaption></figure><div><h5>Tower upgrades</h5><table><thead><tr><th scope="col">Tower</th><th scope="col">Upgrade order</th></tr></thead><tbody>${upgrades.map(([tower,order])=>`<tr><th scope="row">${tower}</th><td>${order}</td></tr>`).join('')}</tbody></table></div></div><div class="worship-td-instructions"><h5>Guide</h5><p><strong>Stormcaller placement:</strong> The Stormcaller stays in the same position in both setups. It was accidentally left out of the top screenshot.</p><p>You can use this guide for lower scores too: use the top setup (or both setups) with fewer upgrades.</p><p><strong>Before attempting a score of 180:</strong> Check waves 150 and 160. In this run, those waves were cleared without mobs reaching the bottom line, but wave 170 still brought mobs close to the totem and required strategic roots. Aim for that performance at 150/160 before attempting 180.</p><ol><li>Spam every wave to start stacking the Equinox bonus early.</li><li>At wave 170, quickly switch your towers from the top setup to the bottom setup and upgrade them. Mobs will not wait.</li><li>If you can beat wave 170 without mobs going underneath, try beating wave 180. According to this guide, that should also get you through wave 190 for a score of 200.</li></ol></div></article>`;
  }
  function rootGuide(){
    const upgrades=[['Party','AAABBB ×5 (BBBBBB ×4)','135'],['Stormcaller','BBBBB<em>A</em> · AAAAA<em>A</em>','141'],['Poisonic','ABABB<em>B</em>','136'],['Frozone','AAAAAA','131'],['Kraken','BAAA','129'],['Void','BBBB','71']];
    return `<article class="worship-td-guide"><h4>TD Root World 1 [220]</h4><p class="worship-td-credit">Guide by Pancakex</p><p>The Roots · Acorn Assault</p><dl class="worship-td-stats"><div><dt>Wave 210 time (harder)</dt><dd>2 hr 15 min</dd></div><div><dt>Atom</dt><dd>1290%</dd></div><div><dt>Cannoli</dt><dd>110 · 2638% effect</dd></div><div><dt>Equinox</dt><dd>28</dd></div></dl><div class="worship-td-guide-layout"><figure><a href="assets/td-acorn-assault-root-220.png" target="_blank" rel="noopener"><img src="assets/td-acorn-assault-root-220.png" alt="Three tower setups for Acorn Assault in The Roots: defensive, Poisonic damage, and Stormcaller damage layouts" width="856" height="1245"></a><figcaption>Root World 1 setups. Click to open the full image.</figcaption></figure><div><h5>Tower upgrades</h5><table><thead><tr><th scope="col">Tower</th><th scope="col">Upgrade order</th><th scope="col">Level</th></tr></thead><tbody>${upgrades.map(([tower,order,level])=>`<tr><th scope="row">${tower}</th><td>${order}</td><td>${level}</td></tr>`).join('')}</tbody></table></div></div><div class="worship-td-instructions"><h5>Guide</h5><ol><li>Pay attention when spamming waves: Void can get stunned.</li><li>Set the Party speed traits based on Kraken reaching 0.33. Do not blindly follow the upgrade sequences above.</li><li>The guide author defeated the wave 210 bosses during that wave, but you can stay defensive or use Poisonic damage for 210. You can carry the bosses over to 220 and beat everything there. If using Stormcallers at 210, switch at around 1900T boss HP.</li><li>For wave 220 defense, use 3 Krakens, 1 Frozone, then 4–5 more Krakens, depending on how many BAAAA upgrades you want to use.</li><li>Wave 220 has more “bosses.” Their HP is lower than at 210 but still high, so Poisonic may work better than Stormcaller against their numbers.</li></ol><p><strong>Saving your score:</strong> The guide recommends saving 200 after a fully defensive run instead of saving 220. Selling towers so many times during the 220 run can leave you with fewer points than at 200.</p></div></article>`;
  }
  function wakawakaGuide(){
    const upgrades=[['Party','AABBBB ×6 · AAABBB ×2 (BBBBBB ×2)','128'],['Stormcaller','BBBBB+','136'],['Poisonic','ABABB+','131'],['Frozone','AAAAA<em>A</em>','125'],['Kraken','BAAA ×4 · BAAAA ×4','125'],['Void','BBB<em>B</em>','67']];
    return `<article class="worship-td-guide"><h4>TD WAKAWAKA WAR World 2 [220]</h4><p class="worship-td-credit">Guide by Pancakex</p><dl class="worship-td-stats"><div><dt>Atom</dt><dd>1204%</dd></div><div><dt>Cannoli</dt><dd>90 · 1035% effect</dd></div></dl><div class="worship-td-guide-layout"><div class="worship-td-images"><figure><a href="assets/td-wakawaka-war-220.png" target="_blank" rel="noopener"><img src="assets/td-wakawaka-war-220.png" alt="Wakawaka War tower placements in three stacked images: base setup, defensive setup, and damage setup" width="958" height="1160"></a><figcaption>Top: base setup. Middle: defensive setup. Bottom: DPS setup. Click to open the full image.</figcaption></figure><figure class="worship-td-extra-image"><a href="assets/td-wakawaka-war-dps-detail.png" target="_blank" rel="noopener"><img src="assets/td-wakawaka-war-dps-detail.png" alt="Additional Wakawaka War DPS setup detail showing tower positions on the lower platforms" width="1080" height="481"></a><figcaption>Additional DPS setup detail. Click to open the full image.</figcaption></figure></div><div><h5>Tower upgrades</h5><table><thead><tr><th scope="col">Tower</th><th scope="col">Upgrade order</th><th scope="col">Level</th></tr></thead><tbody>${upgrades.map(([tower,order,level])=>`<tr><th scope="row">${tower}</th><td>${order}</td><td>${level}</td></tr>`).join('')}</tbody></table></div></div><div class="worship-td-instructions"><h5>Guide</h5><ol><li>Spam waves until the boss wave every time.</li><li>The first image is your base setup. The original guide also mentions a half-DPS setup from a previous guide; that reference was not included here. The second image is your defensive setup, which you switch to after removing all mob colors. The third image is your DPS setup.</li><li>Choose Party traits that get your Krakens to around 0.30 attack speed, rather than blindly following the listed upgrades.</li><li>With eight Krakens at 0.30, upgrade the last four to BAAAA during wave 210 defensive mode to simulate having another Kraken.</li><li>To switch to full DPS at wave 220, kill the mobs until only bosses remain. Stall the bosses with a small defense, sell the remaining towers except the Parties, and place the DPS setup shown in the third image. You can also do this at 210, but you will need to rebuild your defense for 220; the extra selling and replacing costs points in the save feature.</li></ol></div></article>`;
  }
  function frostyGuide(){
    const upgrades=[['Party','AAABBB ×4 · AAAABB · BBBBBB ×4','139'],['Stormcaller','BBBBBA · AAAAAA','144'],['Poisonic','ABABBB','139'],['Frozone','AAAAAA','141'],['Kraken','BAAAA','134'],['Void','BBBB','74']];
    return `<article class="worship-td-guide"><h4>TD Frosty World 3 [220]</h4><p class="worship-td-credit">Guide by Pancakex</p><dl class="worship-td-stats"><div><dt>Wave 210 time (harder)</dt><dd>2 hr 6 min</dd></div><div><dt>Atom</dt><dd>1406%</dd></div><div><dt>Cannoli</dt><dd>110 · 4107% effect</dd></div><div><dt>Equinox</dt><dd>41</dd></div></dl><div class="worship-td-guide-layout"><figure><a href="assets/td-frosty-firefight-220.png" target="_blank" rel="noopener"><img src="assets/td-frosty-firefight-220.png" alt="Frosty Firefight tower placements in three stacked images: defensive setup, Poisonic damage setup, and Stormcaller damage setup" width="958" height="1209"></a><figcaption>Frosty World 3 setups. Click to open the full image.</figcaption></figure><div><h5>Tower upgrades</h5><table><thead><tr><th scope="col">Tower</th><th scope="col">Upgrade order</th><th scope="col">Level</th></tr></thead><tbody>${upgrades.map(([tower,order,level])=>`<tr><th scope="row">${tower}</th><td>${order}</td><td>${level}</td></tr>`).join('')}</tbody></table></div></div><div class="worship-td-instructions"><h5>Guide</h5><ol start="0"><li>Remove Voidinator only after all mobs have had their colors removed. Use at least 2.2 speed on Voidinator.</li><li>Wave 210 has 609 mobs, so it requires a lot of defense. Use the number of Krakens shown in the image, all at level 25 with 0.30 speed. Choose Party traits to reach that speed, and use roots when mobs reach the last Kraken.</li><li>Swap to Stormcallers at around 3800T total HP with only 3 bosses remaining. The mathematical threshold is 3900T, but some bosses might still be above 60% HP.</li><li>Wave 220 has 223 mobs, so you can return to a normal defense. If you do not beat wave 210 in time, carry its bosses over and defeat them while doing 220.</li></ol><p><strong>Saving your score:</strong> Save 200 instead of 220. The guide warns that all the tower swaps waste points in the saved setup.</p></div></article>`;
  }
  function clashGuide(){
    const upgrades=[['Party','AAAABB ×4 · AAABBB ×2 (BBBBBB ×4)','143'],['Stormcaller','BBBBBA · AAAAAA','148'],['Poisonic','ABABBB','144'],['Frozone','AAAAAA','147'],['Kraken','BAAAA','139'],['Void','BBBB','76']];
    return `<article class="worship-td-guide"><h4>TD CLASH OF CANS World 4 [220]</h4><p class="worship-td-credit">Guide by Pancakex</p><dl class="worship-td-stats"><div><dt>Wave 210 time (harder)</dt><dd>~2 hr 44 min · no Stormcaller switch</dd></div><div><dt>Atom</dt><dd>1474%</dd></div><div><dt>Cannoli</dt><dd>110 · 4401% effect</dd></div><div><dt>Equinox</dt><dd>43</dd></div></dl><div class="worship-td-guide-layout"><figure><a href="assets/td-clash-of-cans-220.png" target="_blank" rel="noopener"><img src="assets/td-clash-of-cans-220.png" alt="Clash of Cans tower placements in two stacked images: full defensive setup above and Poisonic damage setup below" width="958" height="830"></a><figcaption>Top: full defense. Bottom: Poisonic DPS setup. Click to open the full image.</figcaption></figure><div><h5>Tower upgrades</h5><table><thead><tr><th scope="col">Tower</th><th scope="col">Upgrade order</th><th scope="col">Level</th></tr></thead><tbody>${upgrades.map(([tower,order,level])=>`<tr><th scope="row">${tower}</th><td>${order}</td><td>${level}</td></tr>`).join('')}</tbody></table></div></div><div class="worship-td-instructions"><h5>Guide</h5><ol start="0"><li>Remove Voidinator only after all mobs have had their colors removed.</li><li>The guide author used all Krakens at level 25 with 0.22 speed, with no split of mobs. Choose Party traits to reach that speed or close to it.</li><li>More Poisonic Elders could be placed, but this setup balances BBBBBB Parties and Poisonic Elders for DPS.</li><li>The author did not switch to Stormcallers because they planned to carry the bosses over to 220, but the Poisonic setup cleared them anyway. If you switch, wait until all three bosses are below 60% HP, then replace all Poisonic Elders with Stormcallers. The guide gives 7.38Q as the combined HP threshold; wait a little longer to ensure each boss is below 60%.</li></ol><p><strong>Saving your score:</strong> Save 200 with the full defensive setup before making swaps. After that, you can spend points on selling and replacing towers without affecting that saved setup. Do not save 220.</p></div></article>`;
  }
  function citricGuide(){
    const upgrades=[['Party','AAAAB ×5','127'],['Stormcaller','BBBBB · AAAAA','135'],['Poisonic','ABABB','129'],['Frozone','AAAAA','124'],['Kraken','BAAA<em>A</em>','124'],['Void','BBB','65']];
    return `<article class="worship-td-guide"><h4>TD OJ Bay World 5 [200]</h4><p class="worship-td-credit">Guide by Pancakex</p><p>OJ Bay · Citric Conflict</p><dl class="worship-td-stats"><div><dt>Atom</dt><dd>1180%</dd></div><div><dt>Cannoli</dt><dd>90 · 276% effect</dd></div></dl><figure><a href="assets/td-citric-conflict-200.png" target="_blank" rel="noopener"><img src="assets/td-citric-conflict-200.png" alt="Four OJ Bay tower setups: initial defense at top left, defense with Stormcaller at top right, Poisonic DPS at bottom left, and final Stormcaller DPS at bottom right" width="1916" height="762"></a><figcaption>OJ Bay defense and DPS setups. Click to open the full image.</figcaption></figure><div class="worship-td-instructions"><h5>Tower upgrades</h5><table><thead><tr><th scope="col">Tower</th><th scope="col">Upgrade order</th><th scope="col">Level</th></tr></thead><tbody>${upgrades.map(([tower,order,level])=>`<tr><th scope="row">${tower}</th><td>${order}</td><td>${level}</td></tr>`).join('')}</tbody></table><h5 class="worship-td-guide-heading">Guide</h5><ol start="0"><li>Start with the Parties’ speed boost to reduce the risk of Voidinator not hitting early.</li><li>Spam until the boss wave, but watch out for purple mobs.</li><li>Choose speed traits based on Kraken reaching 0.27–0.28. This is used to hold bosses exactly in the middle of DPS mode with one A trait.</li><li>Replace Voidinator with a Stormcaller after all mobs lose their colors. Do not do this on early waves.</li><li>Keep the top setup until you feel ready to speed up the process.</li><li>You can use DPS mode on previous waves with fewer upgrades on the DPS towers to save points.</li><li>The main difficulty during the holding phase is wave 180. Some of the middle Krakens need to reach level 25.</li><li>At wave 200, before switching to DPS mode, you can add DPS towers or Voidinator in a few spots, such as the start or end of the line after killing some small mobs.</li><li>Gradually build the DPS setup as the situation allows. You will end up with 6 mobs, including 3 bosses. To hold them in that position, use a BAAAA Kraken at 0.30 speed.</li><li>To hold the remaining 3 bosses, you can use a Kraken with just one A trait.</li><li>Get <strong>every boss below 60% HP</strong> before using the final DPS setup. The guide gives around 590T as the reference and warns that even one boss above the threshold can ruin the attempt.</li></ol></div></article>`;
  }
  function breezyGuide(){
    const upgrades=[['Party','AAAAB ×3 · AAABB (AAABB ×2)','121'],['Stormcaller','BBBBB · AAAAA','130'],['Poisonic','ABABB','124'],['Frozone','AAAAA','120'],['Kraken','BAAA','121'],['Void','BBB','63']];
    const swaps=[['111','1 Frozone · 3 Krakens','2 Poisonics',''],['30','2 Krakens','2 Parties (AAABB ×2)','Krakens at 0.27 speed'],['11','1 Frozone · 1 Kraken','1 Poisonic · 1 Stormcaller',''],['3','2 Krakens','2 Poisonics · 1 Stormcaller','']];
    return `<article class="worship-td-guide"><h4>TD Breezy Battle World 6 [190]</h4><p class="worship-td-credit">Guide by Pancakex</p><dl class="worship-td-stats"><div><dt>Atom</dt><dd>1106%</dd></div><div><dt>Cannoli</dt><dd>90 · 140% effect</dd></div></dl><div class="worship-td-guide-layout"><figure><a href="assets/td-breezy-battle-190.png" target="_blank" rel="noopener"><img src="assets/td-breezy-battle-190.png" alt="Three Breezy Battle tower setups: initial defense, Poisonic DPS, and final Stormcaller DPS" width="702" height="958"></a><figcaption>Top: initial setup. Middle: Poisonic DPS. Bottom: optional Stormcaller DPS. Click to open the full image.</figcaption></figure><div><h5>Tower upgrades</h5><table><thead><tr><th scope="col">Tower</th><th scope="col">Upgrade order</th><th scope="col">Level</th></tr></thead><tbody>${upgrades.map(([tower,order,level])=>`<tr><th scope="row">${tower}</th><td>${order}</td><td>${level}</td></tr>`).join('')}</tbody></table></div></div><div class="worship-td-instructions"><h5>Guide</h5><ol start="0"><li>To place Poisonic at the bottom, first place two towers on the right, then Voidinator and Poisonic. Sell the two temporary towers and continue the run.</li><li>Spam every wave, making sure you have enough speed boost as you progress.</li><li>Choose the four Parties’ speed traits based on Kraken reaching 0.35. If you cannot get below 0.36 with four Parties at five A traits each, use three Poisonics and five Parties. The guide notes that otherwise you may not be ready.</li><li>Transition from the first image to the second using the mob-count swaps below.</li><li>With similar or higher stats, the author suggests you may beat wave 180 without carrying bosses over, at Equinox 11. If needed, use the third setup: it outperforms Poisonic DPS when bosses are below 60% HP. The author did not need that switch but placed it at the end of 190 as an example for lower DPS or faster clears. Save points for wave 190 defense, or place the last towers on the middle line to recover more points when selling them.</li></ol><h5 class="worship-td-guide-heading">Tower swaps by remaining mob count</h5><table class="worship-td-swaps"><thead><tr><th scope="col">Mobs</th><th scope="col">Remove</th><th scope="col">Add</th><th scope="col">Note</th></tr></thead><tbody>${swaps.map(([count,remove,add,note])=>`<tr><th scope="row">${count}</th><td>${remove}</td><td>${add}</td><td>${note||'—'}</td></tr>`).join('')}</tbody></table></div></article>`;
  }
  function pufferblobGuide(){
    const upgrades=[['Party','AAAABB ×4 · AAABBB ×2 (BBBBBB ×3)','143'],['Stormcaller','BBBBBA ×1','149'],['Poisonic','ABABBB ×6/13','144'],['Frozone','AAAAAA ×2','147'],['Kraken','BAAAA ×9','139'],['Void','BBBB ×1','76']];
    return `<article class="worship-td-guide"><h4>TD Pufferblob Brawl World 7 [200]</h4><p class="worship-td-credit">Guide by Pancakex</p><dl class="worship-td-stats"><div><dt>Atom</dt><dd>1478%</dd></div><div><dt>Cannoli</dt><dd>110 · 8585% effect</dd></div><div><dt>Equinox</dt><dd>44</dd></div></dl><div class="worship-td-guide-layout"><figure><a href="assets/td-pufferblob-brawl-200.png" target="_blank" rel="noopener"><img src="assets/td-pufferblob-brawl-200.png" alt="Pufferblob Brawl tower placements: defensive setup above and Poisonic DPS setup below" width="958" height="830"></a><figcaption>Top: defensive setup. Bottom: Poisonic DPS setup. Click to open the full image.</figcaption></figure><div><h5>Tower upgrades</h5><table><thead><tr><th scope="col">Tower</th><th scope="col">Upgrade order and count</th><th scope="col">Level</th></tr></thead><tbody>${upgrades.map(([tower,order,level])=>`<tr><th scope="row">${tower}</th><td>${order}</td><td>${level}</td></tr>`).join('')}</tbody></table></div></div><div class="worship-td-instructions"><h5>Guide</h5><ol start="0"><li>Remove Voidinator only after all mobs have had their colors removed.</li><li>Make sure Frozone is not too low-level: its range can make things harder.</li><li>The guide author used all Krakens at level 25 with 0.22 speed. Try other speeds if you cannot reach that. Save 190 beforehand without selling towers so you do not waste time.</li><li>Start DPS mode at 12 mobs, since 6 have high HP. Add one more Kraken to the left of the Kraken shown in the DPS setup. This setup holds the bosses in position so all DPS towers can hit them without being limited by their placement.</li><li>Do not switch to Stormcallers in DPS mode with these 6 bosses; that switch works better with 3.</li></ol><p><strong>Active attention:</strong> You may need to babysit waves 170 and 180 with the root ability, and you will need to babysit wave 200.</p></div></article>`;
  }
  function goblin230Guide(){
    const upgrades=[['Party','AAABBB ×4 · AAAABB · BBBBBB ×9 · AAAAAA<em>A</em>','139'],['Stormcaller','BBBBBA','144'],['Poisonic','ABABBB','139'],['Frozone','AAAAAA','141'],['Kraken','BAAAA<em>A</em>','134'],['Void','BBBB','74']];
    return `<article class="worship-td-guide"><h4>TD Gublin World 1 [230]</h4><p class="worship-td-credit">Guide by Pancakex</p><dl class="worship-td-stats"><div><dt>Wave 230 time</dt><dd>2 hr 5 min</dd></div><div><dt>Atom</dt><dd>1406%</dd></div><div><dt>Cannoli</dt><dd>110 · 4107% effect</dd></div><div><dt>Equinox</dt><dd>41</dd></div></dl><p>The run could have been faster: small mobs kept avoiding Poisonic hits.</p><div class="worship-td-guide-layout"><figure><a href="assets/td-goblin-gorefest-230.png" target="_blank" rel="noopener"><img src="assets/td-goblin-gorefest-230.png" alt="Goblin Gorefest wave 230 tower placements: defensive setup above and Poisonic DPS setup below" width="890" height="832"></a><figcaption>Top: defensive setup. Bottom: DPS setup. Click to open the full image.</figcaption></figure><div><h5>Tower upgrades</h5><table><thead><tr><th scope="col">Tower</th><th scope="col">Upgrade order</th><th scope="col">Level</th></tr></thead><tbody>${upgrades.map(([tower,order,level])=>`<tr><th scope="row">${tower}</th><td>${order}</td><td>${level}</td></tr>`).join('')}</tbody></table></div></div><div class="worship-td-instructions"><h5>Guide</h5><ol start="0"><li>Remove Voidinator only after all mobs have had their colors removed.</li><li>Wave 230 has almost 500 mobs. Use all Krakens at level 25 with 0.30 speed, choosing Party traits to reach that speed. Use roots when mobs get near the end.</li><li>Place the Parties in the order listed above.</li><li>You can hold the second setup at 14 mobs with a level 30 Kraken and some roots, then hold the remaining 7 bosses easily.</li></ol><p><strong>Saving your score:</strong> If you manage your points carefully, you could save 230 if you do not mind getting fewer than the full amount of points in the save.</p></div></article>`;
  }
  let tdMap=0;
  function renderTD(host,data={}){
    const model=evaluate(data);
    host.innerHTML=`<div class="section-head compact"><div><p class="eyebrow">World 3</p><h2>Worship</h2></div></div><nav class="skill-tabs worship-map-tabs" aria-label="Tower defense maps">${[0,8,1,2,3,4,5,6,7].map(i=>`<button type="button" class="skill-tab${i===tdMap?' active':''}" data-td-map="${i}" aria-pressed="${i===tdMap}" aria-controls="worshipTDMap">${tdMaps[i===8?0:i]}${i===0?' (1ea Tower Tome)':i===8?' (230)':''}</button>`).join('')}</nav><section id="worshipTDMap" class="worship-totalizer" aria-live="polite"></section>`;
    const showMap=()=>{
      host.querySelectorAll('[data-td-map]').forEach(button=>{const active=Number(button.dataset.tdMap)===tdMap;button.classList.toggle('active',active);button.setAttribute('aria-pressed',String(active));});
      host.querySelector('#worshipTDMap').innerHTML=`<h3>${tdMaps[tdMap===8?0:tdMap]}<small>Tower Defense</small></h3><p class="worship-td-wave">Best saved wave: <strong>${model.waves[tdMap===8?0:tdMap]??'Unavailable'}</strong></p>${tdMap===0?goblinGuide():tdMap===1?wakawakaGuide():tdMap===2?rootGuide():tdMap===3?frostyGuide():tdMap===4?clashGuide():tdMap===5?citricGuide():tdMap===6?breezyGuide():tdMap===7?pufferblobGuide():tdMap===8?goblin230Guide():''}`;
    };
    host.querySelectorAll('[data-td-map]').forEach(button=>button.addEventListener('click',()=>{tdMap=Number(button.dataset.tdMap);showMap();}));
    showMap();
  }
  const api={evaluate,render,renderTD,tdMaps};if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.Worship=api;
})(typeof window!=='undefined'?window:globalThis);
